package com.weathernews.Weather;
class AfricaZambia {
public final static CityListClass[] zambia = new CityListClass[] {
	new CityListClass("LSKA",	"루사카",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("LNDZ",	"룬다지",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("LVNGSN",	"리빙스톤",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MZBK",	"마자부카",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MANSA",	"만사",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MONGU",	"몽구",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MWNLN",	"무뉘룽가",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MMBW",	"뭄브아",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("SMFY",	"삼피아",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("SNNG",	"세난가",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("SSHK",	"세쉐케",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("SLWZ",	"솔베지",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("ISOKA",	"아이소카",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MBALA",	"엠발라",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MKSH",	"엠쿠시",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MPIKA",	"엠피카",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("DOLA",	"은돌라",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("NCHLN",	"은첼렝게",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("CHOMA",	"초마",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("CHPT",	"치바타",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("CHNSL",	"친사리",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("CHNGL",	"칭골라",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("KABWE1",	"카브웨",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("KSM1",	"카사마",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("KAOMA",	"카오마",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("KWMBW",	"카왐브아",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("KTT",	"카테테",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("MPSH",	"카피리 음포시",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("KITWE",	"키트웨",	"잠비아",	"Africa/Lusaka"),
	new CityListClass("PTKE",	"페타우케",	"잠비아",	"Africa/Lusaka"),
};
}