package com.weathernews.Weather;
public class Austria_europe {
    public final static CityListClass[] Austria_europe = new CityListClass[] {
	new CityListClass("GRAZ",	"그라츠",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("LZN",	"라이젠",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("LBNTZ",	"라이프니쯔",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("LNDCK",	"랑데크",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("INNKR",	"리트 임 잉크라이스",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("LINZ",	"린즈",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("LIENZ",	"린츠",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("MURAU",	"무라우",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("MRZZS",	"뮈르추슐라크",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("MSTLB",	"미스텔바흐",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("MTTRS",	"미터실",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("BREGN",	"브레겐츠",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("BLDNZ",	"블루덴츠",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("NSTDT",	"비너 노이슈트",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("VIENN",	"비엔나",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("VLLCH",	"빌라흐",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("SCHBB",	"슈아이브스",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("SPTTL",	"슈피탈드라우",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("ESNST",	"아이젠슈타트",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("JNNRS",	"예너스도르프",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("OBRWR",	"오베르바트",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("INNSB",	"인스브루크",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("SLZBR",	"잘츠부르크",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("PNGJ",	"장크트 요한 임 퐁가우",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("PLTNS",	"장크트푈텐",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("ZWTTL",	"쯔베들",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("DONAU",	"크렘스안데어도나우",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("KLGNF",	"클라겐푸르트",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("KRCHD",	"키르히도르프 크렘스",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("KTZBH",	"키츠뷔헬",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("TMSWG",	"탐스베크",	"오스트리아",	"Europe/Vienna"),
	new CityListClass("FRSTD",	"프라이스타트",	"오스트리아",	"Europe/Vienna"),
    };
}
