package com.weathernews.Weather;
public class Swiss_europe {
    public final static CityListClass[] Swiss_europe = new CityListClass[] {
	new CityListClass("GLRS",	"글라루스",	"스위스",	"Europe/Zurich"),
	new CityListClass("NCHTL",	"뇌샤텔",	"스위스",	"Europe/Zurich"),
	new CityListClass("DLMNT",	"들레몽",	"스위스",	"Europe/Zurich"),
	new CityListClass("LSNN",	"로잔",	"스위스",	"Europe/Zurich"),
	new CityListClass("LCRN",	"로카르노",	"스위스",	"Europe/Zurich"),
	new CityListClass("LGN",	"루가노",	"스위스",	"Europe/Zurich"),
	new CityListClass("LZRN",	"루체른",	"스위스",	"Europe/Zurich"),
	new CityListClass("MRTGN",	"마티니",	"스위스",	"Europe/Zurich"),
	new CityListClass("BASLE",	"바젤",	"스위스",	"Europe/Zurich"),
	new CityListClass("BERN1",	"베른",	"스위스",	"Europe/Zurich"),
	new CityListClass("BRIG",	"브리크",	"스위스",	"Europe/Zurich"),
	new CityListClass("BNN1",	"비엔느",	"스위스",	"Europe/Zurich"),
	new CityListClass("WNTRT",	"빈터투어",	"스위스",	"Europe/Zurich"),
	new CityListClass("SCHFF",	"샤프하우젠",	"스위스",	"Europe/Zurich"),
	new CityListClass("SCHWY",	"슈비츠",	"스위스",	"Europe/Zurich"),
	new CityListClass("SION1",	"시옹",	"스위스",	"Europe/Zurich"),
	new CityListClass("AARAU",	"아라우",	"스위스",	"Europe/Zurich"),
	new CityListClass("APPNZ",	"아펜첼주",	"스위스",	"Europe/Zurich"),
	new CityListClass("ALTDR",	"알트도르프",	"스위스",	"Europe/Zurich"),
	new CityListClass("SRNN",	"자르넨",	"스위스",	"Europe/Zurich"),
	new CityListClass("GLLN",	"장크트갈렌",	"스위스",	"Europe/Zurich"),
	new CityListClass("MRTZS",	"장크트모리츠",	"스위스",	"Europe/Zurich"),
	new CityListClass("GNVA",	"제네바",	"스위스",	"Europe/Zurich"),
	new CityListClass("SLTHR",	"졸로투른",	"스위스",	"Europe/Zurich"),
	new CityListClass("ZUG",	"추크",	"스위스",	"Europe/Zurich"),
	new CityListClass("ZRCH",	"취리히",	"스위스",	"Europe/Zurich"),
	new CityListClass("CHUR",	"쿠아르",	"스위스",	"Europe/Zurich"),
	new CityListClass("THUN",	"툰",	"스위스",	"Europe/Zurich"),
	new CityListClass("FRNFL",	"프라우엔펠트",	"스위스",	"Europe/Zurich"),
	new CityListClass("FRBRG1",	"프라이부르크",	"스위스",	"Europe/Zurich"),
    };
}
