package com.weathernews.Weather;

public class Y {
	public final static CityListClass_E[] y = new CityListClass_E[] {
		new CityListClass_E("YAHW", "Yahatanishi", "야하타니시", "일본", "Asia/Tokyo"),
		new CityListClass_E("YKMWA", "Yakima", "얘키모", "미국", "America/Los_Angeles"),
		new CityListClass_E("YKSHM", "Yakushima", "야쿠시마", "일본", "Asia/Tokyo"),
		new CityListClass_E("YKTSK", "Yakutsk", "야쿠츠크", "러시아 연방 국가", "Asia/Yakutsk"),
		new CityListClass_E("YAMG", "Yamagata", "야마가타", "일본", "Asia/Tokyo"),
		new CityListClass_E("YAMC", "Yamaguchi", "야마구치", "일본", "Asia/Tokyo"),
		new CityListClass_E("YMBL", "Yambol", "얌볼", "불가리아", "Europe/Sofia"),
		new CityListClass_E("YMSSK", "Yamoussoukro", "야무수크로", "Cote D'ivoire", "Africa/Abidjan"),
		new CityListClass_E("YNAI", "Yanai", "야나이", "일본", "Asia/Tokyo"),
		new CityListClass_E("YAU", "Yanbu al Bahr", "얀부알바흐르", "사우디아라비아", "Asia/Riyadh"),
		new CityListClass_E("11D10202", "Yanggu", "양구", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11B20304", "Yangju", "양주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("YANGON", "Yangon", "양곤", "미얀마", "Asia/Rangoon"),
		new CityListClass_E("11B20503", "Yangpyung", "양평", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H20102", "Yangsan", "양산", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11D20403", "Yangyang", "양양", "대한민국", "Asia/Seoul"),
		new CityListClass_E("YAREN", "Yaren", "야렌", "Ripublik Naoero", "Pacific/Nauru"),
		new CityListClass_E("YAR", "Yarmouth", "야머스", "캐나다", "America/Halifax"),
		new CityListClass_E("YRSLV", "Yaroslavl", "야로슬라블", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("YND2", "Yaunde", "야운데", "카메룬", "Africa/Douala"),
		new CityListClass_E("YND2", "Yaunde", "야운데", "카메룬", "Africa/Douala"),
		new CityListClass_E("YVZ", "Yaviza", "야비사", "파나마", "America/Panama"),
		new CityListClass_E("11H10303", "Yecheon", "예천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("YKTRN", "Yekaterinburg", "예카테린부르크", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("YLLWK", "Yellowknife", "옐로나이프", "캐나다", "America/Yellowknife"),
		new CityListClass_E("11B20402", "Yeoncheon", "연천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("21F20802", "Yeongam", "영암", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H10702", "Yeongcheon", "영천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H10102", "Yeongdeok", "영덕", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11C10402", "Yeongdong", "영동", "대한민국", "Asia/Seoul"),
		new CityListClass_E("21F20102", "Yeonggwang", "영광", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H10401", "Yeongju", "영주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11D10501", "Yeongwol", "영월", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H10403", "Yeongyang", "영양", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11F20401", "Yeosu", "여수", "대한민국", "Asia/Seoul"),
		new CityListClass_E("YSHN", "Yishun New Town", "이슌뉴타운", "싱가폴", "Asia/Singapore"),
		new CityListClass_E("YKK", "Yokkaichi", "욕카이치", "일본", "Asia/Tokyo"),
		new CityListClass_E("YOK", "Yokohama", "요코하마", "일본", "Asia/Tokyo"),
		new CityListClass_E("YKTE", "Yokote", "요코테", "일본", "Asia/Tokyo"),
		new CityListClass_E("YNG", "Yonago", "요나고", "일본", "Asia/Tokyo"),
		new CityListClass_E("YNGNJM", "Yonagunijima", "요나구니지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("YNZW", "Yonezawa", "요네자와", "일본", "Asia/Tokyo"),
		new CityListClass_E("YNKRS", "Yonkers", "용커스", "미국", "America/New_York"),
		new CityListClass_E("YORK1", "York", "요크", "미국", "America/New_York"),
		new CityListClass_E("YORK", "York", "요크", "영국", "Europe/London"),
		new CityListClass_E("YRKTN", "Yorkton", "요크턴", "캐나다", "America/Regina"),
		new CityListClass_E("YRNJM", "Yoronjima", "요론지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("YSHKR", "Yoshkar-Ola", "요시카르올라", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("YNGST", "Youngstown", "영스타운", "미국", "America/New_York"),
		new CityListClass_E("YZGT", "Yozgat", "요즈가트", "터키", "Europe/Istanbul"),
		new CityListClass_E("YSTAD", "Ystad", "이스타드", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("YUMA", "Yuma", "유마", "미국", "America/Denver"),
		new CityListClass_E("YRMGS", "Yurimaguas", "유리마구아스", "페루", "America/Lima"),
		new CityListClass_E("SKHLN", "Yuzhno-Sakhalinsk", "유즈노사할린스크", "러시아 연방 국가", "Asia/Magadan"),

	};
}
