package com.weathernews.Weather;
class AfricaSouthafrica {
	public final static CityListClass[] southafrica = new CityListClass[] {
	new CityListClass("GNYS",	"가네사",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("NLSPR",	"넬스프룻",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("NWCST",	"뉴캐슬",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("DGLAS",	"더글러스",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("DUR",	"더반",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("DNDEE",	"던디",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("LYDNB",	"라이덴버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("LXTN",	"랙스톤",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("LMBRT",	"램버트베이",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("LNGSB",	"랭스버그",	"남아프리카공화국",	"Africa/Johannesburg"),
//	new CityListClass("LDYBR",	"레이디브랜드",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("LDYSM",	"레이디스미스",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("LRSFN",	"로리스폰테인",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("LTCD",	"루이트리챠드",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("RVRSD",	"리버스데일",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("REITZ",	"리츠",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("RCHMN",	"리치몬드",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MRYDL",	"마리데일",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MRBLA",	"마블 홀",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MFKNG",	"마페킹",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MCLR",	"매클리어",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MSSLB",	"모슬바이",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MRRSB",	"무리즈버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BRKLYW",	"바클리 웨스트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("VRGN",	"버지니아",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BRKLYE",	"버클리 이스트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BRGRS",	"벙거스드롭",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BTHHM",	"베들레헴",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("WLKM",	"벨콤",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BTHVL",	"보채빌",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BFRT",	"보포르 웨스트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BLTMR",	"볼티모어",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BRNDV",	"브란드블레이",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BRDSD",	"브레다스도프",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("VREDE",	"브레데",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BLMFN",	"블룸폰테인",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BISHO",	"비쇼",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("BTTRF",	"비터폰테인",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("SBY",	"살다나",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("STHRL",	"서덜랜드",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("SNKL",	"세네칼",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("SOWE",	"소웨토",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("STNKP",	"슈타인코프",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("STYNB",	"스텐버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("STRYD",	"스트리덴버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("CTRSD",	"시트러스달",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ASKHM",	"아스캄",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ALXRZ",	"알렉산더바이",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ALXND",	"알렉산드리아 ",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ADLD",	"애들레이드",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ABRDN",	"애버딘",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ERML",	"어 멜로",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("UPNGT",	"어핑턴",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ELLT",	"엘리어트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("JGRSF",	"예거스폰테인",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ODTSH",	"오쇼른",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ONSPK",	"온시프칸스",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ALLDY",	"올데이즈",	"남아프리카공화국",	"Africa/Johannesburg"),
//	new CityListClass("OLFNT",	"올리판트쇼엑",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("JHNNS",	"요하네스버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ULND",	"우룽디",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("WRCSR",	"우스터",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("UMTT",	"움타타",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("WRRNT",	"워렌톤",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("WLMRN",	"워메이런즈 스타트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("WRMBT",	"웜배스",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("WNBRG",	"윈버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("WLLWM",	"윌로우모어",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("UTRCT",	"유트레히트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MTBTB",	"음투바투바",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ZRST",	"제루스트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("CRNRV",	"카나본",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KMSKR",	"카미스크룬",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KKMS",	"카카마스",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("CRLTN",	"칼턴빌",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KRKWD",	"커크우드",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("CPT",	"케이프타운",	"남아프리카공화국",	"Africa/Johannesburg"),
//	new CityListClass("KMTPR",	"코마티포트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KSTER",	"코스터",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("CLSBR",	"콜레스버그",	"남아프리카공화국",	"Africa/Johannesburg"),
//	new CityListClass("KURMN",	"쿠루먼",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("CRDCK",	"크래독",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KRGRS",	"크루거스도프",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("CLNWL",	"클랜윌리암",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KLRKS",	"클럭스도르프",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KLPPL",	"클립플라트",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("KMBRL",	"킴벌리",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("THBZM",	"타바짐비",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("TLBGH",	"툴바흐",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("TZNN",	"트자넨",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("PSTMS",	"포스트마스버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("NLLTH",	"포트 놀로쓰",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("EDWRDP",	"포트 에드워드",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("PEL",	"포트 엘리사벳",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("MILIA",	"푼다 미리아",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("VRYBR",	"프라이벅",	"남아프리카공화국",	"Africa/Johannesburg"),
//	new CityListClass("FRSRB",	"프레이저버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("PRTRA",	"프레토리아",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("PRSK",	"프리스카",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("ALBRTP",	"프린스 알버트",	"남아프리카공화국",	"Africa/Johannesburg"),
//	new CityListClass("RTLF",	"피에트 레티프",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("PKTBR",	"피케트버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("PTRMR",	"피터마리츠버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("PTRSB",	"피터즈버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("FCKSB",	"픽스버그",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("HBRN",	"하이브론",	"남아프리카공화국",	"Africa/Johannesburg"),
//	new CityListClass("HRRSM",	"해리스미스",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("HRMNU",	"허머너스",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("HTZL",	"호타젤",	"남아프리카공화국",	"Africa/Johannesburg"),
	new CityListClass("HNDKL",	"혼데클립바이",	"남아프리카공화국",	"Africa/Johannesburg"),
};
}


