package com.weathernews.Weather;

class AsiaJapan {
	public final static CityListClass[] japan = new CityListClass[] {
		new CityListClass("KAG", "가고시마", "일본", "Asia/Tokyo"),
		new CityListClass("KOB", "고베", "일본", "Asia/Tokyo"),
		new CityListClass("KYT", "교토", "일본", "Asia/Tokyo"),
		new CityListClass("GIF", "기후", "일본", "Asia/Tokyo"),
		new CityListClass("NAGA", "나가노", "일본", "Asia/Tokyo"),
		new CityListClass("NGAW", "나가사키", "일본", "Asia/Tokyo"),
		new CityListClass("NGAOK", "나가오카", "일본", "Asia/Tokyo"),
		new CityListClass("NAGO", "나고", "일본", "Asia/Tokyo"),
		new CityListClass("NAG", "나고야", "일본", "Asia/Tokyo"),
		new CityListClass("NARA", "나라", "일본", "Asia/Tokyo"),
		new CityListClass("NAZE", "나제", "일본", "Asia/Tokyo"),
		new CityListClass("NKTSU", "나카츠", "일본", "Asia/Tokyo"),
		new CityListClass("NAH", "나하", "일본", "Asia/Tokyo"),
		new CityListClass("NMR", "네무로", "일본", "Asia/Tokyo"),
		new CityListClass("NBEOK", "노베오카", "일본", "Asia/Tokyo"),
		new CityListClass("NII", "니이가타", "일본", "Asia/Tokyo"),
		new CityListClass("NIIHM", "니이하마", "일본", "Asia/Tokyo"),
		new CityListClass("UTSNMY", "닉코", "일본", "Asia/Tokyo"),
		new CityListClass("TOK", "도쿄", "일본", "Asia/Tokyo"),
		new CityListClass("TOT", "돗토리", "일본", "Asia/Tokyo"),
		new CityListClass("RMI", "루모이", "일본", "Asia/Tokyo"),
		new CityListClass("MAEBSH", "마에바시", "일본", "Asia/Tokyo"),
		new CityListClass("MAI", "마이즈루", "일본", "Asia/Tokyo"),
		new CityListClass("MTSMT", "마츠모토", "일본", "Asia/Tokyo"),
		new CityListClass("MAS", "마츠야마", "일본", "Asia/Tokyo"),
		new CityListClass("MTSUE", "마츠에", "일본", "Asia/Tokyo"),
		new CityListClass("MAKU", "마쿠라자키", "일본", "Asia/Tokyo"),
		new CityListClass("MRIOK", "모리오카", "일본", "Asia/Tokyo"),
		new CityListClass("MBU", "몸베츠", "일본", "Asia/Tokyo"),
		new CityListClass("MUR", "무로란", "일본", "Asia/Tokyo"),
		new CityListClass("MUO", "무로토미사키", "일본", "Asia/Tokyo"),
		new CityListClass("MTS", "무츠", "일본", "Asia/Tokyo"),
		new CityListClass("DAITJM", "미나미다이토지마", "일본", "Asia/Tokyo"),
		new CityListClass("MNKM", "미나카미", "일본", "Asia/Tokyo"),
		new CityListClass("MSHM", "미시마", "일본", "Asia/Tokyo"),
		new CityListClass("MIYZ", "미야자키", "일본", "Asia/Tokyo"),
		new CityListClass("MKE", "미야케지마", "일본", "Asia/Tokyo"),
		new CityListClass("MIY", "미야코", "일본", "Asia/Tokyo"),
		new CityListClass("MKJO", "미야코노조", "일본", "Asia/Tokyo"),
		new CityListClass("MYKJM", "미야코지마", "일본", "Asia/Tokyo"),
		new CityListClass("MIZOB", "미조베", "일본", "Asia/Tokyo"),
		new CityListClass("MITO", "미토", "일본", "Asia/Tokyo"),
		new CityListClass("SAG", "사가", "일본", "Asia/Tokyo"),
		new CityListClass("SASE", "사세보", "일본", "Asia/Tokyo"),
		new CityListClass("SAIGOU", "사이고우", "일본", "Asia/Tokyo"),
		new CityListClass("SAE", "사이키", "일본", "Asia/Tokyo"),
		new CityListClass("SAI", "사이타마", "일본", "Asia/Tokyo"),
		new CityListClass("SKN", "사카이미나토", "일본", "Asia/Tokyo"),
		new CityListClass("SKT", "사카타", "일본", "Asia/Tokyo"),
		new CityListClass("SAPP", "삿포로", "일본", "Asia/Tokyo"),
		new CityListClass("SEN", "센다이", "일본", "Asia/Tokyo"),
		new CityListClass("SHOBR", "쇼우바라", "일본", "Asia/Tokyo"),
		new CityListClass("SUMOT", "스모토", "일본", "Asia/Tokyo"),
		new CityListClass("SUWA", "스와", "일본", "Asia/Tokyo"),
		new CityListClass("SKM", "스쿠모", "일본", "Asia/Tokyo"),
		new CityListClass("STTS", "슷츠", "일본", "Asia/Tokyo"),
		new CityListClass("SRKW", "시라카와", "일본", "Asia/Tokyo"),
		new CityListClass("SROISH", "시로이시", "일본", "Asia/Tokyo"),
		new CityListClass("SHS", "시모노세키", "일본", "Asia/Tokyo"),
		new CityListClass("SHIMK", "시오노미사키", "일본", "Asia/Tokyo"),
		new CityListClass("SHI", "시즈오카", "일본", "Asia/Tokyo"),
		new CityListClass("SHNJ", "신조우", "일본", "Asia/Tokyo"),
		new CityListClass("SHNKB", "신키바", "일본", "Asia/Tokyo"),
		new CityListClass("ABI", "아바시리", "일본", "Asia/Tokyo"),
		new CityListClass("ABS", "아부라츠", "일본", "Asia/Tokyo"),
		new CityListClass("ASHKW", "아사히카와", "일본", "Asia/Tokyo"),
		new CityListClass("ASO", "아소", "일본", "Asia/Tokyo"),
		new CityListClass("AOM", "아오모리", "일본", "Asia/Tokyo"),
		new CityListClass("AIZWKM", "아이즈와카마츠", "일본", "Asia/Tokyo"),
		new CityListClass("AIKAW", "아이카와", "일본", "Asia/Tokyo"),
		new CityListClass("AJIRO", "아지로", "일본", "Asia/Tokyo"),
		new CityListClass("AKUNE", "아쿠네", "일본", "Asia/Tokyo"),
		new CityListClass("AKI", "아키타", "일본", "Asia/Tokyo"),
		new CityListClass("YNAI", "야나이", "일본", "Asia/Tokyo"),
		new CityListClass("YAMG", "야마가타", "일본", "Asia/Tokyo"),
		new CityListClass("YAMC", "야마구치", "일본", "Asia/Tokyo"),
		new CityListClass("YKSHM", "야쿠시마", "일본", "Asia/Tokyo"),
		new CityListClass("YAHW", "야하타니시", "일본", "Asia/Tokyo"),
		new CityListClass("ESSH", "에사시", "일본", "Asia/Tokyo"),
		new CityListClass("ONA", "오나하마", "일본", "Asia/Tokyo"),
		new CityListClass("ODWR", "오다와라", "일본", "Asia/Tokyo"),
		new CityListClass("OMA", "오마에사키", "일본", "Asia/Tokyo"),
		new CityListClass("OMU", "오무", "일본", "Asia/Tokyo"),
		new CityListClass("OBHR", "오비히로", "일본", "Asia/Tokyo"),
		new CityListClass("OSA", "오사카", "일본", "Asia/Tokyo"),
		new CityListClass("OHMUR", "오오무라", "일본", "Asia/Tokyo"),
		new CityListClass("OIS", "오오시마", "일본", "Asia/Tokyo"),
		new CityListClass("OHTWR", "오오타와라", "일본", "Asia/Tokyo"),
		new CityListClass("OHTE", "오오테마치", "일본", "Asia/Tokyo"),
		new CityListClass("OWS", "오와세", "일본", "Asia/Tokyo"),
		new CityListClass("OIT", "오이타", "일본", "Asia/Tokyo"),
		new CityListClass("OOTS", "오츠", "일본", "Asia/Tokyo"),
		new CityListClass("OKAY", "오카야마", "일본", "Asia/Tokyo"),
		new CityListClass("OKNKK", "오쿠닉코", "일본", "Asia/Tokyo"),
		new CityListClass("ERABU", "오키노에라부", "일본", "Asia/Tokyo"),
		new CityListClass("OTR", "오타루", "일본", "Asia/Tokyo"),
		new CityListClass("OTHIME", "오토히메", "일본", "Asia/Tokyo"),
		new CityListClass("OFU", "오후나토", "일본", "Asia/Tokyo"),
		new CityListClass("WJM", "와지마", "일본", "Asia/Tokyo"),
		new CityListClass("WAK", "와카야마", "일본", "Asia/Tokyo"),
		new CityListClass("WKK", "왁카나이", "일본", "Asia/Tokyo"),
		new CityListClass("YNG", "요나고", "일본", "Asia/Tokyo"),
		new CityListClass("YNGNJM", "요나구니지마", "일본", "Asia/Tokyo"),
		new CityListClass("YNZW", "요네자와", "일본", "Asia/Tokyo"),
		new CityListClass("YRNJM", "요론지마", "일본", "Asia/Tokyo"),
		new CityListClass("YKTE", "요코테", "일본", "Asia/Tokyo"),
		new CityListClass("YOK", "요코하마", "일본", "Asia/Tokyo"),
		new CityListClass("YKK", "욕카이치", "일본", "Asia/Tokyo"),
		new CityListClass("URKW", "우라카와", "일본", "Asia/Tokyo"),
		new CityListClass("UBE", "우베", "일본", "Asia/Tokyo"),
		new CityListClass("USHBK", "우시부카", "일본", "Asia/Tokyo"),
		new CityListClass("UEN", "우에노", "일본", "Asia/Tokyo"),
		new CityListClass("UWJ", "우와지마", "일본", "Asia/Tokyo"),
		new CityListClass("IRG", "이라고", "일본", "Asia/Tokyo"),
		new CityListClass("IRO", "이로우자키", "일본", "Asia/Tokyo"),
		new CityListClass("IRIOM", "이리오모테", "일본", "Asia/Tokyo"),
		new CityListClass("IMR", "이마리", "일본", "Asia/Tokyo"),
		new CityListClass("ISGKJM", "이시가키지마", "일본", "Asia/Tokyo"),
		new CityListClass("ISH", "이시노마키", "일본", "Asia/Tokyo"),
		new CityListClass("IWMZW", "이와미자마", "일본", "Asia/Tokyo"),
		new CityListClass("IID", "이이다", "일본", "Asia/Tokyo"),
		new CityListClass("IIZK", "이즈카", "일본", "Asia/Tokyo"),
		new CityListClass("IZHR", "이즈하라", "일본", "Asia/Tokyo"),
		new CityListClass("COS", "초시", "일본", "Asia/Tokyo"),
		new CityListClass("TSU", "츠", "일본", "Asia/Tokyo"),
		new CityListClass("TSRG", "츠루가", "일본", "Asia/Tokyo"),
		new CityListClass("TSYM1", "츠야마", "일본", "Asia/Tokyo"),
		new CityListClass("TCUR", "츠치우라", "일본", "Asia/Tokyo"),
		new CityListClass("TSKB", "츠쿠바", "일본", "Asia/Tokyo"),
		new CityListClass("CHI", "치바", "일본", "Asia/Tokyo"),
		new CityListClass("CHCHB", "치치부", "일본", "Asia/Tokyo"),
		new CityListClass("CHIJ", "치치지마", "일본", "Asia/Tokyo"),
		new CityListClass("KNA", "카나자와", "일본", "Asia/Tokyo"),
		new CityListClass("KNYA", "카노야", "일본", "Asia/Tokyo"),
		new CityListClass("KRUIZW", "카루이자와", "일본", "Asia/Tokyo"),
		new CityListClass("FJKWK", "카와구치코", "일본", "Asia/Tokyo"),
		new CityListClass("KAZEY", "카제야", "일본", "Asia/Tokyo"),
		new CityListClass("KTSUUR", "카츠우라", "일본", "Asia/Tokyo"),
		new CityListClass("KOC", "코치", "일본", "Asia/Tokyo"),
		new CityListClass("KOFU", "코후", "일본", "Asia/Tokyo"),
		new CityListClass("KUR", "쿠레", "일본", "Asia/Tokyo"),
		new CityListClass("KRUM", "쿠루메", "일본", "Asia/Tokyo"),
		new CityListClass("KMGY", "쿠마가야", "일본", "Asia/Tokyo"),
		new CityListClass("KUM", "쿠마모토", "일본", "Asia/Tokyo"),
		new CityListClass("KMJM", "쿠메지마", "일본", "Asia/Tokyo"),
		new CityListClass("KUS", "쿠시로", "일본", "Asia/Tokyo"),
		new CityListClass("KUCCH", "쿳찬", "일본", "Asia/Tokyo"),
		new CityListClass("KKG", "키카이", "일본", "Asia/Tokyo"),
		new CityListClass("KTM", "키타미", "일본", "Asia/Tokyo"),
		new CityListClass("ESSI", "키타미에사시", "일본", "Asia/Tokyo"),
		new CityListClass("TNGSHM", "타네가시마", "일본", "Asia/Tokyo"),
		new CityListClass("TDO", "타도츠", "일본", "Asia/Tokyo"),
		new CityListClass("TKM", "타카마츠", "일본", "Asia/Tokyo"),
		new CityListClass("TKYM", "타카야마", "일본", "Asia/Tokyo"),
		new CityListClass("TKCHH", "타카치호", "일본", "Asia/Tokyo"),
		new CityListClass("TYM", "타테야마", "일본", "Asia/Tokyo"),
		new CityListClass("TOM", "토마코마이", "일본", "Asia/Tokyo"),
		new CityListClass("TSS", "토사시미즈", "일본", "Asia/Tokyo"),
		new CityListClass("TYA", "토야마", "일본", "Asia/Tokyo"),
		new CityListClass("TYNK", "토요나카", "일본", "Asia/Tokyo"),
		new CityListClass("TYOOK", "토요오카", "일본", "Asia/Tokyo"),
		new CityListClass("THYSH", "토요하시", "일본", "Asia/Tokyo"),
		new CityListClass("TSM", "토코시마", "일본", "Asia/Tokyo"),
		new CityListClass("HAGI", "하기", "일본", "Asia/Tokyo"),
		new CityListClass("HANED", "하네다", "일본", "Asia/Tokyo"),
		new CityListClass("HMD", "하마다", "일본", "Asia/Tokyo"),
		new CityListClass("HMM", "하마마츠", "일본", "Asia/Tokyo"),
		new CityListClass("HABOR", "하보로", "일본", "Asia/Tokyo"),
		new CityListClass("HAC", "하치노헤", "일본", "Asia/Tokyo"),
		new CityListClass("HHJ", "하치조지마", "일본", "Asia/Tokyo"),
		new CityListClass("HAK", "하코다테", "일본", "Asia/Tokyo"),
		new CityListClass("FUS", "후시키", "일본", "Asia/Tokyo"),
		new CityListClass("FUJI", "후지", "일본", "Asia/Tokyo"),
		new CityListClass("FKAUR", "후카우라", "일본", "Asia/Tokyo"),
		new CityListClass("FKH", "후쿠시마", "일본", "Asia/Tokyo"),
		new CityListClass("FKY", "후쿠야마", "일본", "Asia/Tokyo"),
		new CityListClass("FKUE", "후쿠에", "일본", "Asia/Tokyo"),
		new CityListClass("FUU", "후쿠오카", "일본", "Asia/Tokyo"),
		new CityListClass("FKI", "후쿠이", "일본", "Asia/Tokyo"),
		new CityListClass("HIRAD", "히라도", "일본", "Asia/Tokyo"),
		new CityListClass("HIR", "히로시마", "일본", "Asia/Tokyo"),
		new CityListClass("HROO", "히로오", "일본", "Asia/Tokyo"),
		new CityListClass("HIM", "히메제", "일본", "Asia/Tokyo"),
		new CityListClass("HWS", "히와사", "일본", "Asia/Tokyo"),
		new CityListClass("HKN", "히코네", "일본", "Asia/Tokyo"),
		new CityListClass("HITA", "히타", "일본", "Asia/Tokyo"),
		new CityListClass("HTYSH", "히토요시", "일본", "Asia/Tokyo"),

//	new CityListClass("KAG",	"가고시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NAGO",	"고",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KOB",	"고베",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KOFU",	"고후",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KYT",	"교토",	"일본",	"Asia/Tokyo"),
//	new CityListClass("GIF",	"기후",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NAGA",	"나가노",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NGAW",	"나가사키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NGAOK",	"나가오카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NAG",	"나고야",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NARA",	"나라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NAZE",	"나제",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NKTSU",	"나카츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NAH",	"나하",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NMR",	"네무로",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NBEOK",	"노베오카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NII",	"니이가타",	"일본",	"Asia/Tokyo"),
//	new CityListClass("NIIHM",	"니이하마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("UTSNMY",	"닛코",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TOK",	"도쿄",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TOT",	"돗토리",	"일본",	"Asia/Tokyo"),
//	new CityListClass("RMI",	"루모이",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MAEBSH",	"마에바시",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MAI",	"마이즈루",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MTSMT",	"마츠모토",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MAS",	"마츠야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MTSUE",	"마츠에",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MAKU",	"마쿠라자키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MRIOK",	"모리오카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MBU",	"몬베츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MUR",	"무로란",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MUO",	"무로토미사키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MTS",	"무츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("DAITJM",	"미나미다이토지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MNKM",	"미나카미",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MSHM",	"미시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MIYZ",	"미야자키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MKE",	"미야케지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MIY",	"미야코",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MKJO",	"미야코노조",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MYKJM",	"미야코지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MIZOB",	"미조베",	"일본",	"Asia/Tokyo"),
//	new CityListClass("MITO",	"미토",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SAG",	"사가",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SASE",	"사에보",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SAIGOU",	"사이고우",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SAE",	"사이키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SAI",	"사이타마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SKN",	"사카이미나토",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SKT",	"사카타",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SAPP",	"삿포로",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SEN",	"센다이",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SHOBR",	"쇼우바라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SUMOT",	"수모토",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SUWA",	"수와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("STTS",	"수츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SKM",	"수쿠모",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SRKW",	"시라카와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SROISH",	"시로이시",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SHS",	"시모노세키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SHIMK",	"시오노미사키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SHI",	"시즈오카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SHNJ",	"신조우",	"일본",	"Asia/Tokyo"),
//	new CityListClass("SHNKB",	"신키바",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TSU",	"쓰",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ABI",	"아바시리",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ABS",	"아부라츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ASHKW",	"아사히카와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ASO",	"아소",	"일본",	"Asia/Tokyo"),
//	new CityListClass("AOM",	"아오모리",	"일본",	"Asia/Tokyo"),
//	new CityListClass("AIZWKM",	"아이즈와카마츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("AIKAW",	"아이카와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("AJIRO",	"아지로",	"일본",	"Asia/Tokyo"),
//	new CityListClass("AKUNE",	"아쿠네",	"일본",	"Asia/Tokyo"),
//	new CityListClass("AKI",	"아키타",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YNAI",	"야나이",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YAMG",	"야마가타",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YAMC",	"야마구치",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YKSHM",	"야쿠시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YAHW",	"야하타니시",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ESSH",	"에사시",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ONA",	"오나하마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ODWR",	"오다와라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OMA",	"오마에사키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OMU",	"오무",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OBHR",	"오비히로",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OSA",	"오사카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OOTS",	"오쓰",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OHMUR",	"오오무라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OIS",	"오오시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OHTWR",	"오오타와라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OHTE",	"오오테마치",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OWS",	"오와세",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OIT",	"오이타",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OKAY",	"오카야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OKNKK",	"오쿠니코",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ERABU",	"오키노에라부",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OTR",	"오타루",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OTHIME",	"오토히메",	"일본",	"Asia/Tokyo"),
//	new CityListClass("OFU",	"오후나토",	"일본",	"Asia/Tokyo"),
//	new CityListClass("WJM",	"와지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("WKK",	"와카나이",	"일본",	"Asia/Tokyo"),
//	new CityListClass("WAK",	"와카야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YNG",	"요나고",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YNGNJM",	"요나구니지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YNZW",	"요네자와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YRNJM",	"요론지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YKK",	"요카이치",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YKTE",	"요코테",	"일본",	"Asia/Tokyo"),
//	new CityListClass("YOK",	"요코하마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("URKW",	"우라카와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("UBE",	"우베",	"일본",	"Asia/Tokyo"),
//	new CityListClass("USHBK",	"우시부카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("UEN",	"우에노",	"일본",	"Asia/Tokyo"),
//	new CityListClass("UWJ",	"우와지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IRG",	"이라고",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IRO",	"이로우자키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IRIOM",	"이리오모테",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IMR",	"이마리",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ISGKJM",	"이시가키지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ISH",	"이시노마키/이시카와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IWMZW",	"이와미자마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IID",	"이이다",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IIZK",	"이즈카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("IZHR",	"이즈하라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("COS",	"초시",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TSRG",	"츠루가",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TSYM1",	"츠야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TCUR",	"츠치우라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TSKB",	"츠쿠바",	"일본",	"Asia/Tokyo"),
//	new CityListClass("CHI",	"치바",	"일본",	"Asia/Tokyo"),
//	new CityListClass("CHCHB",	"치치부",	"일본",	"Asia/Tokyo"),
//	new CityListClass("CHIJ",	"치치지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KNA",	"카나자와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KNYA",	"카노야",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KRUIZW",	"카루이자와",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FJKWK",	"카와구치코",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KTSUUR",	"카츠우라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KAZEY",	"캊야",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KOC",	"코치",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KUR",	"쿠레",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KRUM",	"쿠루메",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KMGY",	"쿠마가야",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KUM",	"쿠마모토",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KMJM",	"쿠메지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KUS",	"쿠시로",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KUCCH",	"쿠찬",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KKG",	"키카이",	"일본",	"Asia/Tokyo"),
//	new CityListClass("KTM",	"키타미",	"일본",	"Asia/Tokyo"),
//	new CityListClass("ESSI",	"키타미에사시",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TNGSHM",	"타네가시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TDO",	"타보츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TKM",	"타카마쯔",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TKYM",	"타카야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TKCHH",	"타카치호",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TYM",	"타테야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TOM",	"토마코마이",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TSS",	"토사시미즈",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TYA",	"토야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TYNK",	"토요나카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TYOOK",	"토요카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("THYSH",	"토요하시",	"일본",	"Asia/Tokyo"),
//	new CityListClass("TSM",	"토코시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HAGI",	"하기",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HANED",	"하네다",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HMD",	"하마다",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HMM",	"하마마츠",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HABOR",	"하보로",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HAC",	"하치노헤",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HHJ",	"하치죠우지마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HAK",	"하코다테",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FUS",	"후시키",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FUJI",	"후지",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FKAUR",	"후카우라",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FKH",	"후쿠시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FKY",	"후쿠야마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FKUE",	"후쿠에",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FUU",	"후쿠오카",	"일본",	"Asia/Tokyo"),
//	new CityListClass("FKI",	"후쿠이",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HIRAD",	"히라도",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HIR",	"히로시마",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HROO",	"히루",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HIM",	"히메제",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HWS",	"히와사",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HKN",	"히코네",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HITA",	"히타",	"일본",	"Asia/Tokyo"),
//	new CityListClass("HTYSH",	"히토요시",	"일본",	"Asia/Tokyo"),

	};
}
