package com.weathernews.Weather;

public class C {
	public final static CityListClass_E[] c = new CityListClass_E[] {
		new CityListClass_E("CBZS", "Cabezas Rubias", "카베자스 루비아스", "스페인", "Europe/Madrid"),
		new CityListClass_E("CSL", "Cabo San Lucas", "까보 산 루까스", "멕시코", "America/Mazatlan"),
		new CityListClass_E("CCRS", "Caceres", "카세레스", "스페인", "Europe/Madrid"),
		new CityListClass_E("CDZ", "Cadiz", "카디스", "스페인", "Europe/Madrid"),
		new CityListClass_E("CNE", "Caen", "캉", "프랑스", "Europe/Paris"),
		new CityListClass_E("CAG", "Cagayan de Oro", "카가얀데오로", "필리핀", "Asia/Manila"),
		new CityListClass_E("CGL", "Cagliari", "칼리아리", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CHRS", "Cahors", "카오르", "프랑스", "Europe/Paris"),
//		new CityListClass_E("CRN", "Cairns", "케언스", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("CAIRO", "Cairo", "카이로", "이집트", "Africa/Cairo"),
		new CityListClass_E("CKVC", "cakovec", "차코베츠", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("CLHRR", "Calahorra", "칼라오라", "스페인", "Europe/Madrid"),
		new CityListClass_E("CLS", "Calais", "칼레", "프랑스", "Europe/Paris"),
		new CityListClass_E("CLRS1", "Calarasi", "칼라라시", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("CLTYD", "Calatayud", "칼라타유드", "스페인", "Europe/Madrid"),
		new CityListClass_E("CAT", "Calcutta", "캘커타", "인도", "Asia/Calcutta"),
		new CityListClass_E("CLLL", "Calella", "칼레라", "스페인", "Europe/Madrid"),
		new CityListClass_E("CLGY", "Calgary", "캘거리", "캐나다", "America/Edmonton"),
		new CityListClass_E("CLHT", "Calheta", "칼레타", "포르투칼", "Atlantic/Madeira"),
		new CityListClass_E("CLHT1", "Calheta", "칼헤타", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("CALI", "Cali", "칼리", "콜롬비아", "America/Bogota"),
		new CityListClass_E("CLCT", "Calicut", "코지코드", "인도", "Asia/Calcutta"),
		new CityListClass_E("CLV1", "Calvia", "칼비아", "스페인", "Europe/Madrid"),
		new CityListClass_E("CMRL", "Camara de Lobos", "카마라 데 로보스", "포르투칼", "Atlantic/Madeira"),
		new CityListClass_E("CBGMA", "Cambridge", "캠브리지", "미국", "America/New_York"),
		new CityListClass_E("CBGG", "Cambridge", "케임브리지", "영국", "Europe/London"),
		new CityListClass_E("CBGC", "Cambridge Bay", "캠브리지 베이", "캐나다", "America/Pangnirtung"),
		new CityListClass_E("CAM", "Camden", "캠든", "미국", "America/New_York"),
		new CityListClass_E("CMR", "Campbell River", "캠벨 리버", "캐나다", "America/Vancouver"),
		new CityListClass_E("BCA", "Campeche", "캄페체", "멕시코", "America/Merida"),
		new CityListClass_E("CMPLL", "Campillos", "캄필로스", "스페인", "Europe/Madrid"),
		new CityListClass_E("CMPNS", "Campinas", "캄피나스", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("CGRND", "Campo Grande", "캄푸그란데", "브라질", "America/Campo_Grande"),
		new CityListClass_E("CMPBS", "Campobasso", "캄포바소", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CNVRS", "Canaveras", "칼라버라스", "스페인", "Europe/Madrid"),
		new CityListClass_E("CNBRR", "Canberra", "캔버라", "오스트레일리아", "Australia/Sydney"),
		new CityListClass_E("CNCN", "Cancun", "칸쿤", "멕시코", "America/Cancun"),
		new CityListClass_E("CNKR", "Cankiri", "창키리", "터키", "Europe/Istanbul"),
		new CityListClass_E("CNTN", "Canton", "캔턴", "미국", "America/New_York"),
		new CityListClass_E("CAPH", "Cap-Haitien", "캅 아이티엔", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("CRCFL", "Cape Coral", "케이프 코럴", "미국", "America/New_York"),
		new CityListClass_E("DRST", "Cape Dorset", "케이프 돌셋", "캐나다", "America/Pangnirtung"),
		new CityListClass_E("GRRD", "Cape Girardeau", "케이프 지라도", "미국", "America/Chicago"),
		new CityListClass_E("CPHRN", "Cape Horn", "케이프 혼", "칠레", "America/Santiago"),
		new CityListClass_E("CPL", "Cape Leeuwin", "루윈곶", "오스트레일리아", "Australia/Perth"),
		new CityListClass_E("CPT", "Cape Town", "케이프타운", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("CPSTR", "Capesterre-Belle-Eau", "카페스테르 벨 오", "과들루프섬", "America/Guadeloupe"),
		new CityListClass_E("LGRNZ", "Capitan Pablo Lagerenza", "케피탄 파블로라헤렌사", "파라과이", "America/Asuncion"),
		new CityListClass_E("CRCL1", "Caracal", "카라칼", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("CRV", "Caracas", "카라카스", "베네수엘라", "America/Caracas"),
		new CityListClass_E("CRBND", "Carbondale", "카본데일", "미국", "America/Chicago"),
		new CityListClass_E("CRBNR", "Carboneras", "카보네라", "스페인", "Europe/Madrid"),
		new CityListClass_E("CRD", "Cardiff", "카디프", "영국", "Europe/London"),
		new CityListClass_E("CRLTN", "Carletonville", "칼턴빌", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("CRLSL", "Carlisle", "칼라일", "영국", "Europe/London"),
		new CityListClass_E("CRLW", "Carlow", "칼로우", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("CRLSB", "Carlsbad", "칼스배드", "체코", "Europe/Prague"),
		new CityListClass_E("CRNRV", "Carnarvon", "카나본", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("RVS", "Carrick-on-Shannon", "캐릭온쉐논", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("CRRGL", "Carrigaline", "카리가린", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("CLLTX", "Carrollton", "캐롤톤", "미국", "America/Chicago"),
		new CityListClass_E("CRSN", "Carson City", "카슨시티", "미국", "America/Los_Angeles"),
		new CityListClass_E("CAR", "Cartagena", "카르타헤나", "콜롬비아", "America/Bogota"),
		new CityListClass_E("CTS", "Cartagena", "카르타헤나", "스페인", "Europe/Madrid"),
		new CityListClass_E("CARY", "Cary", "캐리", "미국", "America/New_York"),
		new CityListClass_E("CAS", "Casablanca", "카사블랑카", "모로코", "Africa/Casablanca"),
		new CityListClass_E("CSPR", "Casper", "캐스퍼", "미국", "America/Denver"),
		new CityListClass_E("CTL", "CastellOn de la Plana", "카스테욘데라플라나", "스페인", "Europe/Madrid"),
		new CityListClass_E("CSTLB", "Castelo Branco", "카스텔로 브랑코", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("CSTLB1", "Castlebar", "캐슬바", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("CSI", "Castries", "캐스트리스", "세인트루시아", "America/St_Lucia"),
		new CityListClass_E("CSTRN", "Castronuno", "캐스트로누노", "스페인", "Europe/Madrid"),
		new CityListClass_E("CSTR", "Castuera", "캐스투에라", "스페인", "Europe/Madrid"),
		new CityListClass_E("CTA", "Catania", "카타니아", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CTNZR", "Catanzaro", "카탄차로", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CAVAN", "Cavan", "카반", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("CYN", "Cayenne", "카옌", "기아나", "America/Cayenne"),
		new CityListClass_E("CEBC", "Cebu City", "세부시티", "필리핀", "Asia/Manila"),
		new CityListClass_E("CEDAR", "Cedar City", "시더 시티", "미국", "America/Denver"),
		new CityListClass_E("CEDARD", "Cedar Rapids", "시더 래피즈", "미국", "America/Chicago"),
		new CityListClass_E("CDNA", "Ceduna", "세두나", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("CGLD", "Cegled", "체글레드", "헝가리", "Europe/Budapest"),
		new CityListClass_E("CELJE", "Celje", "첼례", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("CNTNN", "Centennial", "센터니얼", "미국", "America/Denver"),
		new CityListClass_E("CRRK", "Cerrik", "세리크", "알바니아", "Europe/Tirane"),
		new CityListClass_E("CLRD", "Ceru Colorado", "세루 콜로라도", "아루바", "America/Aruba"),
		new CityListClass_E("PSRG", "Cervera de Pisuerga", "세르베라 드 피수에르가", "스페인", "Europe/Madrid"),
		new CityListClass_E("CESKA", "ceska Lipa", "체스까 리빠", "체코", "Europe/Prague"),
		new CityListClass_E("CTNJ", "Cetinje", "체티녜", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("CHGNS", "Chaguanas", "차구아나스", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass_E("CHLTN", "Chalatenango", "찰라테낭고", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("CLK", "Chalcis", "칼시스", "그리스", "Europe/Athens"),
		new CityListClass_E("CHLN", "Chalon-Sur-Saone", "샬롱쉬르손", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHMPG", "Chalons-en-Champagne", "샤롱장샹파뉴", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHMBR", "Chambersburg", "챔버스버그", "미국", "America/New_York"),
		new CityListClass_E("CHMB1", "Chambery", "챔버리", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHMPG1", "Champaign", "샴페인", "미국", "America/Chicago"),
		new CityListClass_E("CDRAZ", "Chandler", "챈들러", "미국", "America/Denver"),
		new CityListClass_E("CHNGR1", "Changara", "창가라", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("11H20604", "Changnyeong", "창녕", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H20301", "Changwon", "창원", "대한민국", "Asia/Seoul"),
		new CityListClass_E("CHNI", "Chania", "하니아", "그리스", "Europe/Athens"),
		new CityListClass_E("PXB", "Channel-Port aux Basques", "채널 포토바스크", "캐나다", "America/St_Johns"),
		new CityListClass_E("CHPL", "Chapel Hill", "채플 힐", "미국", "America/New_York"),
		new CityListClass_E("CHRLR", "Charleroi", "샤를루아", "벨기에", "Europe/Brussels"),
		new CityListClass_E("CHA", "Charleston", "찰스턴-사우스캐롤라이나", "미국", "America/New_York"),
		new CityListClass_E("CHAWT", "Charleston", "찰스턴-웨스트버지니아", "미국", "America/New_York"),
		new CityListClass_E("CHARLE", "Charleston", "찰스턴-일리노이", "미국", "America/Chicago"),
		new CityListClass_E("CTW", "Charlestown", "찰스타운", "세인트 키츠 네비스", "America/St_Kitts"),
		new CityListClass_E("CHRLVL", "Charleville", "샤를르빌", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("CHRLVM", "Charleville-Mezieres", "샤를르 빌 메지에르", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHRNC", "Charlotte", "샬럿", "미국", "America/New_York"),
		new CityListClass_E("CHRAM", "Charlotte Amalie", "샬럿 아말리에", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass_E("CHRLT", "Charlottesville", "샬로츠빌", "미국", "America/New_York"),
		new CityListClass_E("CTT", "Charlottetown", "샬럿 타운", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("CHRTR", "Chartres", "샤르트르", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHTBL", "Chateaubelair", "샤토 벨레르", "세인트 빈센트 그레나딘", "America/St_Vincent"),
		new CityListClass_E("CHTRX", "Chateauroux", "샤토르", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHTTN", "Chattanooga", "채터누가", "미국", "America/New_York"),
		new CityListClass_E("CHMNT", "Chaumont", "쇼몽", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHVS", "Chaves", "차베스", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("CHEB", "Cheb", "헤프", "체코", "Europe/Prague"),
		new CityListClass_E("CHLMS", "Chelmsford", "첼름스퍼드", "영국", "Europe/London"),
		new CityListClass_E("CHLYB", "Chelyabinsk", "첼야빈스크", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("CHEMN", "Chemnitz", "켐니츠", "독일", "Europe/Berlin"),
		new CityListClass_E("CHNGDU", "Chengtu", "청두", "중국", "Asia/Chongqing"),
		new CityListClass_E("11C20301", "Cheonan", "천안", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H10704", "Cheongdo", "청도", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11K10001", "Cheongjin", "청진", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11C10301", "Cheongju", "청주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H10503", "Cheongsong", "청송", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11C20502", "Cheongyang", "청양", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11D10101", "Cheorwon", "철원", "대한민국", "Asia/Seoul"),
		new CityListClass_E("OCTVL", "Cherbourg-Octeville", "쉘부르", "프랑스", "Europe/Paris"),
		new CityListClass_E("CHRKS", "Cherkessk", "체르케스크", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("CHS", "Chesapeake", "체사피크", "미국", "America/New_York"),
		new CityListClass_E("CHESG", "Chester", "체스터", "영국", "Europe/London"),
		new CityListClass_E("CHTML", "Chetumal", "체투말", "멕시코", "America/Cancun"),
		new CityListClass_E("CHYNN", "Cheyenne", "샤이엔", "미국", "America/Denver"),
		new CityListClass_E("CHNG", "Chiang Mai", "치앙마이", "태국", "Asia/Bangkok"),
		new CityListClass_E("CHRMN", "Chiaromonte", "치아로몬테", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CHI", "Chiba", "치바", "일본", "Asia/Tokyo"),
		new CityListClass_E("CHBGM", "Chibougamau", "치부가모", "캐나다", "America/Montreal"),
		new CityListClass_E("CGO", "Chicago", "시카고", "미국", "America/Chicago"),
		new CityListClass_E("CHCHB", "Chichibu", "치치부", "일본", "Asia/Tokyo"),
		new CityListClass_E("CHIJ", "Chichijima", "치치지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("CHCLY", "Chiclayo", "치클라요", "페루", "America/Lima"),
		new CityListClass_E("CHICO", "Chico", "치코", "미국", "America/Los_Angeles"),
		new CityListClass_E("CHT", "Chieti", "키에티", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CHHH", "Chihuahua", "치와와", "멕시코", "America/Chihuahua"),
		new CityListClass_E("11H10705", "Chilgok", "칠곡", "대한민국", "Asia/Seoul"),
		new CityListClass_E("CHLLC", "Chillicothe", "칠리코시", "미국", "America/New_York"),
		new CityListClass_E("CHLPN", "Chilpancingo", "칠판싱고", "멕시코", "America/Mexico_City"),
		new CityListClass_E("CHB", "Chimbote", "침보테", "페루", "America/Lima"),
		new CityListClass_E("CHMO", "Chimoio", "시모이우", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("CHNND", "Chinandega", "치난데가", "니카라과", "America/Managua"),
		new CityListClass_E("CHNGL", "Chingola", "칭골라", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("CHNHY", "Chinhoyi", "친호이", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("CHNSL", "Chinsali", "친사리", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("CSH", "Chios", "기오", "그리스", "Europe/Athens"),
		new CityListClass_E("CHPT", "Chipata", "치바타", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("CHTR", "Chitre", "치트레", "파나마", "America/Panama"),
		new CityListClass_E("CHTNG", "Chitungwiza", "치퉁귀자", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("CHJNC", "Chojnice", "호이니체", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("CHJNW", "ChojnOw", "호이누프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("CHKW", "Chokwe", "쵸크웨", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("CHLTC", "Choluteca", "촐루테카", "온두라스", "America/Tegucigalpa"),
		new CityListClass_E("CHOMA", "Choma", "초마", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("CHMTV", "Chomutov", "호무토프", "체코", "Europe/Prague"),
//		new CityListClass_E("CHRZW1", "ChorzOw", "호주프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("COS", "Choshi", "초시", "일본", "Asia/Tokyo"),
		new CityListClass_E("CHCH", "Christchurch", "크라이스트 처치", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass_E("CHRST", "Christiansted", "크리스천스테드", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass_E("CHSTM", "Christmas Island", "크리스마스 섬", "크리스마스 섬", "Indian/Christmas"),
		new CityListClass_E("CHRDM", "Chrudim", "흐루딤", "체코", "Europe/Prague"),
//		new CityListClass_E("CHRZN", "ChrzanOw", "하누프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("CVISTA", "Chula Vista", "출라비스타", "미국", "America/Los_Angeles"),
		new CityListClass_E("11D10301", "Chuncheon", "춘천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11C10101", "Chungju", "충주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11C10401", "Chupungnyeong", "추풍령", "대한민국", "Asia/Seoul"),
		new CityListClass_E("CHUR", "Chur", "쿠아르", "스위스", "Europe/Zurich"),
//		new CityListClass_E("CHU", "Churchill", "처칠", "캐나다", "America/Regina"),
		new CityListClass_E("CHRCH", "Churchill Falls", "처칠폭포", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("CICNT", "Cincinnati", "신시내티", "미국", "America/New_York"),
		new CityListClass_E("CITA", "Cita", "치따", "러시아 연방 국가", "Asia/Omsk"),
		new CityListClass_E("CTRSD", "Citrusdal", "시트러스달", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("BLVR", "Ciudad Bolivar", "시우다드 볼리바르", "베네수엘라", "America/Caracas"),
		new CityListClass_E("DLCS", "Ciudad Delicias", "시우다드 델리시아스", "멕시코", "America/Chihuahua"),
		new CityListClass_E("GYN", "Ciudad Guayana", "시우다드 가이아나", "베네수엘라", "America/Caracas"),
		new CityListClass_E("OBRGN", "Ciudad ObregOn", "시우다드 오브레곤", "멕시코", "America/Hermosillo"),
		new CityListClass_E("CDD", "Ciudad Real", "시우다드레알", "스페인", "Europe/Madrid"),
		new CityListClass_E("RDRG", "Ciudad Rodrigo", "시우다드 로드리고", "스페인", "Europe/Madrid"),
		new CityListClass_E("VCTM", "Ciudad Victoria", "시우다드 빅토리아", "멕시코", "America/Monterrey"),
		new CityListClass_E("CTDLL", "Ciutadella", "시우타델라", "스페인", "Europe/Madrid"),
		new CityListClass_E("CIW", "Ciwandan", "시완단", "인도네시아", "Asia/Jakarta"),
		new CityListClass_E("CLNWL", "Clanwilliam", "클랜윌리암", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("CLARE", "Clare", "클래어", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("CLRKS", "Clarksburg", "클락스버그", "미국", "America/New_York"),
		new CityListClass_E("CLKTN", "Clarksville", "클락스빌", "미국", "America/Chicago"),
		new CityListClass_E("CLRWFL", "Clearwater", "클리어워터", "미국", "America/New_York"),
		new CityListClass_E("CLRMN", "Clermont-Ferrand", "클레르몽페랑", "프랑스", "Europe/Paris"),
		new CityListClass_E("CLV", "Cleveland", "클리블랜드", "미국", "America/New_York"),
		new CityListClass_E("CLFTN", "Clifton", "클리프턴", "미국", "America/New_York"),
		new CityListClass_E("CLNML", "Clonmel", "클론멜", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("NPCA", "Cluj-Napoca", "클루지나포카", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("CTPQ", "Coatepeque", "꼬아떼뻬게", "과테말라", "America/Guatemala"),
		new CityListClass_E("COA", "Coatzacoalcos", "꽈싸꽐코스꽈싸꽐코스", "멕시코", "America/Mexico_City"),
		new CityListClass_E("COBAN", "Coban", "코반", "과테말라", "America/Guatemala"),
		new CityListClass_E("COB", "Cobh", "코브", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("CBJ", "Cobija", "코비하", "볼리비아", "America/La_Paz"),
		new CityListClass_E("CCHBM", "Cochabamba", "코챠밤바", "볼리비아", "America/La_Paz"),
		new CityListClass_E("COC", "Cochin", "코친", "인도", "Asia/Calcutta"),
		new CityListClass_E("CCKBR", "Cockburn Harbour", "콕번하버", "터크스 케이커스 제도", "America/Grand_Turk"),
		new CityListClass_E("BEACH", "Cocoa Beach", "코코아 비치", "미국", "America/New_York"),
		new CityListClass_E("CDRNG", "Codrington", "코드링턴", "앤티가바부다", "America/Antigua"),
		new CityListClass_E("ALENE", "Coeur d'Alene", "코틀레인", "미국", "America/Boise"),
		new CityListClass_E("CHRBR", "Coffs Harbour", "콥스하버", "오스트레일리아", "Australia/Sydney"),
		new CityListClass_E("CMBRA", "Coimbra", "코임브라", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("CLSBR", "Colesberg", "콜레스버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("COLM", "Colima", "꼴리마", "멕시코", "America/Mexico_City"),
		new CityListClass_E("VLLLB", "Collado Villalba", "콜라도 빌라바", "스페인", "Europe/Madrid"),
		new CityListClass_E("STTNC", "College Station", "컬리지 스테이션", "미국", "America/Chicago"),
		new CityListClass_E("COLR", "Colmar", "콜마르", "프랑스", "Europe/Paris"),
		new CityListClass_E("CLGN", "Cologne", "쾰른", "독일", "Europe/Berlin"),
		new CityListClass_E("CLN", "Colon", "콜론", "파나마", "America/Panama"),
		new CityListClass_E("SCRMN", "Colonia del Sacramento", "콜로니아 델 사크라멘토", "우루과이", "America/Montevideo"),
		new CityListClass_E("CLRCO", "Colorado Springs", "콜로라도 스프링스", "미국", "America/Denver"),
		new CityListClass_E("COLMB", "Columbia", "콜럼비아-메릴랜드", "미국", "America/New_York"),
		new CityListClass_E("CLMBR", "Columbia", "콜럼비아-미주리", "미국", "America/Chicago"),
		new CityListClass_E("CLMSC", "Columbia", "콜럼비아-사우스캐롤라이나", "미국", "America/New_York"),
		new CityListClass_E("CLUMB", "Columbia", "콜럼비아-테네시", "미국", "America/Chicago"),
		new CityListClass_E("CBSOH", "Columbus", "콜럼버스-오하이오", "미국", "America/New_York"),
		new CityListClass_E("COLUM", "Columbus", "콜럼버스-인디애나", "미국", "America/Indianapolis"),
		new CityListClass_E("CBSGA", "Columbus", "콜럼버스-조지아", "미국", "America/New_York"),
		new CityListClass_E("CLWYN", "Colwyn Bay", "콜윈 베이", "영국", "Europe/London"),
		new CityListClass_E("CMYG", "Comayagua", "코마야과", "온두라스", "America/Tegucigalpa"),
		new CityListClass_E("CMNDD", "Comendador", "꼬멘다도르", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("CMLLS", "Comillas", "코미야스", "스페인", "Europe/Madrid"),
		new CityListClass_E("DMNGZ", "Comitan de Dominguez", "코미탄 데 도밍구에즈", "멕시코", "America/Mexico_City"),
		new CityListClass_E("COMO", "Comodoro Rivadavia", "코모도로리바다비아", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("CRY", "Conakry", "코나크리", "Guinea", "Africa/Conakry"),
		new CityListClass_E("BHC", "ConcepciOn", "콘셉시온", "칠레", "America/Santiago"),
		new CityListClass_E("CNCEP", "Concepcion", "콘셉시온", "파라과이", "America/Asuncion"),
		new CityListClass_E("CDU", "Concepcion del Uruguay", "우루과이", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("CONC", "Concord", "콩고드-노스캐롤라이나", "미국", "America/New_York"),
		new CityListClass_E("CCDNH", "Concord", "콩고드-뉴햄프셔", "미국", "America/New_York"),
		new CityListClass_E("CCD", "Concord", "콩고드-캘리포니아", "미국", "America/Los_Angeles"),
		new CityListClass_E("CTZ", "Constanta", "콘스탄차", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("CNTGM", "Contagem", "콘타젱", "브라질", "America/Bahia"),
		new CityListClass_E("CNWY", "Conway", "컨웨이", "미국", "America/Chicago"),
		new CityListClass_E("CBRP", "Coober Pedy", "쿠버페디", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("CKVLL", "Cookeville", "쿡빌", "미국", "America/Chicago"),
		new CityListClass_E("COP", "Copenhagen", "코펜하겐", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("COQ", "Coquimbo", "코킴보", "칠레", "America/Santiago"),
		new CityListClass_E("CRDB", "Cordoba", "코르도바", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("CRDE", "COrdoba", "코르도바", "스페인", "Europe/Madrid"),
		new CityListClass_E("CORIA", "Coria", "코리아", "스페인", "Europe/Madrid"),
		new CityListClass_E("CNH", "Corinth", "코린트", "그리스", "Europe/Athens"),
		new CityListClass_E("COO", "Corinto", "코린토", "니카라과", "America/Managua"),
		new CityListClass_E("CRK", "Cork", "코르크", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("CBK", "Corner Brook", "코너 브룩", "캐나다", "America/St_Johns"),
		new CityListClass_E("CORO", "Coro", "코로", "베네수엘라", "America/Caracas"),
		new CityListClass_E("CRNA", "Corona", "코로나", "미국", "America/Los_Angeles"),
		new CityListClass_E("CRZL", "Corozal", "코로살", "벨리즈", "America/Belize"),
		new CityListClass_E("COR", "Corpus Christi", "코퍼스 크리스티", "미국", "America/Chicago"),
		new CityListClass_E("CRRNT", "Corrientes", "코리엔테스", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("CRSCN", "Corsicana", "코르시카나", "미국", "America/Chicago"),
		new CityListClass_E("CRCH", "Coruche", "코루체", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("CORUM", "Corum", "초룸", "터키", "Europe/Istanbul"),
		new CityListClass_E("CORVO", "Corvo", "코르보", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("CSNZ", "Cosenza", "코센차", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CMESA", "Costa Mesa", "코스타 메사", "미국", "America/Los_Angeles"),
		new CityListClass_E("CTTBS", "Cottbus", "코트부스", "독일", "Europe/Berlin"),
		new CityListClass_E("CVLH", "Covilha", "코빌랴", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("CRCW", "Cracow", "크라쿠프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("CRDCK", "Cradock", "크래독", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("CRGVN", "Craigavon", "크레이개번", "영국", "Europe/Belfast"),
		new CityListClass_E("CRAV", "Craiova", "크라이오바", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("CRSCNC", "Crescent City", "크레센트 시티", "미국", "America/Los_Angeles"),
		new CityListClass_E("CRTL", "Creteil", "크레테일", "프랑스", "Europe/Paris"),
		new CityListClass_E("CREWE", "Crewe", "크루", "영국", "Europe/London"),
		new CityListClass_E("CRNML", "crnomelj", "크로멜", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("COE", "Crotone", "크로톤", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CRUZB", "Cruz Bay", "크루즈 베이", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass_E("CCT1", "Cucuta", "쿠쿠타", "콜롬비아", "America/Bogota"),
		new CityListClass_E("CLLR", "Cuellar", "쿠에야르", "스페인", "Europe/Madrid"),
		new CityListClass_E("CENC", "Cuenca", "쿠엔카", "에콰도르", "America/Guayaquil"),
		new CityListClass_E("CNC1", "Cuenca", "쿠엔카", "스페인", "Europe/Madrid"),
		new CityListClass_E("CRNVC", "Cuernavaca", "쿠에르나바카", "멕시코", "America/Mexico_City"),
//		new CityListClass_E("CLCN", "Culiacan", "쿨리아칸", "멕시코", "America/Mazatlan"),
		new CityListClass_E("CLPPR", "Culpeper", "컬페퍼", "미국", "America/New_York"),
		new CityListClass_E("CUM", "Cumana", "쿠마나", "베네수엘라", "America/Caracas"),
		new CityListClass_E("CMBRL", "Cumberland", "컴벌랜드", "미국", "America/New_York"),
//		new CityListClass_E("CMNCK", "Cumnock", "컴녹", "영국", "Europe/London"),
		new CityListClass_E("CUNEO", "Cuneo", "쿠네오", "이탈리아", "Europe/Rome"),
		new CityListClass_E("CRTBA", "Curitiba", "쿠리티바", "브라질", "America/Bahia"),
		new CityListClass_E("CUSCO", "Cusco", "쿠스코", "페루", "America/Lima"),
		new CityListClass_E("CZSTC", "Czestochowa", "쳉스토호바", "폴란드", "Europe/Warsaw"),

	};
}
