package com.weathernews.Weather;
public class Czech_europe {
    public final static CityListClass[] Czech_europe = new CityListClass[] {
//	new CityListClass("NCHD",	"나호트",	"체코",	"Europe/Prague"),
	new CityListClass("JICIN",	"노비지신",	"체코",	"Europe/Prague"),
	new CityListClass("DECIN",	"데친",	"체코",	"Europe/Prague"),
	new CityListClass("RKYCN",	"로키차니",	"체코",	"Europe/Prague"),
	new CityListClass("LOUNY",	"루니",	"체코",	"Europe/Prague"),
	new CityListClass("LBRC",	"리베레츠",	"체코",	"Europe/Prague"),
	new CityListClass("LTMRC",	"리토메리체",	"체코",	"Europe/Prague"),
	new CityListClass("LTVNV",	"리트비노프",	"체코",	"Europe/Prague"),
	new CityListClass("MOST",	"모스트",	"체코",	"Europe/Prague"),
	new CityListClass("BLSLV",	"믈라다볼레슬라프",	"체코",	"Europe/Prague"),
	new CityListClass("BRN2",	"베로운",	"체코",	"Europe/Prague"),
	new CityListClass("BDWS",	"부드바이스",	"체코",	"Europe/Prague"),
	new CityListClass("BRNO",	"브르노",	"체코",	"Europe/Prague"),
	new CityListClass("BRCLV",	"브리클라브",	"체코",	"Europe/Prague"),
	new CityListClass("VSTN",	"브세틴",	"체코",	"Europe/Prague"),
	new CityListClass("BLNSK",	"블란스코",	"체코",	"Europe/Prague"),
	new CityListClass("PRSTJ",	"쁘로스띠에요프",	"체코",	"Europe/Prague"),
	new CityListClass("SSC",	"수지스",	"체코",	"Europe/Prague"),
	new CityListClass("SKLV",	"스콜로프",	"체코",	"Europe/Prague"),
	new CityListClass("STRKN",	"스트라코니스",	"체코",	"Europe/Prague"),
	new CityListClass("JBLNC",	"야블로네츠나트니소우",	"체코",	"Europe/Prague"),
	new CityListClass("ORLV",	"오를로바",	"체코",	"Europe/Prague"),
	new CityListClass("OSTRV",	"오스트라바",	"체코",	"Europe/Prague"),
	new CityListClass("OSTRV1",	"오스트로브",	"체코",	"Europe/Prague"),
	new CityListClass("OPAVA",	"오파바",	"체코",	"Europe/Prague"),
	new CityListClass("OLMC",	"올로모츠",	"체코",	"Europe/Prague"),
	new CityListClass("LABEM",	"우스티나트라벰",	"체코",	"Europe/Prague"),
	new CityListClass("HRDST",	"우헤르스케흐라디슈테",	"체코",	"Europe/Prague"),
	new CityListClass("JHLV",	"이흘라바",	"체코",	"Europe/Prague"),
	new CityListClass("JNDRC",	"인지후프 흐라데츠",	"체코",	"Europe/Prague"),
	new CityListClass("ZNJM",	"즈노이모",	"체코",	"Europe/Prague"),
	new CityListClass("ZLIN",	"즐린",	"체코",	"Europe/Prague"),
	new CityListClass("CESKA",	"체스까 리빠",	"체코",	"Europe/Prague"),
	new CityListClass("KADAN",	"카단",	"체코",	"Europe/Prague"),
	new CityListClass("KRVN",	"카르비나",	"체코",	"Europe/Prague"),
	new CityListClass("CRLSB",	"칼스배드",	"체코",	"Europe/Prague"),
	new CityListClass("KOLIN",	"콜린",	"체코",	"Europe/Prague"),
	new CityListClass("KUTNA",	"쿠트나호라",	"체코",	"Europe/Prague"),
	new CityListClass("KRMRZ",	"크로메리츠",	"체코",	"Europe/Prague"),
	new CityListClass("KLDN1",	"클라드노",	"체코",	"Europe/Prague"),
	new CityListClass("KLTVY",	"클라토비",	"체코",	"Europe/Prague"),
	new CityListClass("TABOR",	"타보르",	"체코",	"Europe/Prague"),
	new CityListClass("TCHV",	"타호프",	"체코",	"Europe/Prague"),
	new CityListClass("TPLC",	"테플리체",	"체코",	"Europe/Prague"),
	new CityListClass("TRBC",	"트래빅",	"체코",	"Europe/Prague"),
//	new CityListClass("TRTNV",	"트루트노프",	"체코",	"Europe/Prague"),
	new CityListClass("PRDBC",	"파르두비체",	"체코",	"Europe/Prague"),
	new CityListClass("PRG1",	"프라하",	"체코",	"Europe/Prague"),
	new CityListClass("PRRV",	"프로로프",	"체코",	"Europe/Prague"),
	new CityListClass("MSTK",	"프리데크미스테크",	"체코",	"Europe/Prague"),
	new CityListClass("PRBRM",	"프리브람",	"체코",	"Europe/Prague"),
	new CityListClass("PLZEN",	"플젠",	"체코",	"Europe/Prague"),
	new CityListClass("PISEK",	"피섹",	"체코",	"Europe/Prague"),
	new CityListClass("HVLCK",	"하블리치쿠프브로트",	"체코",	"Europe/Prague"),
	new CityListClass("CHEB",	"헤프",	"체코",	"Europe/Prague"),
	new CityListClass("HDNN",	"호도닌",	"체코",	"Europe/Prague"),
	new CityListClass("CHMTV",	"호무토프",	"체코",	"Europe/Prague"),
	new CityListClass("KRLV",	"흐라데츠 크랄로베",	"체코",	"Europe/Prague"),
	new CityListClass("CHRDM",	"흐루딤",	"체코",	"Europe/Prague"),
    };
}
