package com.weathernews.Weather;

class DA {
	public final static CityListClass[] da = new CityListClass[] {
		new CityListClass("DANLI", "다늘리", "온두라스", "America/Tegucigalpa"),
		new CityListClass("DNLVG", "다닐로브그라드", "세르비아", "Europe/Belgrade"),
		new CityListClass("DMSCS", "다마스쿠스", "시리아", "Asia/Damascus"),
		new CityListClass("DMI", "다미에타", "이집트", "Africa/Cairo"),
		new CityListClass("DAV", "다바오", "필리핀", "Asia/Manila"),
		new CityListClass("DVNPR", "다벤포트다운스", "미국", "America/Chicago"),
		new CityListClass("DAVID", "다비드", "파나마", "America/Panama"),
		new CityListClass("DWNY", "다우니", "미국", "America/Los_Angeles"),
		new CityListClass("DWN", "다윈", "오스트레일리아", "Australia/Darwin"),
		new CityListClass("ZAWRD", "다이르앗자우르", "시리아", "Asia/Damascus"),
		new CityListClass("DYRSB", "다이어스버그", "미국", "America/Chicago"),
		new CityListClass("DKR", "다카르", "세네갈", "Africa/Dakar"),
		new CityListClass("11C10202", "단양", "대한민국", "Asia/Seoul"),
		new CityListClass("DLLS", "달라스", "미국", "America/Chicago"),
		new CityListClass("DLTN", "달튼", "미국", "America/New_York"),
		new CityListClass("11F20504", "담양", "대한민국", "Asia/Seoul"),
		new CityListClass("DODGEC", "닷지 시티", "미국", "America/Chicago"),
		new CityListClass("11C20103", "당진", "대한민국", "Asia/Seoul"),
		new CityListClass("11D20201", "대관령", "대한민국", "Asia/Seoul"),
		new CityListClass("11H10701", "대구", "대한민국", "Asia/Seoul"),
		new CityListClass("11C20401", "대전", "대한민국", "Asia/Seoul"),
		new CityListClass("DNBRY", "댄버리", "미국", "America/New_York"),
		new CityListClass("DNVLL1", "댄빌-버지니아", "미국", "America/New_York"),
		new CityListClass("DNVLL", "댄빌-일리노이", "미국", "America/Chicago"),
		new CityListClass("DALY", "댈리 시티", "미국", "America/Los_Angeles"),
		new CityListClass("PAST", "더 파스", "캐나다", "America/Regina"),
		new CityListClass("DGLS", "더글라스", "영국", "Europe/London"),
		new CityListClass("DGLAS", "더글러스", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("DND", "더니든", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass("DRHM", "더럼", "미국", "America/New_York"),
//		new CityListClass("DRHM1", "더럼", "영국", "Europe/London"),
		new CityListClass("DUR", "더반", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("VALLY", "더밸리", "앵귈라", "America/Anguilla"),
		new CityListClass("DUBBO", "더보", "오스트레일리아", "Australia/Sydney"),
		new CityListClass("DBL", "더블린", "아일랜드", "Europe/Dublin"),
		new CityListClass("DRRG", "더비", "영국", "Europe/London"),
		new CityListClass("DNDK", "던독", "미국", "America/New_York"),
		new CityListClass("DDK", "던독", "아일랜드", "Europe/Dublin"),
		new CityListClass("DNDEE", "던디", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("DDE", "던디", "영국", "Europe/London"),
		new CityListClass("DNFRM", "던펌린", "영국", "Europe/London"),
		new CityListClass("DLU", "덜루스", "미국", "America/Chicago"),
		new CityListClass("DMFRS", "덤프리스", "영국", "Europe/London"),
		new CityListClass("DDC", "데그라드 데 칸", "기아나", "America/Cayenne"),
		new CityListClass("DNZL", "데니즐리", "터키", "Europe/Istanbul"),
		new CityListClass("DEVA", "데바", "루마니아", "Europe/Bucharest"),
		new CityListClass("DEBAR", "데바르", "마케도니아", "Europe/Skopje"),
		new CityListClass("DEV", "데번포트", "오스트레일리아", "Australia/Hobart"),
		new CityListClass("DBRCN", "데브레첸", "헝가리", "Europe/Budapest"),
//		new CityListClass("DBC", "데비차", "폴란드", "Europe/Warsaw"),
		new CityListClass("DSS", "데사우", "독일", "Europe/Berlin"),
		new CityListClass("DYTN", "데이토나 비치", "미국", "America/New_York"),
		new CityListClass("DYNOH", "데이튼", "미국", "America/New_York"),
		new CityListClass("DECIN", "데친", "체코", "Europe/Prague"),
		new CityListClass("DNNRY", "덴느리", "세인트루시아", "America/St_Lucia"),
		new CityListClass("DNV", "덴버", "미국", "America/Denver"),
		new CityListClass("DNTN", "덴튼", "미국", "America/Chicago"),
		new CityListClass("DNPSR", "덴파사르", "인도네시아", "Asia/Makassar"),
		new CityListClass("DEH", "덴헬데르", "네덜란드", "Europe/Amsterdam"),
		new CityListClass("DILI", "델리", "동티모르", "Asia/Dili"),
		new CityListClass("DLCV", "델체보", "마케도니아", "Europe/Skopje"),
		new CityListClass("SBSTN", "도노스티아/산 세바스챤", "스페인", "Europe/Madrid"),
		new CityListClass("DNJVR", "도노우이바로슈", "헝가리", "Europe/Budapest"),
		new CityListClass("DTHN", "도단", "미국", "America/Chicago"),
		new CityListClass("DDM", "도도마", "탄자니아", "Africa/Dar_es_Salaam"),
		new CityListClass("DRTMN", "도르트문트", "독일", "Europe/Berlin"),
		new CityListClass("DOVER", "도버", "미국", "America/New_York"),
		new CityListClass("HRMNS", "도스 에르마나스", "스페인", "Europe/Madrid"),
		new CityListClass("DWSN", "도슨", "캐나다", "America/Dawson"),
		new CityListClass("DBRC", "도우브릭", "불가리아", "Europe/Sofia"),
		new CityListClass("TOK", "도쿄", "일본", "Asia/Tokyo"),
		new CityListClass("DPHN", "도핀", "캐나다", "America/Regina"),
		new CityListClass("DOH", "도하", "카타르", "Asia/Qatar"),
		new CityListClass("11E00102", "독도", "대한민국", "Asia/Seoul"),
		new CityListClass("DMBVR", "돔보바르", "헝가리", "Europe/Budapest"),
//		new CityListClass("DMBS", "돔바스", "노르웨이", "Europe/Oslo"),
		new CityListClass("TOT", "돗토리", "일본", "Asia/Tokyo"),
		new CityListClass("11B20401", "동두천", "대한민국", "Asia/Seoul"),
		new CityListClass("11D20601", "동해", "대한민국", "Asia/Seoul"),
		new CityListClass("CXSD", "두께 데 까시아스", "브라질", "America/Bahia"),
		new CityListClass("DRZN", "두라스노", "우루과이", "America/Montevideo"),
		new CityListClass("DRS", "두르레스", "알바니아", "Europe/Tirane"),
		new CityListClass("DUB", "두바이", "아랍에미리트", "Asia/Dubai"),
		new CityListClass("DBYY", "두바이-외곽", "아랍에미리트", "Asia/Dubai"),
		new CityListClass("DUBR", "두브로브니크", "크로아티아", "Europe/Zagreb"),
		new CityListClass("DSHNB", "두샨베", "타지키스탄", "Asia/Dushanbe"),
		new CityListClass("DKHN", "두칸", "카타르", "Asia/Qatar"),
		new CityListClass("DUQM", "두큼", "오만", "Asia/Muscat"),
		new CityListClass("BOIS", "뒤 보이스", "미국", "America/New_York"),
		new CityListClass("DDLNG", "뒤들랑주", "룩셈부르크", "Europe/Luxembourg"),
		new CityListClass("DSSLD", "뒤셀도르프", "독일", "Europe/Berlin"),
		new CityListClass("DUIS", "뒤스부르크", "독일", "Europe/Berlin"),
		new CityListClass("DUCOS", "뒤코", "마르티니크", "America/Martinique"),
		new CityListClass("DUGMX", "듀랑고", "멕시코", "America/Monterrey"),
		new CityListClass("DRGGN", "드라기냥", "프랑스", "Europe/Paris"),
		new CityListClass("DRA", "드라멘", "노르웨이", "Europe/Oslo"),
		new CityListClass("DRSDN", "드레스덴", "독일", "Europe/Berlin"),
		new CityListClass("DRZDN", "드레즈덴코", "폴란드", "Europe/Warsaw"),
		new CityListClass("DTSEV", "드로베타투르누세베린", "루마니아", "Europe/Bucharest"),
		new CityListClass("DRGHD", "드로이다", "아일랜드", "Europe/Dublin"),
		new CityListClass("DRSKN", "드루스키닌카이", "리투아니아", "Europe/Vilnius"),
		new CityListClass("DRYPS", "드리오피스", "그리스", "Europe/Athens"),
		new CityListClass("DLMNT", "들레몽", "스위스", "Europe/Zurich"),
		new CityListClass("BAINS", "디뉴 레 뱅", "프랑스", "Europe/Paris"),
		new CityListClass("MNSD", "디모인", "미국", "America/Chicago"),
		new CityListClass("DYRBK", "디야르바키르", "터키", "Europe/Istanbul"),
		new CityListClass("DRBRN", "디어본", "미국", "America/Detroit"),
		new CityListClass("DPP", "디에프", "프랑스", "Europe/Paris"),
		new CityListClass("GYOR", "디외르", "헝가리", "Europe/Budapest"),
		new CityListClass("DIJON", "디종", "프랑스", "Europe/Paris"),
		new CityListClass("DEASE", "디즈 레이크", "캐나다", "America/Vancouver"),
		new CityListClass("DZRDW", "디지아르도우오", "폴란드", "Europe/Warsaw"),
		new CityListClass("DCTR", "디카터-알라바마", "미국", "America/Chicago"),
		new CityListClass("DCTR1", "디카터-일리노이", "미국", "America/Chicago"),
		new CityListClass("DKRCH", "디키르히", "룩셈부르크", "Europe/Luxembourg"),
		new CityListClass("DTT", "디트로이트", "미국", "America/Detroit"),
		new CityListClass("DIG", "딕비", "캐나다", "America/Halifax"),
		new CityListClass("PDS", "딕슨항", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("TLN", "따렌", "중국", "Asia/Shanghai"),
		new CityListClass("TPP", "또뽈로밤뽀", "멕시코", "America/Mazatlan"),
		new CityListClass("TBO", "뚜르보", "콜롬비아", "America/Bogota"),
		new CityListClass("TRNT", "뜨레인따 이 뜨레스", "우루과이", "America/Montevideo"),

//		new CityListClass("DANLI","다늘리","온두라스","America/Tegucigalpa"),
//		new CityListClass("DNLVG","다닐로브그라드","세르비아","Europe/Belgrade"),
//		new CityListClass("DMSCS","다마스쿠스","시리아","Asia/Damascus"),
//	new CityListClass("DMI","다미에타","이집트","Africa/Cairo"),
//		new CityListClass("DAV","다바오","필리핀","Asia/Manila"),
//		new CityListClass("DVNPR","다벤포트다운스","미국","America/Chicago"),
//		new CityListClass("DAVID","다비드","파나마","America/Panama"),
//		new CityListClass("DWNY","다우니","미국","America/Los_Angeles"),
//		new CityListClass("DWN","다윈","오스트레일리아","Australia/Darwin"),
//		new CityListClass("ZAWRD","다이르앗자우르","시리아","Asia/Damascus"),
//		new CityListClass("DYRSB","다이어스버그","미국","America/Chicago"),
//		new CityListClass("DKR","다카르","세네갈","Africa/Dakar"),
//			new CityListClass("11C10202","단양","대한민국","Asia/Seoul"),
//		new CityListClass("DLLS","달라스","미국","America/Chicago"),
//		new CityListClass("DLTN","달튼","미국","America/New_York"),
//			new CityListClass("11F20504","담양","대한민국","Asia/Seoul"),
//		new CityListClass("DODGEC","닷지 시티","미국","America/Chicago"),
//			new CityListClass("11C20103","당진","대한민국","Asia/Seoul"),
//			new CityListClass("11D20201","대관령","대한민국","Asia/Seoul"),
//			new CityListClass("11H10701","대구","대한민국","Asia/Seoul"),
//			new CityListClass("11C20401","대전","대한민국","Asia/Seoul"),
//		new CityListClass("DNBRY","댄버리","미국","America/New_York"),
//		new CityListClass("DNVLL1","댄빌","미국","America/New_York"),
//		new CityListClass("DNVLL","댄빌","미국","America/Chicago"),
//		new CityListClass("DALY","댈리 시티","미국","America/Los_Angeles"),
//		new CityListClass("PAST","더 파스","캐나다","America/Regina"),
//		new CityListClass("DGLS","더글라스","영국","Europe/London"),
//		new CityListClass("DGLAS","더글러스","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("DND","더니든","뉴질랜드","Pacific/Auckland"),
//		new CityListClass("DRHM","더럼","미국","America/New_York"),
//		new CityListClass("DRHM1","더럼","영국","Europe/London"),
//		new CityListClass("DUR","더반","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("VALLY","더밸리","앵귈라","America/Anguilla"),
//		new CityListClass("DUBBO","더보","오스트레일리아","Australia/Sydney"),
//		new CityListClass("DBL","더블린","아일랜드","Europe/Dublin"),
//		new CityListClass("DRRG","더비","영국","Europe/London"),
//		new CityListClass("DNDK","던독","미국","America/New_York"),
//		new CityListClass("DDK","던독","아일랜드","Europe/Dublin"),
//		new CityListClass("DNDEE","던디","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("DDE","던디","영국","Europe/London"),
//		new CityListClass("DNFRM","던펌린","영국","Europe/London"),
//		new CityListClass("DLU","덜루스","미국","America/Chicago"),
//		new CityListClass("DMFRS","덤프리스","영국","Europe/London"),
//		new CityListClass("DDC","데그라드 데 칸","기아나","America/Cayenne"),
//		new CityListClass("DNZL","데니즐리","터키","Europe/Istanbul"),
//		new CityListClass("DEVA","데바","루마니아","Europe/Bucharest"),
//		new CityListClass("DEBAR","데바르","마케도니아","Europe/Skopje"),
//		new CityListClass("DEV","데번포트","오스트레일리아","Australia/Hobart"),
//		new CityListClass("DBC","데비차","폴란드","Europe/Warsaw"),
//		new CityListClass("DSS","데사우","독일","Europe/Berlin"),
//		new CityListClass("DYTN","데이토나 비치","미국","America/New_York"),
//		new CityListClass("DYNOH","데이튼","미국","America/New_York"),
//		new CityListClass("DECIN","데친","체코","Europe/Prague"),
//		new CityListClass("DNNRY","덴느리","세인트루시아","America/St_Lucia"),
//		new CityListClass("DNV","덴버","미국","America/Denver"),
//		new CityListClass("DNTN","덴튼","미국","America/Chicago"),
//		new CityListClass("DNPSR","덴파사르","인도네시아","Asia/Makassar"),
//		new CityListClass("DILI","델리","동티모르","Asia/Dili"),
//		new CityListClass("DLCV","델체보","마케도니아","Europe/Skopje"),
//		new CityListClass("SBSTN","도노스티아/산 세바스챤","스페인","Europe/Madrid"),
//		new CityListClass("DTHN","도단","미국","America/Chicago"),
//		new CityListClass("DDM","도도마","탄자니아","Africa/Dar_es_Salaam"),
//		new CityListClass("DRTMN","도르트문트","독일","Europe/Berlin"),
//		new CityListClass("DOVER","도버","미국","America/New_York"),
//		new CityListClass("HRMNS","도스 에르마나스","스페인","Europe/Madrid"),
//		new CityListClass("DWSN","도슨","캐나다","America/Dawson"),
//		new CityListClass("DBRC","도우브릭","불가리아","Europe/Sofia"),
//		new CityListClass("TOK","도쿄","일본","Asia/Tokyo"),
//		new CityListClass("DPHN","도핀","캐나다","America/Regina"),
//		new CityListClass("DOH","도하","카타르","Asia/Qatar"),
//			new CityListClass("11E00102","독도","대한민국","Asia/Seoul"),
//		new CityListClass("DMBS","돔바스","노르웨이","Europe/Oslo"),
//		new CityListClass("TOT","돗토리","일본","Asia/Tokyo"),
//			new CityListClass("11B20401","동두천","대한민국","Asia/Seoul"),
//			new CityListClass("11D20601","동해","대한민국","Asia/Seoul"),
//		new CityListClass("CXSD","두께 데 까시아스","브라질","America/Bahia"),
//		new CityListClass("DRZN","두라스노","우루과이","America/Montevideo"),
//		new CityListClass("DRS","두르레스","알바니아","Europe/Tirane"),
//		new CityListClass("DUB","두바이","아랍에미리트","Asia/Dubai"),
//		new CityListClass("DBYY","두바이-외곽","아랍에미리트","Asia/Dubai"),
//		new CityListClass("DUBR","두브로브니크","크로아티아","Europe/Zagreb"),
//		new CityListClass("DSHNB","두샨베","타지키스탄","Asia/Dushanbe"),
//		new CityListClass("DKHN","두칸","카타르","Asia/Qatar"),
//		new CityListClass("DUQM","두큼","오만","Asia/Muscat"),
//		new CityListClass("BOIS","뒤 보이스","미국","America/New_York"),
//		new CityListClass("DDLNG","뒤들랑주","룩셈부르크","Europe/Luxembourg"),
//		new CityListClass("DSSLD","뒤셀도르프","독일","Europe/Berlin"),
//		new CityListClass("DUIS","뒤스부르크","독일","Europe/Berlin"),
//		new CityListClass("DUCOS","뒤코","마르티니크","America/Martinique"),
//		new CityListClass("DUGMX","듀랑고","멕시코","America/Monterrey"),
//		new CityListClass("DRGGN","드라기냥","프랑스","Europe/Paris"),
//		new CityListClass("DRA","드라멘","노르웨이","Europe/Oslo"),
//		new CityListClass("DRSDN","드레스덴","독일","Europe/Berlin"),
//		new CityListClass("DRZDN","드레즈덴코","폴란드","Europe/Warsaw"),
//		new CityListClass("DTSEV","드로베타투르누세베린","루마니아","Europe/Bucharest"),
//		new CityListClass("DRGHD","드로이다","아일랜드","Europe/Dublin"),
//	    	new CityListClass("DRSKN","드루스키닌카이","리투아니아","Europe/Vilnius"),
//		new CityListClass("DRYPS","드리오피스","그리스","Europe/Athens"),
//		new CityListClass("DLMNT","들레몽","스위스","Europe/Zurich"),
//		new CityListClass("BAINS","디뉴 레 뱅","프랑스","Europe/Paris"),
//		new CityListClass("MNSD","디모인","미국","America/Chicago"),
//		new CityListClass("DYRBK","디야르바키르","터키","Europe/Istanbul"),
//		new CityListClass("DRBRN","디어본","미국","America/Detroit"),
//		new CityListClass("DPP","디에프","프랑스","Europe/Paris"),
//		new CityListClass("DIJON","디종","프랑스","Europe/Paris"),
//		new CityListClass("DEASE","디즈 레이크","캐나다","America/Vancouver"),
//		new CityListClass("DZRDW","디지아르도우오","폴란드","Europe/Warsaw"),
//		new CityListClass("DCTR1",	"디카터-일리노이",	"미국",	"America/Chicago"),
//		new CityListClass("DCTR",	"디카터-알라바마",	"미국",	"America/Chicago"),
//		new CityListClass("DKRCH","디키르히","룩셈부르크","Europe/Luxembourg"),
//		new CityListClass("DTT","디트로이트","미국","America/Detroit"),
//		new CityListClass("DIG","딕비","캐나다","America/Halifax"),
//				new CityListClass("PDS","딕슨항","말레이시아","Asia/Kuala_Lumpur"),
//			new CityListClass("TLN","따렌","중국","Asia/Shanghai"),
//		new CityListClass("TPP","또뽈로밤뽀","멕시코","America/Mazatlan"),
//		new CityListClass("TBO","뚜르보","콜롬비아","America/Bogota"),
//		new CityListClass("TRNT","뜨레인따 이 뜨레스","우루과이","America/Montevideo"),
	};
}
