package com.weathernews.Weather;
public class Denmark_europe {
    public final static CityListClass[] Denmark_europe = new CityListClass[] {
	new CityListClass("NSTVD",	"네스트베드",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("NUUK",	"누크",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("NYKBN",	"뉘쾨빙팔스터",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("SORO1",	"로뢰",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("RSKLD",	"로스킬레",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("RIBE",	"리베",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("RNGKB",	"링쾨빙",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("MAIBO",	"마리보",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("VEJLE",	"바일레",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("BRNDB",	"브뢴드비",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("VBRG",	"비보르",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("SDB",	"쇠네르보르",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("SKG",	"스카겐",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("STEGE",	"스티지",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("SLKBR",	"실게보르",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("EGTVD",	"에그트베드",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("ESB",	"에스비에르",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("ELS",	"엘시노어",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("ODN",	"오덴세",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("AAS",	"오르후스",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("AAB",	"오벤로",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("AAL",	"올보르",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("KOGE",	"코게",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("COP",	"코펜하겐",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("THSTD",	"티스테드",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("FARUM",	"파룸",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("FBRG",	"파아보리",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("HRNNG",	"헤닝",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("HLBK",	"홀베크",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("HLSTB",	"홀스테브로",	"덴마크",	"Europe/Copenhagen"),
	new CityListClass("HLLRD",	"힐러르웨드",	"덴마크",	"Europe/Copenhagen"),
    };
}
