package com.weathernews.Weather;

public class E {
	public final static CityListClass_E[] e = new CityListClass_E[] {
		new CityListClass_E("LVRPLE", "East Liverpool", "이스트 리버풀", "미국", "America/New_York"),
		new CityListClass_E("ELAX", "East Los Angeles", "이스트 로스 앤젤레스", "미국", "America/Los_Angeles"),
		new CityListClass_E("POINT", "East Point", "이스트 포인트", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("ISLND", "Easter Island", "이스터섬", "칠레", "Pacific/Easter"),
		new CityListClass_E("CLRE", "Eau Claire", "오클레어", "미국", "America/Chicago"),
		new CityListClass_E("ECIJA", "ecija", "에키자", "스페인", "Europe/Madrid"),
		new CityListClass_E("EDB", "Edinburgh", "에딘버러", "영국", "Europe/London"),
		new CityListClass_E("EDRN", "Edirne", "에디르네", "터키", "Europe/Istanbul"),
		new CityListClass_E("EDSN", "Edison", "에디슨", "미국", "America/New_York"),
		new CityListClass_E("EDM", "Edmonton", "에드몬튼", "캐나다", "America/Edmonton"),
		new CityListClass_E("EDMND", "Edmundston", "애드먼스턴", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("ENHN", "Eenhana", "인하나", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("EGER1", "Eger", "에게르", "헝가리", "Europe/Budapest"),
		new CityListClass_E("EGRSN", "Egersund", "에게르순", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("EGLSS", "Egilsstadir", "에길스타디르", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass_E("EGTVD", "Egtved", "에그트베드", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("ENDHV", "Eindhoven", "에인트호번", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("ESNCH", "Eisenach", "아이제나흐", "독일", "Europe/Berlin"),
		new CityListClass_E("ESNST", "Eisenstadt", "아이젠슈타트", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("EBL", "El Bluff", "엘브럴프", "니카라과", "America/Managua"),
		new CityListClass_E("EJIDO", "El Ejido", "엘 에히도", "스페인", "Europe/Madrid"),
		new CityListClass_E("MONTE", "El Monte", "엘 몬테", "미국", "America/Los_Angeles"),
		new CityListClass_E("PASO", "El Paso", "엘파소", "미국", "America/Denver"),
		new CityListClass_E("SUERT", "El Pont de Suert", "엘폰데 수에르", "스페인", "Europe/Madrid"),
		new CityListClass_E("PRVNR", "El Porvenir", "엘포베니르", "파나마", "America/Panama"),
		new CityListClass_E("ELZG", "Elazig", "엘라지", "터키", "Europe/Istanbul"),
		new CityListClass_E("ELBSN", "Elbasan", "엘바산", "알바니아", "Europe/Tirane"),
		new CityListClass_E("ELBLG", "Elblag", "엘블라크", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("ELKTR1", "Elektrenai", "엘렉트레네이", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("ELST", "Elista", "옐리스타", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("ELZ", "Elizabeth", "엘리자베스", "미국", "America/New_York"),
		new CityListClass_E("ELZBT", "Elizabethtown", "엘리자베스타운", "미국", "America/New_York"),
		new CityListClass_E("ELZND", "Elizondo", "엘리존도", "스페인", "Europe/Madrid"),
		new CityListClass_E("GROVE", "Elk Grove", "엘크 그로브", "미국", "America/Los_Angeles"),
		new CityListClass_E("ELKHR", "Elkhart", "엘크 하트", "미국", "America/Indianapolis"),
		new CityListClass_E("ELLT", "Elliot", "엘리어트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("ELS", "Elsinore", "엘시노어", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("ELX", "Elx", "엘체", "스페인", "Europe/Madrid"),
		new CityListClass_E("EMD", "Emmen", "엠멘", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("ENCRN", "Encarnacion", "엔카나시온", "파라과이", "America/Asuncion"),
		new CityListClass_E("ENCNS", "Encinasola", "엔시나소라", "스페인", "Europe/Madrid"),
		new CityListClass_E("HRBR", "English Harbour Town", "잉글리쉬 하버 타운", "앤티가바부다", "America/Antigua"),
		new CityListClass_E("ENNIS", "Ennis", "에니스", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("ENSCH", "Enschede", "엔스헤데", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("ENS", "Ensenada", "엔세나다", "멕시코", "America/Mazatlan"),
		new CityListClass_E("EPNL", "epinal", "에피날", "프랑스", "Europe/Paris"),
		new CityListClass_E("EPWRT", "Epworth", "에프워스", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("ERD", "erd", "에르디", "헝가리", "Europe/Budapest"),
		new CityListClass_E("ERSS", "Eresos", "에레소스", "그리스", "Europe/Athens"),
		new CityListClass_E("ERVN", "Ereven", "에레벤", "아르메니아", "Asia/Yerevan"),
		new CityListClass_E("ERFRT", "Erfurt", "에르푸르트", "독일", "Europe/Berlin"),
		new CityListClass_E("ERIEPA", "Erie", "에리", "미국", "America/New_York"),
		new CityListClass_E("ERK1", "Erk", "어크", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("ERML", "Ermelo", "어 멜로", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("ERMPL", "Ermupoli", "에르무폴리", "그리스", "Europe/Athens"),
		new CityListClass_E("ERRMNG", "Erromango Island", "에로망고 섬", "Vanuatu", "Pacific/Efate"),
		new CityListClass_E("ERZNC", "Erzincan", "에르진잔", "터키", "Europe/Istanbul"),
		new CityListClass_E("ERZRM", "Erzurum", "에르주룸", "터키", "Europe/Istanbul"),
		new CityListClass_E("ESSH", "Esashi", "에사시", "일본", "Asia/Tokyo"),
		new CityListClass_E("ESB", "Esbjerg", "에스비에르", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("ALZTT", "Esch-sur-Alzette", "에쉬 슈르 알체떼", "룩셈부르크", "Europe/Luxembourg"),
		new CityListClass_E("ESCHN", "Eschen", "에셴", "리히텐슈타인", "Europe/Vaduz"),
		new CityListClass_E("ESDD", "Escondido", "에스콘디도", "미국", "America/Los_Angeles"),
		new CityListClass_E("ESCNT", "Escuintla", "에스쿠인틀라", "과테말라", "America/Guatemala"),
		new CityListClass_E("ESKSH", "Eskisehir", "에스키셰히르", "터키", "Europe/Istanbul"),
		new CityListClass_E("ESS", "Esmeraldas", "에스메랄다스", "에콰도르", "America/Guayaquil"),
		new CityListClass_E("ESSEN", "Essen", "에센", "독일", "Europe/Berlin"),
		new CityListClass_E("ESTL", "Esteli", "에스텔리", "니카라과", "America/Managua"),
		new CityListClass_E("EGN", "Eugene", "유진", "미국", "America/Los_Angeles"),
		new CityListClass_E("11C10103", "Eumseong", "음성", "대한민국", "Asia/Seoul"),
		new CityListClass_E("EUPEN", "Eupen", "외펜", "벨기에", "Europe/Brussels"),
		new CityListClass_E("ERK", "Eureka", "유레카", "미국", "America/Los_Angeles"),
		new CityListClass_E("EVNSV", "Evansville", "에반스빌", "미국", "America/Chicago"),
		new CityListClass_E("EVE", "Everett", "에버렛", "미국", "America/Los_Angeles"),
		new CityListClass_E("EVORA", "evora", "에보라", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("EVRX", "evreux", "에브뢰", "프랑스", "Europe/Paris"),
		new CityListClass_E("EVRY", "evry", "에브리", "프랑스", "Europe/Paris"),
		new CityListClass_E("EXTR", "Exeter", "엑서터", "영국", "Europe/London"),
		new CityListClass_E("EXG", "Exmouth", "에스 마우스", "오스트레일리아", "Australia/Perth"),
		new CityListClass_E("EZCRY", "Ezcaray", "에즈까레이", "스페인", "Europe/Madrid"),

	};
}
