package com.weathernews.Weather;
public class England_europe {
    public final static CityListClass[] England_europe = new CityListClass[] {
//	new CityListClass("GRNCK",	"그리녹",	"영국",	"Europe/London"),
//	new CityListClass("GLS",	"글래스고",	"영국",	"Europe/London"),
	new CityListClass("GLNLC",	"글렌루스",	"영국",	"Europe/London"),
//	new CityListClass("GLO",	"글로스터",	"영국",	"Europe/London"),
	new CityListClass("NRWCH",	"노리치",	"영국",	"Europe/London"),
	new CityListClass("NRTHP",	"노샘프턴",	"영국",	"Europe/London"),
	new CityListClass("NTTNG",	"노팅엄",	"영국",	"Europe/London"),
//	new CityListClass("NCE",	"뉴캐슬어폰타인",	"영국",	"Europe/London"),
	new CityListClass("NWTNB",	"뉴튼애비",	"영국",	"Europe/Belfast"),
	new CityListClass("NPT",	"뉴포트",	"영국",	"Europe/London"),
	new CityListClass("DGLS",	"더글라스",	"영국",	"Europe/London"),
//	new CityListClass("DRHM1",	"더럼",	"영국",	"Europe/London"),
	new CityListClass("DRRG",	"더비",	"영국",	"Europe/London"),
	new CityListClass("DDE",	"던디",	"영국",	"Europe/London"),
	new CityListClass("DNFRM",	"던펌린",	"영국",	"Europe/London"),
	new CityListClass("DMFRS",	"덤프리스",	"영국",	"Europe/London"),
	new CityListClass("LER",	"러윅",	"영국",	"Europe/London"),
	new CityListClass("LDN",	"런던",	"영국",	"Europe/London"),
	new CityListClass("LDD",	"런던데리",	"영국",	"Europe/Belfast"),
	new CityListClass("READG",	"레딩",	"영국",	"Europe/London"),
	new CityListClass("LCSTR",	"레스터",	"영국",	"Europe/London"),
	new CityListClass("WRXH",	"렉섬",	"영국",	"Europe/London"),
	new CityListClass("LTHRH",	"리더헤드",	"영국",	"Europe/London"),
	new CityListClass("LIV",	"리버풀",	"영국",	"Europe/London"),
	new CityListClass("LIVIN",	"리빙스톤",	"영국",	"Europe/London"),
	new CityListClass("LEEDS",	"리즈",	"영국",	"Europe/London"),
	new CityListClass("LSBRN",	"리즈번",	"영국",	"Europe/Belfast"),
	new CityListClass("RHYL",	"릴",	"영국",	"Europe/London"),
	new CityListClass("LNCOL",	"링컨",	"영국",	"Europe/London"),
	new CityListClass("MCH",	"맨체스터",	"영국",	"Europe/London"),
	new CityListClass("MRTHY",	"머서티드빌",	"영국",	"Europe/London"),
	new CityListClass("MBH",	"미들즈브러",	"영국",	"Europe/London"),
	new CityListClass("FRNSS",	"배로인퍼니스",	"영국",	"Europe/London"),
//	new CityListClass("BANGR",	"뱅거",	"영국",	"Europe/Belfast"),
	new CityListClass("BRMNG",	"버밍엄",	"영국",	"Europe/London"),
//	new CityListClass("BFA",	"벨파스트",	"영국",	"Europe/Belfast"),
	new CityListClass("BGNR",	"보그너리저스",	"영국",	"Europe/London"),
	new CityListClass("BRNMT",	"본머스",	"영국",	"Europe/London"),
	new CityListClass("BLTN",	"볼턴",	"영국",	"Europe/London"),
	new CityListClass("BRGHT",	"브라이턴",	"영국",	"Europe/London"),
	new CityListClass("BTO",	"브리스톨",	"영국",	"Europe/London"),
	new CityListClass("BLCKP",	"블랙풀",	"영국",	"Europe/London"),
//	new CityListClass("STHND",	"사우스엔드온시",	"영국",	"Europe/London"),
	new CityListClass("SOU",	"사우스햄턴",	"영국",	"Europe/London"),
	new CityListClass("ALBNS",	"세인트올번스",	"영국",	"Europe/London"),
	new CityListClass("SAINT",	"세인트이브스",	"영국",	"Europe/London"),
//	new CityListClass("SHFFL",	"쉐필드",	"영국",	"Europe/London"),
	new CityListClass("SHRWS",	"슈루즈버리",	"영국",	"Europe/London"),
	new CityListClass("TRENT",	"스노크온트렌트",	"영국",	"Europe/London"),
	new CityListClass("ABRTW",	"스완지",	"영국",	"Europe/London"),
	new CityListClass("SWNDN",	"스윈던",	"영국",	"Europe/London"),
	new CityListClass("STRLN",	"스털링",	"영국",	"Europe/London"),
	new CityListClass("SRY",	"스토너웨이",	"영국",	"Europe/London"),
	new CityListClass("SLGH",	"슬로",	"영국",	"Europe/London"),
//	new CityListClass("ARRAN",	"애런 섬",	"영국",	"Europe/London"),
	new CityListClass("ABE",	"애버딘",	"영국",	"Europe/London"),
	new CityListClass("ABRYS",	"애버리스트위스",	"영국",	"Europe/London"),
	new CityListClass("ASHFR",	"애쉬포드",	"영국",	"Europe/London"),
	new CityListClass("IRVIN",	"얼바인",	"영국",	"Europe/London"),
	new CityListClass("EDB",	"에딘버러",	"영국",	"Europe/London"),
//	new CityListClass("AYR",	"에어",	"영국",	"Europe/London"),
	new CityListClass("EXTR",	"엑서터",	"영국",	"Europe/London"),
	new CityListClass("OMAGH",	"오마",	"영국",	"Europe/Belfast"),
//	new CityListClass("OBAN",	"오반",	"영국",	"Europe/London"),
	new CityListClass("OXF",	"옥스퍼드",	"영국",	"Europe/London"),
	new CityListClass("ALSTN",	"올스턴",	"영국",	"Europe/London"),
	new CityListClass("YORK",	"요크",	"영국",	"Europe/London"),
//	new CityListClass("WORCE",	"우스터",	"영국",	"Europe/London"),
	new CityListClass("INVRNY",	"인버네스",	"영국",	"Europe/London"),
	new CityListClass("IPS",	"입스위치",	"영국",	"Europe/London"),
//	new CityListClass("GLLNG",	"질링엄",	"영국",	"Europe/London"),
	new CityListClass("CHESG",	"체스터",	"영국",	"Europe/London"),
	new CityListClass("CHLMS",	"첼름스퍼드",	"영국",	"Europe/London"),
	new CityListClass("CRD",	"카디프",	"영국",	"Europe/London"),
	new CityListClass("CRLSL",	"칼라일",	"영국",	"Europe/London"),
	new CityListClass("STPHN",	"커크비 스티븐",	"영국",	"Europe/London"),
	new CityListClass("KRK",	"커크월l",	"영국",	"Europe/London"),
//	new CityListClass("CMNCK",	"컴녹",	"영국",	"Europe/London"),
	new CityListClass("KSWCK",	"케스윅",	"영국",	"Europe/London"),
	new CityListClass("CBGG",	"케임브리지",	"영국",	"Europe/London"),
	new CityListClass("KNDL",	"켄다l",	"영국",	"Europe/London"),
	new CityListClass("CLWYN",	"콜윈 베이",	"영국",	"Europe/London"),
	new CityListClass("CRGVN",	"크레이개번",	"영국",	"Europe/Belfast"),
	new CityListClass("CREWE",	"크루",	"영국",	"Europe/London"),
	new CityListClass("KLMRN",	"킬마낙",	"영국",	"Europe/London"),
	new CityListClass("TNTN1",	"톤턴",	"영국",	"Europe/London"),
	new CityListClass("PERTH",	"퍼스",	"영국",	"Europe/London"),
//	new CityListClass("PSLY",	"페이즐리",	"영국",	"Europe/London"),
	new CityListClass("PRTR",	"포오트리",	"영국",	"Europe/London"),
	new CityListClass("FLKRK",	"폴커크",	"영국",	"Europe/London"),
	new CityListClass("PLY",	"플리머스",	"영국",	"Europe/London"),
	new CityListClass("FSHGR",	"피시가드",	"영국",	"Europe/London"),
	new CityListClass("PRBRG",	"피터버러",	"영국",	"Europe/London"),
//	new CityListClass("HWCK",	"하윅",	"영국",	"Europe/London"),
	new CityListClass("HUL",	"헐",	"영국",	"Europe/London"),
//	new CityListClass("HXHM",	"헥섬",	"영국",	"Europe/London"),
	new CityListClass("HLY",	"홀리헤드",	"영국",	"Europe/London"),
    };
}
