package com.weathernews.Weather;
public class Etc_southamerica {
    public final static CityListClass[] Etc_southamerica = new CityListClass[] {
	new CityListClass("GRLD",	"게라즈",	"몬세라트산",	"America/Montserrat"),
	new CityListClass("GYV",	"고야드",	"그레나다",	"America/Grenada"),
//	new CityListClass("GTML",	"과테말라",	"과테말라",	"America/Guatemala"),
	new CityListClass("GRND",	"그라나다",	"니카라과",	"America/Managua"),
	new CityListClass("GRAND",	"그랜드 터크",	"터크스 케이커스 제도",	"America/Grand_Turk"),
	new CityListClass("GRNDA",	"그랜드안세",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("BOURG",	"그렌버그",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("ISLET",	"그로스이슬랫",	"세인트루시아",	"America/St_Lucia"),
	new CityListClass("GRNVL",	"그린빌",	"그레나다",	"America/Grenada"),
	new CityListClass("QTZLT",	"께짤테낭고",	"과테말라",	"America/Guatemala"),
	new CityListClass("CMNDD",	"꼬멘다도르",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("CTPQ",	"꼬아떼뻬게",	"과테말라",	"America/Guatemala"),
	new CityListClass("NAS",	"나소",	"바하마",	"America/Nassau"),
	new CityListClass("NGRL",	"네그릴",	"자메이카",	"America/Jamaica"),
	new CityListClass("NOORD",	"노르트",	"아루바",	"America/Aruba"),
	new CityListClass("NSU",	"뉴 니케리",	"수리남",	"America/Paramaribo"),
	new CityListClass("NWA",	"뉴 암스테르담",	"가이아나",	"America/Guyana"),
	new CityListClass("AMSTR",	"뉴 암스테르담",	"수리남",	"America/Paramaribo"),
	new CityListClass("VALLY",	"더밸리",	"앵귈라",	"America/Anguilla"),
	new CityListClass("DDC",	"데그라드 데 칸",	"기아나",	"America/Cayenne"),
	new CityListClass("DNNRY",	"덴느리",	"세인트루시아",	"America/St_Lucia"),
	new CityListClass("DUCOS",	"뒤코",	"마르티니크",	"America/Martinique"),
	new CityListClass("LRM",	"라 로마나",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("PAZ",	"라 파스",	"볼리비아",	"America/La_Paz"),
	new CityListClass("PLNL",	"라 플라이네",	"도미니카",	"America/Dominica"),
	new CityListClass("LTHM",	"레뎀",	"가이아나",	"America/Guyana"),
	new CityListClass("ABYMS",	"레스 아비메스",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("LEON",	"레온",	"니카라과",	"America/Managua"),
	new CityListClass("RDT",	"로드 타운",	"세인트 키츠 네비스",	"America/Tortola"),
	new CityListClass("RSU",	"로조",	"도미니카",	"America/Dominica"),
	new CityListClass("GSR",	"르 고시어",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("LMNTN",	"르 라멘틴",	"마르티니크",	"America/Martinique"),
	new CityListClass("LRRN",	"르 로라인",	"마르티니크",	"America/Martinique"),
	new CityListClass("RBRT",	"르 로베르또",	"마르티니크",	"America/Martinique"),
	new CityListClass("MARIN",	"르 마린",	"마르티니크",	"America/Martinique"),
	new CityListClass("MOULE",	"르 무르",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("FRNCS",	"르 프랑수아",	"마르티니크",	"America/Martinique"),
	new CityListClass("RIVAS",	"리바스",	"니카라과",	"America/Managua"),
	new CityListClass("LBRT",	"리버타",	"앤티가바부다",	"America/Antigua"),
	new CityListClass("RBRLT",	"리베랄타",	"볼리비아",	"America/La_Paz"),
	new CityListClass("RVRP",	"리비 에르",	"마르티니크",	"America/Martinique"),
	new CityListClass("LINDN",	"린덴",	"가이아나",	"America/Guyana"),
	new CityListClass("MNG1",	"마나과",	"니카라과",	"America/Managua"),
	new CityListClass("MRGT",	"마리고트",	"도미니카",	"America/Dominica"),
	new CityListClass("MBRM",	"마바루마",	"가이아나",	"America/Guyana"),
	new CityListClass("MZTNN",	"마사테낭고",	"과테말라",	"America/Guatemala"),
	new CityListClass("MTGLP",	"마타갈파",	"니카라과",	"America/Managua"),
	new CityListClass("MATNY",	"마투리",	"기아나",	"America/Cayenne"),
	new CityListClass("MNDVL",	"만드빌",	"자메이카",	"America/Jamaica"),
	new CityListClass("MNG",	"모엥구",	"수리남",	"America/Paramaribo"),
//	new CityListClass("MTB",	"몬테고 베이",	"자메이카",	"America/Jamaica"),
	new CityListClass("MCD",	"미쿠드",	"세인트루시아",	"America/St_Lucia"),
//	new CityListClass("MIXCO",	"믹스꼬",	"과테말라",	"America/Guatemala"),
	new CityListClass("BRTC",	"바르티카",	"가이아나",	"America/Guyana"),
	new CityListClass("BRBR",	"바버",	"앤틸리스제도",	"America/Curacao"),
	new CityListClass("BST",	"바스테르",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("BSSTR",	"바스테르",	"세인트 키츠 네비스",	"America/St_Kitts"),
	new CityListClass("BTHSH",	"밧세바",	"바베이도스",	"America/Barbados"),
	new CityListClass("BRK1",	"베레쿠아",	"도미니카",	"America/Dominica"),
	new CityListClass("BLZ",	"벨리즈 시티",	"벨리즈",	"America/Belize"),
	new CityListClass("BLMPN",	"벨모판",	"벨리즈",	"America/Belize"),
	new CityListClass("BONAO",	"보나오",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("VIEUX",	"뷰포트",	"세인트루시아",	"America/St_Lucia"),
	new CityListClass("BRKPN",	"브로코폰도",	"수리남",	"America/Paramaribo"),
	new CityListClass("BGT",	"브리지타운",	"바베이도스",	"America/Barbados"),
	new CityListClass("VLLG",	"블로잉 포인트 빌리지",	"앵귈라",	"America/Anguilla"),
	new CityListClass("BLFLD",	"블루필즈",	"니카라과",	"America/Managua"),
//	new CityListClass("NUEVAV",	"비야누에바",	"과테말라",	"America/Guatemala"),
	new CityListClass("BCE",	"빅크리크",	"벨리즈",	"America/Belize"),
	new CityListClass("WLS",	"빌렘스타트",	"앤틸리스제도",	"America/Curacao"),
	new CityListClass("SBNT",	"사바네타",	"아루바",	"America/Aruba"),
	new CityListClass("SAUL",	"사울",	"기아나",	"America/Cayenne"),
	new CityListClass("CRLS1",	"산 카를로스",	"니카라과",	"America/Managua"),
	new CityListClass("PPL",	"산 펠리페 데 푸에르토 플라타",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("SANTAC",	"산타크루스",	"아루바",	"America/Aruba"),
	new CityListClass("SCDLS",	"산타크루스데라시에라",	"볼리비아",	"America/La_Paz"),
	new CityListClass("SAF",	"산토 도 밍고",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("CBLLR",	"산티아고 데 로스 카바예로스",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("SAQ",	"산페드로데마코리스",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("SFL",	"산페르난도",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("FRNCSM",	"산프란시스코 데 마코리스",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("SLM",	"살렘",	"몬세라트산",	"America/Montserrat"),
	new CityListClass("GRNDS",	"상그레그란데",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("PDJ",	"샌디포인트타운",	"세인트 키츠 네비스",	"America/St_Kitts"),
	new CityListClass("SNTM",	"샹테마리",	"마르티니크",	"America/Martinique"),
	new CityListClass("SNTA",	"샹테안느",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("CLRD",	"세루 콜로라도",	"아루바",	"America/Aruba"),
	new CityListClass("SANAB",	"세이트 앤 베이",	"자메이카",	"America/Jamaica"),
	new CityListClass("LRNT",	"세인트 로랑 다다오",	"기아나",	"America/Cayenne"),
	new CityListClass("SANTJS",	"세인트 조셉",	"도미니카",	"America/Dominica"),
	new CityListClass("GRGS",	"세인트 조지스",	"그레나다",	"America/Grenada"),
	new CityListClass("GRGSS",	"세인트 조지스",	"기아나",	"America/Cayenne"),
	new CityListClass("SAINTJ",	"세인트 존스",	"앤티가바부다",	"America/Antigua"),
	new CityListClass("VLLGS",	"세인트 존스 빌리지",	"몬세라트산",	"America/Montserrat"),
	new CityListClass("STRS",	"소퇴르",	"그레나다",	"America/Grenada"),
	new CityListClass("SUCRE",	"수크레",	"볼리비아",	"America/La_Paz"),
	new CityListClass("SFRR",	"수프리에르",	"세인트루시아",	"America/St_Lucia"),
	new CityListClass("SCAR",	"스카버러",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("SPGHT",	"스페이츠 타운",	"바베이도스",	"America/Barbados"),
	new CityListClass("SPR1",	"시파리아",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("NCL",	"신트 니콜라스",	"아루바",	"America/Aruba"),
	new CityListClass("ARIMA",	"아리마",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("APORA",	"아포에라",	"수리남",	"America/Paramaribo"),
	new CityListClass("ALBN",	"알비나",	"수리남",	"America/Paramaribo"),
	new CityListClass("ESCNT",	"에스쿠인틀라",	"과테말라",	"America/Guatemala"),
	new CityListClass("ESTL",	"에스텔리",	"니카라과",	"America/Managua"),
	new CityListClass("EBL",	"엘브럴프",	"니카라과",	"America/Managua"),
	new CityListClass("ORJ",	"오랑예스타드",	"아루바",	"America/Aruba"),
	new CityListClass("ORNG",	"오렌지 워크",	"벨리즈",	"America/Belize"),
	new CityListClass("ORURO",	"오루로",	"볼리비아",	"America/La_Paz"),
	new CityListClass("OCR",	"오초에 리오스",	"자메이카",	"America/Jamaica"),
	new CityListClass("WGG",	"와게닝엔",	"수리남",	"America/Paramaribo"),
//	new CityListClass("HHTNN",	"우이우이테낭고",	"과테말라",	"America/Guatemala"),
	new CityListClass("HGY1",	"이구에이",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("ITUNI",	"이투니",	"가이아나",	"America/Guyana"),
	new CityListClass("HRBR",	"잉글리쉬 하버 타운",	"앤티가바부다",	"America/Antigua"),
	new CityListClass("GEO",	"조지타운",	"가이아나",	"America/Guyana"),
	new CityListClass("GRGT",	"조지타운",	"케이맨 제도",	"America/Cayman"),
	new CityListClass("CHGNS",	"차구아나스",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("CTW",	"찰스타운",	"세인트 키츠 네비스",	"America/St_Kitts"),
	new CityListClass("CHNND",	"치난데가",	"니카라과",	"America/Managua"),
	new CityListClass("CYN",	"카옌",	"기아나",	"America/Cayenne"),
	new CityListClass("CPSTR",	"카페스테르 벨 오",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("CSI",	"캐스트리스",	"세인트루시아",	"America/St_Lucia"),
	new CityListClass("CDRNG",	"코드링턴",	"앤티가바부다",	"America/Antigua"),
	new CityListClass("CRZL",	"코로살",	"벨리즈",	"America/Belize"),
	new CityListClass("COO",	"코린토",	"니카라과",	"America/Managua"),
	new CityListClass("COBAN",	"코반",	"과테말라",	"America/Guatemala"),
	new CityListClass("CBJ",	"코비하",	"볼리비아",	"America/La_Paz"),
	new CityListClass("CCHBM",	"코챠밤바",	"볼리비아",	"America/La_Paz"),
	new CityListClass("CCKBR",	"콕번하버",	"터크스 케이커스 제도",	"America/Grand_Turk"),
	new CityListClass("KOU",	"쿠루",	"기아나",	"America/Cayenne"),
	new CityListClass("KEW",	"큐",	"터크스 케이커스 제도",	"America/Grand_Turk"),
	new CityListClass("KRLND",	"크라렌디즈크",	"앤틸리스제도",	"America/Curacao"),
	new CityListClass("CRANE",	"크레인",	"바베이도스",	"America/Barbados"),
	new CityListClass("KGT",	"킹스턴",	"자메이카",	"America/Jamaica"),
	new CityListClass("TRJ1",	"타리하",	"볼리비아",	"America/La_Paz"),
	new CityListClass("TRNDD",	"트리니다드",	"볼리비아",	"America/La_Paz"),
	new CityListClass("PNM",	"파라남",	"수리남",	"America/Paramaribo"),
	new CityListClass("PAS",	"파라마리보",	"수리남",	"America/Paramaribo"),
	new CityListClass("PRK1",	"파리카",	"가이아나",	"America/Guyana"),
	new CityListClass("PDRNL",	"페더날레스",	"도미나카공화국",	"America/Santo_Domingo"),
	new CityListClass("FTF",	"포르드프랑스",	"마르티니크",	"America/Martinique"),
	new CityListClass("PTPN",	"포인트 아 피어",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("PFT",	"포인트 포르틴",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("POTSM",	"포츠머스",	"도미니카",	"America/Dominica"),
	new CityListClass("VLLGP",	"포터스 빌리지",	"앤티가바부다",	"America/Antigua"),
//	new CityListClass("PTS1",	"포토시",	"볼리비아",	"America/La_Paz"),
	new CityListClass("PSNN",	"포트 오브 스페인",	"트리니다드토바고",	"America/Port_of_Spain"),
	new CityListClass("POI",	"포트 카이저",	"자메이카",	"America/Jamaica"),
//	new CityListClass("PBA",	"푸에르토 바 리오스",	"과테말라",	"America/Guatemala"),
	new CityListClass("PCZ",	"푸에르토 카베자스",	"니카라과",	"America/Managua"),
//	new CityListClass("GORDA",	"푼타 고르다",	"벨리즈",	"America/Belize"),
	new CityListClass("BOURGP",	"프티부그",	"과들루프섬",	"America/Guadeloupe"),
	new CityListClass("PYMTH",	"플러 머스",	"몬세라트산",	"America/Montserrat"),
//	new CityListClass("FLRS",	"플로레스",	"과테말라",	"America/Guatemala"),
	new CityListClass("PHG",	"필립스버그",	"앤틸리스제도",	"America/Curacao"),
//	new CityListClass("HAV",	"하바나",	"쿠바",	"America/Havana"),
	new CityListClass("HLTWN",	"호울타운",	"바베이도스",	"America/Barbados"),
	new CityListClass("HLLSB",	"힐스보로",	"그레나다",	"America/Grenada"),
    };
}
