package com.weathernews.Weather;

public class H {
	public final static CityListClass_E[] h = new CityListClass_E[] {
		new CityListClass_E("HPSL1", "Haapsalu", "합살루", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("HRLM", "Haarlem", "하를럼", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("HABOR", "Haboro", "하보로", "일본", "Asia/Tokyo"),
		new CityListClass_E("HHJ", "Hachijojima", "하치조지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("HAC", "Hachinohe", "하치노헤", "일본", "Asia/Tokyo"),
		new CityListClass_E("11I20001", "Haeju", "해주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11F20302", "Haenam", "해남", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HAGI", "Hagi", "하기", "일본", "Asia/Tokyo"),
		new CityListClass_E("HAGUE", "Hague", "헤이그", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("HAK", "Hakodate", "하코다테", "일본", "Asia/Tokyo"),
		new CityListClass_E("HLBRS", "Halberstadt", "할버슈타트", "독일", "Europe/Berlin"),
		new CityListClass_E("HAL", "Halifax", "핼리팩스", "캐나다", "America/Halifax"),
		new CityListClass_E("HLLE", "Halle", "할레", "독일", "Europe/Berlin"),
//		new CityListClass_E("HLM", "Halmstad", "할름스타드", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("HMD", "Hamada", "하마다", "일본", "Asia/Tokyo"),
		new CityListClass_E("HAMAH", "Hamah", "하마", "시리아", "Asia/Damascus"),
		new CityListClass_E("HMM", "Hamamatsu", "하마마츠", "일본", "Asia/Tokyo"),
		new CityListClass_E("11H20603", "Haman", "함안", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HAMAR", "Hamar", "하마르", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("HAM", "Hamburg", "함부르크", "독일", "Europe/Berlin"),
		new CityListClass_E("HML", "Hamilton", "해밀턴", "캐나다", "America/Toronto"),
		new CityListClass_E("HMTN", "Hamilton", "해밀턴", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass_E("HMMRF", "Hammerfest", "함메르페스트", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("HPT", "Hampton", "햄튼", "미국", "America/New_York"),
		new CityListClass_E("21F20101", "Hampyeong", "함평", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H20501", "Hamyang", "함양", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HANED", "Haneda", "하네다", "일본", "Asia/Tokyo"),
		new CityListClass_E("HANOI", "Hanoi", "하노이", "베트남", "Asia/Saigon"),
		new CityListClass_E("HNNVR", "Hanover", "하노버", "독일", "Europe/Berlin"),
		new CityListClass_E("11H20503", "Hapcheon", "합천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("VLLY", "Happy Valley-Goose Bay", "해피 밸리 - 구스 베이", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("HRRE", "Harare", "하라레", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("HRBN", "Harbin", "하얼빈", "중국", "Asia/Harbin"),
		new CityListClass_E("HRRSB", "Harrisburg", "해리스 버그", "미국", "America/New_York"),
//		new CityListClass_E("HRRSM", "Harrismith", "해리스미스", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("HRRSN", "Harrisonburg", "해리슨 버그", "미국", "America/New_York"),
		new CityListClass_E("HRTCT", "Hartford", "하트 포드", "미국", "America/New_York"),
//		new CityListClass_E("HSKV", "Haskovo", "하스코보", "불가리아", "Europe/Sofia"),
		new CityListClass_E("HSSLH", "Hassleholm", "헤슬레홀름", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("HTG", "Hastings", "헤이스팅스", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass_E("YAI", "Hat Yai", "핫야이", "태국", "Asia/Bangkok"),
		new CityListClass_E("HTTSB", "Hattiesburg", "해티스버그", "미국", "America/Chicago"),
		new CityListClass_E("HAU", "Haugesund", "헤우게순", "노르웨이", "Europe/Oslo"),
//		new CityListClass_E("HAV", "Havana", "하바나", "쿠바", "America/Havana"),
		new CityListClass_E("HVLCK", "Havlickuv Brod", "하블리치쿠프브로트", "체코", "Europe/Prague"),
//		new CityListClass_E("HWCK", "Hawick", "하윅", "영국", "Europe/London"),
		new CityListClass_E("RIVER", "Hay River", "헤이 리버", "캐나다", "America/Yellowknife"),
		new CityListClass_E("HYWCA", "Hayward", "헤이워드", "미국", "America/Los_Angeles"),
		new CityListClass_E("HBRN", "Heibron", "하이브론", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("HEIDE", "Heide", "하이데", "독일", "Europe/Berlin"),
		new CityListClass_E("HEILB", "Heilbronn", "하일브론", "독일", "Europe/Berlin"),
		new CityListClass_E("HLLN", "Hellin", "헬린", "스페인", "Europe/Madrid"),
		new CityListClass_E("HEL", "Helsingborg", "헬싱보리", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("HMPST", "Hempstead", "햄스테드", "미국", "America/New_York"),
		new CityListClass_E("HRK", "Heraklion", "헤라클리온", "그리스", "Europe/Athens"),
		new CityListClass_E("HRNVN", "Heerenveen", "헤렌벤", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("HRCG", "Herceg Novi", "헤르첵노비", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("HRMNU", "Hermanus", "허머너스", "남아프리카공화국", "Africa/Johannesburg"),
//		new CityListClass_E("HRMSL", "Hermosillo", "에르모시요", "멕시코", "America/Hermosillo"),
		new CityListClass_E("HRNNG", "Herning", "헤닝", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("HRTGN", "Hertogenbosch", "헤르토겐보쉬", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("11F20701", "Heuksando", "흑산도", "대한민국", "Asia/Seoul"),
//		new CityListClass_E("HXHM", "Hexham", "헥섬", "영국", "Europe/London"),
		new CityListClass_E("HDLGP", "Hidalgo del Parral", "이달고델파랄", "멕시코", "America/Chihuahua"),
		new CityListClass_E("POINTH", "High Point", "하이 포인트", "미국", "America/New_York"),
		new CityListClass_E("HGY1", "Higuey", "이구에이", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("HKN", "Hikone", "히코네", "일본", "Asia/Tokyo"),
		new CityListClass_E("HLLRD", "Hillerod", "힐러르웨드", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("HLLSB", "Hillsborough", "힐스보로", "그레나다", "America/Grenada"),
		new CityListClass_E("HIM", "Himeje", "히메제", "일본", "Asia/Tokyo"),
		new CityListClass_E("HIMS", "Hims", "힘스", "시리아", "Asia/Damascus"),
		new CityListClass_E("HNCH", "Hinche", "인셰", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("HIRAD", "Hirado", "히라도", "일본", "Asia/Tokyo"),
		new CityListClass_E("HROO", "Hiroo", "히로오", "일본", "Asia/Tokyo"),
		new CityListClass_E("HIR", "Hiroshima", "히로시마", "일본", "Asia/Tokyo"),
		new CityListClass_E("HITA", "Hita", "히타", "일본", "Asia/Tokyo"),
		new CityListClass_E("HTYSH", "Hitoyoshi", "히토요시", "일본", "Asia/Tokyo"),
		new CityListClass_E("HWS", "Hiwasa", "히와사", "일본", "Asia/Tokyo"),
		new CityListClass_E("HLTS", "Hlotse", "흘로체", "레소토", "Africa/Maseru"),
		new CityListClass_E("CHMNH", "Ho Chiminh", "호치민", "베트남", "Asia/Saigon"),
		new CityListClass_E("HOB", "Hobart", "호바트", "오스트레일리아", "Australia/Hobart"),
		new CityListClass_E("HDNN", "Hodonin", "호도닌", "체코", "Europe/Prague"),
		new CityListClass_E("11D10402", "Hoengseong", "횡성", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HOFN", "Hofn", "호픈", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass_E("HLBK", "Holbaek", "홀베크", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("HLTWN", "Holetown", "호울타운", "바베이도스", "America/Barbados"),
		new CityListClass_E("HLYW", "Hollywood", "할리우드", "미국", "America/New_York"),
		new CityListClass_E("HLSTB", "Holstebro", "홀스테브로", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("HLY", "Holyhead", "홀리헤드", "영국", "Europe/London"),
		new CityListClass_E("HMBRG1", "Homburg", "홈부르크", "독일", "Europe/Berlin"),
		new CityListClass_E("HNDKL", "Hondeklipbaai", "혼데클립바이", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("11D10302", "Hongcheon", "홍천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HNGKN", "Hongkong", "홍콩", "중국", "Asia/Shanghai"),
		new CityListClass_E("11C20104", "Hongseong", "홍성", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HNR", "Honiara", "호니아라", "솔로몬제도", "Pacific/Guadalcanal"),
		new CityListClass_E("HRSHM", "Horsham", "호셤", "오스트레일리아", "Australia/Melbourne"),
//		new CityListClass_E("HORTA", "Horta", "오르타", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("SPRNG", "Hot Springs", "핫 스프링스", "미국", "America/Chicago"),
		new CityListClass_E("HTZL", "Hotazel", "호타젤", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KRLV", "Hradec Kralove", "흐라데츠 크랄로베", "체코", "Europe/Prague"),
		new CityListClass_E("HRBSZ", "HrubieszOw", "흐루비에슈프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("HNCY", "Huancayo", "우안까요", "페루", "America/Lima"),
		new CityListClass_E("HNC", "Huanuco", "우아누꼬", "페루", "America/Lima"),
		new CityListClass_E("HDKSV", "Hudiksvall", "허딕스볼", "스웨덴", "Europe/Stockholm"),
//		new CityListClass_E("HHTNN", "Huehuetenango", "우이우이테낭고", "과테말라", "America/Guatemala"),
		new CityListClass_E("HVA", "Huelva", "우엘바", "스페인", "Europe/Madrid"),
		new CityListClass_E("HSC1", "Huesca", "우에스카", "스페인", "Europe/Madrid"),
		new CityListClass_E("HSCR", "Huescar", "우아스카르", "스페인", "Europe/Madrid"),
//		new CityListClass_E("HKNTS", "Hukuntsi", "후쿤치", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("HUL", "Hull", "헐", "영국", "Europe/London"),
		new CityListClass_E("HNDR", "Hunedoara", "후네도아라", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("HTGWV", "Huntington", "헌팅턴", "미국", "America/New_York"),
		new CityListClass_E("HTGCA", "Huntington Beach", "헌팅턴 비치", "미국", "America/Los_Angeles"),
		new CityListClass_E("HNTAL", "Huntsville", "헌츠빌-알라바마", "미국", "America/Chicago"),
		new CityListClass_E("HUNSV", "Huntsville", "헌츠빌-텍사스", "미국", "America/Chicago"),
		new CityListClass_E("HTCHN", "Hutchinson", "허친슨", "미국", "America/Chicago"),
		new CityListClass_E("11D10102", "Hwacheon", "화천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11B20604", "Hwaseong", "화성", "대한민국", "Asia/Seoul"),

	};
}
