package com.weathernews.Weather;
public class Hungary_europe {
    public final static CityListClass[] Hungary_europe = new CityListClass[] {
    	new CityListClass("NYRGY", "니레지하치", "헝가리", "Europe/Budapest"),
    	new CityListClass("DBRCN", "데브레첸", "헝가리", "Europe/Budapest"),
    	new CityListClass("DNJVR", "도노우이바로슈", "헝가리", "Europe/Budapest"),
    	new CityListClass("DMBVR", "돔보바르", "헝가리", "Europe/Budapest"),
    	new CityListClass("GYOR", "디외르", "헝가리", "Europe/Budapest"),
    	new CityListClass("MTSZL", "모테살카", "헝가리", "Europe/Budapest"),
    	new CityListClass("MHCS", "모하치", "헝가리", "Europe/Budapest"),
    	new CityListClass("MSKLC", "미슈콜츠", "헝가리", "Europe/Budapest"),
    	new CityListClass("BARCS", "바르치", "헝가리", "Europe/Budapest"),
    	new CityListClass("VAC1", "바크", "헝가리", "Europe/Budapest"),
    	new CityListClass("VSZPR", "베스프렘", "헝가리", "Europe/Budapest"),
    	new CityListClass("BKSCS", "베케스크사바", "헝가리", "Europe/Budapest"),
    	new CityListClass("BAJA", "보요", "헝가리", "Europe/Budapest"),
    	new CityListClass("BDPST", "부다페스트", "헝가리", "Europe/Budapest"),
    	new CityListClass("STRLJ", "샤토럴려우이헤이", "헝가리", "Europe/Budapest"),
    	new CityListClass("SZKSF", "세케슈페헤르바르", "헝가리", "Europe/Budapest"),
    	new CityListClass("SZNTS", "센테시", "헝가리", "Europe/Budapest"),
    	new CityListClass("SLGTR", "셔로터랸", "헝가리", "Europe/Budapest"),
    	new CityListClass("SZLNK", "솔노크", "헝가리", "Europe/Budapest"),
    	new CityListClass("SZMBT", "솜보텔리", "헝가리", "Europe/Budapest"),
    	new CityListClass("SPRN1", "쇼프론", "헝가리", "Europe/Budapest"),
    	new CityListClass("SZGD", "슈제츠트", "헝가리", "Europe/Budapest"),
    	new CityListClass("SFK", "시오포크", "헝가리", "Europe/Budapest"),
    	new CityListClass("JSZBR", "야스베레니", "헝가리", "Europe/Budapest"),
    	new CityListClass("EGER1", "에게르", "헝가리", "Europe/Budapest"),
    	new CityListClass("ERD", "에르디", "헝가리", "Europe/Budapest"),
    	new CityListClass("ORSHZ", "오로슈하저", "헝가리", "Europe/Budapest"),
    	new CityListClass("OZD", "오즈드", "헝가리", "Europe/Budapest"),
    	new CityListClass("ZLGRS", "잘레에게르세그", "헝가리", "Europe/Budapest"),
    	new CityListClass("CGLD", "체글레드", "헝가리", "Europe/Budapest"),
    	new CityListClass("SZKSZ", "체크자드", "헝가리", "Europe/Budapest"),
    	new CityListClass("KPSVR", "카보스바르", "헝가리", "Europe/Budapest"),
    	new CityListClass("KRCG", "커르처그", "헝가리", "Europe/Budapest"),
    	new CityListClass("KCSKM", "케치케메트", "헝가리", "Europe/Budapest"),
    	new CityListClass("TTBNY", "토토바뇨", "헝가리", "Europe/Budapest"),
    	new CityListClass("PAPA1", "파파", "헝가리", "Europe/Budapest"),
    	new CityListClass("PECS", "페치", "헝가리", "Europe/Budapest"),
    };
}
