package com.weathernews.Weather;
public class Ireland_europe {
    public final static CityListClass[] Ireland_europe = new CityListClass[] {
	new CityListClass("GWA",	"갈웨이",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("NAVAN",	"네번",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("NAAS",	"네이스",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("NNGH",	"니나",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("DBL",	"더블린",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("DDK",	"던독",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("DRGHD",	"드로이다",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("LTTRK",	"레터케니",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("RSCMM",	"로스코먼",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("LNGFR",	"롱퍼드",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("LMK",	"리머릭",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("MNGHN",	"모너핸",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("MLLNG",	"물린가",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("BLLN",	"발리나",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("BOYLE",	"보일",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("BNCRN",	"분크라나",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("BRAY",	"브레이",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("BIRR",	"비르",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("THRLS",	"셀레스",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("SLIGO",	"슬라이고",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("ATHLN",	"애슬로",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("ENNIS",	"에니스",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("WTF",	"워터포드",	"아일랜드",	"Europe/Dublin"),
//	new CityListClass("WXFRD",	"웩스퍼드",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("WCKLW",	"위클로",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("CRRGL",	"카리가린",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("CAVAN",	"카반",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("CRLW",	"칼로우",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("RVS",	"캐릭온쉐논",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("CSTLB1",	"캐슬바",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("CRK",	"코르크",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("COB",	"코브",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("CLNML",	"클론멜",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("KLKNN",	"킬케니",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("TLLMR",	"툴라모어",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("TRL",	"트롤리",	"아일랜드",	"Europe/Dublin"),
	new CityListClass("PRTLG1",	"포트라오이즈",	"아일랜드",	"Europe/Dublin"),
    };
}
