package com.weathernews.Weather;

public class J {
	public final static CityListClass_E[] j = new CityListClass_E[] {
		new CityListClass_E("JBLNC", "Jablonec nad Nisou", "야블로네츠나트니소우", "체코", "Europe/Prague"),
		new CityListClass_E("JBT", "Jaboatao", "자부아탕", "브라질", "America/Recife"),
		new CityListClass_E("JACKS", "Jackson", "잭슨-미시간", "미국", "America/Detroit"),
		new CityListClass_E("JSN", "Jackson", "잭슨-미시시피", "미국", "America/Chicago"),
		new CityListClass_E("JAKSO", "Jackson", "잭슨-와이오밍", "미국", "America/Denver"),
		new CityListClass_E("JAKSN", "Jackson", "잭슨-테네시", "미국", "America/Chicago"),
		new CityListClass_E("JCKSN", "Jacksonville", "잭슨빌-노스캐롤라이나", "미국", "America/Chicago"),
		new CityListClass_E("JAKNV", "Jacksonville", "잭슨빌-아칸소", "미국", "America/New_York"),
		new CityListClass_E("JAX", "Jacksonville", "잭슨빌-플로리다", "미국", "America/New_York"),
		new CityListClass_E("JCML", "Jacmel", "쟈크메", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("JAEN", "Jaen", "하엔", "스페인", "Europe/Madrid"),
		new CityListClass_E("JGRSF", "Jagersfontein", "예거스폰테인", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("DJA", "Jakarta", "자카르타", "인도네시아", "Asia/Jakarta"),
		new CityListClass_E("JLP", "Jalapa", "할라파", "멕시코", "America/Mexico_City"),
		new CityListClass_E("JMSTW1", "Jamestown", "제임스타운", "미국", "America/New_York"),
		new CityListClass_E("11F20304", "Jangheung", "장흥", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11F20502", "Jangseong", "장성", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11F10301", "Jangsu", "장수", "대한민국", "Asia/Seoul"),
		new CityListClass_E("JNKW", "Janikowo", "야니코우", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("JRSRW", "Jarosraw", "야로스와프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("JSPR", "Jasper", "재스퍼", "캐나다", "America/Edmonton"),
//		new CityListClass_E("JSTRZ", "Jastrzebie-ZdrOj", "야스트제비에-지드루이", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("JSZBR", "Jaszbereny", "야스베레니", "헝가리", "Europe/Budapest"),
		new CityListClass_E("11C10201", "Jecheon", "제천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("JFFRS", "Jefferson City", "제퍼슨시티", "미국", "America/Chicago"),
		new CityListClass_E("11G00201", "Jeju", "제주", "대한민국", "Asia/Seoul"),
//		new CityListClass_E("JLNG", "Jelenia GOra", "옐레니아구라", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("JENA", "Jena", "예나", "독일", "Europe/Berlin"),
		new CityListClass_E("JNNRS", "Jennersdorf", "예너스도르프", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("11F10203", "Jeongeup", "정읍", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11D10502", "Jeongseon", "정선", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11F10201", "Jeonju", "전주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("JRM", "Jeremie", "제레미", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("JFRNTR", "Jerez de la Frontera", "헤레스데라프론테라", "스페인", "Europe/Madrid"),
		new CityListClass_E("JRC", "Jerica", "제리카", "스페인", "Europe/Madrid"),
		new CityListClass_E("JRSYC", "Jersey City", "저지시티", "미국", "America/New_York"),
		new CityListClass_E("JRSLM", "Jerusalem", "예루살렘", "이스라엘", "Asia/Jerusalem"),
		new CityListClass_E("JSNC", "Jesenice", "예세니체", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("11C10304", "Jeungpyeong", "증평", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HAFS", "Jidd Hafs", "지드 하프스", "바레인", "Asia/Bahrain"),
		new CityListClass_E("JED", "Jiddah", "지다", "사우디아라비아", "Asia/Riyadh"),
		new CityListClass_E("JHLV", "Jihlava", "이흘라바", "체코", "Europe/Prague"),
		new CityListClass_E("11F10303", "Jinan", "진안", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11C10102", "Jincheon", "진천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("21F20201", "Jindo", "진도", "대한민국", "Asia/Seoul"),
		new CityListClass_E("JNDRC", "Jindrichuv Hradec", "인지후프 흐라데츠", "체코", "Europe/Prague"),
		new CityListClass_E("11H20303", "Jinhae", "진해", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H20701", "Jinju", "진주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("GIZ", "Jizan", "지잔", "사우디아라비아", "Asia/Riyadh"),
		new CityListClass_E("PSS", "Joao Pessoa", "주앙 페소아", "브라질", "America/Fortaleza"),
		new CityListClass_E("JGV", "Jogeva", "요게바", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("JHNNS", "Johannesburg", "요하네스버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("JHNSN", "Johnson City", "존슨시티", "미국", "America/New_York"),
		new CityListClass_E("JHNST", "Johnstown", "존스타운", "미국", "America/New_York"),
		new CityListClass_E("BAHRU", "Johor Bahru", "조호르주", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("JOHVI", "Johvi", "요비", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("JKKMK", "Jokkmokk", "요크모크", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("JLT", "Joliet", "졸리엣", "미국", "America/Chicago"),
		new CityListClass_E("JOL", "Jolo", "홀로", "필리핀", "Asia/Manila"),
		new CityListClass_E("JNV", "Jonava", "요나바", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("JNSBR", "Jonesboro", "존즈버러", "미국", "America/Chicago"),
		new CityListClass_E("JNKPN", "Jonkoping", "욘코핑", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("JPLN", "Joplin", "조플린", "미국", "America/Chicago"),
		new CityListClass_E("JRZ", "Juarez", "후아레스", "멕시코", "America/Chihuahua"),
		new CityListClass_E("JMLL", "Jumilla", "후미야", "스페인", "Europe/Madrid"),
		new CityListClass_E("JUN", "Juneau", "주노", "미국", "America/Juneau"),
		new CityListClass_E("JRBRK", "Jurbarkas", "유르바르카스", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("JTCLP", "Juticalpa", "저스티칼파", "온두라스", "America/Tegucigalpa"),

	};
}
