package com.weathernews.Weather;

class JA {
	public final static CityListClass[] ja = new CityListClass[] {
		new CityListClass("ZAGAN", "자간", "폴란드", "Europe/Warsaw"),
		new CityListClass("ZGRB", "자그레브", "크로아티아", "Europe/Zagreb"),
		new CityListClass("SSVT", "자그레브-외곽", "크로아티아", "Europe/Zagreb"),
		new CityListClass("ZAD", "자다르", "크로아티아", "Europe/Zagreb"),
		new CityListClass("SRNN", "자르넨", "스위스", "Europe/Zurich"),
		new CityListClass("SRBRC", "자르브뤼켄", "독일", "Europe/Berlin"),
//		new CityListClass("ZMSC", "자모스치", "폴란드", "Europe/Warsaw"),
		new CityListClass("ZBBR", "자바르", "몰타", "Europe/Malta"),
		new CityListClass("JBT", "자부아탕", "브라질", "America/Recife"),
//		new CityListClass("ZBRZ", "자브제", "폴란드", "Europe/Warsaw"),
		new CityListClass("SRLS", "자얼루이", "독일", "Europe/Berlin"),
		new CityListClass("XAI", "자이-자이", "모잠비크", "Africa/Maputo"),
		new CityListClass("DJA", "자카르타", "인도네시아", "Asia/Jakarta"),
		new CityListClass("ZKPN", "자코파네", "폴란드", "Europe/Warsaw"),
		new CityListClass("ZKNTH", "자퀸토스", "그리스", "Europe/Athens"),
		new CityListClass("ZALAU", "잘러우", "루마니아", "Europe/Bucharest"),
		new CityListClass("ZLGRS", "잘레에게르세그", "헝가리", "Europe/Budapest"),
		new CityListClass("SLZBR", "잘츠부르크", "오스트리아", "Europe/Vienna"),
		new CityListClass("ZMBRW", "잠브루프", "폴란드", "Europe/Warsaw"),
		new CityListClass("11F20502", "장성", "대한민국", "Asia/Seoul"),
		new CityListClass("11F10301", "장수", "대한민국", "Asia/Seoul"),
		new CityListClass("PNGJ", "장크트 요한 임 퐁가우", "오스트리아", "Europe/Vienna"),
		new CityListClass("GLLN", "장크트갈렌", "스위스", "Europe/Zurich"),
		new CityListClass("MRTZS", "장크트모리츠", "스위스", "Europe/Zurich"),
		new CityListClass("PLTNS", "장크트푈텐", "오스트리아", "Europe/Vienna"),
		new CityListClass("11F20304", "장흥", "대한민국", "Asia/Seoul"),
		new CityListClass("JSPR", "재스퍼", "캐나다", "America/Edmonton"),
		new CityListClass("JACKS", "잭슨-미시간", "미국", "America/Detroit"),
		new CityListClass("JSN", "잭슨-미시시피", "미국", "America/Chicago"),
		new CityListClass("JAKSO", "잭슨-와이오밍", "미국", "America/Denver"),
		new CityListClass("JAKSN", "잭슨-테네시", "미국", "America/Chicago"),
		new CityListClass("JCKSN", "잭슨빌-노스캐롤라이나", "미국", "America/Chicago"),
		new CityListClass("JAKNV", "잭슨빌-아칸소", "미국", "America/New_York"),
		new CityListClass("JAX", "잭슨빌-플로리다", "미국", "America/New_York"),
		new CityListClass("JCML", "쟈크메", "아이티", "America/Port-au-Prince"),
		new CityListClass("JTCLP", "저스티칼파", "온두라스", "America/Tegucigalpa"),
		new CityListClass("JRSYC", "저지시티", "미국", "America/New_York"),
		new CityListClass("11F10201", "전주", "대한민국", "Asia/Seoul"),
		new CityListClass("GLG", "절롱", "오스트레일리아", "Australia/Melbourne"),
		new CityListClass("11D10502", "정선", "대한민국", "Asia/Seoul"),
		new CityListClass("11F10203", "정읍", "대한민국", "Asia/Seoul"),
		new CityListClass("GNVA", "제네바", "스위스", "Europe/Zurich"),
//		new CityListClass("GEN", "제노바", "이탈리아", "Europe/Rome"),
		new CityListClass("ZNC", "제니차", "보스니아-헤르체고비나", "Europe/Sarajevo"),
		new CityListClass("GDT", "제럴턴", "오스트레일리아", "Australia/Perth"),
		new CityListClass("JRM", "제레미", "아이티", "America/Port-au-Prince"),
		new CityListClass("ZRST", "제루스트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("JRC", "제리카", "스페인", "Europe/Madrid"),
		new CityListClass("ZBBG", "제부즈", "몰타", "Europe/Malta"),
		new CityListClass("GVGLJ", "제브젤리야", "마케도니아", "Europe/Skopje"),
		new CityListClass("RZSZW", "제슈프", "폴란드", "Europe/Warsaw"),
		new CityListClass("ZNSVL", "제인즈빌", "미국", "America/New_York"),
		new CityListClass("JMSTW1", "제임스타운", "미국", "America/New_York"),
		new CityListClass("11G00201", "제주", "대한민국", "Asia/Seoul"),
		new CityListClass("11C10201", "제천", "대한민국", "Asia/Seoul"),
		new CityListClass("JFFRS", "제퍼슨시티", "미국", "America/Chicago"),
		new CityListClass("GERTWN", "조지타운", "세인트 빈센트 그레나딘", "America/St_Vincent"),
		new CityListClass("GRGT", "조지타운", "케이맨 제도", "America/Cayman"),
		new CityListClass("GEO", "조지타운", "가이아나", "America/Guyana"),
		new CityListClass("JPLN", "조플린", "미국", "America/Chicago"),
		new CityListClass("BAHRU", "조호르주", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("JHNST", "존스타운", "미국", "America/New_York"),
		new CityListClass("JHNSN", "존슨시티", "미국", "America/New_York"),
		new CityListClass("JNSBR", "존즈버러", "미국", "America/Chicago"),
		new CityListClass("ZRTW", "졸로토", "폴란드", "Europe/Warsaw"),
//		new CityListClass("ZRTRY", "졸로토르야", "폴란드", "Europe/Warsaw"),
		new CityListClass("SLTHR", "졸로투른", "스위스", "Europe/Zurich"),
		new CityListClass("JLT", "졸리엣", "미국", "America/Chicago"),
		new CityListClass("ZNGLD", "종굴다크", "터키", "Europe/Istanbul"),
		new CityListClass("GERT", "죠지타운", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("JUN", "주노", "미국", "America/Juneau"),
		new CityListClass("PSS", "주앙 페소아", "브라질", "America/Fortaleza"),
		new CityListClass("SUHL", "줄", "독일", "Europe/Berlin"),
		new CityListClass("SLCN", "줄레친", "폴란드", "Europe/Warsaw"),
		new CityListClass("ZNJM", "즈노이모", "체코", "Europe/Prague"),
		new CityListClass("ZDNSK", "즈둔스카볼라", "폴란드", "Europe/Warsaw"),
		new CityListClass("ZRNJN", "즈레냐닌", "세르비아", "Europe/Belgrade"),
		new CityListClass("ZLIN", "즐린", "체코", "Europe/Prague"),
		new CityListClass("11C10304", "증평", "대한민국", "Asia/Seoul"),
		new CityListClass("SIGN", "지겐", "독일", "Europe/Berlin"),
		new CityListClass("ZGRZL", "지고르젤레크", "폴란드", "Europe/Warsaw"),
		new CityListClass("JED", "지다", "사우디아라비아", "Asia/Riyadh"),
		new CityListClass("HAFS", "지드 하프스", "바레인", "Asia/Bahrain"),
		new CityListClass("GRNA", "지로나", "스페인", "Europe/Madrid"),
		new CityListClass("GJRKS", "지로카스터", "알바니아", "Europe/Tirane"),
		new CityListClass("DJB", "지부티", "Djibouti", "Africa/Djibouti"),
		new CityListClass("ZYWC", "지비에츠", "폴란드", "Europe/Warsaw"),
//		new CityListClass("DZRZN", "지에르조니오프", "폴란드", "Europe/Warsaw"),
		new CityListClass("ZLN", "지엘로나구라", "폴란드", "Europe/Warsaw"),
		new CityListClass("GRG1", "지우르지우", "루마니아", "Europe/Bucharest"),
//		new CityListClass("GZYCK", "지작코", "폴란드", "Europe/Warsaw"),
		new CityListClass("GIZ", "지잔", "사우디아라비아", "Asia/Riyadh"),
		new CityListClass("ZNIN", "진", "폴란드", "Europe/Warsaw"),
		new CityListClass("21F20201", "진도", "대한민국", "Asia/Seoul"),
		new CityListClass("11F10303", "진안", "대한민국", "Asia/Seoul"),
		new CityListClass("11H20701", "진주", "대한민국", "Asia/Seoul"),
		new CityListClass("11C10102", "진천", "대한민국", "Asia/Seoul"),
		new CityListClass("11H20303", "진해", "대한민국", "Asia/Seoul"),
		new CityListClass("ZLN1", "질리나", "슬로바키아", "Europe/Bratislava"),
//		new CityListClass("GLLNG", "질링엄", "영국", "Europe/London"),
		new CityListClass("ZWTTL", "쯔베들", "오스트리아", "Europe/Vienna"),

//		new CityListClass("ZAGAN","자간","폴란드","Europe/Warsaw"),
//		new CityListClass("ZGRB","자그레브","크로아티아","Europe/Zagreb"),
//		new CityListClass("SSVT","자그레브-외곽","크로아티아","Europe/Zagreb"),
//		new CityListClass("ZAD","자다르","크로아티아","Europe/Zagreb"),
//		new CityListClass("SRNN","자르넨","스위스","Europe/Zurich"),
//		new CityListClass("SRBRC","자르브뤼켄","독일","Europe/Berlin"),
//		new CityListClass("ZMSC","자모스치","폴란드","Europe/Warsaw"),
//		new CityListClass("ZBBR","자바르","몰타","Europe/Malta"),
//		new CityListClass("JBT","자부아탕","브라질","America/Recife"),
//		new CityListClass("ZBRZ","자브제","폴란드","Europe/Warsaw"),
//		new CityListClass("SRLS","자얼루이","독일","Europe/Berlin"),
//		new CityListClass("XAI","자이-자이","모잠비크","Africa/Maputo"),
//		new CityListClass("DJA","자카르타","인도네시아","Asia/Jakarta"),
//		new CityListClass("ZKPN","자코파네","폴란드","Europe/Warsaw"),
//		new CityListClass("ZKNTH","자퀸토스","그리스","Europe/Athens"),
//		new CityListClass("ZALAU","잘러우","루마니아","Europe/Bucharest"),
//		new CityListClass("SLZBR","잘츠부르크","오스트리아","Europe/Vienna"),
//		new CityListClass("ZMBRW","잠브루프","폴란드","Europe/Warsaw"),
//			new CityListClass("11F20502","장성","대한민국","Asia/Seoul"),
//			new CityListClass("11F10301","장수","대한민국","Asia/Seoul"),
//		new CityListClass("PNGJ","장크트 요한 임 퐁가우","오스트리아","Europe/Vienna"),
//		new CityListClass("GLLN","장크트갈렌","스위스","Europe/Zurich"),
//		new CityListClass("MRTZS","장크트모리츠","스위스","Europe/Zurich"),
//		new CityListClass("PLTNS","장크트푈텐","오스트리아","Europe/Vienna"),
//			new CityListClass("11F20304","장흥","대한민국","Asia/Seoul"),
//		new CityListClass("JSPR","재스퍼","캐나다","America/Edmonton"),
//		new CityListClass("JACKS","잭슨-미시간","미국","America/Detroit"),
//		new CityListClass("JSN","잭슨-미시시피","미국","America/Chicago"),
//		new CityListClass("JAKSO","잭슨-와이오밍","미국","America/Denver"),
//		new CityListClass("JAKSN","잭슨-테네시","미국","America/Chicago"),
//		new CityListClass("JCKSN","잭슨빌-노스캐롤라이나","미국","America/Chicago"),
//		new CityListClass("JAKNV","잭슨빌-아칸소","미국","America/New_York"),
//		new CityListClass("JAX","잭슨빌-플로리다","미국","America/New_York"),
//		new CityListClass("JCML","쟈크메","아이티","America/Port-au-Prince"),
//	    	new CityListClass("JTCLP","저스티칼파","온두라스","America/Tegucigalpa"),
//		new CityListClass("JRSYC","저지시티","미국","America/New_York"),
//			new CityListClass("11F10201","전주","대한민국","Asia/Seoul"),
//		new CityListClass("GLG","절롱","오스트레일리아","Australia/Melbourne"),
//			new CityListClass("11D10502","정선","대한민국","Asia/Seoul"),
//			new CityListClass("11F10203","정읍","대한민국","Asia/Seoul"),
//		new CityListClass("GNVA","제네바","스위스","Europe/Zurich"),
//		new CityListClass("GEN","제노바","이탈리아","Europe/Rome"),
//		new CityListClass("ZNC","제니차","보스니아-헤르체고비나","Europe/Sarajevo"),
//		new CityListClass("GDT","제럴턴","오스트레일리아","Australia/Perth"),
//		new CityListClass("JRM","제레미","아이티","America/Port-au-Prince"),
//		new CityListClass("ZRST","제루스트","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("JRC","제리카","스페인","Europe/Madrid"),
//		new CityListClass("ZBBG","제부즈","몰타","Europe/Malta"),
//		new CityListClass("GVGLJ","제브젤리야","마케도니아","Europe/Skopje"),
//		new CityListClass("RZSZW","제슈프","폴란드","Europe/Warsaw"),
//		new CityListClass("ZNSVL","제인즈빌","미국","America/New_York"),
//		new CityListClass("JMSTW1","제임스타운","미국","America/New_York"),
//			new CityListClass("11G00201","제주","대한민국","Asia/Seoul"),
//			new CityListClass("11C10201","제천","대한민국","Asia/Seoul"),
//		new CityListClass("JFFRS","제퍼슨시티","미국","America/Chicago"),
//		new CityListClass("GERTWN","조지타운","세인트 빈센트 그레나딘","America/St_Vincent"),
//		new CityListClass("GEO","조지타운","가이아나","America/Guyana"),
//		new CityListClass("GRGT","조지타운","케이맨 제도","America/Cayman"),
//		new CityListClass("JPLN","조플린","미국","America/Chicago"),
//		new CityListClass("BAHRU","조호르주","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("JHNST","존스타운","미국","America/New_York"),
//		new CityListClass("JHNSN","존슨시티","미국","America/New_York"),
//		new CityListClass("JNSBR","존즈버러","미국","America/Chicago"),
//		new CityListClass("ZRTW","졸로토","폴란드","Europe/Warsaw"),
//		new CityListClass("ZRTRY","졸로토르야","폴란드","Europe/Warsaw"),
//		new CityListClass("SLTHR","졸로투른","스위스","Europe/Zurich"),
//		new CityListClass("JLT","졸리엣","미국","America/Chicago"),
//		new CityListClass("ZNGLD","종굴다크","터키","Europe/Istanbul"),
//		new CityListClass("GERT","죠지타운","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("JUN","주노","미국","America/Juneau"),
//		new CityListClass("PSS","주앙 페소아","브라질","America/Fortaleza"),
//		new CityListClass("SUHL","줄","독일","Europe/Berlin"),
//		new CityListClass("SLCN","줄레친","폴란드","Europe/Warsaw"),
//		new CityListClass("ZNJM","즈노이모","체코","Europe/Prague"),
//		new CityListClass("ZDNSK","즈둔스카볼라","폴란드","Europe/Warsaw"),
//		new CityListClass("ZRNJN","즈레냐닌","세르비아","Europe/Belgrade"),
//		new CityListClass("ZLIN","즐린","체코","Europe/Prague"),
//			new CityListClass("11C10304","증평","대한민국","Asia/Seoul"),
//		new CityListClass("SIGN","지겐","독일","Europe/Berlin"),
//		new CityListClass("ZGRZL","지고르젤레크","폴란드","Europe/Warsaw"),
//		new CityListClass("JED","지다","사우디아라비아","Asia/Riyadh"),
//		new CityListClass("HAFS","지드 하프스","바레인","Asia/Bahrain"),
//		new CityListClass("GRNA","지로나","스페인","Europe/Madrid"),
//		new CityListClass("GJRKS","지로카스터","알바니아","Europe/Tirane"),
//		new CityListClass("DJB","지부티","Djibouti","Africa/Djibouti"),
//		new CityListClass("ZYWC","지비에츠","폴란드","Europe/Warsaw"),
//		new CityListClass("DZRZN","지에르조니오프","폴란드","Europe/Warsaw"),
//		new CityListClass("ZLN","지엘로나구라","폴란드","Europe/Warsaw"),
//		new CityListClass("GRG1","지우르지우","루마니아","Europe/Bucharest"),
//		new CityListClass("GZYCK","지작코","폴란드","Europe/Warsaw"),
//		new CityListClass("GIZ","지잔","사우디아라비아","Asia/Riyadh"),
//		new CityListClass("ZNIN","진","폴란드","Europe/Warsaw"),
//			new CityListClass("21F20201","진도","대한민국","Asia/Seoul"),
//			new CityListClass("11F10303","진안","대한민국","Asia/Seoul"),
//			new CityListClass("11H20701","진주","대한민국","Asia/Seoul"),
//			new CityListClass("11C10102","진천","대한민국","Asia/Seoul"),
//			new CityListClass("11H20303","진해","대한민국","Asia/Seoul"),
//		new CityListClass("ZLN1","질리나","슬로바키아","Europe/Bratislava"),
//		new CityListClass("GLLNG","질링엄","영국","Europe/London"),
//		new CityListClass("ZWTTL","쯔베들","오스트리아","Europe/Vienna"),
	};
}
