package com.weathernews.Weather;

public class K {
	public final static CityListClass_E[] k = new CityListClass_E[] {
		new CityListClass_E("KABUL", "Kabul", "카불", "아프가 니스탄", "Asia/Kabul"),
		new CityListClass_E("KABWE1", "Kabwe", "카브웨", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("KCHK", "Kachikau", "카치카우", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("KADAN", "Kadan", "카단", "체코", "Europe/Prague"),
		new CityListClass_E("KDM", "Kadoma", "카도마", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("KAG", "Kagoshima", "가고시마", "일본", "Asia/Tokyo"),
		new CityListClass_E("KHRMN", "Kahramanamaras", "카흐라만마라스", "터키", "Europe/Istanbul"),
		new CityListClass_E("KAH", "Kahului", "카훌루이", "미국", "Pacific/Honolulu"),
		new CityListClass_E("KSRSL", "Kaiserslautern", "카이저슬라우테른", "독일", "Europe/Berlin"),
		new CityListClass_E("KKMS", "Kakamas", "카카마스", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KMT", "Kalamata", "칼라마타", "그리스", "Europe/Athens"),
		new CityListClass_E("KLMZ", "Kalamazoo", "칼라마주", "미국", "America/Detroit"),
		new CityListClass_E("KLNDR", "Kalandra", "칼란드라", "그리스", "Europe/Athens"),
		new CityListClass_E("KLVRT", "Kalavrita", "칼라브리타", "그리스", "Europe/Athens"),
		new CityListClass_E("KLGRL", "Kalgoorlie", "캘굴리", "오스트레일리아", "Australia/Perth"),
		new CityListClass_E("KLR", "Kaliningrad", "칼리닌그라드", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("KLSZ", "Kalisz", "칼리시", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KLMR", "Kalmar", "칼마르", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("KLGA", "Kaluga", "칼루가", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("KLVRJ", "Kalvarija", "칼바리야", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("KMSKR", "Kamieskroon", "카미스크룬", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KMLPS", "Kamloops", "캠루프스", "캐나다", "America/Vancouver"),
		new CityListClass_E("KMPL", "Kampala", "캄팔라", "우간다", "Africa/Kampala"),
		new CityListClass_E("KMPL", "Kampala", "캄팔라", "우간다", "Africa/Kampala"),
		new CityListClass_E("KNA", "Kanazawa", "카나자와", "일본", "Asia/Tokyo"),
		new CityListClass_E("KAD", "Kandla", "칸들라", "인도", "Asia/Calcutta"),
		new CityListClass_E("KNKK", "Kankakee", "캔카키", "미국", "America/Chicago"),
		new CityListClass_E("KNYA", "Kanoya", "카노야", "일본", "Asia/Tokyo"),
		new CityListClass_E("KNPR", "Kanpur", "칸푸르", "인도", "Asia/Calcutta"),
		new CityListClass_E("KS", "Kansas City", "캔자스 시티-미주리", "미국", "America/Chicago"),
		new CityListClass_E("KNSS", "Kansas City", "캔자스 시티-캔자스", "미국", "America/Chicago"),
		new CityListClass_E("KANYE", "Kanye", "카니에", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("KAO", "Kaohsiung", "가우슝", "대만", "Asia/Taipei"),
		new CityListClass_E("KAOMA", "Kaoma", "카오마", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MPSH", "Kapiri Mposhi", "카피리 음포시", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("KPSVR", "Kaposvar", "카보스바르", "헝가리", "Europe/Budapest"),
		new CityListClass_E("KAR", "Karachi", "카라치", "파키스탄", "Asia/Karachi"),
		new CityListClass_E("KARA", "Karaman", "카라만", "터키", "Europe/Istanbul"),
		new CityListClass_E("KRSBR", "Karasburg", "카라스버그", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("KRSJK", "Karasjok", "카라쇽", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("KRCG", "Karcag", "커르처그", "헝가리", "Europe/Budapest"),
		new CityListClass_E("KRDL", "Kardla", "캐르들라", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("KRDZH", "Kardzhali", "카르드잘리", "불가리아", "Europe/Sofia"),
		new CityListClass_E("KRLVC", "Karlovac", "카를로바츠", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("KRLVO", "Karlovo", "카를로보", "불가리아", "Europe/Sofia"),
		new CityListClass_E("KARL", "Karlskrona", "칼스크로나", "스웨덴", "Europe/Stockholm"),
//		new CityListClass_E("KRLSR", "Karlsruhe", "카를스루에", "독일", "Europe/Berlin"),
		new CityListClass_E("KRLST", "Karlstad", "칼스타드", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("KRPNS", "Karpenissi", "카르페니시", "그리스", "Europe/Athens"),
		new CityListClass_E("KRRTH", "Karratha", "카라타", "오스트레일리아", "Australia/Perth"),
		new CityListClass_E("KRUIZW", "Karuizawa", "카루이자와", "일본", "Asia/Tokyo"),
		new CityListClass_E("KRVN", "Karvina", "카르비나", "체코", "Europe/Prague"),
		new CityListClass_E("KSM1", "Kasama", "카사마", "잠비아", "Africa/Lusaka"),
//		new CityListClass_E("KSNE", "Kasane", "카세인", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("KSSEL", "Kassel", "카셀", "독일", "Europe/Berlin"),
		new CityListClass_E("KSTR", "Kastoria", "카스토랴", "그리스", "Europe/Athens"),
		new CityListClass_E("KTRN", "Katerini", "카테리니", "그리스", "Europe/Athens"),
		new CityListClass_E("KTT", "Katete", "카테테", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("KTHRN", "Katherine", "캐서린", "오스트레일리아", "Australia/Darwin"),
		new CityListClass_E("MLLK", "Katima Mulilo", "카티마 무릴로", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("KTMND", "Katmandu", "카트만두", "네팔", "Asia/Katmandu"),
		new CityListClass_E("KTMB", "Katoomba", "카툼바", "오스트레일리아", "Australia/Sydney"),
//		new CityListClass_E("KTWC1", "Katowice", "카토비체", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KTRNH", "Katrineholm", "카트리네홀름", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("KTSUUR", "Katsuura", "카츠우라", "일본", "Asia/Tokyo"),
		new CityListClass_E("KUNS", "Kaunas", "카우나스", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("KVDRC", "Kavadarci", "카바다치", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("KVL", "Kavala", "카발라", "그리스", "Europe/Athens"),
		new CityListClass_E("FJKWK", "Kawaguchiko", "카와구치코", "일본", "Asia/Tokyo"),
		new CityListClass_E("KWMBW", "Kawambwa", "카왐브아", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("KYSR", "Kayseri", "카이세리", "터키", "Europe/Istanbul"),
		new CityListClass_E("KASAN", "Kazan", "카잔", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("KAZEY", "Kazeya", "카제야", "일본", "Asia/Tokyo"),
		new CityListClass_E("KCSKM", "Kecskemet", "케치케메트", "헝가리", "Europe/Budapest"),
		new CityListClass_E("KDN", "Kedainiai", "케다이네이", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("KDZRZ", "Kedzierzyn-Kozle", "켕지에진 코질레", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KTMNS", "Keetmanshoop", "키트만슙", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("KFLVK", "Keflavik", "케플라빅", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass_E("KEITH", "Keith", "키스", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("KELME", "Kelme", "케레메", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("KLWN", "Kelowna", "켈로나", "캐나다", "America/Vancouver"),
		new CityListClass_E("KNDL", "Kendal", "켄다l", "영국", "Europe/London"),
		new CityListClass_E("KNR", "Kenora", "케노라", "캐나다", "America/Toronto"),
		new CityListClass_E("KEPNO", "Kepno", "켕프노", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KRKYR", "Kerkira", "케르키라", "그리스", "Europe/Athens"),
		new CityListClass_E("KSWCK", "Keswick", "케스윅", "영국", "Europe/London"),
		new CityListClass_E("KEW", "Kew", "큐", "터크스 케이커스 제도", "America/Grand_Turk"),
		new CityListClass_E("BSCYN", "Key Biscayne", "키 비스캐인", "미국", "America/New_York"),
		new CityListClass_E("KEY", "Key West", "키 웨스트", "미국", "America/New_York"),
		new CityListClass_E("KHRBR", "Khabarovsk", "하바롭스크", "러시아 연방 국가", "Asia/Vladivostok"),
		new CityListClass_E("KHRTM", "Khartoum", "하르툼", "Sudan", "Africa/Khartoum"),
		new CityListClass_E("KAF", "Khawr Fakkan", "코르 파칸", "아랍에미리트", "Asia/Dubai"),
		new CityListClass_E("KHOLM", "Kholm", "콜름", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KAEN", "Khon Kaen", "콘캔", "태국", "Asia/Bangkok"),
		new CityListClass_E("KHRXS", "Khorixas", "코리사스", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("KCV", "Kicevo", "케체보", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("KIL", "Kiel", "킬", "독일", "Europe/Berlin"),
		new CityListClass_E("KLC", "Kielce", "키엘체", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KIEV", "Kiev", "키예프", "우크라이나", "Europe/Kiev"),
		new CityListClass_E("KGLI", "Kigali", "키갈리", "Rwanda", "Africa/Kigali"),
		new CityListClass_E("KKG", "Kikai", "키카이", "일본", "Asia/Tokyo"),
		new CityListClass_E("KLKNN", "Kilkenny", "킬케니", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("KLKS", "Kilkis", "킬키스", "그리스", "Europe/Athens"),
		new CityListClass_E("KLLN", "Killeen", "킬린", "미국", "America/Chicago"),
		new CityListClass_E("KLMRN", "Kilmarnock", "킬마낙", "영국", "Europe/London"),
		new CityListClass_E("KMBRL", "Kimberley", "킴벌리", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KNGSP", "Kingsport", "킹즈포트", "미국", "America/New_York"),
		new CityListClass_E("KNGTG", "Kingston", "킹스턴", "캐나다", "America/Toronto"),
		new CityListClass_E("KGT", "Kingston", "킹스턴", "자메이카", "America/Jamaica"),
		new CityListClass_E("KNGST", "Kingston", "킹스톤", "미국", "America/New_York"),
		new CityListClass_E("KTN", "Kingstown", "킹스타운", "세인트 빈센트 그레나딘", "America/St_Vincent"),
		new CityListClass_E("KNSHS", "Kinshasa", "킨샤사", "콩고", "Africa/Brazzaville"),
		new CityListClass_E("KPRSS", "Kiparissia", "키파리시아", "그리스", "Europe/Athens"),
		new CityListClass_E("STPHN", "Kirby Stephen", "커크비 스티븐", "영국", "Europe/London"),
		new CityListClass_E("KRCHD", "Kirchdorf an der Krems", "키르히도르프 크렘스", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("KRKKL", "Kirikkale", "키리칼레", "터키", "Europe/Istanbul"),
		new CityListClass_E("KRK", "Kirkwall", "커크월l", "영국", "Europe/London"),
		new CityListClass_E("KRKWD", "Kirkwood", "커크우드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KIROW", "Kirow", "키로브", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("KRNA", "Kiruna", "키루나", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("KSHNY", "Kishinyov", "키시뇨프", "Moldova", "Europe/Chisinau"),
		new CityListClass_E("KSSMM", "Kissimmee", "키시미", "미국", "America/New_York"),
		new CityListClass_E("KTM", "Kitami", "키타미", "일본", "Asia/Tokyo"),
		new CityListClass_E("ESSI", "Kitamiesashi", "키타미에사시", "일본", "Asia/Tokyo"),
		new CityListClass_E("KTCHN", "Kitchener", "키치너", "캐나다", "America/Toronto"),
//		new CityListClass_E("KTHR", "Kithira", "키시라", "그리스", "Europe/Athens"),
		new CityListClass_E("KITWE", "Kitwe", "키트웨", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("KTZBH", "Kitzbuhel", "키츠뷔헬", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("KLDN1", "Kladno", "클라드노", "체코", "Europe/Prague"),
		new CityListClass_E("KLGNF", "Klagenfurt", "클라겐푸르트", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("KLP", "Klaipeda", "클레이페다", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("KLG", "Klang", "클랑", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KLTVY", "Klatovy", "클라토비", "체코", "Europe/Prague"),
		new CityListClass_E("KLRKS", "Klerksdorp", "클럭스도르프", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KLPPL", "Klipplaat", "클립플라트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KLCZB", "Kluczbork", "크로이츠부르크", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KNXTN", "Knoxville", "녹스빌", "미국", "America/New_York"),
		new CityListClass_E("KOB", "Kobe", "고베", "일본", "Asia/Tokyo"),
		new CityListClass_E("KBLNZ", "Koblenz", "코블렌츠", "독일", "Europe/Berlin"),
		new CityListClass_E("KCL", "Kocaeli", "코잘리", "터키", "Europe/Istanbul"),
		new CityListClass_E("KCNI", "Kocani", "코차니", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("KOC", "Kochi", "코치", "일본", "Asia/Tokyo"),
		new CityListClass_E("KOFU", "Kofu", "코후", "일본", "Asia/Tokyo"),
		new CityListClass_E("KOGE", "Koge", "코게", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("KHTL", "Kohtla-Jarve", "코흐틀라-예르베", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("KKM", "Kokomo", "코코모", "미국", "America/Indianapolis"),
		new CityListClass_E("KOLIN", "Kolin", "콜린", "체코", "Europe/Prague"),
//		new CityListClass_E("KMTPR", "Komatipoort", "코마티포트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KMTN", "Komotini", "코모티니", "그리스", "Europe/Athens"),
		new CityListClass_E("KNGSG", "Kongsberg", "콩스버그", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("KNTS", "Konitsa", "코니트사", "그리스", "Europe/Athens"),
		new CityListClass_E("KONYA", "Konya", "콘야", "터키", "Europe/Istanbul"),
		new CityListClass_E("KOP", "Koper", "코퍼", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("KPRVN", "Koprivnica", "코프리브니카", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("KORCE", "Korce", "코어스", "알바니아", "Europe/Tirane"),
		new CityListClass_E("KOROR", "Koror", "코로르", "팔라우", "Pacific/Palau"),
		new CityListClass_E("KOSX", "Kos", "코스", "그리스", "Europe/Athens"),
		new CityListClass_E("KSC", "Kosice", "코시체", "슬로바키아", "Europe/Bratislava"),
		new CityListClass_E("KSTER", "Koster", "코스터", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KSTRM", "Kostroma", "코스트로마", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("KSZLN", "Koszalin", "코살린", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("BHR", "Kota Baharu", "코타바하루", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KKB", "Kota Kinabalu", "코타키나발루", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KOTOR", "Kotor", "코토르", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("KOU", "Kourou", "쿠루", "기아나", "America/Cayenne"),
		new CityListClass_E("KZN", "Kozani", "코자니", "그리스", "Europe/Athens"),
		new CityListClass_E("KRGJV", "Kragujevac", "크라구예바츠", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("KRLND", "Kralendijk", "크라렌디즈크", "앤틸리스제도", "America/Curacao"),
		new CityListClass_E("KRLJV", "Kraljevo", "크라예보", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("KRANJ", "Kranj", "크란", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("KRPN", "Krapina", "크라피나", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("KRSNK", "KraSnik", "크라스닉", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("KRSND1", "Krasnodar", "크라스노다르", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("KRSNJ", "Krasnoyarsk", "크라스노야르스크", "러시아 연방 국가", "Asia/Krasnoyarsk"),
		new CityListClass_E("DONAU", "Krems an der Donau", "크렘스안데어도나우", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("KRTNG", "Kretinga", "크레팅가", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("KRT", "Kristiansand", "크리스티안산", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("KRTD", "Kristianstad", "크리스티안스타드", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("KTD", "Kristiansund", "크리스티안순", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("PLNK", "Kriva Palanka", "크리바팔란카", "마케도니아", "Europe/Skopje"),
//		new CityListClass_E("KRDZK", "Krodzko", "크워츠코", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KRMRZ", "KromeriZ", "크로메리츠", "체코", "Europe/Prague"),
		new CityListClass_E("KRSN", "Krosno", "크로스노", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("ODRZN", "Krosno Odrzanskie", "크로스노 오드잔스키에", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KRGRS", "Krugersdorf", "크루거스도프", "남아프리카공화국", "Africa/Johannesburg"),
//		new CityListClass_E("KRSZW", "Kruszwica", "크루쉬비차", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KRYNC", "Krynica-ZdrOj", "크리니카-즈드루이", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LMPR", "Kuala Lumpur", "쿠알라룸푸르", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KLT", "Kuala Terengganu", "콸라테렝가누", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KNGCH", "Kuangchou", "광저우", "중국", "Asia/Shanghai"),
		new CityListClass_E("KUA", "Kuantan", "콴탄", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KUCCH", "Kucchan", "쿳찬", "일본", "Asia/Tokyo"),
		new CityListClass_E("KUC", "Kuching", "쿠칭", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KDT", "Kudat", "쿠다트", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("KEILN", "Kueilin", "구이린", "중국", "Asia/Chongqing"),
		new CityListClass_E("KGLKT", "Kugluktuk", "쿠글룩툭", "캐나다", "America/Pangnirtung"),
		new CityListClass_E("KUKES", "Kukes", "쿠커스", "알바니아", "Europe/Tirane"),
		new CityListClass_E("KULP", "Kulp", "쿨프", "터키", "Europe/Istanbul"),
		new CityListClass_E("KULU", "Kulu", "쿨루", "터키", "Europe/Istanbul"),
		new CityListClass_E("KMGY", "Kumagaya", "쿠마가야", "일본", "Asia/Tokyo"),
		new CityListClass_E("KUM", "Kumamoto", "쿠마모토", "일본", "Asia/Tokyo"),
		new CityListClass_E("KMNV", "Kumanovo", "쿠마노보", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("KMJM", "Kumejima", "쿠메지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("KNGSB", "Kungsbacka", "쿵스바카", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("KNNRR", "Kununurra", "쿠누누라", "오스트레일리아", "Australia/Perth"),
		new CityListClass_E("KUP", "Kupang", "쿠팡", "인도네시아", "Asia/Makassar"),
		new CityListClass_E("KUR", "Kure", "쿠레", "일본", "Asia/Tokyo"),
		new CityListClass_E("KRSSR", "Kuressaare", "쿠레사레", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("KRGN", "Kurgan", "쿠르간", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("KURSK", "Kursk", "쿠르스크", "러시아 연방 국가", "Europe/Moscow"),
//		new CityListClass_E("KURMN", "Kuruman", "쿠루먼", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("KRUM", "Kurume", "쿠루메", "일본", "Asia/Tokyo"),
		new CityListClass_E("KUS", "Kushiro", "쿠시로", "일본", "Asia/Tokyo"),
		new CityListClass_E("KTHY", "Kutahya", "퀴타하아", "터키", "Europe/Istanbul"),
		new CityListClass_E("KTN1", "Kutina", "쿠티나", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("KUTNA", "Kutna Hora", "쿠트나호라", "체코", "Europe/Prague"),
		new CityListClass_E("KJJQ", "Kuujjuaq", "쿠주아크", "캐나다", "America/Montreal"),
//		new CityListClass_E("KJJRP", "Kuujjuarapik", "쿠주아라픽", "캐나다", "America/Montreal"),
		new CityListClass_E("KUW", "Kuwait", "쿠웨이트", "쿠웨이트", "Asia/Kuwait"),
		new CityListClass_E("KWKW", "Kwekwe", "퀘퀘", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("KWDZY", "Kwidzyn", "크비진", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("KYT", "Kyoto", "교토", "일본", "Asia/Tokyo"),
		new CityListClass_E("KYSTN", "Kyustendil", "큐스텐딜", "불가리아", "Europe/Sofia"),
		new CityListClass_E("KYZYL", "Kyzyl", "키질", "러시아 연방 국가", "Asia/Omsk"),

	};
}
