package com.weathernews.Weather;

class KA {
	public final static CityListClass[] ka = new CityListClass[] {
		new CityListClass("CAG", "카가얀데오로", "필리핀", "Asia/Manila"),
		new CityListClass("CRNRV", "카나본", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("KNA", "카나자와", "일본", "Asia/Tokyo"),
		new CityListClass("KNYA", "카노야", "일본", "Asia/Tokyo"),
		new CityListClass("KANYE", "카니에", "보츠와나", "Africa/Gaborone"),
		new CityListClass("KADAN", "카단", "체코", "Europe/Prague"),
		new CityListClass("KDM", "카도마", "짐바브웨", "Africa/Harare"),
		new CityListClass("CDZ", "카디스", "스페인", "Europe/Madrid"),
		new CityListClass("CRD", "카디프", "영국", "Europe/London"),
		new CityListClass("KARA", "카라만", "터키", "Europe/Istanbul"),
		new CityListClass("KRSJK", "카라쇽", "노르웨이", "Europe/Oslo"),
		new CityListClass("KRSBR", "카라스버그", "나미비아", "Africa/Windhoek"),
		new CityListClass("KAR", "카라치", "파키스탄", "Asia/Karachi"),
		new CityListClass("CRV", "카라카스", "베네수엘라", "America/Caracas"),
		new CityListClass("CRCL1", "카라칼", "루마니아", "Europe/Bucharest"),
		new CityListClass("KRRTH", "카라타", "오스트레일리아", "Australia/Perth"),
		new CityListClass("KRUIZW", "카루이자와", "일본", "Asia/Tokyo"),
		new CityListClass("KRDZH", "카르드잘리", "불가리아", "Europe/Sofia"),
		new CityListClass("KRVN", "카르비나", "체코", "Europe/Prague"),
		new CityListClass("CAR", "카르타헤나", "콜롬비아", "America/Bogota"),
		new CityListClass("CTS", "카르타헤나", "스페인", "Europe/Madrid"),
		new CityListClass("KRPNS", "카르페니시", "그리스", "Europe/Athens"),
		new CityListClass("KRLVC", "카를로바츠", "크로아티아", "Europe/Zagreb"),
		new CityListClass("KRLVO", "카를로보", "불가리아", "Europe/Sofia"),
//		new CityListClass("KRLSR", "카를스루에", "독일", "Europe/Berlin"),
		new CityListClass("CRRGL", "카리가린", "아일랜드", "Europe/Dublin"),
		new CityListClass("CMRL", "카마라 데 로보스", "포르투칼", "Atlantic/Madeira"),
		new CityListClass("KMSKR", "카미스크룬", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SKRZY", "카미엔나", "폴란드", "Europe/Warsaw"),
		new CityListClass("KVDRC", "카바다치", "마케도니아", "Europe/Skopje"),
		new CityListClass("CAVAN", "카반", "아일랜드", "Europe/Dublin"),
		new CityListClass("KVL", "카발라", "그리스", "Europe/Athens"),
		new CityListClass("CBZS", "카베자스 루비아스", "스페인", "Europe/Madrid"),
		new CityListClass("CRBNR", "카보네라", "스페인", "Europe/Madrid"),
		new CityListClass("KPSVR", "카보스바르", "헝가리", "Europe/Budapest"),
		new CityListClass("CRBND", "카본데일", "미국", "America/Chicago"),
		new CityListClass("KABUL", "카불", "아프가 니스탄", "Asia/Kabul"),
		new CityListClass("KABWE1", "카브웨", "잠비아", "Africa/Lusaka"),
		new CityListClass("KSM1", "카사마", "잠비아", "Africa/Lusaka"),
		new CityListClass("CAS", "카사블랑카", "모로코", "Africa/Casablanca"),
		new CityListClass("CCRS", "카세레스", "스페인", "Europe/Madrid"),
//		new CityListClass("KSNE", "카세인", "보츠와나", "Africa/Gaborone"),
		new CityListClass("KSSEL", "카셀", "독일", "Europe/Berlin"),
		new CityListClass("CTL", "카스테욘데라플라나", "스페인", "Europe/Madrid"),
		new CityListClass("CSTLB", "카스텔로 브랑코", "포르투칼", "Europe/Lisbon"),
		new CityListClass("KSTR", "카스토랴", "그리스", "Europe/Athens"),
		new CityListClass("CRSN", "카슨시티", "미국", "America/Los_Angeles"),
		new CityListClass("CYN", "카옌", "기아나", "America/Cayenne"),
		new CityListClass("CHRS", "카오르", "프랑스", "Europe/Paris"),
		new CityListClass("KAOMA", "카오마", "잠비아", "Africa/Lusaka"),
		new CityListClass("FJKWK", "카와구치코", "일본", "Asia/Tokyo"),
		new CityListClass("KWMBW", "카왐브아", "잠비아", "Africa/Lusaka"),
		new CityListClass("KUNS", "카우나스", "리투아니아", "Europe/Vilnius"),
		new CityListClass("CAIRO", "카이로", "이집트", "Africa/Cairo"),
		new CityListClass("KYSR", "카이세리", "터키", "Europe/Istanbul"),
		new CityListClass("KSRSL", "카이저슬라우테른", "독일", "Europe/Berlin"),
		new CityListClass("KASAN", "카잔", "러시아", "Europe/Moscow"),
		new CityListClass("KAZEY", "카제야", "일본", "Asia/Tokyo"),
		new CityListClass("QACHA", "카차스네크", "레소토", "Africa/Maseru"),
		new CityListClass("KTSUUR", "카츠우라", "일본", "Asia/Tokyo"),
		new CityListClass("KCHK", "카치카우", "보츠와나", "Africa/Gaborone"),
		new CityListClass("KKMS", "카카마스", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("CTA", "카타니아", "이탈리아", "Europe/Rome"),
		new CityListClass("CTNZR", "카탄차로", "이탈리아", "Europe/Rome"),
		new CityListClass("KTRN", "카테리니", "그리스", "Europe/Athens"),
		new CityListClass("KTT", "카테테", "잠비아", "Africa/Lusaka"),
//		new CityListClass("KTWC1", "카토비체", "폴란드", "Europe/Warsaw"),
		new CityListClass("KTMB", "카툼바", "오스트레일리아", "Australia/Sydney"),
		new CityListClass("KTRNH", "카트리네홀름", "스웨덴", "Europe/Stockholm"),
		new CityListClass("KTMND", "카트만두", "네팔", "Asia/Katmandu"),
		new CityListClass("MLLK", "카티마 무릴로", "나미비아", "Africa/Windhoek"),
		new CityListClass("CPSTR", "카페스테르 벨 오", "과들루프섬", "America/Guadeloupe"),
		new CityListClass("MPSH", "카피리 음포시", "잠비아", "Africa/Lusaka"),
		new CityListClass("KAH", "카훌루이", "미국", "Pacific/Honolulu"),
		new CityListClass("KHRMN", "카흐라만마라스", "터키", "Europe/Istanbul"),
		new CityListClass("KAD", "칸들라", "인도", "Asia/Calcutta"),
		new CityListClass("CNCN", "칸쿤", "멕시코", "America/Cancun"),
		new CityListClass("KNPR", "칸푸르", "인도", "Asia/Calcutta"),
		new CityListClass("CLRS1", "칼라라시", "루마니아", "Europe/Bucharest"),
		new CityListClass("KLMZ", "칼라마주", "미국", "America/Detroit"),
		new CityListClass("KMT", "칼라마타", "그리스", "Europe/Athens"),
		new CityListClass("CNVRS", "칼라버라스", "스페인", "Europe/Madrid"),
		new CityListClass("KLVRT", "칼라브리타", "그리스", "Europe/Athens"),
		new CityListClass("CLHRR", "칼라오라", "스페인", "Europe/Madrid"),
		new CityListClass("CRLSL", "칼라일", "영국", "Europe/London"),
		new CityListClass("CLTYD", "칼라타유드", "스페인", "Europe/Madrid"),
		new CityListClass("KLNDR", "칼란드라", "그리스", "Europe/Athens"),
		new CityListClass("CLS", "칼레", "프랑스", "Europe/Paris"),
		new CityListClass("CLLL", "칼레라", "스페인", "Europe/Madrid"),
		new CityListClass("CLHT", "칼레타", "포르투칼", "Atlantic/Madeira"),
		new CityListClass("CRLW", "칼로우", "아일랜드", "Europe/Dublin"),
		new CityListClass("KLGA", "칼루가", "러시아", "Europe/Moscow"),
		new CityListClass("CALI", "칼리", "콜롬비아", "America/Bogota"),
		new CityListClass("KLR", "칼리닌그라드", "러시아", "Europe/Moscow"),
		new CityListClass("KLSZ", "칼리시", "폴란드", "Europe/Warsaw"),
		new CityListClass("CGL", "칼리아리", "이탈리아", "Europe/Rome"),
		new CityListClass("KLMR", "칼마르", "스웨덴", "Europe/Stockholm"),
		new CityListClass("KLVRJ", "칼바리야", "리투아니아", "Europe/Vilnius"),
		new CityListClass("CLV1", "칼비아", "스페인", "Europe/Madrid"),
		new CityListClass("CRLSB", "칼스배드", "체코", "Europe/Prague"),
		new CityListClass("KARL", "칼스크로나", "스웨덴", "Europe/Stockholm"),
		new CityListClass("KRLST", "칼스타드", "스웨덴", "Europe/Stockholm"),
		new CityListClass("CLK", "칼시스", "그리스", "Europe/Athens"),
		new CityListClass("CRLTN", "칼턴빌", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("CLHT1", "칼헤타", "포르투칼", "Atlantic/Azores"),
		new CityListClass("KMPL", "캄팔라", "우간다", "Africa/Kampala"),
		new CityListClass("KMPL", "캄팔라", "우간다", "Africa/Kampala"),
		new CityListClass("BCA", "캄페체", "멕시코", "America/Merida"),
		new CityListClass("CMPBS", "캄포바소", "이탈리아", "Europe/Rome"),
		new CityListClass("CGRND", "캄푸그란데", "브라질", "America/Campo_Grande"),
		new CityListClass("CMPNS", "캄피나스", "브라질", "America/Sao_Paulo"),
		new CityListClass("CMPLL", "캄필로스", "스페인", "Europe/Madrid"),
		new CityListClass("CAPH", "캅 아이티엔", "아이티", "America/Port-au-Prince"),
		new CityListClass("CNE", "캉", "프랑스", "Europe/Paris"),
		new CityListClass("CLLTX", "캐롤톤", "미국", "America/Chicago"),
		new CityListClass("KRDL", "캐르들라", "에스토니아", "Europe/Tallinn"),
		new CityListClass("CARY", "캐리", "미국", "America/New_York"),
		new CityListClass("RVS", "캐릭온쉐논", "아일랜드", "Europe/Dublin"),
		new CityListClass("KTHRN", "캐서린", "오스트레일리아", "Australia/Darwin"),
		new CityListClass("CSTR", "캐스투에라", "스페인", "Europe/Madrid"),
		new CityListClass("CSTRN", "캐스트로누노", "스페인", "Europe/Madrid"),
		new CityListClass("CSI", "캐스트리스", "세인트루시아", "America/St_Lucia"),
		new CityListClass("CSPR", "캐스퍼", "미국", "America/Denver"),
		new CityListClass("CSTLB1", "캐슬바", "아일랜드", "Europe/Dublin"),
		new CityListClass("CNBRR", "캔버라", "오스트레일리아", "Australia/Sydney"),
		new CityListClass("KS", "캔자스 시티-미주리", "미국", "America/Chicago"),
		new CityListClass("KNSS", "캔자스 시티-캔자스", "미국", "America/Chicago"),
		new CityListClass("KNKK", "캔카키", "미국", "America/Chicago"),
		new CityListClass("CNTN", "캔턴", "미국", "America/New_York"),
		new CityListClass("CLGY", "캘거리", "캐나다", "America/Edmonton"),
		new CityListClass("KLGRL", "캘굴리", "오스트레일리아", "Australia/Perth"),
		new CityListClass("CAT", "캘커타", "인도", "Asia/Calcutta"),
		new CityListClass("CAM", "캠든", "미국", "America/New_York"),
		new CityListClass("KMLPS", "캠루프스", "캐나다", "America/Vancouver"),
		new CityListClass("CMR", "캠벨 리버", "캐나다", "America/Vancouver"),
		new CityListClass("CBGMA", "캠브리지", "미국", "America/New_York"),
		new CityListClass("CBGC", "캠브리지 베이", "캐나다", "America/Pangnirtung"),
		new CityListClass("QMPR", "캥페르", "프랑스", "Europe/Paris"),
		new CityListClass("KRCG", "커르처그", "헝가리", "Europe/Budapest"),
		new CityListClass("STPHN", "커크비 스티븐", "영국", "Europe/London"),
		new CityListClass("KRKWD", "커크우드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("KRK", "커크월l", "영국", "Europe/London"),
		new CityListClass("CNWY", "컨웨이", "미국", "America/Chicago"),
		new CityListClass("STTNC", "컬리지 스테이션", "미국", "America/Chicago"),
		new CityListClass("CLPPR", "컬페퍼", "미국", "America/New_York"),
//		new CityListClass("CMNCK", "컴녹", "영국", "Europe/London"),
		new CityListClass("CMBRL", "컴벌랜드", "미국", "America/New_York"),
		new CityListClass("KNR", "케노라", "캐나다", "America/Toronto"),
		new CityListClass("KDN", "케다이네이", "리투아니아", "Europe/Vilnius"),
		new CityListClass("KELME", "케레메", "리투아니아", "Europe/Vilnius"),
		new CityListClass("KRKYR", "케르키라", "그리스", "Europe/Athens"),
		new CityListClass("QZN", "케손시티", "필리핀", "Asia/Manila"),
		new CityListClass("KSWCK", "케스윅", "영국", "Europe/London"),
//		new CityListClass("CRN", "케언스", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass("DRST", "케이프 돌셋", "캐나다", "America/Pangnirtung"),
		new CityListClass("GRRD", "케이프 지라도", "미국", "America/Chicago"),
		new CityListClass("CRCFL", "케이프 코럴", "미국", "America/New_York"),
		new CityListClass("CPHRN", "케이프 혼", "칠레", "America/Santiago"),
		new CityListClass("CPT", "케이프타운", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("CBGG", "케임브리지", "영국", "Europe/London"),
		new CityListClass("KCV", "케체보", "마케도니아", "Europe/Skopje"),
		new CityListClass("KCSKM", "케치케메트", "헝가리", "Europe/Budapest"),
		new CityListClass("KFLVK", "케플라빅", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass("LGRNZ", "케피탄 파블로라헤렌사", "파라과이", "America/Asuncion"),
		new CityListClass("KNDL", "켄다l", "영국", "Europe/London"),
		new CityListClass("KLWN", "켈로나", "캐나다", "America/Vancouver"),
		new CityListClass("QEL", "켈리마네", "모잠비크", "Africa/Maputo"),
		new CityListClass("CHEMN", "켐니츠", "독일", "Europe/Berlin"),
		new CityListClass("KDZRZ", "켕지에진 코질레", "폴란드", "Europe/Warsaw"),
		new CityListClass("KEPNO", "켕프노", "폴란드", "Europe/Warsaw"),
		new CityListClass("KOGE", "코게", "덴마크", "Europe/Copenhagen"),
		new CityListClass("CRY", "코나크리", "Guinea", "Africa/Conakry"),
		new CityListClass("CBK", "코너 브룩", "캐나다", "America/St_Johns"),
		new CityListClass("KNTS", "코니트사", "그리스", "Europe/Athens"),
		new CityListClass("CDRNG", "코드링턴", "앤티가바부다", "America/Antigua"),
		new CityListClass("CORO", "코로", "베네수엘라", "America/Caracas"),
		new CityListClass("CRNA", "코로나", "미국", "America/Los_Angeles"),
		new CityListClass("KOROR", "코로르", "팔라우", "Pacific/Palau"),
		new CityListClass("CRZL", "코로살", "벨리즈", "America/Belize"),
		new CityListClass("LCO", "코루나", "스페인", "Europe/Madrid"),
		new CityListClass("CRCH", "코루체", "포르투칼", "Europe/Lisbon"),
		new CityListClass("KAF", "코르 파칸", "아랍에미리트", "Asia/Dubai"),
		new CityListClass("CRDB", "코르도바", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("CRDE", "코르도바", "스페인", "Europe/Madrid"),
		new CityListClass("CORVO", "코르보", "포르투칼", "Atlantic/Azores"),
		new CityListClass("CRSCN", "코르시카나", "미국", "America/Chicago"),
		new CityListClass("CRK", "코르크", "아일랜드", "Europe/Dublin"),
		new CityListClass("KHRXS", "코리사스", "나미비아", "Africa/Windhoek"),
		new CityListClass("CORIA", "코리아", "스페인", "Europe/Madrid"),
		new CityListClass("CRRNT", "코리엔테스", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("COO", "코린토", "니카라과", "America/Managua"),
		new CityListClass("CNH", "코린트", "그리스", "Europe/Athens"),
		new CityListClass("CMYG", "코마야과", "온두라스", "America/Tegucigalpa"),
//		new CityListClass("KMTPR", "코마티포트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("COMO", "코모도로리바다비아", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("KMTN", "코모티니", "그리스", "Europe/Athens"),
		new CityListClass("CMLLS", "코미야스", "스페인", "Europe/Madrid"),
		new CityListClass("DMNGZ", "코미탄 데 도밍구에즈", "멕시코", "America/Mexico_City"),
		new CityListClass("COBAN", "코반", "과테말라", "America/Guatemala"),
		new CityListClass("COB", "코브", "아일랜드", "Europe/Dublin"),
		new CityListClass("KBLNZ", "코블렌츠", "독일", "Europe/Berlin"),
		new CityListClass("CBJ", "코비하", "볼리비아", "America/La_Paz"),
		new CityListClass("CVLH", "코빌랴", "포르투칼", "Europe/Lisbon"),
		new CityListClass("KSZLN", "코살린", "폴란드", "Europe/Warsaw"),
		new CityListClass("CSNZ", "코센차", "이탈리아", "Europe/Rome"),
		new CityListClass("KOSX", "코스", "그리스", "Europe/Athens"),
		new CityListClass("CMESA", "코스타 메사", "미국", "America/Los_Angeles"),
		new CityListClass("KSTER", "코스터", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("KSTRM", "코스트로마", "러시아", "Europe/Moscow"),
		new CityListClass("KSC", "코시체", "슬로바키아", "Europe/Bratislava"),
		new CityListClass("KORCE", "코어스", "알바니아", "Europe/Tirane"),
		new CityListClass("CMBRA", "코임브라", "포르투칼", "Europe/Lisbon"),
		new CityListClass("KZN", "코자니", "그리스", "Europe/Athens"),
		new CityListClass("KCL", "코잘리", "터키", "Europe/Istanbul"),
		new CityListClass("CLCT", "코지코드", "인도", "Asia/Calcutta"),
		new CityListClass("KCNI", "코차니", "마케도니아", "Europe/Skopje"),
		new CityListClass("CCHBM", "코챠밤바", "볼리비아", "America/La_Paz"),
		new CityListClass("KOC", "코치", "일본", "Asia/Tokyo"),
		new CityListClass("COC", "코친", "인도", "Asia/Calcutta"),
		new CityListClass("KKM", "코코모", "미국", "America/Indianapolis"),
		new CityListClass("BEACH", "코코아 비치", "미국", "America/New_York"),
		new CityListClass("COQ", "코킴보", "칠레", "America/Santiago"),
		new CityListClass("BHR", "코타바하루", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("KKB", "코타키나발루", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("KOTOR", "코토르", "세르비아", "Europe/Belgrade"),
		new CityListClass("CTTBS", "코트부스", "독일", "Europe/Berlin"),
		new CityListClass("ALENE", "코틀레인", "미국", "America/Boise"),
		new CityListClass("KOP", "코퍼", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass("COR", "코퍼스 크리스티", "미국", "America/Chicago"),
		new CityListClass("COP", "코펜하겐", "덴마크", "Europe/Copenhagen"),
		new CityListClass("KPRVN", "코프리브니카", "크로아티아", "Europe/Zagreb"),
		new CityListClass("KOFU", "코후", "일본", "Asia/Tokyo"),
		new CityListClass("KHTL", "코흐틀라-예르베", "에스토니아", "Europe/Tallinn"),
		new CityListClass("CCKBR", "콕번하버", "터크스 케이커스 제도", "America/Grand_Turk"),
		new CityListClass("BHC", "콘셉시온", "칠레", "America/Santiago"),
		new CityListClass("CNCEP", "콘셉시온", "파라과이", "America/Asuncion"),
		new CityListClass("CTZ", "콘스탄차", "루마니아", "Europe/Bucharest"),
		new CityListClass("THMMR", "콘시탐마라트", "태국", "Asia/Bangkok"),
		new CityListClass("KONYA", "콘야", "터키", "Europe/Istanbul"),
		new CityListClass("KAEN", "콘캔", "태국", "Asia/Bangkok"),
		new CityListClass("CNTGM", "콘타젱", "브라질", "America/Bahia"),
		new CityListClass("VLLLB", "콜라도 빌라바", "스페인", "Europe/Madrid"),
		new CityListClass("CBSOH", "콜럼버스-오하이오", "미국", "America/New_York"),
		new CityListClass("COLUM", "콜럼버스-인디애나", "미국", "America/Indianapolis"),
		new CityListClass("CBSGA", "콜럼버스-조지아", "미국", "America/New_York"),
		new CityListClass("COLMB", "콜럼비아-메릴랜드", "미국", "America/New_York"),
		new CityListClass("CLMBR", "콜럼비아-미주리", "미국", "America/Chicago"),
		new CityListClass("CLMSC", "콜럼비아-사우스캐롤라이나", "미국", "America/New_York"),
		new CityListClass("CLUMB", "콜럼비아-테네시", "미국", "America/Chicago"),
		new CityListClass("CLSBR", "콜레스버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SCRMN", "콜로니아 델 사크라멘토", "우루과이", "America/Montevideo"),
		new CityListClass("CLRCO", "콜로라도 스프링스", "미국", "America/Denver"),
		new CityListClass("CLN", "콜론", "파나마", "America/Panama"),
		new CityListClass("KHOLM", "콜름", "폴란드", "Europe/Warsaw"),
		new CityListClass("KOLIN", "콜린", "체코", "Europe/Prague"),
		new CityListClass("COLR", "콜마르", "프랑스", "Europe/Paris"),
		new CityListClass("CLWYN", "콜윈 베이", "영국", "Europe/London"),
		new CityListClass("CHRBR", "콥스하버", "오스트레일리아", "Australia/Sydney"),
		new CityListClass("CONC", "콩고드-노스캐롤라이나", "미국", "America/New_York"),
		new CityListClass("CCDNH", "콩고드-뉴햄프셔", "미국", "America/New_York"),
		new CityListClass("CCD", "콩고드-캘리포니아", "미국", "America/Los_Angeles"),
		new CityListClass("KNGSG", "콩스버그", "노르웨이", "Europe/Oslo"),
		new CityListClass("KUA", "콴탄", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("KLT", "콸라테렝가누", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("CLGN", "쾰른", "독일", "Europe/Berlin"),
		new CityListClass("KGLKT", "쿠글룩툭", "캐나다", "America/Pangnirtung"),
		new CityListClass("CUNEO", "쿠네오", "이탈리아", "Europe/Rome"),
		new CityListClass("KNNRR", "쿠누누라", "오스트레일리아", "Australia/Perth"),
		new CityListClass("KDT", "쿠다트", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("KUR", "쿠레", "일본", "Asia/Tokyo"),
		new CityListClass("KRSSR", "쿠레사레", "에스토니아", "Europe/Tallinn"),
		new CityListClass("KOU", "쿠루", "기아나", "America/Cayenne"),
//		new CityListClass("KURMN", "쿠루먼", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("KRUM", "쿠루메", "일본", "Asia/Tokyo"),
		new CityListClass("KRGN", "쿠르간", "러시아", "Asia/Yekaterinburg"),
		new CityListClass("KURSK", "쿠르스크", "러시아", "Europe/Moscow"),
		new CityListClass("CRTBA", "쿠리티바", "브라질", "America/Bahia"),
		new CityListClass("KMGY", "쿠마가야", "일본", "Asia/Tokyo"),
		new CityListClass("CUM", "쿠마나", "베네수엘라", "America/Caracas"),
		new CityListClass("KMNV", "쿠마노보", "마케도니아", "Europe/Skopje"),
		new CityListClass("KUM", "쿠마모토", "일본", "Asia/Tokyo"),
		new CityListClass("KMJM", "쿠메지마", "일본", "Asia/Tokyo"),
		new CityListClass("CBRP", "쿠버페디", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass("CUSCO", "쿠스코", "페루", "America/Lima"),
		new CityListClass("KUS", "쿠시로", "일본", "Asia/Tokyo"),
		new CityListClass("CHUR", "쿠아르", "스위스", "Europe/Zurich"),
		new CityListClass("LMPR", "쿠알라룸푸르", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("CRNVC", "쿠에르나바카", "멕시코", "America/Mexico_City"),
		new CityListClass("CLLR", "쿠에야르", "스페인", "Europe/Madrid"),
		new CityListClass("CENC", "쿠엔카", "에콰도르", "America/Guayaquil"),
		new CityListClass("CNC1", "쿠엔카", "스페인", "Europe/Madrid"),
		new CityListClass("KUW", "쿠웨이트", "쿠웨이트", "Asia/Kuwait"),
//		new CityListClass("KJJRP", "쿠주아라픽", "캐나다", "America/Montreal"),
		new CityListClass("KJJQ", "쿠주아크", "캐나다", "America/Montreal"),
		new CityListClass("KUC", "쿠칭", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("KUKES", "쿠커스", "알바니아", "Europe/Tirane"),
		new CityListClass("CCT1", "쿠쿠타", "콜롬비아", "America/Bogota"),
		new CityListClass("KUTNA", "쿠트나호라", "체코", "Europe/Prague"),
		new CityListClass("QUTUF", "쿠트푸", "아랍에미리트", "Asia/Dubai"),
		new CityListClass("KTN1", "쿠티나", "크로아티아", "Europe/Zagreb"),
		new CityListClass("QTHNG", "쿠팅", "레소토", "Africa/Maseru"),
		new CityListClass("KUP", "쿠팡", "인도네시아", "Asia/Makassar"),
		new CityListClass("CKVLL", "쿡빌", "미국", "America/Chicago"),
		new CityListClass("KULU", "쿨루", "터키", "Europe/Istanbul"),
//		new CityListClass("CLCN", "쿨리아칸", "멕시코", "America/Mazatlan"),
		new CityListClass("KULP", "쿨프", "터키", "Europe/Istanbul"),
		new CityListClass("KUCCH", "쿳찬", "일본", "Asia/Tokyo"),
		new CityListClass("KNGSB", "쿵스바카", "스웨덴", "Europe/Stockholm"),
		new CityListClass("QVD", "퀘베도", "에콰도르", "America/Guayaquil"),
		new CityListClass("QBC", "퀘벡", "캐나다", "America/Montreal"),
		new CityListClass("KWKW", "퀘퀘", "짐바브웨", "Africa/Harare"),
		new CityListClass("KTHY", "퀴타하아", "터키", "Europe/Istanbul"),
		new CityListClass("QUITO", "퀴토", "에콰도르", "America/Guayaquil"),
		new CityListClass("QNC", "퀸시-매사추세츠", "미국", "America/New_York"),
		new CityListClass("QUNCY", "퀸시-일리노이", "미국", "America/Chicago"),
		new CityListClass("KEW", "큐", "터크스 케이커스 제도", "America/Grand_Turk"),
		new CityListClass("KYSTN", "큐스텐딜", "불가리아", "Europe/Sofia"),
		new CityListClass("KRGJV", "크라구예바츠", "세르비아", "Europe/Belgrade"),
		new CityListClass("KRLND", "크라렌디즈크", "앤틸리스제도", "America/Curacao"),
//		new CityListClass("KRSND1", "크라스노다르", "러시아", "Europe/Moscow"),
		new CityListClass("KRSNJ", "크라스노야르스크", "러시아", "Asia/Krasnoyarsk"),
		new CityListClass("KRSNK", "크라스닉", "폴란드", "Europe/Warsaw"),
		new CityListClass("KRLJV", "크라예보", "세르비아", "Europe/Belgrade"),
		new CityListClass("CHCH", "크라이스트 처치", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass("CRAV", "크라이오바", "루마니아", "Europe/Bucharest"),
		new CityListClass("CRCW", "크라쿠프", "폴란드", "Europe/Warsaw"),
		new CityListClass("KRPN", "크라피나", "크로아티아", "Europe/Zagreb"),
		new CityListClass("KRANJ", "크란", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass("CRDCK", "크래독", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("CRSCNC", "크레센트 시티", "미국", "America/Los_Angeles"),
		new CityListClass("CRGVN", "크레이개번", "영국", "Europe/Belfast"),
		new CityListClass("CRANE", "크레인", "바베이도스", "America/Barbados"),
		new CityListClass("CRTL", "크레테일", "프랑스", "Europe/Paris"),
		new CityListClass("KRTNG", "크레팅가", "리투아니아", "Europe/Vilnius"),
		new CityListClass("DONAU", "크렘스안데어도나우", "오스트리아", "Europe/Vienna"),
		new CityListClass("KRMRZ", "크로메리츠", "체코", "Europe/Prague"),
		new CityListClass("CRNML", "크로멜", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass("KRSN", "크로스노", "폴란드", "Europe/Warsaw"),
		new CityListClass("ODRZN", "크로스노 오드잔스키에", "폴란드", "Europe/Warsaw"),
		new CityListClass("KLCZB", "크로이츠부르크", "폴란드", "Europe/Warsaw"),
		new CityListClass("COE", "크로톤", "이탈리아", "Europe/Rome"),
		new CityListClass("CREWE", "크루", "영국", "Europe/London"),
		new CityListClass("KRGRS", "크루거스도프", "남아프리카공화국", "Africa/Johannesburg"),
//		new CityListClass("KRSZW", "크루쉬비차", "폴란드", "Europe/Warsaw"),
		new CityListClass("CRUZB", "크루즈 베이", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass("KRYNC", "크리니카-즈드루이", "폴란드", "Europe/Warsaw"),
		new CityListClass("PLNK", "크리바팔란카", "마케도니아", "Europe/Skopje"),
		new CityListClass("CHSTM", "크리스마스 섬", "크리스마스 섬", "Indian/Christmas"),
		new CityListClass("CHRST", "크리스천스테드", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass("KRT", "크리스티안산", "노르웨이", "Europe/Oslo"),
		new CityListClass("KTD", "크리스티안순", "노르웨이", "Europe/Oslo"),
		new CityListClass("KRTD", "크리스티안스타드", "스웨덴", "Europe/Stockholm"),
		new CityListClass("KWDZY", "크비진", "폴란드", "Europe/Warsaw"),
		new CityListClass("XNTH", "크산티", "그리스", "Europe/Athens"),
		new CityListClass("SBYH", "크와르 아스 사비야", "쿠웨이트", "Asia/Kuwait"),
//		new CityListClass("KRDZK", "크워츠코", "폴란드", "Europe/Warsaw"),
		new CityListClass("KLGNF", "클라겐푸르트", "오스트리아", "Europe/Vienna"),
		new CityListClass("KLDN1", "클라드노", "체코", "Europe/Prague"),
		new CityListClass("KLTVY", "클라토비", "체코", "Europe/Prague"),
		new CityListClass("CLRKS", "클락스버그", "미국", "America/New_York"),
		new CityListClass("CLKTN", "클락스빌", "미국", "America/Chicago"),
		new CityListClass("KLG", "클랑", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("CLARE", "클래어", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass("CLNWL", "클랜윌리암", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("KLRKS", "클럭스도르프", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("CLRMN", "클레르몽페랑", "프랑스", "Europe/Paris"),
		new CityListClass("KLP", "클레이페다", "리투아니아", "Europe/Vilnius"),
		new CityListClass("CLNML", "클론멜", "아일랜드", "Europe/Dublin"),
		new CityListClass("NPCA", "클루지나포카", "루마니아", "Europe/Bucharest"),
		new CityListClass("CLV", "클리블랜드", "미국", "America/New_York"),
		new CityListClass("CLRWFL", "클리어워터", "미국", "America/New_York"),
		new CityListClass("CLFTN", "클리프턴", "미국", "America/New_York"),
		new CityListClass("KLPPL", "클립플라트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("BSCYN", "키 비스캐인", "미국", "America/New_York"),
		new CityListClass("KEY", "키 웨스트", "미국", "America/New_York"),
		new CityListClass("KGLI", "키갈리", "Rwanda", "Africa/Kigali"),
		new CityListClass("KIROW", "키로브", "러시아", "Asia/Yekaterinburg"),
		new CityListClass("KRNA", "키루나", "스웨덴", "Europe/Stockholm"),
		new CityListClass("KRCHD", "키르히도르프 크렘스", "오스트리아", "Europe/Vienna"),
		new CityListClass("KRKKL", "키리칼레", "터키", "Europe/Istanbul"),
		new CityListClass("KEITH", "키스", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass("KSHNY", "키시뇨프", "Moldova", "Europe/Chisinau"),
//		new CityListClass("KTHR", "키시라", "그리스", "Europe/Athens"),
		new CityListClass("KSSMM", "키시미", "미국", "America/New_York"),
		new CityListClass("CHT", "키에티", "이탈리아", "Europe/Rome"),
		new CityListClass("KLC", "키엘체", "폴란드", "Europe/Warsaw"),
		new CityListClass("KIEV", "키예프", "우크라이나", "Europe/Kiev"),
		new CityListClass("KYZYL", "키질", "러시아", "Asia/Omsk"),
		new CityListClass("KTZBH", "키츠뷔헬", "오스트리아", "Europe/Vienna"),
		new CityListClass("KTCHN", "키치너", "캐나다", "America/Toronto"),
		new CityListClass("KKG", "키카이", "일본", "Asia/Tokyo"),
		new CityListClass("KTM", "키타미", "일본", "Asia/Tokyo"),
		new CityListClass("ESSI", "키타미에사시", "일본", "Asia/Tokyo"),
		new CityListClass("KTMNS", "키트만슙", "나미비아", "Africa/Windhoek"),
		new CityListClass("KITWE", "키트웨", "잠비아", "Africa/Lusaka"),
		new CityListClass("KPRSS", "키파리시아", "그리스", "Europe/Athens"),
		new CityListClass("KNSHS", "킨샤사", "콩고", "Africa/Brazzaville"),
		new CityListClass("KIL", "킬", "독일", "Europe/Berlin"),
		new CityListClass("KLLN", "킬린", "미국", "America/Chicago"),
		new CityListClass("KLMRN", "킬마낙", "영국", "Europe/London"),
		new CityListClass("KLKNN", "킬케니", "아일랜드", "Europe/Dublin"),
		new CityListClass("KLKS", "킬키스", "그리스", "Europe/Athens"),
		new CityListClass("KMBRL", "킴벌리", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("KTN", "킹스타운", "세인트 빈센트 그레나딘", "America/St_Vincent"),
		new CityListClass("KNGTG", "킹스턴", "캐나다", "America/Toronto"),
		new CityListClass("KGT", "킹스턴", "자메이카", "America/Jamaica"),
		new CityListClass("KNGST", "킹스톤", "미국", "America/New_York"),
		new CityListClass("KNGSP", "킹즈포트", "미국", "America/New_York"),

//		new CityListClass("CAG","카가얀데오로","필리핀","Asia/Manila"),
//		new CityListClass("CRNRV","카나본","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("KNA","카나자와","일본","Asia/Tokyo"),
//		new CityListClass("KNYA","카노야","일본","Asia/Tokyo"),
//		new CityListClass("KANYE","카니에","보츠와나","Africa/Gaborone"),
//		new CityListClass("KADAN","카단","체코","Europe/Prague"),
//		new CityListClass("KDM","카도마","짐바브웨","Africa/Harare"),
//		new CityListClass("CDZ","카디스","스페인","Europe/Madrid"),
//		new CityListClass("CRD","카디프","영국","Europe/London"),
//		new CityListClass("KARA","카라만","터키","Europe/Istanbul"),
//		new CityListClass("KRSJK","카라쇽","노르웨이","Europe/Oslo"),
//		new CityListClass("KRSBR","카라스버그","나미비아","Africa/Windhoek"),
//		new CityListClass("KAR","카라치","파키스탄","Asia/Karachi"),
//	    	new CityListClass("CRV","카라카스","베네수엘라","America/Caracas"),
//		new CityListClass("CRCL1","카라칼","루마니아","Europe/Bucharest"),
//		new CityListClass("KRRTH","카라타","오스트레일리아","Australia/Perth"),
//		new CityListClass("KRUIZW","카루이자와","일본","Asia/Tokyo"),
//		new CityListClass("KRDZH","카르드잘리","불가리아","Europe/Sofia"),
//		new CityListClass("KRVN","카르비나","체코","Europe/Prague"),
//		new CityListClass("CAR","카르타헤나","콜롬비아","America/Bogota"),
//		new CityListClass("CTS","카르타헤나","스페인","Europe/Madrid"),
//		new CityListClass("KRPNS","카르페니시","그리스","Europe/Athens"),
//		new CityListClass("KRLVC","카를로바츠","크로아티아","Europe/Zagreb"),
//		new CityListClass("KRLVO","카를로보","불가리아","Europe/Sofia"),
//		new CityListClass("KRLSR","카를스루에","독일","Europe/Berlin"),
//		new CityListClass("CRRGL","카리가린","아일랜드","Europe/Dublin"),
//		new CityListClass("CMRL","카마라 데 로보스","포르투칼","Atlantic/Madeira"),
//		new CityListClass("KMSKR","카미스크룬","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SKRZY","카미엔나","폴란드","Europe/Warsaw"),
//		new CityListClass("KVDRC","카바다치","마케도니아","Europe/Skopje"),
//		new CityListClass("CAVAN","카반","아일랜드","Europe/Dublin"),
//		new CityListClass("KVL","카발라","그리스","Europe/Athens"),
//		new CityListClass("CBZS","카베자스 루비아스","스페인","Europe/Madrid"),
//		new CityListClass("CRBNR","카보네라","스페인","Europe/Madrid"),
//		new CityListClass("CRBND","카본데일","미국","America/Chicago"),
//		new CityListClass("KABUL","카불","아프가 니스탄","Asia/Kabul"),
//		new CityListClass("KABWE1","카브웨","잠비아","Africa/Lusaka"),
//		new CityListClass("KSM1","카사마","잠비아","Africa/Lusaka"),
//		new CityListClass("CAS","카사블랑카","모로코","Africa/Casablanca"),
//		new CityListClass("CCRS","카세레스","스페인","Europe/Madrid"),
//		new CityListClass("KSNE","카세인","보츠와나","Africa/Gaborone"),
//		new CityListClass("KSSEL","카셀","독일","Europe/Berlin"),
//		new CityListClass("CTL","카스테욘데라플라나","스페인","Europe/Madrid"),
//		new CityListClass("CSTLB","카스텔로 브랑코","포르투칼","Europe/Lisbon"),
//		new CityListClass("KSTR","카스토랴","그리스","Europe/Athens"),
//		new CityListClass("CRSN","카슨시티","미국","America/Los_Angeles"),
//		new CityListClass("CYN","카옌","기아나","America/Cayenne"),
//		new CityListClass("CHRS","카오르","프랑스","Europe/Paris"),
//		new CityListClass("KAOMA","카오마","잠비아","Africa/Lusaka"),
//		new CityListClass("FJKWK","카와구치코","일본","Asia/Tokyo"),
//		new CityListClass("KWMBW","카왐브아","잠비아","Africa/Lusaka"),
//	    	new CityListClass("KUNS","카우나스","리투아니아","Europe/Vilnius"),
//			new CityListClass("CAIRO","카이로","이집트","Africa/Cairo"),
//		new CityListClass("KYSR","카이세리","터키","Europe/Istanbul"),
//		new CityListClass("KSRSL","카이저슬라우테른","독일","Europe/Berlin"),
//		new CityListClass("KASAN","카잔","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("QACHA","카차스네크","레소토","Africa/Maseru"),
//		new CityListClass("KTSUUR","카츠우라","일본","Asia/Tokyo"),
//		new CityListClass("KCHK","카치카우","보츠와나","Africa/Gaborone"),
//		new CityListClass("KKMS","카카마스","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("CTA","카타니아","이탈리아","Europe/Rome"),
//		new CityListClass("CTNZR","카탄차로","이탈리아","Europe/Rome"),
//		new CityListClass("KTRN","카테리니","그리스","Europe/Athens"),
//		new CityListClass("KTT","카테테","잠비아","Africa/Lusaka"),
//		new CityListClass("KTWC1","카토비체","폴란드","Europe/Warsaw"),
//		new CityListClass("KTMB","카툼바","오스트레일리아","Australia/Sydney"),
//		new CityListClass("KTRNH","카트리네홀름","스웨덴","Europe/Stockholm"),
//		new CityListClass("KTMND","카트만두","네팔","Asia/Katmandu"),
//		new CityListClass("MLLK","카티마 무릴로","나미비아","Africa/Windhoek"),
//		new CityListClass("CPSTR","카페스테르 벨 오","과들루프섬","America/Guadeloupe"),
//		new CityListClass("MPSH","카피리 음포시","잠비아","Africa/Lusaka"),
//		new CityListClass("KAH","카훌루이","미국","Pacific/Honolulu"),
//		new CityListClass("KHRMN","카흐라만마라스","터키","Europe/Istanbul"),
//		new CityListClass("KAD","칸들라","인도","Asia/Calcutta"),
//		new CityListClass("CNCN","칸쿤","멕시코","America/Cancun"),
//		new CityListClass("KNPR","칸푸르","인도","Asia/Calcutta"),
//		new CityListClass("CLRS1","칼라라시","루마니아","Europe/Bucharest"),
//		new CityListClass("KLMZ","칼라마주","미국","America/Detroit"),
//		new CityListClass("KMT","칼라마타","그리스","Europe/Athens"),
//		new CityListClass("CNVRS","칼라버라스","스페인","Europe/Madrid"),
//		new CityListClass("KLVRT","칼라브리타","그리스","Europe/Athens"),
//		new CityListClass("CLHRR","칼라오라","스페인","Europe/Madrid"),
//		new CityListClass("CRLSL","칼라일","영국","Europe/London"),
//		new CityListClass("CLTYD","칼라타유드","스페인","Europe/Madrid"),
//		new CityListClass("KLNDR","칼란드라","그리스","Europe/Athens"),
//		new CityListClass("CLS","칼레","프랑스","Europe/Paris"),
//		new CityListClass("CLLL","칼레라","스페인","Europe/Madrid"),
//		new CityListClass("CLHT","칼레타","포르투칼","Atlantic/Madeira"),
//		new CityListClass("CRLW","칼로우","아일랜드","Europe/Dublin"),
//		new CityListClass("KLGA","칼루가","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("CALI","칼리","콜롬비아","America/Bogota"),
//		new CityListClass("KLR","칼리닌그라드","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("KLSZ","칼리시","폴란드","Europe/Warsaw"),
//		new CityListClass("CGL","칼리아리","이탈리아","Europe/Rome"),
//		new CityListClass("KLMR","칼마르","스웨덴","Europe/Stockholm"),
//	    	new CityListClass("KLVRJ","칼바리야","리투아니아","Europe/Vilnius"),
//		new CityListClass("CLV1","칼비아","스페인","Europe/Madrid"),
//		new CityListClass("CRLSB","칼스배드","체코","Europe/Prague"),
//		new CityListClass("KARL","칼스크로나","스웨덴","Europe/Stockholm"),
//		new CityListClass("KRLST","칼스타드","스웨덴","Europe/Stockholm"),
//		new CityListClass("CLK","칼시스","그리스","Europe/Athens"),
//		new CityListClass("CRLTN","칼턴빌","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("CLHT1","칼헤타","포르투칼","Atlantic/Azores"),
//		new CityListClass("KMPL","캄팔라","우간다","Africa/Kampala"),
//		new CityListClass("KMPL","캄팔라","우간다","Africa/Kampala"),
//		new CityListClass("BCA","캄페체","멕시코","America/Merida"),
//		new CityListClass("CMPBS","캄포바소","이탈리아","Europe/Rome"),
//		new CityListClass("CGRND","캄푸그란데","브라질","America/Campo_Grande"),
//		new CityListClass("CMPNS","캄피나스","브라질","America/Sao_Paulo"),
//		new CityListClass("CMPLL","캄필로스","스페인","Europe/Madrid"),
//		new CityListClass("CAPH","캅 아이티엔","아이티","America/Port-au-Prince"),
//		new CityListClass("CNE","캉","프랑스","Europe/Paris"),
//		new CityListClass("KAZEY","캊야","일본","Asia/Tokyo"),
//		new CityListClass("CLLTX","캐롤톤","미국","America/Chicago"),
//		new CityListClass("KRDL","캐르들라","에스토니아","Europe/Tallinn"),
//		new CityListClass("CARY","캐리","미국","America/New_York"),
//		new CityListClass("RVS","캐릭온쉐논","아일랜드","Europe/Dublin"),
//		new CityListClass("KTHRN","캐서린","오스트레일리아","Australia/Darwin"),
//		new CityListClass("CSTR","캐스투에라","스페인","Europe/Madrid"),
//		new CityListClass("CSTRN","캐스트로누노","스페인","Europe/Madrid"),
//		new CityListClass("CSI","캐스트리스","세인트루시아","America/St_Lucia"),
//		new CityListClass("CSPR","캐스퍼","미국","America/Denver"),
//		new CityListClass("CSTLB1","캐슬바","아일랜드","Europe/Dublin"),
//		new CityListClass("CNBRR","캔버라","오스트레일리아","Australia/Sydney"),
//		new CityListClass("KS","캔자스 시티-미주리","미국","America/Chicago"),
//		new CityListClass("KNSS","캔자스 시티-캔자스","미국","America/Chicago"),
//		new CityListClass("KNKK","캔카키","미국","America/Chicago"),
//		new CityListClass("CNTN","캔턴","미국","America/New_York"),
//		new CityListClass("CLGY","캘거리","캐나다","America/Edmonton"),
//		new CityListClass("KLGRL","캘굴리","오스트레일리아","Australia/Perth"),
//		new CityListClass("CAT","캘커타","인도","Asia/Calcutta"),
//		new CityListClass("CAM","캠든","미국","America/New_York"),
//		new CityListClass("KMLPS","캠루프스","캐나다","America/Vancouver"),
//		new CityListClass("CMR","캠벨 리버","캐나다","America/Vancouver"),
//		new CityListClass("CBGMA","캠브리지","미국","America/New_York"),
//		new CityListClass("CBGC","캠브리지 베이","캐나다","America/Pangnirtung"),
//		new CityListClass("QMPR","캥페르","프랑스","Europe/Paris"),
//		new CityListClass("STPHN","커크비 스티븐","영국","Europe/London"),
//		new CityListClass("KRKWD","커크우드","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("KRK","커크월l","영국","Europe/London"),
//		new CityListClass("CNWY","컨웨이","미국","America/Chicago"),
//		new CityListClass("STTNC","컬리지 스테이션","미국","America/Chicago"),
//		new CityListClass("CLPPR","컬페퍼","미국","America/New_York"),
//		new CityListClass("CMNCK","컴녹","영국","Europe/London"),
//		new CityListClass("CMBRL","컴벌랜드","미국","America/New_York"),
//		new CityListClass("KNR","케노라","캐나다","America/Toronto"),
//	    	new CityListClass("KDN","케다이네이","리투아니아","Europe/Vilnius"),
//	    	new CityListClass("KELME","케레메","리투아니아","Europe/Vilnius"),
//		new CityListClass("KRKYR","케르키라","그리스","Europe/Athens"),
//		new CityListClass("QZN","케손시티","필리핀","Asia/Manila"),
//		new CityListClass("KSWCK","케스윅","영국","Europe/London"),
//		new CityListClass("CRN","케언스","오스트레일리아","Australia/Brisbane"),
//		new CityListClass("DRST","케이프 돌셋","캐나다","America/Pangnirtung"),
//		new CityListClass("GRRD","케이프 지라도","미국","America/Chicago"),
//		new CityListClass("CRCFL","케이프 코럴","미국","America/New_York"),
//		new CityListClass("CPHRN","케이프 혼","칠레","America/Santiago"),
//		new CityListClass("CPT","케이프타운","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("CBGG","케임브리지","영국","Europe/London"),
//		new CityListClass("KCV","케체보","마케도니아","Europe/Skopje"),
//		new CityListClass("KFLVK","케플라빅","아이스랜드","Atlantic/Reykjavik"),
//		new CityListClass("LGRNZ","케피탄 파블로라헤렌사","파라과이","America/Asuncion"),
//		new CityListClass("KNDL","켄다l","영국","Europe/London"),
//		new CityListClass("KLWN","켈로나","캐나다","America/Vancouver"),
//		new CityListClass("QEL","켈리마네","모잠비크","Africa/Maputo"),
//		new CityListClass("CHEMN","켐니츠","독일","Europe/Berlin"),
//		new CityListClass("KDZRZ","켕지에진 코질레","폴란드","Europe/Warsaw"),
//		new CityListClass("KEPNO","켕프노","폴란드","Europe/Warsaw"),
//		new CityListClass("KOGE","코게","덴마크","Europe/Copenhagen"),
//		new CityListClass("CRY","코나크리","Guinea","Africa/Conakry"),
//		new CityListClass("CBK","코너 브룩","캐나다","America/St_Johns"),
//		new CityListClass("KNTS","코니트사","그리스","Europe/Athens"),
//		new CityListClass("CDRNG","코드링턴","앤티가바부다","America/Antigua"),
//	    	new CityListClass("CORO","코로","베네수엘라","America/Caracas"),
//		new CityListClass("CRNA","코로나","미국","America/Los_Angeles"),
//		new CityListClass("KOROR","코로르","팔라우","Pacific/Palau"),
//		new CityListClass("CRZL","코로살","벨리즈","America/Belize"),
//		new CityListClass("LCO","코루나","스페인","Europe/Madrid"),
//		new CityListClass("CRCH","코루체","포르투칼","Europe/Lisbon"),
//		new CityListClass("KAF","코르 파칸","아랍에미리트","Asia/Dubai"),
//		new CityListClass("CRDB","코르도바","아르헨티나","America/Argentina/Buenos_Aires"),
//		new CityListClass("CRDE","코르도바","스페인","Europe/Madrid"),
//		new CityListClass("CORVO","코르보","포르투칼","Atlantic/Azores"),
//		new CityListClass("CRSCN","코르시카나","미국","America/Chicago"),
//		new CityListClass("CRK","코르크","아일랜드","Europe/Dublin"),
//		new CityListClass("KHRXS","코리사스","나미비아","Africa/Windhoek"),
//		new CityListClass("CORIA","코리아","스페인","Europe/Madrid"),
//		new CityListClass("CRRNT","코리엔테스","아르헨티나","America/Argentina/Buenos_Aires"),
//		new CityListClass("COO","코린토","니카라과","America/Managua"),
//		new CityListClass("CNH","코린트","그리스","Europe/Athens"),
//	    	new CityListClass("CMYG","코마야과","온두라스","America/Tegucigalpa"),
//		new CityListClass("KMTPR","코마티포트","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("COMO","코모도로리바다비아","아르헨티나","America/Argentina/Buenos_Aires"),
//		new CityListClass("KMTN","코모티니","그리스","Europe/Athens"),
//		new CityListClass("CMLLS","코미야스","스페인","Europe/Madrid"),
//		new CityListClass("DMNGZ","코미탄 데 도밍구에즈","멕시코","America/Mexico_City"),
//		new CityListClass("COBAN","코반","과테말라","America/Guatemala"),
//		new CityListClass("COB","코브","아일랜드","Europe/Dublin"),
//		new CityListClass("KBLNZ","코블렌츠","독일","Europe/Berlin"),
//		new CityListClass("CBJ","코비하","볼리비아","America/La_Paz"),
//		new CityListClass("CVLH","코빌랴","포르투칼","Europe/Lisbon"),
//		new CityListClass("KSZLN","코살린","폴란드","Europe/Warsaw"),
//		new CityListClass("CSNZ","코센차","이탈리아","Europe/Rome"),
//		new CityListClass("KOSX","코스","그리스","Europe/Athens"),
//		new CityListClass("CMESA","코스타 메사","미국","America/Los_Angeles"),
//		new CityListClass("KSTER","코스터","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("KSTRM","코스트로마","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("KSC","코시체","슬로바키아","Europe/Bratislava"),
//		new CityListClass("KORCE","코어스","알바니아","Europe/Tirane"),
//		new CityListClass("CMBRA","코임브라","포르투칼","Europe/Lisbon"),
//		new CityListClass("KZN","코자니","그리스","Europe/Athens"),
//		new CityListClass("KCL","코잘리","터키","Europe/Istanbul"),
//		new CityListClass("CLCT","코지코드","인도","Asia/Calcutta"),
//		new CityListClass("KCNI","코차니","마케도니아","Europe/Skopje"),
//		new CityListClass("CCHBM","코챠밤바","볼리비아","America/La_Paz"),
//		new CityListClass("KOC","코치","일본","Asia/Tokyo"),
//		new CityListClass("COC","코친","인도","Asia/Calcutta"),
//		new CityListClass("KKM","코코모","미국","America/Indianapolis"),
//		new CityListClass("BEACH","코코아 비치","미국","America/New_York"),
//		new CityListClass("COQ","코킴보","칠레","America/Santiago"),
//		new CityListClass("BHR","코타바하루","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("KKB","코타키나발루","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("KOTOR","코토르","세르비아","Europe/Belgrade"),
//		new CityListClass("CTTBS","코트부스","독일","Europe/Berlin"),
//		new CityListClass("ALENE","코틀레인","미국","America/Boise"),
//		new CityListClass("KOP","코퍼","슬로바키아","Europe/Ljubljana"),
//		new CityListClass("COR","코퍼스 크리스티","미국","America/Chicago"),
//		new CityListClass("COP","코펜하겐","덴마크","Europe/Copenhagen"),
//		new CityListClass("KPRVN","코프리브니카","크로아티아","Europe/Zagreb"),
//		new CityListClass("KHTL","코흐틀라-예르베","에스토니아","Europe/Tallinn"),
//		new CityListClass("CCKBR","콕번하버","터크스 케이커스 제도","America/Grand_Turk"),
//		new CityListClass("BHC","콘셉시온","칠레","America/Santiago"),
//		new CityListClass("CNCEP","콘셉시온","파라과이","America/Asuncion"),
//		new CityListClass("CTZ","콘스탄차","루마니아","Europe/Bucharest"),
//		new CityListClass("THMMR","콘시탐마라트","태국","Asia/Bangkok"),
//		new CityListClass("KONYA","콘야","터키","Europe/Istanbul"),
//		new CityListClass("KAEN","콘캔","태국","Asia/Bangkok"),
//		new CityListClass("CNTGM","콘타젱","브라질","America/Bahia"),
//		new CityListClass("VLLLB","콜라도 빌라바","스페인","Europe/Madrid"),
//		new CityListClass("CBSOH","콜럼버스-오하이오","미국","America/New_York"),
//		new CityListClass("COLUM","콜럼버스-인디애나","미국","America/Indianapolis"),
//		new CityListClass("CBSGA","콜럼버스-조지아","미국","America/New_York"),
//		new CityListClass("COLMB","콜럼비아-메릴랜드","미국","America/New_York"),
//		new CityListClass("CLMBR","콜럼비아-미주리","미국","America/Chicago"),
//		new CityListClass("CLMSC","콜럼비아-사우스캐롤라이나","미국","America/New_York"),
//		new CityListClass("CLUMB","콜럼비아-테네시","미국","America/Chicago"),
//		new CityListClass("CLSBR","콜레스버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SCRMN","콜로니아 델 사크라멘토","우루과이","America/Montevideo"),
//		new CityListClass("CLRCO","콜로라도 스프링스","미국","America/Denver"),
//		new CityListClass("CLN","콜론","파나마","America/Panama"),
//		new CityListClass("KHOLM","콜름","폴란드","Europe/Warsaw"),
//		new CityListClass("KOLIN","콜린","체코","Europe/Prague"),
//		new CityListClass("COLR","콜마르","프랑스","Europe/Paris"),
//		new CityListClass("CLWYN","콜윈 베이","영국","Europe/London"),
//		new CityListClass("CHRBR","콥스하버","오스트레일리아","Australia/Sydney"),
//		new CityListClass("CONC","콩고드-노스캐롤라이나","미국","America/New_York"),
//		new CityListClass("CCDNH","콩고드-뉴햄프셔","미국","America/New_York"),
//		new CityListClass("CCD","콩고드-캘리포니아","미국","America/Los_Angeles"),
//		new CityListClass("KNGSG","콩스버그","노르웨이","Europe/Oslo"),
//		new CityListClass("KUA","콴탄","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("KLT","콸라테렝가누","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("CLGN","쾰른","독일","Europe/Berlin"),
//		new CityListClass("KGLKT","쿠글룩툭","캐나다","America/Pangnirtung"),
//		new CityListClass("CUNEO","쿠네오","이탈리아","Europe/Rome"),
//		new CityListClass("KNNRR","쿠누누라","오스트레일리아","Australia/Perth"),
//		new CityListClass("KDT","쿠다트","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("KUR","쿠레","일본","Asia/Tokyo"),
//		new CityListClass("KRSSR","쿠레사레","에스토니아","Europe/Tallinn"),
//		new CityListClass("KOU","쿠루","기아나","America/Cayenne"),
//		new CityListClass("KURMN","쿠루먼","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("KRUM","쿠루메","일본","Asia/Tokyo"),
//		new CityListClass("KRGN","쿠르간","러시아 연방 국가","Asia/Yekaterinburg"),
//		new CityListClass("KURSK","쿠르스크","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("CRTBA","쿠리티바","브라질","America/Bahia"),
//		new CityListClass("KMGY","쿠마가야","일본","Asia/Tokyo"),
//	    	new CityListClass("CUM","쿠마나","베네수엘라","America/Caracas"),
//		new CityListClass("KMNV","쿠마노보","마케도니아","Europe/Skopje"),
//		new CityListClass("KUM","쿠마모토","일본","Asia/Tokyo"),
//		new CityListClass("KMJM","쿠메지마","일본","Asia/Tokyo"),
//		new CityListClass("CBRP","쿠버페디","오스트레일리아","Australia/Adelaide"),
//		new CityListClass("CUSCO","쿠스코","페루","America/Lima"),
//		new CityListClass("KUS","쿠시로","일본","Asia/Tokyo"),
//		new CityListClass("CHUR","쿠아르","스위스","Europe/Zurich"),
//		new CityListClass("LMPR","쿠알라룸푸르","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("CRNVC","쿠에르나바카","멕시코","America/Mexico_City"),
//		new CityListClass("CLLR","쿠에야르","스페인","Europe/Madrid"),
//		new CityListClass("CENC","쿠엔카","에콰도르","America/Guayaquil"),
//		new CityListClass("CNC1","쿠엔카","스페인","Europe/Madrid"),
//		new CityListClass("KUW","쿠웨이트","쿠웨이트","Asia/Kuwait"),
//		new CityListClass("KJJRP","쿠주아라픽","캐나다","America/Montreal"),
//		new CityListClass("KJJQ","쿠주아크","캐나다","America/Montreal"),
//		new CityListClass("KUCCH","쿠찬","일본","Asia/Tokyo"),
//		new CityListClass("KUC","쿠칭","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("KUKES","쿠커스","알바니아","Europe/Tirane"),
//		new CityListClass("CCT1","쿠쿠타","콜롬비아","America/Bogota"),
//		new CityListClass("KUTNA","쿠트나호라","체코","Europe/Prague"),
//		new CityListClass("QUTUF","쿠트푸","아랍에미리트","Asia/Dubai"),
//		new CityListClass("KTN1","쿠티나","크로아티아","Europe/Zagreb"),
//		new CityListClass("QTHNG","쿠팅","레소토","Africa/Maseru"),
//		new CityListClass("KUP","쿠팡","인도네시아","Asia/Makassar"),
//		new CityListClass("CKVLL","쿡빌","미국","America/Chicago"),
//		new CityListClass("KULU","쿨루","터키","Europe/Istanbul"),
//		new CityListClass("CLCN","쿨리아칸","멕시코","America/Mazatlan"),
//		new CityListClass("KULP","쿨프","터키","Europe/Istanbul"),
//		new CityListClass("KNGSB","쿵스바카","스웨덴","Europe/Stockholm"),
//		new CityListClass("QVD","퀘베도","에콰도르","America/Guayaquil"),
//		new CityListClass("QBC","퀘벡","캐나다","America/Montreal"),
//		new CityListClass("KWKW","퀘퀘","짐바브웨","Africa/Harare"),
//		new CityListClass("KTHY","퀴타하아","터키","Europe/Istanbul"),
//		new CityListClass("QUITO","퀴토","에콰도르","America/Guayaquil"),
//		new CityListClass("QNC","퀸시-매사추세츠","미국","America/New_York"),
//		new CityListClass("QUNCY","퀸시-일리노이","미국","America/Chicago"),
//		new CityListClass("KEW","큐","터크스 케이커스 제도","America/Grand_Turk"),
//		new CityListClass("KYSTN","큐스텐딜","불가리아","Europe/Sofia"),
//		new CityListClass("KRGJV","크라구예바츠","세르비아","Europe/Belgrade"),
//		new CityListClass("KRLND","크라렌디즈크","앤틸리스제도","America/Curacao"),
//		new CityListClass("KRSND1","크라스노다르","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("KRSNJ","크라스노야르스크","러시아 연방 국가","Asia/Krasnoyarsk"),
//		new CityListClass("KRSNK","크라스닉","폴란드","Europe/Warsaw"),
//		new CityListClass("KRLJV","크라예보","세르비아","Europe/Belgrade"),
//		new CityListClass("CHCH","크라이스트 처치","뉴질랜드","Pacific/Auckland"),
//		new CityListClass("CRAV","크라이오바","루마니아","Europe/Bucharest"),
//		new CityListClass("CRCW","크라쿠프","폴란드","Europe/Warsaw"),
//		new CityListClass("KRPN","크라피나","크로아티아","Europe/Zagreb"),
//		new CityListClass("KRANJ","크란","슬로바키아","Europe/Ljubljana"),
//		new CityListClass("CRDCK","크래독","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("CRSCNC","크레센트 시티","미국","America/Los_Angeles"),
//		new CityListClass("CRGVN","크레이개번","영국","Europe/Belfast"),
//		new CityListClass("CRANE","크레인","바베이도스","America/Barbados"),
//		new CityListClass("CRTL","크레테일","프랑스","Europe/Paris"),
//	    	new CityListClass("KRTNG","크레팅가","리투아니아","Europe/Vilnius"),
//		new CityListClass("DONAU","크렘스안데어도나우","오스트리아","Europe/Vienna"),
//		new CityListClass("KRMRZ","크로메리츠","체코","Europe/Prague"),
//		new CityListClass("CRNML","크로멜","슬로바키아","Europe/Ljubljana"),
//		new CityListClass("KRSN","크로스노","폴란드","Europe/Warsaw"),
//		new CityListClass("ODRZN","크로스노 오드잔스키에","폴란드","Europe/Warsaw"),
//		new CityListClass("KLCZB","크로이츠부르크","폴란드","Europe/Warsaw"),
//		new CityListClass("COE","크로톤","이탈리아","Europe/Rome"),
//		new CityListClass("CREWE","크루","영국","Europe/London"),
//		new CityListClass("KRGRS","크루거스도프","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("KRSZW","크루쉬비차","폴란드","Europe/Warsaw"),
//		new CityListClass("CRUZB","크루즈 베이","버진 아일랜드","America/St_Thomas"),
//		new CityListClass("KRYNC","크리니카-즈드루이","폴란드","Europe/Warsaw"),
//		new CityListClass("PLNK","크리바팔란카","마케도니아","Europe/Skopje"),
//		new CityListClass("CHSTM","크리스마스 섬","크리스마스 섬","Indian/Christmas"),
//		new CityListClass("CHRST","크리스천스테드","버진 아일랜드","America/St_Thomas"),
//		new CityListClass("KRT","크리스티안산","노르웨이","Europe/Oslo"),
//		new CityListClass("KTD","크리스티안순","노르웨이","Europe/Oslo"),
//		new CityListClass("KRTD","크리스티안스타드","스웨덴","Europe/Stockholm"),
//		new CityListClass("KWDZY","크비진","폴란드","Europe/Warsaw"),
//		new CityListClass("XNTH","크산티","그리스","Europe/Athens"),
//		new CityListClass("SBYH","크와르 아스 사비야","쿠웨이트","Asia/Kuwait"),
//		new CityListClass("KRDZK","크워츠코","폴란드","Europe/Warsaw"),
//		new CityListClass("KLGNF","클라겐푸르트","오스트리아","Europe/Vienna"),
//		new CityListClass("KLDN1","클라드노","체코","Europe/Prague"),
//		new CityListClass("KLTVY","클라토비","체코","Europe/Prague"),
//		new CityListClass("CLRKS","클락스버그","미국","America/New_York"),
//		new CityListClass("CLKTN","클락스빌","미국","America/Chicago"),
//		new CityListClass("KLG","클랑","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("CLARE","클래어","오스트레일리아","Australia/Adelaide"),
//		new CityListClass("CLNWL","클랜윌리암","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("KLRKS","클럭스도르프","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("CLRMN","클레르몽페랑","프랑스","Europe/Paris"),
//	    	new CityListClass("KLP","클레이페다","리투아니아","Europe/Vilnius"),
//		new CityListClass("CLNML","클론멜","아일랜드","Europe/Dublin"),
//		new CityListClass("NPCA","클루지나포카","루마니아","Europe/Bucharest"),
//		new CityListClass("CLV","클리블랜드","미국","America/New_York"),
//		new CityListClass("CLRWFL","클리어워터","미국","America/New_York"),
//		new CityListClass("CLFTN","클리프턴","미국","America/New_York"),
//		new CityListClass("KLPPL","클립플라트","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("BSCYN","키 비스캐인","미국","America/New_York"),
//		new CityListClass("KEY","키 웨스트","미국","America/New_York"),
//		new CityListClass("KGLI","키갈리","Rwanda","Africa/Kigali"),
//		new CityListClass("KIROW","키로브","러시아 연방 국가","Asia/Yekaterinburg"),
//		new CityListClass("KRNA","키루나","스웨덴","Europe/Stockholm"),
//		new CityListClass("KRCHD","키르히도르프 크렘스","오스트리아","Europe/Vienna"),
//		new CityListClass("KRKKL","키리칼레","터키","Europe/Istanbul"),
//		new CityListClass("KEITH","키스","오스트레일리아","Australia/Adelaide"),
//		new CityListClass("KSHNY","키시뇨프","Moldova","Europe/Chisinau"),
//		new CityListClass("KTHR","키시라","그리스","Europe/Athens"),
//		new CityListClass("KSSMM","키시미","미국","America/New_York"),
//		new CityListClass("CHT","키에티","이탈리아","Europe/Rome"),
//		new CityListClass("KLC","키엘체","폴란드","Europe/Warsaw"),
//		new CityListClass("KIEV","키예프","터키","Europe/Kiev"),
//		new CityListClass("KYZYL","키질","러시아 연방 국가","Asia/Omsk"),
//		new CityListClass("KTZBH","키츠뷔헬","오스트리아","Europe/Vienna"),
//		new CityListClass("KTCHN","키치너","캐나다","America/Toronto"),
//		new CityListClass("KKG","키카이","일본","Asia/Tokyo"),
//		new CityListClass("KTM","키타미","일본","Asia/Tokyo"),
//		new CityListClass("ESSI","키타미에사시","일본","Asia/Tokyo"),
//		new CityListClass("KTMNS","키트만슙","나미비아","Africa/Windhoek"),
//		new CityListClass("KITWE","키트웨","잠비아","Africa/Lusaka"),
//		new CityListClass("KPRSS","키파리시아","그리스","Europe/Athens"),
//		new CityListClass("KNSHS","킨샤사","콩고","Africa/Brazzaville"),
//		new CityListClass("KIL","킬","독일","Europe/Berlin"),
//		new CityListClass("KLLN","킬린","미국","America/Chicago"),
//		new CityListClass("KLMRN","킬마낙","영국","Europe/London"),
//		new CityListClass("KLKNN","킬케니","아일랜드","Europe/Dublin"),
//		new CityListClass("KLKS","킬키스","그리스","Europe/Athens"),
//		new CityListClass("KMBRL","킴벌리","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("KTN","킹스타운","세인트 빈센트 그레나딘","America/St_Vincent"),
//		new CityListClass("KNGTG","킹스턴","캐나다","America/Toronto"),
//		new CityListClass("KGT","킹스턴","자메이카","America/Jamaica"),
//		new CityListClass("KNGST","킹스톤","미국","America/New_York"),
//		new CityListClass("KNGSP","킹즈포트","미국","America/New_York"),
	};
}
