package com.weathernews.Weather;

public class L {
	public final static CityListClass_E[] l = new CityListClass_E[] {
		new CityListClass_E("AQL", "L'Aquila", "라퀼라", "이탈리아", "Europe/Rome"),
		new CityListClass_E("ASNCNL", "La Asuncion", "라 아순시온", "베네수엘라", "America/Caracas"),
		new CityListClass_E("LAC", "La Ceiba", "라 시바", "온두라스", "America/Tegucigalpa"),
		new CityListClass_E("CRSS", "La Crosse", "라크로스", "미국", "America/Chicago"),
		new CityListClass_E("LGU", "La Guaira", "라 구아이라", "베네수엘라", "America/Caracas"),
		new CityListClass_E("LLB", "La Libertad", "라 리베르타드", "에콰도르", "America/Guayaquil"),
		new CityListClass_E("LBRTD", "La Libertad", "라 리베르타드", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("CNCPC", "La Linea de la ConcepciOn", "라 리네아 데 콘셉시온", "스페인", "Europe/Madrid"),
		new CityListClass_E("LVRL", "La Louviere", "라 루비 에르", "벨기에", "Europe/Brussels"),
		new CityListClass_E("PALMA", "La Palma", "라 팔마", "파나마", "America/Panama"),
		new CityListClass_E("PAZ", "La Paz", "라 파스", "볼리비아", "America/La_Paz"),
		new CityListClass_E("LPZ", "La Paz", "라 파스", "멕시코", "America/Mazatlan"),
		new CityListClass_E("PLNL", "La Plaine", "라 플라이네", "도미니카", "America/Dominica"),
		new CityListClass_E("LPA", "La Plata", "라 플라타", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("ROCHE", "La Roche-sur-Yon", "라로슈 쉬르욘", "프랑스", "Europe/Paris"),
		new CityListClass_E("LAR", "La Rochelle", "라호쉘", "프랑스", "Europe/Paris"),
		new CityListClass_E("LRM", "La Romana", "라 로마나", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("SPZL", "La Spezia", "라 스페치아", "이탈리아", "Europe/Rome"),
		new CityListClass_E("LUE", "La Union", "라 우니온", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("LBRDR", "Labrador City", "라브라도어 시티", "캐나다", "America/Goose_Bay"),
//		new CityListClass_E("LDYBR", "Ladybrand", "레이디브랜드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("LDYSM", "Ladysmith", "레이디스미스", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("LAFET", "Lafayette", "라피엣-인디아나", "미국", "America/Indianapolis"),
		new CityListClass_E("LFYLA", "Lafayette", "라피엣-루지애나", "미국", "America/Chicago"),
		new CityListClass_E("LAH", "Lahad Datu", "라하드다투", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("LNGSB", "Laingsburg", "랭스버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("FLO", "Lajes das Flores", "라제스 다 플로레스", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("LAJESP", "Lajes do Pico", "라제스 도 피쿠", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("LCH", "Lake Charles", "레이크 찰스", "미국", "America/Chicago"),
		new CityListClass_E("HVS", "Lake Havasu City", "레이크 하바수 시티", "미국", "America/Denver"),
		new CityListClass_E("LKLND", "Lakeland", "레이크랜드", "미국", "America/New_York"),
		new CityListClass_E("LKWD", "Lakewood", "레이크우드", "미국", "America/Denver"),
		new CityListClass_E("LALIN", "Lalin", "란", "스페인", "Europe/Madrid"),
		new CityListClass_E("LMBRT", "Lamberts Bay", "램버트베이", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("LAMIA", "Lamia", "라미아", "그리스", "Europe/Athens"),
		new CityListClass_E("LMPNG", "Lampang", "람빵", "태국", "Asia/Bangkok"),
		new CityListClass_E("LNSTR", "Lancaster", "랭커스터-캘리포니아", "미국", "America/Los_Angeles"),
		new CityListClass_E("LNCST", "Lancaster", "랭커스터-팬실베니아", "미국", "America/New_York"),
		new CityListClass_E("LNDCK", "Landeck", "랑데크", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("LNGN", "Langon", "랑공", "프랑스", "Europe/Paris"),
		new CityListClass_E("LNSNG", "Lansing", "랜싱", "미국", "America/Detroit"),
		new CityListClass_E("LNSEI", "Lanusei", "라누세이", "이탈리아", "Europe/Rome"),
		new CityListClass_E("LRD", "Laredo", "러레이도", "미국", "America/Chicago"),
		new CityListClass_E("LRS", "Larissa", "라리사", "그리스", "Europe/Athens"),
		new CityListClass_E("LRN", "Larnaca", "라르나카", "키프로스", "Asia/Nicosia"),
		new CityListClass_E("CRCS", "Las Cruces", "라스 크루체스", "미국", "America/Denver"),
		new CityListClass_E("WGC", "Las Palmas de Gran Canaria", "라스팔마스 데 그란 카나리아", "스페인", "Atlantic/Canary"),
		new CityListClass_E("PDRS", "Las Piedras", "라 스피에드라스", "우루과이", "America/Montevideo"),
		new CityListClass_E("TBLS", "Las Tablas", "라 스따블라스", "파나마", "America/Panama"),
		new CityListClass_E("VGS", "Las Vegas", "라스베이거스", "미국", "America/Los_Angeles"),
		new CityListClass_E("LAT", "Latakia", "라타키아", "시리아", "Asia/Damascus"),
		new CityListClass_E("LTRB", "Latrobe Valley", "라트로브 벨리", "오스트레일리아", "Australia/Melbourne"),
		new CityListClass_E("LGHLN", "Laughlin", "라플린", "미국", "America/Los_Angeles"),
//		new CityListClass_E("LNS", "Launceston", "론서스턴", "오스트레일리아", "Australia/Hobart"),
		new CityListClass_E("LSNN", "Lausanne", "로잔", "스위스", "Europe/Zurich"),
		new CityListClass_E("LAVAL", "Laval", "라발", "프랑스", "Europe/Paris"),
		new CityListClass_E("LVRN", "Lavrion", "라브리온", "그리스", "Europe/Athens"),
		new CityListClass_E("LWRNC", "Lawrence", "로렌스", "미국", "America/New_York"),
		new CityListClass_E("LWTN", "Lawton", "로턴", "미국", "America/Chicago"),
		new CityListClass_E("LXTN", "Laxton", "랙스톤", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("LAZ", "Lazaro Cardenas", "라사로 까르데나스", "멕시코", "America/Mexico_City"),
		new CityListClass_E("FRNCS", "Le Francois", "르 프랑수아", "마르티니크", "America/Martinique"),
		new CityListClass_E("GSR", "Le Gosier", "르 고시어", "과들루프섬", "America/Guadeloupe"),
		new CityListClass_E("LEH", "Le Havre", "르아브르", "프랑스", "Europe/Paris"),
		new CityListClass_E("LMNTN", "Le Lamentin", "르 라멘틴", "마르티니크", "America/Martinique"),
		new CityListClass_E("LRRN", "Le Lorrain", "르 로라인", "마르티니크", "America/Martinique"),
		new CityListClass_E("MANS", "Le Mans", "르망", "프랑스", "Europe/Paris"),
		new CityListClass_E("MARIN", "Le Marin", "르 마린", "마르티니크", "America/Martinique"),
		new CityListClass_E("MOULE", "Le Moule", "르 무르", "과들루프섬", "America/Guadeloupe"),
		new CityListClass_E("RBRT", "Le Robert", "르 로베르또", "마르티니크", "America/Martinique"),
		new CityListClass_E("LTHRH", "Leatherhead", "리더헤드", "영국", "Europe/London"),
		new CityListClass_E("LBNN", "Lebanon", "레바논", "미국", "America/New_York"),
		new CityListClass_E("LBRJ", "Lebrija", "레브리하", "스페인", "Europe/Madrid"),
		new CityListClass_E("LEBU", "Lebu", "레부", "칠레", "America/Santiago"),
		new CityListClass_E("LECCE", "Lecce", "레체", "이탈리아", "Europe/Rome"),
		new CityListClass_E("LEEDS", "Leeds", "리즈", "영국", "Europe/London"),
		new CityListClass_E("SMMT", "Lees Summit", "리스 서밋", "미국", "America/Chicago"),
		new CityListClass_E("LWRDN", "Leeuwarden", "레이와르던", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("LFKD", "Lefkada", "레프카다", "그리스", "Europe/Athens"),
		new CityListClass_E("LEG", "Legaspi City", "레가스피시티", "필리핀", "Asia/Manila"),
		new CityListClass_E("LGNC", "Legnica", "레그니차", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LBNTZ", "Leibnitz", "라이프니쯔", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("LCSTR", "Leicester", "레스터", "영국", "Europe/London"),
		new CityListClass_E("LKNGR", "Leikanger", "레이캉게르", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("LPZG", "Leipzig", "라이프치히", "독일", "Europe/Berlin"),
		new CityListClass_E("LEIRI", "Leiria", "레이리아", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("LLYST", "Lelystad", "렐리스테이드", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("LNDV", "Lendava", "렌다바", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("LEON", "Leon", "레온", "니카라과", "America/Managua"),
		new CityListClass_E("LEOM", "LeOn", "레온", "멕시코", "America/Mexico_City"),
		new CityListClass_E("LEOES", "LeOn", "레온", "스페인", "Europe/Madrid"),
		new CityListClass_E("LNDHN", "Leonidhion", "레오니데온", "그리스", "Europe/Athens"),
		new CityListClass_E("LEPE", "Lepe", "레뻬", "스페인", "Europe/Madrid"),
		new CityListClass_E("LER", "Lerwick", "러윅", "영국", "Europe/London"),
		new CityListClass_E("LES", "Les", "레스", "스페인", "Europe/Madrid"),
		new CityListClass_E("ABYMS", "Les Abymes", "레스 아비메스", "과들루프섬", "America/Guadeloupe"),
		new CityListClass_E("CAYES", "Les Cayes", "레스 카예스", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("LSKVC", "Leskovac", "레스코바츠", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("LSZN", "Leszno", "레즈노", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LTHBR", "Lethbridge", "레스브리지", "캐나다", "America/Edmonton"),
		new CityListClass_E("LTHM", "Lethem", "레뎀", "가이아나", "America/Guyana"),
		new CityListClass_E("LTC", "Leticia", "레티샤", "콜롬비아", "America/Bogota"),
		new CityListClass_E("LTTRK", "Letterkenny", "레터케니", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("LVN1", "Leuven", "루븐", "벨기에", "Europe/Brussels"),
		new CityListClass_E("LVTTW", "Levittown", "레빗타운", "미국", "America/New_York"),
		new CityListClass_E("LWSTN", "Lewiston", "루이스턴", "미국", "America/New_York"),
		new CityListClass_E("LXNKY", "Lexington", "렉싱턴", "미국", "America/New_York"),
		new CityListClass_E("LXNGT", "Lexington Park", "렉싱턴 파크", "미국", "America/New_York"),
		new CityListClass_E("LYG", "Leyte", "레이테", "필리핀", "Asia/Manila"),
		new CityListClass_E("LZJSK", "Lezajsk", "레자이스크", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("LEZHE", "Lezhe", "레체", "알바니아", "Europe/Tirane"),
		new CityListClass_E("LBRC", "Liberec", "리베레츠", "체코", "Europe/Prague"),
		new CityListClass_E("LBR1", "Liberia", "리베리아", "코스타리카", "America/Costa_Rica"),
		new CityListClass_E("LBRT", "Liberta", "리버타", "앤티가바부다", "America/Antigua"),
		new CityListClass_E("LIB", "Libreville", "리브르빌", "가봉", "Africa/Libreville"),
		new CityListClass_E("LCHNG", "Lichinga", "리칭가", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("LDKPN", "Lidkoping", "리드셰핑", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("WRMNS", "Lidzbark Warminski", "리즈바르크바르민스키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LIEGE", "Liege", "리에주", "벨기에", "Europe/Brussels"),
		new CityListClass_E("LIENZ", "Lienz", "린츠", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("LZN", "Liezen", "라이젠", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("LIHUE", "Lihue", "리후에", "미국", "Pacific/Honolulu"),
		new CityListClass_E("LILLE", "Lille", "릴", "프랑스", "Europe/Paris"),
		new CityListClass_E("LLLHM", "Lillehammer", "릴레함메르", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("LLWM", "Lilongwe", "리롱과", "말라위", "Africa/Blantyre"),
		new CityListClass_E("LIMA1", "Lima", "리마", "미국", "America/New_York"),
		new CityListClass_E("LIMA", "Lima", "리마", "페루", "America/Lima"),
		new CityListClass_E("LMNW", "Limanowa", "리마노바", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LIM", "Limassol", "리마솔", "키프로스", "Asia/Nicosia"),
		new CityListClass_E("LMK", "Limerick", "리머릭", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("LMTR", "Limetree", "라임트리", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass_E("LMGS", "Limoges", "리모주", "프랑스", "Europe/Paris"),
		new CityListClass_E("LNRS", "Linares", "리나레스", "스페인", "Europe/Madrid"),
		new CityListClass_E("LNCLN", "Lincoln", "링컨", "미국", "America/Chicago"),
		new CityListClass_E("LNCOL", "Lincoln", "링컨", "영국", "Europe/London"),
		new CityListClass_E("LINDN", "Linden", "린덴", "가이아나", "America/Guyana"),
		new CityListClass_E("LINZ", "Linz", "린즈", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("LPZK", "Lipezk", "리즈번", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("LIS", "Lisbon", "리스본", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("LSBRN", "Lisburn", "리즈번", "영국", "Europe/Belfast"),
		new CityListClass_E("LSMR", "Lismore", "리스모어", "오스트레일리아", "Australia/Sydney"),
		new CityListClass_E("LTMRC", "Litomerice", "리토메리체", "체코", "Europe/Prague"),
		new CityListClass_E("LTTLR", "Little Rock", "리틀 록", "미국", "America/Chicago"),
		new CityListClass_E("LTVNV", "Litvinov", "리트비노프", "체코", "Europe/Prague"),
		new CityListClass_E("LVN2", "Livani", "라트비아", "라트비아", "Europe/Riga"),
		new CityListClass_E("LIV", "Liverpool", "리버풀", "영국", "Europe/London"),
		new CityListClass_E("LIVIN", "Livingston", "리빙스톤", "영국", "Europe/London"),
		new CityListClass_E("LVNGSN", "Livingstone", "리빙스톤", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("LIVNO", "Livno", "리보노", "보스니아-헤르체고비나", "Europe/Sarajevo"),
		new CityListClass_E("LVRNO", "Livorno", "리보르노", "이탈리아", "Europe/Rome"),
		new CityListClass_E("LJBLJ", "Ljubljana", "류블랴나", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("LJSDL", "Ljusdal", "엘쥬스달", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("LLD", "Lleida", "예이다", "스페인", "Europe/Madrid"),
		new CityListClass_E("LLYDM", "Lloydminster", "로이드민스터", "캐나다", "America/Edmonton"),
		new CityListClass_E("LBTS", "Lobatse", "로바츠", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("LCRN", "Locarno", "로카르노", "스위스", "Europe/Zurich"),
		new CityListClass_E("LOGAN", "Logan", "로건", "미국", "America/Denver"),
		new CityListClass_E("LGRN", "Logrono", "로그로뇨", "스페인", "Europe/Madrid"),
		new CityListClass_E("LOJA", "Loja", "로자", "에콰도르", "America/Guayaquil"),
		new CityListClass_E("LME", "Lome", "로마", "토고", "Africa/Lome"),
		new CityListClass_E("LNDN", "London", "런던", "캐나다", "America/Toronto"),
		new CityListClass_E("LDN", "London", "런던", "영국", "Europe/London"),
		new CityListClass_E("LDD", "Londonderry", "런던데리", "영국", "Europe/Belfast"),
		new CityListClass_E("LBE", "Long Beach", "롱비치", "미국", "America/Los_Angeles"),
		new CityListClass_E("BRNCH", "Long Branch", "롱브랜치", "미국", "America/New_York"),
		new CityListClass_E("LNGFR", "Longford", "롱퍼드", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("LNGRC", "Longreach", "롱리치", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("LNGVW", "Longview", "롱뷰", "미국", "America/Chicago"),
		new CityListClass_E("LORA", "Lora del Rio", "로라델리오", "스페인", "Europe/Madrid"),
		new CityListClass_E("LRCA", "Lorca", "로르카", "스페인", "Europe/Madrid"),
		new CityListClass_E("LRT", "Loreto", "로라토", "멕시코", "America/Mazatlan"),
		new CityListClass_E("LOR", "Lorient", "로리앙", "프랑스", "Europe/Paris"),
		new CityListClass_E("LRSFN", "Loriesfontein", "로리스폰테인", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("LAX", "Los Angeles", "로스 앤젤레스", "미국", "America/Los_Angeles"),
		new CityListClass_E("MCHSL", "Los Mochis", "로스모치스", "멕시코", "America/Mazatlan"),
//		new CityListClass_E("TQS", "Los Teques", "로스테크", "베네수엘라", "America/Caracas"),
		new CityListClass_E("LTCD", "Louis Trichardt", "루이트리챠드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("LSVL", "Louisville", "루이빌", "미국", "America/Louisville"),
		new CityListClass_E("LOUNY", "Louny", "루니", "체코", "Europe/Prague"),
		new CityListClass_E("LVCH", "Lovech", "로베치", "불가리아", "Europe/Sofia"),
		new CityListClass_E("LWLL", "Lowell", "로웰", "미국", "America/New_York"),
		new CityListClass_E("LUA", "Luanda", "루안다", "앙골라", "Africa/Luanda"),
		new CityListClass_E("LRC", "Luarca", "루아르카", "스페인", "Europe/Madrid"),
//		new CityListClass_E("LBCZW", "LubaczOw", "루바추프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LUBAN", "Luban", "루반", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LBRTW", "LubartOw", "루바르투프", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LBBK", "Lubbock", "러벅", "미국", "America/Chicago"),
		new CityListClass_E("LUB", "Lubeck", "뤼벡", "독일", "Europe/Berlin"),
		new CityListClass_E("LUBIN", "Lubin", "루빈", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LBLN", "Lublin", "루블린", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("LUD", "Luderitz", "루데리츠", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("LDVK", "Ludvika", "루드비카", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("LFKN", "Lufkin", "러프킨", "미국", "America/Chicago"),
		new CityListClass_E("LGN", "Lugano", "루가노", "스위스", "Europe/Zurich"),
		new CityListClass_E("LUGOE", "Lugo", "루고", "스페인", "Europe/Madrid"),
		new CityListClass_E("LUL", "Lulea", "룰레오", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("LMBRR", "Lumbreras", "럼브게라스", "스페인", "Europe/Madrid"),
		new CityListClass_E("LUMUT", "Lumut", "루무트", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("LNDZ", "Lundazi", "룬다지", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("LNNBR", "Lunenburg", "루넌버그", "캐나다", "America/Halifax"),
		new CityListClass_E("LPN", "Lupane", "루파네", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("LSKA", "Lusaka", "루사카", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("LXMBC", "Luxembourg City", "룩셈부르크 시티", "룩셈부르크", "Europe/Luxembourg"),
		new CityListClass_E("LUXOR", "Luxor", "룩소르", "이집트", "Africa/Cairo"),
		new CityListClass_E("LZRN", "Luzern", "루체른", "스위스", "Europe/Zurich"),
		new CityListClass_E("LYDNB", "Lydenburg", "라이덴버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("LYNCH", "Lynchburg", "린치버그", "미국", "America/New_York"),
		new CityListClass_E("LYON", "Lyon", "리옹", "프랑스", "Europe/Paris"),

	};
}
