package com.weathernews.Weather;
public class Lithuania_europe {
    public final static CityListClass[] Lithuania_europe = new CityListClass[] {
    	new CityListClass("GRGZD", "가르다이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("DRSKN", "드루스키닌카이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("RDVLS", "라드빌리슈키스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("RSN1", "라세이냐이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("RKSKS", "로키스키스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("RUSNE", "루스네", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("MRJMP", "마리얌폴레", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("MAZEI", "마제이키에이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("VRN1", "바례나", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("BRZJ", "비르제이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("VSGNS", "비사기나스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("VLNS", "빌뉴스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("SAKIA", "사키아이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("SIAUL", "시아울리아이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("SLT1", "실루트", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("ANYKS", "아닉슈체이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("AKMN", "아크메네", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("ALYTS", "알리투스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("ELKTR1", "엘렉트레네이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("JNV", "요나바", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("UKMRG", "우크메게", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("UTENA", "우테나", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("JRBRK", "유르바르카스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("KUNS", "카우나스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("KLVRJ", "칼바리야", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("KDN", "케다이네이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("KELME", "케레메", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("KRTNG", "크레팅가", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("KLP", "클레이페다", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("TRG1", "타우라게", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("TLS3", "텔시아이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("PGG1", "파게기에이", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("PNVZY", "파네베지스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("PSVLY", "파스발리스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("PKRJS", "파크루오이스", "리투아니아", "Europe/Vilnius"),
    	new CityListClass("PLNG", "플런지", "리투아니아", "Europe/Vilnius"),
    };
}
