package com.weathernews.Weather;

public class M {
	public final static CityListClass_E[] m = new CityListClass_E[] {
		new CityListClass_E("MAAN", "Maan", "마안", "요르단", "Asia/Amman"),
		new CityListClass_E("MSTRCH", "Maastricht", "마스트리흐트", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("MBRM", "Mabaruma", "마바루마", "가이아나", "America/Guyana"),
		new CityListClass_E("MBLE", "Mabule", "마블", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("MACAO", "Macao", "마카오", "중국", "Asia/Shanghai"),
		new CityListClass_E("CVLRS", "Macedo de Cavaleiros", "마세도드 카발레로스", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("MAO", "MaceiO", "마세이오", "브라질", "America/Maceio"),
		new CityListClass_E("MCHL", "Machala", "마찰라", "에콰도르", "America/Guayaquil"),
		new CityListClass_E("MCHTS", "Machatschkala", "마차츠카라", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("MCHP", "Machu Picchu", "마추피추", "페루", "America/Lima"),
		new CityListClass_E("MCY", "Mackay", "맥케이", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("MCLR", "Maclear", "매클리어", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("MACN", "Macon", "메이컨", "미국", "America/New_York"),
		new CityListClass_E("MDNT", "Madinat Isa", "이사 타운", "바레인", "Asia/Bahrain"),
		new CityListClass_E("MDNWI", "Madison", "매디슨", "미국", "America/Chicago"),
		new CityListClass_E("CHEN", "Madras", "마드라스", "인도", "Asia/Calcutta"),
		new CityListClass_E("MDRE", "Madrid", "마드리드", "스페인", "Europe/Madrid"),
		new CityListClass_E("MDR1", "Madurai", "마두라이", "인도", "Asia/Calcutta"),
		new CityListClass_E("MAEBSH", "Maebashi", "마에바시", "일본", "Asia/Tokyo"),
		new CityListClass_E("MFKNG", "Mafeking", "마페킹", "남아프리카공화국", "Africa/Johannesburg"),
//		new CityListClass_E("MFTNG", "Mafeteng", "마페텡", "레소토", "Africa/Maseru"),
		new CityListClass_E("MAGA", "Magadan", "마가단", "러시아 연방 국가", "Asia/Magadan"),
		new CityListClass_E("MGDBR", "Magdeburg", "마그데부르크", "독일", "Europe/Berlin"),
//		new CityListClass_E("MHLPY", "Mahalapye", "마하라페", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("MAHON", "Mahon", "마혼", "스페인", "Europe/Madrid"),
		new CityListClass_E("MKP", "Maikop", "마이코프", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("MAINZ", "Mainz", "마인츠", "독일", "Europe/Berlin"),
		new CityListClass_E("MATLD", "Maitland", "메이틀랜드", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("MAI", "Maizuru", "마이즈루", "일본", "Asia/Tokyo"),
		new CityListClass_E("MJDHN", "Majadahonda", "마하다혼다", "스페인", "Europe/Madrid"),
		new CityListClass_E("MAJ", "Majuro", "마주로", "마셜", "Pacific/Majuro"),
		new CityListClass_E("MCS", "Makassar", "마카사르", "인도네시아", "Asia/Makassar"),
		new CityListClass_E("MAKU", "Makurazaki", "마쿠라자키", "일본", "Asia/Tokyo"),
		new CityListClass_E("MLB", "Malabo", "말라보", "적도기니", "Africa/Malabo"),
		new CityListClass_E("MLG", "Malaga", "말라가", "스페인", "Europe/Madrid"),
		new CityListClass_E("MLTY", "Malatya", "말라티아", "터키", "Europe/Istanbul"),
		new CityListClass_E("FALLSM", "Malay Falls", "말레이 폭포", "캐나다", "America/Halifax"),
		new CityListClass_E("MLDND", "Maldonado", "말도나도", "우루과이", "America/Montevideo"),
		new CityListClass_E("MLE", "Male", "말레", "몰디브", "Indian/Maldives"),
		new CityListClass_E("MLO", "Malmo", "말뫼", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("MLSLV", "Malselv", "말샐브", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("MNCR", "Manacor", "마나코르", "스페인", "Europe/Madrid"),
		new CityListClass_E("MNG1", "Managua", "마나과", "니카라과", "America/Managua"),
		new CityListClass_E("MANH", "Manama", "마나마", "바레인", "Asia/Bahrain"),
		new CityListClass_E("MNS", "Manaus", "마나우스", "브라질", "America/Manaus"),
		new CityListClass_E("MCH", "Manchester", "맨체스터", "영국", "Europe/London"),
		new CityListClass_E("MCHUS", "Manchester", "맨체스터-뉴햄프셔", "미국", "America/New_York"),
		new CityListClass_E("MNCHS", "Manchester", "맨체스터-코네티컷", "미국", "America/New_York"),
		new CityListClass_E("MNDVL", "Mandeville", "만드빌", "자메이카", "America/Jamaica"),
		new CityListClass_E("MNHTT", "Manhattan", "맨해튼", "미국", "America/Chicago"),
		new CityListClass_E("MNHTTB", "Manhattan Beach", "맨해튼 비치", "미국", "America/Los_Angeles"),
		new CityListClass_E("MBY", "Manila", "마닐라", "필리핀", "Asia/Manila"),
		new CityListClass_E("MNS1", "Manisa", "마니사", "터키", "Europe/Istanbul"),
		new CityListClass_E("MNTWC", "Manitowoc", "매니토웍", "미국", "America/Chicago"),
		new CityListClass_E("MNKT", "Mankato", "맨케이토", "미국", "America/Chicago"),
		new CityListClass_E("MNNHM", "Mannheim", "만하임", "독일", "Europe/Berlin"),
		new CityListClass_E("MNRS", "Manresa", "만레사", "스페인", "Europe/Madrid"),
		new CityListClass_E("MANSA", "Mansa", "만사", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MNSFL1", "Mansfield", "맨스필드", "미국", "America/New_York"),
		new CityListClass_E("MNT", "Manta", "만타", "에콰도르", "America/Guayaquil"),
		new CityListClass_E("MNTV", "Mantova", "만토바", "이탈리아", "Europe/Rome"),
		new CityListClass_E("MAN", "Manzanillo", "만사니요", "멕시코", "America/Mexico_City"),
		new CityListClass_E("MNZN", "Manzini", "만지니", "스와질란드", "Africa/Mbabane"),
		new CityListClass_E("PLNS", "Maple Plains", "메이플 플레인", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("MAP", "Maputo", "마푸토", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("MDP", "Mar del Plata", "마르델 플라타", "아르헨티나", "America/Argentina/Buenos_Aires"),
//		new CityListClass_E("MAR", "Maracaibo", "마라 카 이보", "베네수엘라", "America/Caracas"),
		new CityListClass_E("MRCY", "Maracay", "마라카이", "베네수엘라", "America/Caracas"),
		new CityListClass_E("MRNDL1", "Marandellas", "마론데라", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("MBL", "Marbella", "마 르벨라", "스페인", "Europe/Madrid"),
		new CityListClass_E("MRBLA", "Marble Hall", "마블 홀", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("MRDN", "Mardin", "마르딘", "터키", "Europe/Istanbul"),
		new CityListClass_E("MARDU", "Mardu", "마르토", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("MAIBO", "Maribo", "마리보", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("MRBR", "Maribor", "마리보르", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("MRNTL", "Mariental", "마리엔탈", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("MRTT", "Marietta", "매리에타", "미국", "America/New_York"),
		new CityListClass_E("MRGT", "Marigot", "마리고트", "도미니카", "America/Dominica"),
		new CityListClass_E("MRJMP", "Marijampole", "마리얌폴레", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("MAM", "Marmagao", "마르마가오", "인도", "Asia/Calcutta"),
		new CityListClass_E("MRQTT", "Marquette", "마켓", "미국", "America/Detroit"),
		new CityListClass_E("MTRH", "Marsa Matruh", "마르사마트루흐", "이집트", "Africa/Cairo"),
		new CityListClass_E("MAL", "Marseille", "마르세유", "프랑스", "Europe/Paris"),
		new CityListClass_E("MRSHL", "Marshall", "마샬", "미국", "America/Chicago"),
		new CityListClass_E("MRTGN", "Martigny", "마티니", "스위스", "Europe/Zurich"),
		new CityListClass_E("MRTNS", "Martinsville", "마틴즈빌", "미국", "America/New_York"),
		new CityListClass_E("MRYBR", "Maryborough", "메리버러", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("MRYDL", "Marydale", "마리데일", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("11H20302", "Masan", "마산", "대한민국", "Asia/Seoul"),
//		new CityListClass_E("MSRMU", "Maseru", "마세루", "레소토", "Africa/Maseru"),
		new CityListClass_E("MASSA", "Massa", "마사", "이탈리아", "Europe/Rome"),
		new CityListClass_E("MSVNG", "Masvingo", "마스빙고", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("MTGLP", "Matagalpa", "마타갈파", "니카라과", "America/Managua"),
		new CityListClass_E("MTMRS", "Matamoros", "마타모로스", "멕시코", "America/Monterrey"),
		new CityListClass_E("MTR1", "MatarO", "마타로", "스페인", "Europe/Madrid"),
		new CityListClass_E("MTRA", "Matera", "마테라", "이탈리아", "Europe/Rome"),
		new CityListClass_E("MTSZL", "Mateszalka", "모테살카", "헝가리", "Europe/Budapest"),
		new CityListClass_E("MTO", "Matola", "마톨라", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("MATNY", "Matoury", "마투리", "기아나", "America/Cayenne"),
		new CityListClass_E("MTRH1", "Matrah", "마트라", "오만", "Asia/Muscat"),
		new CityListClass_E("MTSUE", "Matsue", "마츠에", "일본", "Asia/Tokyo"),
		new CityListClass_E("MTSMT", "Matsumoto", "마츠모토", "일본", "Asia/Tokyo"),
		new CityListClass_E("MAS", "Matsuyama", "마츠야마", "일본", "Asia/Tokyo"),
//		new CityListClass_E("MTRN", "Maturin", "마투린", "베네수엘라", "America/Caracas"),
//		new CityListClass_E("MAUN", "Maun", "마운", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("MXX", "Maxixe", "마씨씨", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("MAYO1", "Mayo", "마요", "캐나다", "America/Dawson"),
		new CityListClass_E("MZBK", "Mazabuka", "마자부카", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MZTN", "Mazatan", "마사탄", "멕시코", "America/Mexico_City"),
		new CityListClass_E("MZTNN", "Mazatenango", "마사테낭고", "과테말라", "America/Guatemala"),
		new CityListClass_E("MAZEI", "Mazeikiai", "마제이키에이", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("MBBN", "Mbabane", "음바바네", "스와질란드", "Africa/Mbabane"),
		new CityListClass_E("MBALA", "Mbala", "엠발라", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MCLLN", "McAllen", "매캘런", "미국", "America/Chicago"),
		new CityListClass_E("MEAUX1", "Meaux", "모", "프랑스", "Europe/Paris"),
		new CityListClass_E("MECCA", "Mecca", "메카", "사우디아라비아", "Asia/Riyadh"),
		new CityListClass_E("MCHLN", "Mechlin", "메크린", "벨기에", "Europe/Brussels"),
		new CityListClass_E("EDA", "Medan", "메단", "인도네시아", "Asia/Jakarta"),
		new CityListClass_E("MDLLN", "Medellin", "메델린", "콜롬비아", "America/Bogota"),
		new CityListClass_E("MDF", "Medford", "메드퍼드", "미국", "America/Boise"),
//		new CityListClass_E("MDCN", "Medicine Hat", "메디신 햇", "캐나다", "America/Edmonton"),
		new CityListClass_E("MDNP", "Medina de Pomar", "메디나 데 포마르", "스페인", "Europe/Madrid"),
		new CityListClass_E("RSC", "Medina de Rioseco", "메디나데리오세코", "스페인", "Europe/Madrid"),
		new CityListClass_E("KHRNM", "Megalon khorion", "메가론코랴온", "그리스", "Europe/Athens"),
		new CityListClass_E("MKA", "Melaka", "멜라카", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("MELU", "Melbourne", "멜버른", "미국", "America/New_York"),
		new CityListClass_E("MEL", "Melbourne", "멜버른", "오스트레일리아", "Australia/Melbourne"),
		new CityListClass_E("MELO", "Melo", "멜로", "우루과이", "America/Montevideo"),
		new CityListClass_E("MPHSAR", "Memphis", "멤피스", "미국", "America/Chicago"),
		new CityListClass_E("MENDE", "Mende", "망드", "프랑스", "Europe/Paris"),
		new CityListClass_E("MNDZ", "Mendoza", "멘도사", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("MRCDS", "Mercedes", "메르세데스", "우루과이", "America/Montevideo"),
		new CityListClass_E("MRDA", "Merida", "메리다", "멕시코", "America/Merida"),
		new CityListClass_E("MRD1", "Merida", "메리다", "스페인", "Europe/Madrid"),
		new CityListClass_E("MERD", "Merida", "메리다", "베네수엘라", "America/Caracas"),
		new CityListClass_E("MRDN1", "Meriden", "메리덴", "미국", "America/New_York"),
		new CityListClass_E("MRDIN", "Meridian", "메리디언", "미국", "America/Chicago"),
		new CityListClass_E("MER", "Mersin", "메르신", "터키", "Europe/Istanbul"),
		new CityListClass_E("MRTHY", "Merthyr Tydfil", "머서티드빌", "영국", "Europe/London"),
		new CityListClass_E("MRTL", "Mertola", "메르똘라", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("MESA", "Mesa", "메사", "미국", "America/Denver"),
		new CityListClass_E("MSQTM", "Mesquite", "메스키트", "미국", "America/Chicago"),
		new CityListClass_E("MSSNA", "Messina", "메시나", "이탈리아", "Europe/Rome"),
		new CityListClass_E("MTHN", "Methoni", "메토니", "그리스", "Europe/Athens"),
		new CityListClass_E("METZ", "Metz", "메스", "프랑스", "Europe/Paris"),
		new CityListClass_E("MXCL", "Mexicali", "메히칼리", "멕시코", "America/Mazatlan"),
		new CityListClass_E("CMXC", "Mexico City", "멕시코 시티", "멕시코", "America/Mexico_City"),
		new CityListClass_E("MZC", "MeZica", "메지차", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("MIM", "Miami", "마이애미", "미국", "America/New_York"),
		new CityListClass_E("PBCH", "Miami Beach", "마이애미 비치", "미국", "America/New_York"),
		new CityListClass_E("MSTK1", "Miastko", "미아스트코", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("MCD", "Micoud", "미쿠드", "세인트루시아", "America/St_Lucia"),
		new CityListClass_E("MDDLB", "Middelburg", "미델뷔르흐", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("MBH", "Middlesbrough", "미들즈브러", "영국", "Europe/London"),
		new CityListClass_E("MDDLT", "Middletown", "미들타운-뉴욕", "미국", "America/New_York"),
		new CityListClass_E("MDDLT1", "Middletown", "미들타운-오하이오", "미국", "America/New_York"),
		new CityListClass_E("MDLND", "Midland", "미들랜드-미시간", "미국", "America/Detroit"),
		new CityListClass_E("MDD", "Midland", "미들랜드-텍사스", "미국", "America/Chicago"),
		new CityListClass_E("MCHW", "MiechOw", "미애츠오", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("MDZYR", "Miedzyrzec Podlaski", "미엥지제츠포들라스키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("MDZYR1", "Miedzyrzecz", "미엥지제치", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("MRCR", "Miercurea-Ciuc", "미에르쿠레아치우크", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("MLN", "Milano", "밀라노", "이탈리아", "Europe/Rome"),
		new CityListClass_E("MLDR", "Mildura", "밀두라", "오스트레일리아", "Australia/Melbourne"),
		new CityListClass_E("MLLU", "Millau", "미요", "프랑스", "Europe/Paris"),
		new CityListClass_E("MLW", "Milwaukee", "밀워키", "미국", "America/Chicago"),
		new CityListClass_E("JAA", "Mina Jabal Ali", "미나 제벨 알리", "아랍에미리트", "Asia/Dubai"),
		new CityListClass_E("MSQ", "Mina Saqr", "미나 사크르", "아랍에미리트", "Asia/Dubai"),
		new CityListClass_E("MZD", "Mina Zayid", "미나 자에드", "아랍에미리트", "Asia/Dubai"),
		new CityListClass_E("MNKM", "Minakami", "미나카미", "일본", "Asia/Tokyo"),
		new CityListClass_E("DAITJM", "Minamidaitojima", "미나미다이토지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("MINAS", "Minas", "미나스", "우루과이", "America/Montevideo"),
		new CityListClass_E("MNP", "Minneapolis", "미니애폴리스", "미국", "America/Chicago"),
		new CityListClass_E("MINSK", "Minsk", "민스크", "Belarus", "Europe/Minsk"),
		new CityListClass_E("MZWCK", "Minsk Mazowiecki", "민스크마조비에츠키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("MIRG", "Miragoane", "미라고아네", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("MIRC", "Miramichi", "미라미치", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("MRNDE", "Miranda de Ebro", "미란다데에브로", "스페인", "Europe/Madrid"),
		new CityListClass_E("MRNDL2", "Mirandela", "미란델라", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("MIR", "Miri", "미리", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("11H20601", "Miryang", "밀양", "대한민국", "Asia/Seoul"),
		new CityListClass_E("MSHM", "Mishima", "미시마", "일본", "Asia/Tokyo"),
		new CityListClass_E("MSKLC", "Miskolc", "미슈콜츠", "헝가리", "Europe/Budapest"),
		new CityListClass_E("MSSN", "Mission Viejo", "미션 비에호", "미국", "America/Los_Angeles"),
		new CityListClass_E("MSSL", "Missoula", "미줄라", "미국", "America/Denver"),
		new CityListClass_E("MSTLB", "Mistelbach", "미스텔바흐", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("MITO", "Mito", "미토", "일본", "Asia/Tokyo"),
		new CityListClass_E("MTTRS", "Mittersill", "미터실", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("MITU", "Mitu", "미투", "콜롬비아", "America/Bogota"),
//		new CityListClass_E("MIXCO", "Mixco", "믹스꼬", "과테말라", "America/Guatemala"),
		new CityListClass_E("MKE", "Miyakejima", "미야케지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("MIY", "Miyako", "미야코", "일본", "Asia/Tokyo"),
		new CityListClass_E("MYKJM", "Miyakojima", "미야코지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("MKJO", "Miyakonojo", "미야코노조", "일본", "Asia/Tokyo"),
		new CityListClass_E("MIYZ", "Miyazaki", "미야자키", "일본", "Asia/Tokyo"),
		new CityListClass_E("MIZOB", "Mizobe", "미조베", "일본", "Asia/Tokyo"),
		new CityListClass_E("MKSH", "Mkushi", "엠쿠시", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("BLSLV", "Mlada Boleslav", "믈라다볼레슬라프", "체코", "Europe/Prague"),
		new CityListClass_E("RANA", "Mo i Rana", "모이라나", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("MOAB", "Moab", "모아브", "미국", "America/Denver"),
		new CityListClass_E("MOB", "Mobile", "모빌", "미국", "America/Chicago"),
		new CityListClass_E("MCHD1", "Mochudi", "모추디", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("MDST", "Modesto", "머데스토", "미국", "America/Los_Angeles"),
		new CityListClass_E("MNG", "Moengo", "모엥구", "수리남", "America/Paramaribo"),
		new CityListClass_E("MGDSC", "Mogadiscio", "모가딧슈", "소말리아", "Africa/Mogadishu"),
		new CityListClass_E("MGDR", "Mogadouro", "모가도루", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("MGDTS", "Mogoditshane", "모고디츠하네", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("MHCS", "Mohacs", "모하치", "헝가리", "Europe/Budapest"),
		new CityListClass_E("MHLS", "Mohales Hoek", "모헬레 후크", "레소토", "Africa/Maseru"),
		new CityListClass_E("MJKVC", "Mojkovac", "모이코바츠", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("MKHTL", "Mokhotlong", "모코틀롱", "레소토", "Africa/Maseru"),
		new CityListClass_E("21F20801", "Mokpo", "목포", "대한민국", "Asia/Seoul"),
		new CityListClass_E("MOLDE", "Molde", "몰데", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("MLPLL", "Molepolole", "몰레폴로레", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("MOLN", "Moline", "멀린", "미국", "America/Chicago"),
		new CityListClass_E("MLK", "Moloka'i", "몰로카이", "미국", "Pacific/Honolulu"),
		new CityListClass_E("MBU", "Mombetsu", "몸베츠", "일본", "Asia/Tokyo"),
		new CityListClass_E("MNC", "Monaco", "모나코", "Monaco", "Europe/Monaco"),
		new CityListClass_E("MNGHN", "Monaghan", "모너핸", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("MNCHN", "Monchengladbach", "보루시아", "독일", "Europe/Berlin"),
		new CityListClass_E("MNCLV", "Monclova", "몬클로바", "멕시코", "America/Monterrey"),
		new CityListClass_E("MNCTN", "Moncton", "멍크턴", "캐나다", "America/Goose_Bay"),
//		new CityListClass_E("MNMVS", "Monemvasia", "모넴바시아", "그리스", "Europe/Athens"),
		new CityListClass_E("MNFRT", "Monforte de Lemos", "몬포테 데 레모스", "스페인", "Europe/Madrid"),
		new CityListClass_E("MONGU", "Mongu", "몽구", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MONKI", "Monki", "몬키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("MNR1", "Monroe", "먼로", "미국", "America/Chicago"),
		new CityListClass_E("MOR", "Monrovia", "몬로비아", "라이베리아", "Africa/Monrovia"),
		new CityListClass_E("MNTN", "Montana", "몬태나", "불가리아", "Europe/Sofia"),
		new CityListClass_E("MNTRG", "Montargis", "몽타르지", "프랑스", "Europe/Paris"),
		new CityListClass_E("MNTBN", "Montauban", "몽토방", "프랑스", "Europe/Paris"),
//		new CityListClass_E("MTB", "Montego Bay", "몬테고 베이", "자메이카", "America/Jamaica"),
		new CityListClass_E("ONOVO", "Montemor-o-Novo", "몬떼모르 우 노부", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("MNTPZ", "Montepuez", "몬테푸즈", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("MTRY", "Monterrey", "몬테레이", "멕시코", "America/Monterrey"),
		new CityListClass_E("MOT", "Montevideo", "몬테비데오", "우루과이", "America/Montevideo"),
		new CityListClass_E("MTGAL1", "Montgomery", "몽고메리", "미국", "America/Chicago"),
		new CityListClass_E("MNTLC", "Montlucon", "몽뤼꽁", "프랑스", "Europe/Paris"),
		new CityListClass_E("MNTR", "Montoro", "몬토루", "스페인", "Europe/Madrid"),
		new CityListClass_E("MNTPL", "Montpelier", "몬트필리어", "미국", "America/New_York"),
		new CityListClass_E("MPLLR", "Montpellier", "몽펠리에", "프랑스", "Europe/Paris"),
		new CityListClass_E("MTL", "Montreal", "몬트리올", "캐나다", "America/Montreal"),
		new CityListClass_E("MRRSB", "Moorreesburg", "무리즈버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("MST1", "Mooste", "무스트", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("MORA", "Mora", "모라", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("MRTLL", "Moratalla", "모라탈라", "스페인", "Europe/Madrid"),
		new CityListClass_E("MORL", "Morelia", "모렐 리아", "멕시코", "America/Mexico_City"),
		new CityListClass_E("MRLL", "Morella", "모렐라", "스페인", "Europe/Madrid"),
		new CityListClass_E("MNVLLY", "Moreno Valley", "모레노 밸리", "미국", "America/Los_Angeles"),
		new CityListClass_E("MRIOK", "Morioka", "모리오카", "일본", "Asia/Tokyo"),
		new CityListClass_E("MFRNTR", "Moron de la Frontera", "모론데라프론테라", "스페인", "Europe/Madrid"),
		new CityListClass_E("MRI", "Moroni", "모로니", "코모로", "Indian/Comoro"),
		new CityListClass_E("MRRMB", "Morrumbala", "모룸발라", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("MSCW3", "Moscow", "모스크바", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("MOS", "Mosjoen", "모쇼엔", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("MSSLB", "Mosselbaai", "모슬바이", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("MOST", "Most", "모스트", "체코", "Europe/Prague"),
		new CityListClass_E("MOSTA", "Mosta", "모스타", "몰타", "Europe/Malta"),
		new CityListClass_E("MSTR", "Mostar", "모스타르", "보스니아-헤르체고비나", "Europe/Sarajevo"),
		new CityListClass_E("MTL4", "Motala", "모탈라", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("MTR", "Motril", "모트릴", "스페인", "Europe/Madrid"),
		new CityListClass_E("EVRST", "Mount Everest", "에베레스트산", "네팔", "Asia/Katmandu"),
		new CityListClass_E("PLSNT", "Mount Pleasant", "마운트 플레전트", "미국", "America/Detroit"),
		new CityListClass_E("VRNN", "Mount Vernon", "마운트 버넌", "미국", "America/Chicago"),
		new CityListClass_E("MSCRN", "Mouscron", "모우스크론", "벨기에", "Europe/Brussels"),
		new CityListClass_E("MPIKA", "Mpika", "엠피카", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MRAWA", "Mrawa", "므라와", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("GMBRM", "Mt Gambier", "마운트 갬비어", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("MISA", "Mt Isa", "마운트 아이자", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("MTBTB", "Mtubatuba", "음투바투바", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("21F20804", "Muan", "무안", "대한민국", "Asia/Seoul"),
		new CityListClass_E("MUEDA", "Mueda", "무에다", "모잠비크", "Africa/Maputo"),
		new CityListClass_E("11F10302", "Muju", "무주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("MLHS", "Mulhouse", "뮐루즈", "프랑스", "Europe/Paris"),
		new CityListClass_E("MLLNG", "Mullingar", "물린가", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("MMBW", "Mumbwa", "뭄브아", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MNC1", "Muncie", "먼시", "미국", "America/Indianapolis"),
		new CityListClass_E("11H10301", "Mungyeong", "문경", "대한민국", "Asia/Seoul"),
		new CityListClass_E("MUNIC", "Munich", "뮌헨", "독일", "Europe/Berlin"),
		new CityListClass_E("11B20305", "Munsan", "문산", "대한민국", "Asia/Seoul"),
		new CityListClass_E("MURAU", "Murau", "무라우", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("MRCA", "Murcia", "무르시아", "스페인", "Europe/Madrid"),
		new CityListClass_E("MRFRS", "Murfreesboro", "머프리즈버로", "미국", "America/Chicago"),
		new CityListClass_E("MSK", "Murmansk", "무르만스크", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("MUR", "Muroran", "무로란", "일본", "Asia/Tokyo"),
		new CityListClass_E("MUO", "Murotomisaki", "무로토미사키", "일본", "Asia/Tokyo"),
		new CityListClass_E("SBTM", "Murska Sobota", "무르스카소보타", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("MRZZS", "Murzzuschlag", "뮈르추슐라크", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("MUS", "Muscat", "무스카트", "오만", "Asia/Muscat"),
		new CityListClass_E("MSKGN", "Muskegon", "머스키건", "미국", "America/Detroit"),
		new CityListClass_E("MSKG", "Muskogee", "머스코지", "미국", "America/Chicago"),
		new CityListClass_E("MTRE", "Mutare", "무타레", "짐바브웨", "Africa/Harare"),
		new CityListClass_E("MTS", "Mutsu", "무츠", "일본", "Asia/Tokyo"),
		new CityListClass_E("MWNLN", "Mwinilunga", "무뉘룽가", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("MYRTL", "Myrtle Beach", "머틀 비치", "미국", "America/New_York"),
		new CityListClass_E("MYSLN", "MySlenice", "미샐니시", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("MYSLB", "MySlibOrz", "미실리부스", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("MYSZK", "MyszkOw", "미스즈오", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("MYTLN", "Mytilene", "미틸리니", "그리스", "Europe/Athens"),

	};
}
