package com.weathernews.Weather;
public class Norway_europe {
    public final static CityListClass[] Norway_europe = new CityListClass[] {
//	new CityListClass("NVK",	"나르비크",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("NMSS",	"남소스",	"노르웨이",	"Europe/Oslo"),
//	new CityListClass("DMBS",	"돔바스",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("DRA",	"드라멘",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("LKNGR",	"레이캉게르",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("ROROS",	"로로스",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("LLLHM",	"릴레함메르",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("MLSLV",	"말샐브",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("MOS",	"모쇼엔",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("RANA",	"모이라나",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("MOLDE",	"몰데",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("VADSO",	"바드쇠",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("BGN",	"베르겐",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("BODO",	"보도족",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("VOSS",	"보스",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("BYGLN",	"뷔글란",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("SANDE",	"산데",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("SNNDL",	"순달소라",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("SVLVR",	"스볼베르",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("SVR",	"스타방게르",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("STNKJ",	"스테인헤르",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("SKIEN",	"시엔",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("ARNDL",	"아렌달",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("ALTA",	"알타",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("ASKER",	"애스커",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("EGRSN",	"에게르순",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("OSO",	"오슬로",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("ALSD",	"올레순",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("KRSJK",	"카라쇽",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("KNGSG",	"콩스버그",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("KRT",	"크리스티안산",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("KTD",	"크리스티안순",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("TON",	"퇸스베르",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("TRO",	"트론헤임",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("TMS",	"트롬소",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("FGRNS",	"파게르네스",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("FDS",	"프레드릭스타",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("HAMAR",	"하마르",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("HMMRF",	"함메르페스트",	"노르웨이",	"Europe/Oslo"),
	new CityListClass("HAU",	"헤우게순",	"노르웨이",	"Europe/Oslo"),
    };
}
