package com.weathernews.Weather;

class PA {
	public final static CityListClass[] pa = new CityListClass[] {
		new CityListClass("PGG1", "파게기에이", "리투아니아", "Europe/Vilnius"),
		new CityListClass("FGRNS", "파게르네스", "노르웨이", "Europe/Oslo"),
		new CityListClass("FARGO", "파고", "미국", "America/Chicago"),
		new CityListClass("OLO", "파나마", "파나마", "America/Panama"),
		new CityListClass("PCY", "파나마 시티", "미국", "America/New_York"),
		new CityListClass("ROXP", "파나이", "필리핀", "Asia/Manila"),
		new CityListClass("PJI", "파나지", "인도", "Asia/Calcutta"),
		new CityListClass("PNVZY", "파네베지스", "리투아니아", "Europe/Vilnius"),
		new CityListClass("PDN", "파당", "인도네시아", "Asia/Jakarta"),
		new CityListClass("PDVA", "파도바", "이탈리아", "Europe/Rome"),
		new CityListClass("VADUZ", "파두츠", "리히텐슈타인", "Europe/Vaduz"),
		new CityListClass("FGRS", "파라가스", "루마니아", "Europe/Bucharest"),
		new CityListClass("PNM", "파라남", "수리남", "America/Paramaribo"),
		new CityListClass("PAS", "파라마리보", "수리남", "America/Paramaribo"),
		new CityListClass("PLKST", "파라이카스트론", "그리스", "Europe/Athens"),
		new CityListClass("PAROS", "파로스", "그리스", "Europe/Athens"),
		new CityListClass("FRO", "파루", "포르투칼", "Europe/Lisbon"),
		new CityListClass("FARUM", "파룸", "덴마크", "Europe/Copenhagen"),
		new CityListClass("PRDBC", "파르두비체", "체코", "Europe/Prague"),
		new CityListClass("PARIS", "파리", "미국", "America/Chicago"),
		new CityListClass("PARI", "파리", "프랑스", "Europe/Paris"),
		new CityListClass("PRK1", "파리카", "가이아나", "America/Guyana"),
		new CityListClass("PLMRS", "파머스턴노스", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass("PSSU", "파사우", "독일", "Europe/Berlin"),
		new CityListClass("PSCN", "파슈카니", "루마니아", "Europe/Bucharest"),
		new CityListClass("PSVLY", "파스발리스", "리투아니아", "Europe/Vilnius"),
		new CityListClass("PASTO", "파스토", "콜롬비아", "America/Bogota"),
		new CityListClass("FBRG", "파아보리", "덴마크", "Europe/Copenhagen"),
		new CityListClass("PAIDE", "파이드", "에스토니아", "Europe/Tallinn"),
		new CityListClass("PYSND", "파이산뒤", "우루과이", "America/Montevideo"),
		new CityListClass("BLUFF", "파인 블러프", "미국", "America/Chicago"),
		new CityListClass("PILES", "파일", "그리스", "Europe/Athens"),
		new CityListClass("PZRDZ", "파자르디크", "불가리아", "Europe/Sofia"),
		new CityListClass("11B20303", "파주", "대한민국", "Asia/Seoul"),
		new CityListClass("PCHC", "파추카", "멕시코", "America/Mexico_City"),
		new CityListClass("PRKVL", "파커빌", "미국", "America/New_York"),
		new CityListClass("PRKRS", "파커즈버그", "미국", "America/New_York"),
		new CityListClass("PKMBN", "파켐반간", "인도네시아", "Asia/Jakarta"),
		new CityListClass("PKRJS", "파크루오이스", "리투아니아", "Europe/Vilnius"),
		new CityListClass("PPS", "파트라스", "그리스", "Europe/Athens"),
		new CityListClass("PAPA1", "파파", "헝가리", "Europe/Budapest"),
		new CityListClass("PAP", "파페에테", "폴리네시아", "Pacific/Tahiti"),
		new CityListClass("PPHS", "파포스", "키프로스", "Asia/Nicosia"),
		new CityListClass("PARLA", "팔라", "스페인", "Europe/Madrid"),
		new CityListClass("PLCHR", "팔라이오코라", "그리스", "Europe/Athens"),
		new CityListClass("PMD", "팔레르모", "이탈리아", "Europe/Rome"),
		new CityListClass("PLNC", "팔렌시아", "스페인", "Europe/Madrid"),
		new CityListClass("PLNR", "팔리누로", "이탈리아", "Europe/Rome"),
		new CityListClass("PLKR", "팔리키르", "미크로네시아", "Pacific/Yap"),
		new CityListClass("PMM", "팔마", "스페인", "Europe/Madrid"),
		new CityListClass("PRSPP", "팔시파니", "미국", "America/New_York"),
		new CityListClass("SPRNGP", "팜 스프링스", "미국", "America/Los_Angeles"),
		new CityListClass("PLMD", "팜데일", "미국", "America/Los_Angeles"),
		new CityListClass("PMPLN", "팜플로나", "스페인", "Europe/Madrid"),
//		new CityListClass("PNGNR", "팡니르텅", "캐나다", "America/Pangnirtung"),
		new CityListClass("SOUND", "패리 사운드", "캐나다", "America/Toronto"),
		new CityListClass("PAXCA", "패서디나-캘리포니아", "미국", "America/Los_Angeles"),
		new CityListClass("PAX", "패서디나-텍사스", "미국", "America/Chicago"),
		new CityListClass("PSG", "패스커굴라", "미국", "America/Chicago"),
		new CityListClass("PSNNJ", "패터슨", "미국", "America/New_York"),
		new CityListClass("PEC", "팩", "세르비아", "Europe/Belgrade"),
		new CityListClass("PDCH", "퍼두커", "미국", "America/Chicago"),
		new CityListClass("PER", "퍼스", "오스트레일리아", "Australia/Perth"),
		new CityListClass("PERTH", "퍼스", "영국", "Europe/London"),
		new CityListClass("PERM", "펌", "러시아", "Asia/Yekaterinburg"),
//		new CityListClass("PNCH1", "페니체", "포르투칼", "Europe/Lisbon"),
		new CityListClass("PDRNL", "페더날레스", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass("PERIA", "페레이라", "콜롬비아", "America/Bogota"),
		new CityListClass("PRRNJ", "페렌자스", "알바니아", "Europe/Tirane"),
		new CityListClass("PRGA", "페루자", "이탈리아", "Europe/Rome"),
		new CityListClass("PARNU", "페르누", "에스토니아", "Europe/Tallinn"),
		new CityListClass("PRNK", "페르니크", "불가리아", "Europe/Sofia"),
		new CityListClass("PRPGN", "페르피냥", "프랑스", "Europe/Paris"),
		new CityListClass("PRGX", "페리괴", "프랑스", "Europe/Paris"),
		new CityListClass("PSR", "페사로", "이탈리아", "Europe/Rome"),
		new CityListClass("VSTRV", "페스테어빅", "스웨덴", "Europe/Stockholm"),
//		new CityListClass("FRBNK", "페어 뱅크스", "미국", "America/Yakutat"),
		new CityListClass("FFDCA", "페어 필드", "미국", "America/Los_Angeles"),
		new CityListClass("FTYNC1", "페이어트빌-노스캐롤라이나", "미국", "America/New_York"),
		new CityListClass("FTYNC", "페이어트빌-아칸소", "미국", "America/Chicago"),
//		new CityListClass("PSLY", "페이즐리", "영국", "Europe/London"),
		new CityListClass("PAGE", "페이지", "미국", "America/Denver"),
		new CityListClass("PECS", "페치", "헝가리", "Europe/Budapest"),
		new CityListClass("PEK", "페칸바루", "인도네시아", "Asia/Jakarta"),
		new CityListClass("PECOS", "페코스", "미국", "America/Chicago"),
		new CityListClass("PTR1", "페타레", "베네수엘라", "America/Caracas"),
		new CityListClass("PTKE", "페타우케", "잠비아", "Africa/Lusaka"),
		new CityListClass("PTRZV", "페트로자봇스크", "러시아", "Europe/Moscow"),
		new CityListClass("PTRPW", "페트로파블롭스크캄차츠키", "러시아", "Asia/Magadan"),
		new CityListClass("PTRC", "페트리치", "불가리아", "Europe/Sofia"),
		new CityListClass("PENSA", "펜사", "러시아", "Asia/Yekaterinburg"),
		new CityListClass("PNC", "펜서콜라", "미국", "America/New_York"),
		new CityListClass("PEB", "펨바", "모잠비크", "Africa/Maputo"),
		new CityListClass("11D10503", "평창", "대한민국", "Asia/Seoul"),
		new CityListClass("11B20606", "평택", "대한민국", "Asia/Seoul"),
		new CityListClass("PDGRC", "포드고리차", "세르비아", "Europe/Belgrade"),
		new CityListClass("PAIX", "포르 드 파익스", "아이티", "America/Port-au-Prince"),
//		new CityListClass("PRDNN", "포르데노네", "이탈리아", "Europe/Rome"),
		new CityListClass("FTF", "포르드프랑스", "마르티니크", "America/Martinique"),
		new CityListClass("PRTLG", "포르탈레그르", "포르투칼", "Europe/Lisbon"),
		new CityListClass("FRTLZ", "포르탈레자", "브라질", "America/Fortaleza"),
		new CityListClass("PORTEN", "포르테 노보", "Benin", "Africa/Porto-Novo"),
		new CityListClass("OPO", "포르토", "포르투칼", "Europe/Lisbon"),
		new CityListClass("MONIZ", "포르토 모니즈", "포르투칼", "Atlantic/Madeira"),
		new CityListClass("PAB", "포르토 알레그레", "브라질", "America/Bahia"),
		new CityListClass("PAU", "포르토 프 랭스", "아이티", "America/Port-au-Prince"),
		new CityListClass("PRTVJ", "포르토비헤호", "에콰도르", "America/Guayaquil"),
		new CityListClass("PRTFR", "포르토페라이오", "이탈리아", "Europe/Rome"),
		new CityListClass("PMAO", "포르티마오", "포르투칼", "Europe/Lisbon"),
		new CityListClass("POMO", "포모나", "미국", "America/Los_Angeles"),
		new CityListClass("PVC1", "포보아카오", "포르투칼", "Atlantic/Azores"),
		new CityListClass("PSDS", "포사다스", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("PSTMS", "포스트마스버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PRTR", "포오트리", "영국", "Europe/London"),
		new CityListClass("PTPN", "포인트 아 피어", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass("PFT", "포인트 포르틴", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass("HDLG", "포자 리카 드 히달고", "멕시코", "America/Mexico_City"),
		new CityListClass("PZG", "포제가", "크로아티아", "Europe/Zagreb"),
		new CityListClass("PZNN", "포즈난", "폴란드", "Europe/Warsaw"),
//		new CityListClass("FGG", "포지아", "이탈리아", "Europe/Rome"),
		new CityListClass("11B20403", "포천", "대한민국", "Asia/Seoul"),
		new CityListClass("POTSD", "포츠담", "독일", "Europe/Berlin"),
		new CityListClass("PRTSM", "포츠머스", "미국", "America/New_York"),
		new CityListClass("POTSM", "포츠머스", "도미니카", "America/Dominica"),
		new CityListClass("PCTLL", "포커텔로", "미국", "America/Boise"),
		new CityListClass("PGHKP", "포킵시", "미국", "America/New_York"),
		new CityListClass("PTMS", "포타모스", "그리스", "Europe/Athens"),
		new CityListClass("PTM", "포타모이", "그리스", "Europe/Athens"),
		new CityListClass("VLLGP", "포터스 빌리지", "앤티가바부다", "America/Antigua"),
		new CityListClass("PWTCK", "포터컷", "미국", "America/New_York"),
		new CityListClass("PTNZ", "포텐자", "이탈리아", "Europe/Rome"),
//		new CityListClass("PTS1", "포토시", "볼리비아", "America/La_Paz"),
		new CityListClass("NLSN", "포트 넬슨", "캐나다", "America/Vancouver"),
		new CityListClass("NLLTH", "포트 놀로쓰", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("FTL", "포트 로더데일", "미국", "America/New_York"),
		new CityListClass("LOUIS", "포트 루이스", "Mauritius", "Indian/Mauritius"),
		new CityListClass("PLC", "포트 링컨", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass("FMYR", "포트 마이어스", "미국", "America/New_York"),
		new CityListClass("MCMRR", "포트 맥머리", "캐나다", "America/Edmonton"),
		new CityListClass("PRM", "포트 모레스비", "파푸아뉴기니", "Pacific/Port_Moresby"),
		new CityListClass("PVI", "포트 빌라", "바누아투", "Pacific/Efate"),
		new CityListClass("PSA", "포트 사이드", "이집트", "Africa/Cairo"),
		new CityListClass("CHRLTP", "포트 샬롯", "미국", "America/New_York"),
		new CityListClass("LUCIE", "포트 세인트 루시", "미국", "America/New_York"),
		new CityListClass("SMTHAR", "포트 스미스", "미국", "America/Chicago"),
		new CityListClass("FRTSMT", "포트 스미스", "캐나다", "America/Yellowknife"),
		new CityListClass("SMPSN", "포트 심슨", "캐나다", "America/Yellowknife"),
		new CityListClass("PAG", "포트 앤젤레스", "미국", "America/Los_Angeles"),
		new CityListClass("EDWRDP", "포트 에드워드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PEL", "포트 엘리사벳", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PTELZ", "포트 엘리자베스", "세인트 빈센트 그레나딘", "America/St_Vincent"),
		new CityListClass("PSNN", "포트 오브 스페인", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass("WORT", "포트 워스", "미국", "America/Chicago"),
		new CityListClass("WAYNE", "포트 웨인", "미국", "America/Indianapolis"),
		new CityListClass("POI", "포트 카이저", "자메이카", "America/Jamaica"),
		new CityListClass("CLLNS", "포트 콜린스", "미국", "America/Denver"),
		new CityListClass("PPI", "포트 피리", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass("HDLND", "포트 헤들랜드", "오스트레일리아", "Australia/Perth"),
		new CityListClass("PRTLG1", "포트라오이즈", "아일랜드", "Europe/Dublin"),
		new CityListClass("PBLR", "포트블레어", "인도", "Asia/Calcutta"),
		new CityListClass("PTL", "포틀랜드-메인", "미국", "America/New_York"),
		new CityListClass("PDT", "포틀랜드-오레곤", "미국", "America/Boise"),
		new CityListClass("11H10201", "포항", "대한민국", "Asia/Seoul"),
		new CityListClass("FCSN", "폭샤니", "루마니아", "Europe/Bucharest"),
		new CityListClass("FOND", "폰뒬락", "미국", "America/Chicago"),
		new CityListClass("INLET", "폰드 인렛", "캐나다", "America/Pangnirtung"),
		new CityListClass("FONT", "폰타나", "미국", "America/Los_Angeles"),
		new CityListClass("PDE", "폰타델가다", "포르투칼", "Atlantic/Azores"),
		new CityListClass("PONTE", "폰테 데 소레", "포르투칼", "Europe/Lisbon"),
		new CityListClass("PNTVD", "폰테베드라", "스페인", "Europe/Madrid"),
		new CityListClass("PTK", "폰티아타크", "인도네시아", "Asia/Pontianak"),
		new CityListClass("PNFRR", "폰페라다", "스페인", "Europe/Madrid"),
		new CityListClass("FAL", "폴 리버", "미국", "America/New_York"),
		new CityListClass("PLYGY", "폴리기로스", "그리스", "Europe/Athens"),
		new CityListClass("POLVA", "폴바마콘드", "에스토니아", "Europe/Tallinn"),
		new CityListClass("FLKRK", "폴커크", "영국", "Europe/London"),
		new CityListClass("PMBL", "폼발", "포르투칼", "Europe/Lisbon"),
		new CityListClass("PON", "퐁디셰리", "인도", "Asia/Calcutta"),
		new CityListClass("PONCA", "퐁카 시티", "미국", "America/Chicago"),
		new CityListClass("PNTVY", "퐁티비", "프랑스", "Europe/Paris"),
		new CityListClass("FNFT", "푸나푸티", "Tuvalu", "Pacific/Funafuti"),
		new CityListClass("PRWY", "푸라우", "폴란드", "Europe/Warsaw"),
		new CityListClass("PTRS", "푸아티에", "프랑스", "Europe/Paris"),
		new CityListClass("PNTPT", "푸앵트아피트르", "프랑스", "America/Guadeloupe"),
//		new CityListClass("AYCCH", "푸에르 아야쿠초", "베네수엘라", "America/Caracas"),
		new CityListClass("TRNF", "푸에르 엘 트리운포", "엘살바도르", "America/El_Salvador"),
		new CityListClass("PUCS", "푸에르 카스티 야", "온두라스", "America/Tegucigalpa"),
		new CityListClass("OLMP", "푸에르테올림포", "파라과이", "America/Asuncion"),
		new CityListClass("RSR", "푸에르토 델 로사리오", "스페인", "Atlantic/Canary"),
		new CityListClass("PLM", "푸에르토 리몬", "코스타리카", "America/Costa_Rica"),
		new CityListClass("MLDNDP", "푸에르토 말도나도", "페루", "America/Lima"),
		new CityListClass("PNSC", "푸에르토 메낭또", "멕시코", "America/Hermosillo"),
		new CityListClass("PUM", "푸에르토 몽트", "칠레", "America/Santiago"),
//		new CityListClass("PBA", "푸에르토 바 리오스", "과테말라", "America/Guatemala"),
		new CityListClass("PVA", "푸에르토 발라타", "멕시코", "America/Mexico_City"),
		new CityListClass("PCZ", "푸에르토 카베자스", "니카라과", "America/Managua"),
		new CityListClass("PUC", "푸에르토 코르테즈", "온두라스", "America/Tegucigalpa"),
		new CityListClass("QEP", "푸에르토 퀘스포스", "코스타리카", "America/Costa_Rica"),
		new CityListClass("PUW", "푸에르토프린세사", "필리핀", "Asia/Manila"),
		new CityListClass("PBL1", "푸에블라", "멕시코", "America/Mexico_City"),
		new CityListClass("RDRGP", "푸에블라 데 돈 로드리고", "스페인", "Europe/Madrid"),
		new CityListClass("SNBR", "푸에블라 데 사나브리아", "스페인", "Europe/Madrid"),
		new CityListClass("PBLO", "푸에블로", "미국", "America/Denver"),
		new CityListClass("ESCND", "푸에트토 에스콘디도", "멕시코", "America/Mexico_City"),
		new CityListClass("PNT1", "푸엔테헤닐", "스페인", "Europe/Madrid"),
		new CityListClass("FNGRL", "푸엔히롤라", "스페인", "Europe/Madrid"),
		new CityListClass("PLLNO", "푸엘톨라노", "스페인", "Europe/Madrid"),
		new CityListClass("PUK", "푸켓", "태국", "Asia/Bangkok"),
		new CityListClass("MILIA", "푼다 미리아", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("FNC", "푼샬", "포르투칼", "Atlantic/Madeira"),
//		new CityListClass("GORDA", "푼타 고르다", "벨리즈", "America/Belize"),
		new CityListClass("PEU", "푼타 델 에스테", "우루과이", "America/Montevideo"),
//		new CityListClass("PNTRN", "푼타 레나스", "코스타리카", "America/Costa_Rica"),
		new CityListClass("PNTA", "푼타 아레 나스", "칠레", "America/Santiago"),
		new CityListClass("PUY", "풀라", "크로아티아", "Europe/Zagreb"),
		new CityListClass("FLLR", "풀러턴", "미국", "America/Los_Angeles"),
		new CityListClass("PNMPN", "프놈펜", "캄보디아", "Asia/Phnom_Penh"),
		new CityListClass("FRNFL", "프라우엔펠트", "스위스", "Europe/Zurich"),
		new CityListClass("VRYBR", "프라이벅", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("FYB", "프라이벤토스", "우루과이", "America/Montevideo"),
		new CityListClass("FRBRG1", "프라이부르크", "스위스", "Europe/Zurich"),
		new CityListClass("FRSTD", "프라이스타트", "오스트리아", "Europe/Vienna"),
		new CityListClass("PPR", "프라이아", "Cape Verde", "Atlantic/Cape_Verde"),
		new CityListClass("PRG1", "프라하", "체코", "Europe/Prague"),
		new CityListClass("FRNCST", "프란시스타운", "보츠와나", "Africa/Gaborone"),
		new CityListClass("FRNK", "프랑크푸르트", "독일", "Europe/Berlin"),
		new CityListClass("FRNKFO", "프랭크퍼트", "미국", "America/New_York"),
		new CityListClass("FDS", "프레드릭스타", "노르웨이", "Europe/Oslo"),
		new CityListClass("FRED", "프레드릭스테드", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass("FRDRC", "프레드릭턴", "캐나다", "America/Goose_Bay"),
		new CityListClass("PRSV", "프레솝", "슬로바키아", "Europe/Bratislava"),
		new CityListClass("PRSCT", "프레스콧", "미국", "America/Denver"),
//		new CityListClass("FRSRB", "프레이저버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("FRSN", "프레즈노", "미국", "America/Los_Angeles"),
		new CityListClass("PRTRA", "프레토리아", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("FLN", "프렌스부르크", "독일", "Europe/Berlin"),
		new CityListClass("PGR", "프로그레소", "멕시코", "America/Merida"),
		new CityListClass("PRRV", "프로로프", "체코", "Europe/Prague"),
		new CityListClass("PRO", "프로비던스", "미국", "America/New_York"),
		new CityListClass("FRSNN", "프로시노네", "이탈리아", "Europe/Rome"),
//		new CityListClass("PROCK", "프록", "폴란드", "Europe/Warsaw"),
		new CityListClass("FRNTR", "프론테라", "스페인", "Atlantic/Canary"),
		new CityListClass("PRDNK", "프루드닉", "폴란드", "Europe/Warsaw"),
//		new CityListClass("FRMNT", "프리 몬트", "미국", "America/Los_Angeles"),
		new CityListClass("MSTK", "프리데크미스테크", "체코", "Europe/Prague"),
		new CityListClass("PRBRM", "프리브람", "체코", "Europe/Prague"),
		new CityListClass("PRSK", "프리스카", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PRSTN", "프리스티나", "세르비아", "Europe/Belgrade"),
		new CityListClass("FRWN", "프리오운", "Sierra Leone", "Africa/Freetown"),
		new CityListClass("PRZRN", "프리즈렌", "세르비아", "Europe/Belgrade"),
		new CityListClass("PRI", "프린스 루퍼트", "캐나다", "America/Vancouver"),
		new CityListClass("ALBRTP", "프린스 알버트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("ALBRT", "프린스 앨버트", "캐나다", "America/Regina"),
		new CityListClass("GRG2", "프린스 조지", "캐나다", "America/Vancouver"),
		new CityListClass("PRLP", "프릴레프", "마케도니아", "Europe/Skopje"),
		new CityListClass("PSARA", "프사라", "그리스", "Europe/Athens"),
		new CityListClass("PSKOW", "프스코프", "러시아", "Europe/Moscow"),
		new CityListClass("BOURGP", "프티부그", "과들루프섬", "America/Guadeloupe"),
		new CityListClass("PLAV", "플라", "세르비아", "Europe/Belgrade"),
		new CityListClass("PLSNC", "플라센시아", "스페인", "Europe/Madrid"),
		new CityListClass("FLGST", "플래그스태프", "미국", "America/Denver"),
		new CityListClass("PLNO", "플래이노", "미국", "America/Chicago"),
		new CityListClass("PLTTS", "플래츠버그", "미국", "America/New_York"),
		new CityListClass("PYMTH", "플러 머스", "몬세라트산", "America/Montserrat"),
		new CityListClass("PLNG", "플런지", "리투아니아", "Europe/Vilnius"),
		new CityListClass("PLVN", "플레벤", "불가리아", "Europe/Sofia"),
		new CityListClass("PLJVL", "플레블라", "세르비아", "Europe/Belgrade"),
		new CityListClass("PLSNT1", "플레즌턴", "미국", "America/Los_Angeles"),
//		new CityListClass("FLRS", "플로레스", "과테말라", "America/Guatemala"),
		new CityListClass("FLRD1", "플로리다", "우루과이", "America/Montevideo"),
		new CityListClass("FLRSS", "플로리쌩", "미국", "America/Chicago"),
		new CityListClass("PLVDV", "플로브디프", "불가리아", "Europe/Sofia"),
		new CityListClass("PLST", "플로이에쉬티", "루마니아", "Europe/Bucharest"),
		new CityListClass("PLZN", "플루지네", "세르비아", "Europe/Belgrade"),
		new CityListClass("PLYMT", "플리머스-메사추세츠", "미국", "America/New_York"),
		new CityListClass("PLYMH", "플리머스-미네소타", "미국", "America/Chicago"),
		new CityListClass("PLY", "플리머스", "영국", "Europe/London"),
		new CityListClass("FLON", "플린 플론", "캐나다", "America/Regina"),
		new CityListClass("FLINT", "플린트", "미국", "America/Detroit"),
		new CityListClass("PLZEN", "플젠", "체코", "Europe/Prague"),
		new CityListClass("FGRES", "피게레스", "스페인", "Europe/Madrid"),
		new CityListClass("FDF", "피게이라다포스", "포르투칼", "Europe/Lisbon"),
		new CityListClass("PHX", "피닉스", "미국", "America/Denver"),
		new CityListClass("FRNZ", "피렌체", "이탈리아", "Europe/Rome"),
		new CityListClass("PYRGS", "피르고스", "그리스", "Europe/Athens"),
		new CityListClass("PRPLS", "피리아포리스", "우루과이", "America/Montevideo"),
		new CityListClass("PISEK", "피섹", "체코", "Europe/Prague"),
		new CityListClass("FSTRR", "피스테라", "스페인", "Europe/Madrid"),
		new CityListClass("FSHGR", "피시가드", "영국", "Europe/London"),
		new CityListClass("PCNZ", "피아첸차", "이탈리아", "Europe/Rome"),
		new CityListClass("PTNMT", "피아트라네암츠", "루마니아", "Europe/Bucharest"),
		new CityListClass("PRR1", "피어", "미국", "America/Chicago"),
		new CityListClass("FIER", "피어필드", "알바니아", "Europe/Tirane"),
		new CityListClass("PDRSN", "피에드라스 네그라스", "멕시코", "America/Monterrey"),
//		new CityListClass("RTLF", "피에트 레티프", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PEOAZ", "피오리아-애리조나", "미국", "America/Denver"),
		new CityListClass("PEOIL", "피오리아-일리노이", "미국", "America/Chicago"),
		new CityListClass("PIURA", "피우라", "페루", "America/Lima"),
		new CityListClass("PHTSN", "피차눌로크", "태국", "Asia/Bangkok"),
		new CityListClass("PTTB", "피츠버그", "미국", "America/New_York"),
		new CityListClass("PTTSF", "피츠필드", "미국", "America/New_York"),
		new CityListClass("PKTBR", "피케트버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PKSKL", "피크스킬", "미국", "America/New_York"),
		new CityListClass("PTRMR", "피터마리츠버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PRBRG", "피터버러", "영국", "Europe/London"),
		new CityListClass("PTRSB", "피터즈버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("PTST", "피테스티", "루마니아", "Europe/Bucharest"),
		new CityListClass("PIGGS", "픽스 피크", "스와질란드", "Africa/Mbabane"),
		new CityListClass("FCKSB", "픽스버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SWDNK", "핀드닉", "폴란드", "Europe/Warsaw"),
		new CityListClass("FNDLY", "핀들레이", "미국", "America/New_York"),
		new CityListClass("PNHL", "핀헬", "포르투칼", "Europe/Lisbon"),
		new CityListClass("PHL", "필라델피아", "미국", "America/New_York"),
		new CityListClass("PHG", "필립스버그", "앤틸리스제도", "America/Curacao"),

//		new CityListClass("PGG1","파게기에이","리투아니아","Europe/Vilnius"),
//		new CityListClass("FGRNS","파게르네스","노르웨이","Europe/Oslo"),
//		new CityListClass("FARGO","파고","미국","America/Chicago"),
//		new CityListClass("OLO","파나마","파나마","America/Panama"),
//		new CityListClass("PCY","파나마 시티","미국","America/New_York"),
//		new CityListClass("ROXP","파나이","필리핀","Asia/Manila"),
//		new CityListClass("PJI","파나지","인도","Asia/Calcutta"),
//	    	new CityListClass("PNVZY","파네베지스","리투아니아","Europe/Vilnius"),
//		new CityListClass("PDN","파당","인도네시아","Asia/Jakarta"),
//		new CityListClass("PDVA","파도바","이탈리아","Europe/Rome"),
//		new CityListClass("VADUZ","파두츠","리히텐슈타인","Europe/Vaduz"),
//		new CityListClass("FGRS","파라가스","루마니아","Europe/Bucharest"),
//		new CityListClass("PNM","파라남","수리남","America/Paramaribo"),
//		new CityListClass("PAS","파라마리보","수리남","America/Paramaribo"),
//		new CityListClass("PLKST","파라이카스트론","그리스","Europe/Athens"),
//		new CityListClass("PAROS","파로스","그리스","Europe/Athens"),
//		new CityListClass("FRO","파루","포르투칼","Europe/Lisbon"),
//		new CityListClass("FARUM","파룸","덴마크","Europe/Copenhagen"),
//		new CityListClass("PRDBC","파르두비체","체코","Europe/Prague"),
//		new CityListClass("PARIS","파리","미국","America/Chicago"),
//		new CityListClass("PARI","파리","프랑스","Europe/Paris"),
//		new CityListClass("PRK1","파리카","가이아나","America/Guyana"),
//		new CityListClass("PLMRS","파머스턴노스","뉴질랜드","Pacific/Auckland"),
//		new CityListClass("PSSU","파사우","독일","Europe/Berlin"),
//		new CityListClass("PSCN","파슈카니","루마니아","Europe/Bucharest"),
//	    	new CityListClass("PSVLY","파스발리스","리투아니아","Europe/Vilnius"),
//		new CityListClass("PASTO","파스토","콜롬비아","America/Bogota"),
//		new CityListClass("FBRG","파아보리","덴마크","Europe/Copenhagen"),
//		new CityListClass("PAIDE","파이드","에스토니아","Europe/Tallinn"),
//		new CityListClass("PYSND","파이산뒤","우루과이","America/Montevideo"),
//		new CityListClass("BLUFF","파인 블러프","미국","America/Chicago"),
//		new CityListClass("PILES","파일","그리스","Europe/Athens"),
//		new CityListClass("PZRDZ","파자르디크","불가리아","Europe/Sofia"),
//			new CityListClass("11B20303","파주","대한민국","Asia/Seoul"),
//		new CityListClass("PCHC","파추카","멕시코","America/Mexico_City"),
//		new CityListClass("PRKVL","파커빌","미국","America/New_York"),
//		new CityListClass("PRKRS","파커즈버그","미국","America/New_York"),
//		new CityListClass("PKMBN","파켐반간","인도네시아","Asia/Jakarta"),
//	    	new CityListClass("PKRJS","파크루오이스","리투아니아","Europe/Vilnius"),
//		new CityListClass("PPS","파트라스","그리스","Europe/Athens"),
//		new CityListClass("PAP","파페에테","폴리네시아","Pacific/Tahiti"),
//		new CityListClass("PPHS","파포스","키프로스","Asia/Nicosia"),
//		new CityListClass("PARLA","팔라","스페인","Europe/Madrid"),
//		new CityListClass("PLCHR","팔라이오코라","그리스","Europe/Athens"),
//		new CityListClass("PMD","팔레르모","이탈리아","Europe/Rome"),
//		new CityListClass("PLNC","팔렌시아","스페인","Europe/Madrid"),
//		new CityListClass("PLNR","팔리누로","이탈리아","Europe/Rome"),
//		new CityListClass("PLKR","팔리키르","미크로네시아","Pacific/Yap"),
//		new CityListClass("PMM","팔마","스페인","Europe/Madrid"),
//		new CityListClass("PRSPP","팔시파니","미국","America/New_York"),
//		new CityListClass("SPRNGP","팜 스프링스","미국","America/Los_Angeles"),
//		new CityListClass("PLMD","팜데일","미국","America/Los_Angeles"),
//		new CityListClass("PMPLN","팜플로나","스페인","Europe/Madrid"),
//		new CityListClass("PNGNR","팡니르텅","캐나다","America/Pangnirtung"),
//		new CityListClass("SOUND","패리 사운드","캐나다","America/Toronto"),
//		new CityListClass("PAXCA","패서디나-캘리포니아","미국","America/Los_Angeles"),
//		new CityListClass("PAX","패서디나-텍사스","미국","America/Chicago"),
//		new CityListClass("PSG","패스커굴라","미국","America/Chicago"),
//		new CityListClass("PSNNJ","패터슨","미국","America/New_York"),
//		new CityListClass("PEC","팩","세르비아","Europe/Belgrade"),
//		new CityListClass("PDCH","퍼두커","미국","America/Chicago"),
//		new CityListClass("PER","퍼스","오스트레일리아","Australia/Perth"),
//		new CityListClass("PERTH","퍼스","영국","Europe/London"),
//		new CityListClass("PERM","펌","러시아 연방 국가","Asia/Yekaterinburg"),
//		new CityListClass("PNCH1","페니체","포르투칼","Europe/Lisbon"),
//		new CityListClass("PDRNL","페더날레스","도미나카공화국","America/Santo_Domingo"),
//		new CityListClass("PERIA","페레이라","콜롬비아","America/Bogota"),
//		new CityListClass("PRRNJ","페렌자스","알바니아","Europe/Tirane"),
//		new CityListClass("PRGA","페루자","이탈리아","Europe/Rome"),
//		new CityListClass("PARNU","페르누","에스토니아","Europe/Tallinn"),
//		new CityListClass("PRNK","페르니크","불가리아","Europe/Sofia"),
//		new CityListClass("PRPGN","페르피냥","프랑스","Europe/Paris"),
//		new CityListClass("PRGX","페리괴","프랑스","Europe/Paris"),
//		new CityListClass("PSR","페사로","이탈리아","Europe/Rome"),
//		new CityListClass("VSTRV","페스테어빅","스웨덴","Europe/Stockholm"),
//		new CityListClass("FRBNK","페어 뱅크스","미국","America/Yakutat"),
//		new CityListClass("FFDCA","페어 필드","미국","America/Los_Angeles"),
//		new CityListClass("FTYNC1","페이어트빌-노스캐롤라이나","미국","America/New_York"),
//		new CityListClass("FTYNC","페이어트빌-아칸소","미국","America/Chicago"),
//		new CityListClass("PSLY","페이즐리","영국","Europe/London"),
//		new CityListClass("PAGE","페이지","미국","America/Denver"),
//		new CityListClass("PEK","페칸바루","인도네시아","Asia/Jakarta"),
//		new CityListClass("PECOS","페코스","미국","America/Chicago"),
//	    	new CityListClass("PTR1","페타레","베네수엘라","America/Caracas"),
//		new CityListClass("PTKE","페타우케","잠비아","Africa/Lusaka"),
//		new CityListClass("PTRZV","페트로자봇스크","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("PTRPW","페트로파블롭스크캄차츠키","러시아 연방 국가","Asia/Magadan"),
//		new CityListClass("PTRC","페트리치","불가리아","Europe/Sofia"),
//		new CityListClass("PENSA","펜사","러시아 연방 국가","Asia/Yekaterinburg"),
//		new CityListClass("PNC","펜서콜라","미국","America/New_York"),
//		new CityListClass("PEB","펨바","모잠비크","Africa/Maputo"),
//			new CityListClass("11D10503","평창","대한민국","Asia/Seoul"),
//			new CityListClass("11B20606","평택","대한민국","Asia/Seoul"),
//		new CityListClass("PDGRC","포드고리차","세르비아","Europe/Belgrade"),
//		new CityListClass("PAIX","포르 드 파익스","아이티","America/Port-au-Prince"),
//		new CityListClass("PRDNN","포르데노네","이탈리아","Europe/Rome"),
//		new CityListClass("FTF","포르드프랑스","마르티니크","America/Martinique"),
//		new CityListClass("PRTLG","포르탈레그르","포르투칼","Europe/Lisbon"),
//		new CityListClass("FRTLZ","포르탈레자","브라질","America/Fortaleza"),
//			new CityListClass("PORTEN","포르테 노보","Benin","Africa/Porto-Novo"),
//		new CityListClass("OPO","포르토","포르투칼","Europe/Lisbon"),
//		new CityListClass("MONIZ","포르토 모니즈","포르투칼","Atlantic/Madeira"),
//		new CityListClass("PAB","포르토 알레그레","브라질","America/Bahia"),
//		new CityListClass("PAU","포르토 프 랭스","아이티","America/Port-au-Prince"),
//		new CityListClass("PRTVJ","포르토비헤호","에콰도르","America/Guayaquil"),
//		new CityListClass("PRTFR","포르토페라이오","이탈리아","Europe/Rome"),
//		new CityListClass("PMAO","포르티마오","포르투칼","Europe/Lisbon"),
//		new CityListClass("POMO","포모나","미국","America/Los_Angeles"),
//		new CityListClass("PVC1","포보아카오","포르투칼","Atlantic/Azores"),
//		new CityListClass("PSDS","포사다스","아르헨티나","America/Argentina/Buenos_Aires"),
//		new CityListClass("PSTMS","포스트마스버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PRTR","포오트리","영국","Europe/London"),
//		new CityListClass("PTPN","포인트 아 피어","트리니다드토바고","America/Port_of_Spain"),
//		new CityListClass("PFT","포인트 포르틴","트리니다드토바고","America/Port_of_Spain"),
//		new CityListClass("HDLG","포자 리카 드 히달고","멕시코","America/Mexico_City"),
//		new CityListClass("PZG","포제가","크로아티아","Europe/Zagreb"),
//		new CityListClass("PZNN","포즈난","폴란드","Europe/Warsaw"),
//		new CityListClass("FGG","포지아","이탈리아","Europe/Rome"),
//			new CityListClass("11B20403","포천","대한민국","Asia/Seoul"),
//		new CityListClass("POTSD","포츠담","독일","Europe/Berlin"),
//		new CityListClass("PRTSM","포츠머스","미국","America/New_York"),
//		new CityListClass("POTSM","포츠머스","도미니카","America/Dominica"),
//		new CityListClass("PCTLL","포커텔로","미국","America/Boise"),
//		new CityListClass("PGHKP","포킵시","미국","America/New_York"),
//		new CityListClass("PTMS","포타모스","그리스","Europe/Athens"),
//		new CityListClass("PTM","포타모이","그리스","Europe/Athens"),
//		new CityListClass("VLLGP","포터스 빌리지","앤티가바부다","America/Antigua"),
//		new CityListClass("PWTCK","포터컷","미국","America/New_York"),
//		new CityListClass("PTNZ","포텐자","이탈리아","Europe/Rome"),
//		new CityListClass("PTS1","포토시","볼리비아","America/La_Paz"),
//		new CityListClass("NLSN","포트 넬슨","캐나다","America/Vancouver"),
//		new CityListClass("NLLTH","포트 놀로쓰","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("FTL","포트 로더데일","미국","America/New_York"),
//		new CityListClass("LOUIS","포트 루이스","Mauritius","Indian/Mauritius"),
//		new CityListClass("PLC","포트 링컨","오스트레일리아","Australia/Adelaide"),
//		new CityListClass("FMYR","포트 마이어스","미국","America/New_York"),
//		new CityListClass("MCMRR","포트 맥머리","캐나다","America/Edmonton"),
//		new CityListClass("PRM","포트 모레스비","파푸아뉴기니","Pacific/Port_Moresby"),
//		new CityListClass("PVI","포트 빌라","바누아투","Pacific/Efate"),
//			new CityListClass("PSA","포트 사이드","이집트","Africa/Cairo"),
//		new CityListClass("CHRLTP","포트 샬롯","미국","America/New_York"),
//		new CityListClass("LUCIE","포트 세인트 루시","미국","America/New_York"),
//		new CityListClass("SMTHAR","포트 스미스","미국","America/Chicago"),
//		new CityListClass("FRTSMT","포트 스미스","캐나다","America/Yellowknife"),
//		new CityListClass("SMPSN","포트 심슨","캐나다","America/Yellowknife"),
//		new CityListClass("PAG","포트 앤젤레스","미국","America/Los_Angeles"),
//		new CityListClass("EDWRDP","포트 에드워드","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PEL","포트 엘리사벳","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PTELZ","포트 엘리자베스","세인트 빈센트 그레나딘","America/St_Vincent"),
//		new CityListClass("PSNN","포트 오브 스페인","트리니다드토바고","America/Port_of_Spain"),
//		new CityListClass("WORT","포트 워스","미국","America/Chicago"),
//		new CityListClass("WAYNE","포트 웨인","미국","America/Indianapolis"),
//		new CityListClass("POI","포트 카이저","자메이카","America/Jamaica"),
//		new CityListClass("CLLNS","포트 콜린스","미국","America/Denver"),
//		new CityListClass("PPI","포트 피리","오스트레일리아","Australia/Adelaide"),
//		new CityListClass("HDLND","포트 헤들랜드","오스트레일리아","Australia/Perth"),
//		new CityListClass("PRTLG1","포트라오이즈","아일랜드","Europe/Dublin"),
//		new CityListClass("PBLR","포트블레어","인도","Asia/Calcutta"),
//		new CityListClass("PTL","포틀랜드","미국","America/New_York"),
//		new CityListClass("PDT","포틀랜드","미국","America/Boise"),
//			new CityListClass("11H10201","포항","대한민국","Asia/Seoul"),
//		new CityListClass("FCSN","폭샤니","루마니아","Europe/Bucharest"),
//		new CityListClass("FOND","폰뒬락","미국","America/Chicago"),
//		new CityListClass("INLET","폰드 인렛","캐나다","America/Pangnirtung"),
//		new CityListClass("FONT","폰타나","미국","America/Los_Angeles"),
//		new CityListClass("PDE","폰타델가다","포르투칼","Atlantic/Azores"),
//		new CityListClass("PONTE","폰테 데 소레","포르투칼","Europe/Lisbon"),
//		new CityListClass("PNTVD","폰테베드라","스페인","Europe/Madrid"),
//		new CityListClass("PTK","폰티아타크","인도네시아","Asia/Pontianak"),
//		new CityListClass("PNFRR","폰페라다","스페인","Europe/Madrid"),
//		new CityListClass("FAL","폴 리버","미국","America/New_York"),
//		new CityListClass("PLYGY","폴리기로스","그리스","Europe/Athens"),
//		new CityListClass("POLVA","폴바마콘드","에스토니아","Europe/Tallinn"),
//		new CityListClass("FLKRK","폴커크","영국","Europe/London"),
//		new CityListClass("PMBL","폼발","포르투칼","Europe/Lisbon"),
//		new CityListClass("PON","퐁디셰리","인도","Asia/Calcutta"),
//		new CityListClass("PONCA","퐁카 시티","미국","America/Chicago"),
//		new CityListClass("PNTVY","퐁티비","프랑스","Europe/Paris"),
//		new CityListClass("FNFT","푸나푸티","Tuvalu","Pacific/Funafuti"),
//		new CityListClass("PRWY","푸라우","폴란드","Europe/Warsaw"),
//		new CityListClass("PTRS","푸아티에","프랑스","Europe/Paris"),
//		new CityListClass("PNTPT","푸앵트아피트르","프랑스","America/Guadeloupe"),
//	    	new CityListClass("AYCCH","푸에르 아야쿠초","베네수엘라","America/Caracas"),
//		new CityListClass("TRNF","푸에르 엘 트리운포","엘살바도르","America/El_Salvador"),
//	    	new CityListClass("PUCS","푸에르 카스티 야","온두라스","America/Tegucigalpa"),
//		new CityListClass("OLMP","푸에르테올림포","파라과이","America/Asuncion"),
//		new CityListClass("RSR","푸에르토 델 로사리오","스페인","Atlantic/Canary"),
//		new CityListClass("PLM","푸에르토 리몬","코스타리카","America/Costa_Rica"),
//		new CityListClass("MLDNDP","푸에르토 말도나도","페루","America/Lima"),
//		new CityListClass("PNSC","푸에르토 메낭또","멕시코","America/Hermosillo"),
//		new CityListClass("PUM","푸에르토 몽트","칠레","America/Santiago"),
//		new CityListClass("PBA","푸에르토 바 리오스","과테말라","America/Guatemala"),
//		new CityListClass("PVA","푸에르토 발라타","멕시코","America/Mexico_City"),
//		new CityListClass("PCZ","푸에르토 카베자스","니카라과","America/Managua"),
//	    	new CityListClass("PUC","푸에르토 코르테즈","온두라스","America/Tegucigalpa"),
//		new CityListClass("QEP","푸에르토 퀘스포스","코스타리카","America/Costa_Rica"),
//		new CityListClass("PUW","푸에르토프린세사","필리핀","Asia/Manila"),
//		new CityListClass("PBL1","푸에블라","멕시코","America/Mexico_City"),
//		new CityListClass("RDRGP","푸에블라 데 돈 로드리고","스페인","Europe/Madrid"),
//		new CityListClass("SNBR","푸에블라 데 사나브리아","스페인","Europe/Madrid"),
//		new CityListClass("PBLO","푸에블로","미국","America/Denver"),
//		new CityListClass("ESCND","푸에트토 에스콘디도","멕시코","America/Mexico_City"),
//		new CityListClass("PNT1","푸엔테헤닐","스페인","Europe/Madrid"),
//		new CityListClass("FNGRL","푸엔히롤라","스페인","Europe/Madrid"),
//		new CityListClass("PLLNO","푸엘톨라노","스페인","Europe/Madrid"),
//		new CityListClass("PUK","푸켓","태국","Asia/Bangkok"),
//		new CityListClass("MILIA","푼다 미리아","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("FNC","푼샬","포르투칼","Atlantic/Madeira"),
//		new CityListClass("GORDA","푼타 고르다","벨리즈","America/Belize"),
//		new CityListClass("PEU","푼타 델 에스테","우루과이","America/Montevideo"),
//		new CityListClass("PNTRN","푼타 레나스","코스타리카","America/Costa_Rica"),
//		new CityListClass("PNTA","푼타 아레 나스","칠레","America/Santiago"),
//		new CityListClass("PUY","풀라","크로아티아","Europe/Zagreb"),
//		new CityListClass("FLLR","풀러턴","미국","America/Los_Angeles"),
//		new CityListClass("PNMPN","프놈펜","캄보디아","Asia/Phnom_Penh"),
//		new CityListClass("FRNFL","프라우엔펠트","스위스","Europe/Zurich"),
//		new CityListClass("VRYBR","프라이벅","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("FYB","프라이벤토스","우루과이","America/Montevideo"),
//		new CityListClass("FRBRG1","프라이부르크","스위스","Europe/Zurich"),
//		new CityListClass("FRSTD","프라이스타트","오스트리아","Europe/Vienna"),
//		new CityListClass("PPR","프라이아","Cape Verde","Atlantic/Cape_Verde"),
//		new CityListClass("PRG1","프라하","체코","Europe/Prague"),
//		new CityListClass("FRNCST","프란시스타운","보츠와나","Africa/Gaborone"),
//		new CityListClass("FRNK","프랑크푸르트","독일","Europe/Berlin"),
//		new CityListClass("FRNKFO","프랭크퍼트","미국","America/New_York"),
//		new CityListClass("FDS","프레드릭스타","노르웨이","Europe/Oslo"),
//		new CityListClass("FRED","프레드릭스테드","버진 아일랜드","America/St_Thomas"),
//		new CityListClass("FRDRC","프레드릭턴","캐나다","America/Goose_Bay"),
//		new CityListClass("PRSV","프레솝","슬로바키아","Europe/Bratislava"),
//		new CityListClass("PRSCT","프레스콧","미국","America/Denver"),
//		new CityListClass("FRSRB","프레이저버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("FRSN","프레즈노","미국","America/Los_Angeles"),
//		new CityListClass("PRTRA","프레토리아","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("FLN","프렌스부르크","독일","Europe/Berlin"),
//		new CityListClass("PGR","프로그레소","멕시코","America/Merida"),
//		new CityListClass("PRRV","프로로프","체코","Europe/Prague"),
//		new CityListClass("PRO","프로비던스","미국","America/New_York"),
//		new CityListClass("FRSNN","프로시노네","이탈리아","Europe/Rome"),
//		new CityListClass("PROCK","프록","폴란드","Europe/Warsaw"),
//		new CityListClass("FRNTR","프론테라","스페인","Atlantic/Canary"),
//		new CityListClass("PRDNK","프루드닉","폴란드","Europe/Warsaw"),
//		new CityListClass("FRMNT","프리 몬트","미국","America/Los_Angeles"),
//		new CityListClass("MSTK","프리데크미스테크","체코","Europe/Prague"),
//		new CityListClass("PRBRM","프리브람","체코","Europe/Prague"),
//		new CityListClass("PRSK","프리스카","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PRSTN","프리스티나","세르비아","Europe/Belgrade"),
//		new CityListClass("FRWN","프리오운","Sierra Leone","Africa/Freetown"),
//		new CityListClass("PRZRN","프리즈렌","세르비아","Europe/Belgrade"),
//		new CityListClass("PRI","프린스 루퍼트","캐나다","America/Vancouver"),
//		new CityListClass("ALBRTP","프린스 알버트","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("ALBRT","프린스 앨버트","캐나다","America/Regina"),
//		new CityListClass("GRG2","프린스 조지","캐나다","America/Vancouver"),
//		new CityListClass("PRLP","프릴레프","마케도니아","Europe/Skopje"),
//		new CityListClass("PSARA","프사라","그리스","Europe/Athens"),
//		new CityListClass("PSKOW","프스코프","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("BOURGP","프티부그","과들루프섬","America/Guadeloupe"),
//		new CityListClass("PLAV","플라","세르비아","Europe/Belgrade"),
//		new CityListClass("PLSNC","플라센시아","스페인","Europe/Madrid"),
//		new CityListClass("FLGST","플래그스태프","미국","America/Denver"),
//		new CityListClass("PLNO","플래이노","미국","America/Chicago"),
//		new CityListClass("PLTTS","플래츠버그","미국","America/New_York"),
//		new CityListClass("PYMTH","플러 머스","몬세라트산","America/Montserrat"),
//	    	new CityListClass("PLNG","플런지","리투아니아","Europe/Vilnius"),
//		new CityListClass("PLVN","플레벤","불가리아","Europe/Sofia"),
//		new CityListClass("PLJVL","플레블라","세르비아","Europe/Belgrade"),
//		new CityListClass("PLSNT1","플레즌턴","미국","America/Los_Angeles"),
//		new CityListClass("FLRS","플로레스","과테말라","America/Guatemala"),
//		new CityListClass("FLRD1","플로리다","우루과이","America/Montevideo"),
//		new CityListClass("FLRSS","플로리쌩","미국","America/Chicago"),
//		new CityListClass("PLVDV","플로브디프","불가리아","Europe/Sofia"),
//		new CityListClass("PLST","플로이에쉬티","루마니아","Europe/Bucharest"),
//		new CityListClass("PLZN","플루지네","세르비아","Europe/Belgrade"),
//		new CityListClass("PLYMT","플리머스","미국","America/New_York"),
//		new CityListClass("PLYMH","플리머스","미국","America/Chicago"),
//		new CityListClass("PLY","플리머스","영국","Europe/London"),
//		new CityListClass("FLON","플린 플론","캐나다","America/Regina"),
//		new CityListClass("FLINT","플린트","미국","America/Detroit"),
//		new CityListClass("PLZEN","플젠","체코","Europe/Prague"),
//		new CityListClass("FGRES","피게레스","스페인","Europe/Madrid"),
//		new CityListClass("FDF","피게이라다포스","포르투칼","Europe/Lisbon"),
//		new CityListClass("PHX","피닉스","미국","America/Denver"),
//		new CityListClass("FRNZ","피렌체","이탈리아","Europe/Rome"),
//		new CityListClass("PYRGS","피르고스","그리스","Europe/Athens"),
//		new CityListClass("PRPLS","피리아포리스","우루과이","America/Montevideo"),
//		new CityListClass("PISEK","피섹","체코","Europe/Prague"),
//		new CityListClass("FSTRR","피스테라","스페인","Europe/Madrid"),
//		new CityListClass("FSHGR","피시가드","영국","Europe/London"),
//		new CityListClass("PCNZ","피아첸차","이탈리아","Europe/Rome"),
//		new CityListClass("PTNMT","피아트라네암츠","루마니아","Europe/Bucharest"),
//		new CityListClass("PRR1","피어","미국","America/Chicago"),
//		new CityListClass("FIER","피어필드","알바니아","Europe/Tirane"),
//		new CityListClass("PDRSN","피에드라스 네그라스","멕시코","America/Monterrey"),
//		new CityListClass("RTLF","피에트 레티프","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PEOAZ","피오리아-애리조나","미국","America/Denver"),
//		new CityListClass("PEOIL","피오리아-일리노이","미국","America/Chicago"),
//		new CityListClass("PIURA","피우라","페루","America/Lima"),
//		new CityListClass("PHTSN","피차눌로크","태국","Asia/Bangkok"),
//		new CityListClass("PTTB","피츠버그","미국","America/New_York"),
//		new CityListClass("PTTSF","피츠필드","미국","America/New_York"),
//		new CityListClass("PKTBR","피케트버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PKSKL","피크스킬","미국","America/New_York"),
//		new CityListClass("PTRMR","피터마리츠버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PRBRG","피터버러","영국","Europe/London"),
//		new CityListClass("PTRSB","피터즈버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("PTST","피테스티","루마니아","Europe/Bucharest"),
//		new CityListClass("PIGGS","픽스 피크","스와질란드","Africa/Mbabane"),
//		new CityListClass("FCKSB","픽스버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SWDNK","핀드닉","폴란드","Europe/Warsaw"),
//		new CityListClass("FNDLY","핀들레이","미국","America/New_York"),
//		new CityListClass("PNHL","핀헬","포르투칼","Europe/Lisbon"),
//		new CityListClass("PHL","필라델피아","미국","America/New_York"),
//		new CityListClass("PHG","필립스버그","앤틸리스제도","America/Curacao"),
	};
}
