package com.weathernews.Weather;
public class Romania_europe {
    public final static CityListClass[] Romania_europe = new CityListClass[] {
	new CityListClass("GLT",	"갈라치",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("DEVA",	"데바",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("DTSEV",	"드로베타투르누세베린",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("RST1",	"레지타",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("RMNC",	"름니쿠블체아",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("MRCR",	"미에르쿠레아치우크",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("VSL",	"바슬루이",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("MAREB",	"바이아마레",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BACAU",	"바커우",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BLST",	"버일레슈티",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BTSN",	"보토샤니",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BUZAU",	"부저우",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BCHRS",	"부쿠레슈티",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BFT",	"부프테아",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BRSV1",	"브라쇼브",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BIA",	"브러일라",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("BSTRT1",	"비스트리차",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("MARES",	"사투마레",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("SCVA",	"수체아바",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("GHRGH",	"스핀두게오르게",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("SLTN",	"슬라티나",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("SLBZ",	"슬로보지아",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("SIBIU",	"시비우",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("ARAD",	"아라드",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("IULIA",	"알바이 울리아",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("ALXNR",	"알이스칸다리야",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("ORDEA",	"오라데아",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("IASI",	"이아시",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("ZALAU",	"잘러우",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("GRG1",	"지우르지우",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("CRCL1",	"카라칼",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("CLRS1",	"칼라라시",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("CTZ",	"콘스탄차",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("CRAV",	"크라이오바",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("NPCA",	"클루지나포카",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("TCC",	"테쿠치",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("TLC",	"툴체아",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("TRGMRS",	"트루구뮤어",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("TRGVS1",	"트르고비슈테",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("TARGU",	"트르구지우",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("TMSR",	"티미쇼아라",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("FGRS",	"파라가스",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("PSCN",	"파슈카니",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("FCSN",	"폭샤니",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("PLST",	"플로이에쉬티",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("PTNMT",	"피아트라네암츠",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("PTST",	"피테스티",	"루마니아",	"Europe/Bucharest"),
	new CityListClass("HNDR",	"후네도아라",	"루마니아",	"Europe/Bucharest"),
    };
}
