package com.weathernews.Weather;

public class RR {
	public final static CityListClass_E[] rr = new CityListClass_E[] {
		new CityListClass_E("RKH", "Ra's al Khaymah", "라스알카이마", "아랍에미리트", "Asia/Dubai"),
		new CityListClass_E("RABAT", "Rabat", "라바트", "모로코", "Africa/Casablanca"),
		new CityListClass_E("MDINA", "Rabat-Mdina", "라바트 - 메디나", "몰타", "Europe/Malta"),
		new CityListClass_E("RCN", "Racine", "라신", "미국", "America/Chicago"),
		new CityListClass_E("RADOM", "Radom", "라돔", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("RDMSK", "Radomsko", "라돔스코", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("RDVS", "Radovis", "라도비시", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("RDVLS", "Radviliskis", "라드빌리슈키스", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("RGS", "Ragusa", "라구사", "이탈리아", "Europe/Rome"),
		new CityListClass_E("RKVR", "Rakvere", "라크베레", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("RLGH", "Raleigh", "롤리", "미국", "America/New_York"),
		new CityListClass_E("RMLLH", "Ramallah", "람알라", "팔레스타인", "Asia/Gaza"),
		new CityListClass_E("RMNC", "Ramnicu Valcea", "름니쿠블체아", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("RNCG", "Rancagua", "랑카구아", "칠레", "America/Santiago"),
		new CityListClass_E("CCMNG", "Rancho Cucamonga", "랜초 쿠카몬가", "미국", "America/Los_Angeles"),
		new CityListClass_E("RNKN", "Rankin Inlet", "랑킨 인렛", "캐나다", "America/Pangnirtung"),
		new CityListClass_E("RAPD", "Rapid City", "래피드 시티", "미국", "America/Denver"),
		new CityListClass_E("RAPLA", "Rapla", "라프라", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("RSN1", "Raseiniai", "라세이냐이", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("RAV", "Ravenna", "라벤나", "이탈리아", "Europe/Rome"),
		new CityListClass_E("MINT", "Raysut", "레이슈트", "오만", "Asia/Muscat"),
		new CityListClass_E("RZGRD", "Razgrad", "라즈그라트", "불가리아", "Europe/Sofia"),
		new CityListClass_E("READG", "Reading", "레딩", "영국", "Europe/London"),
		new CityListClass_E("REDNG", "Reading", "레딩-뉴욕", "미국", "America/New_York"),
		new CityListClass_E("REC", "Recife", "레시페", "브라질", "America/Recife"),
		new CityListClass_E("DEER", "Red Deer", "레드 디어", "캐나다", "America/Edmonton"),
		new CityListClass_E("RDDNG", "Redding", "레딩-캘리포니아", "미국", "America/Los_Angeles"),
		new CityListClass_E("RDMND", "Redmond", "레드몬드", "미국", "America/Los_Angeles"),
		new CityListClass_E("RDNDB", "Redondo Beach", "레돈도 비치", "미국", "America/Los_Angeles"),
		new CityListClass_E("RWC", "Redwood City", "레드우드 시티", "미국", "America/Los_Angeles"),
		new CityListClass_E("RGNSB", "Regensburg", "레겐스부르크", "독일", "Europe/Berlin"),
		new CityListClass_E("RDC", "Reggio Calabria", "레지오 칼라 브리아", "이탈리아", "Europe/Rome"),
		new CityListClass_E("EML", "Reggio Emilia", "레지오 에밀리아", "이탈리아", "Europe/Rome"),
		new CityListClass_E("RGN", "Regina", "리자이나", "캐나다", "America/Regina"),
		new CityListClass_E("RGNGS", "Reguengos de Monsaraz", "레구엔고스 데 몬싸라스", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("REIMS", "Reims", "랭스", "프랑스", "Europe/Paris"),
		new CityListClass_E("RNS", "Reinosa", "레이노사", "스페인", "Europe/Madrid"),
		new CityListClass_E("REITZ", "Reitz", "리츠", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("RNMRK", "Renmark", "렌마크", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("RNNS", "Rennes", "렌느", "프랑스", "Europe/Paris"),
		new CityListClass_E("RENO", "Reno", "리노", "미국", "America/Los_Angeles"),
		new CityListClass_E("RQN", "Requena", "레퀘나", "스페인", "Europe/Madrid"),
		new CityListClass_E("RESEN", "Resen", "레센", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("RST1", "Resita", "레지타", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("RTHYM", "Rethymno", "레심노", "그리스", "Europe/Athens"),
		new CityListClass_E("BLLQ", "Retuerta del Bullaque", "레투에르타 델 블라크", "스페인", "Europe/Madrid"),
		new CityListClass_E("REUS", "Reus", "레우스", "스페인", "Europe/Madrid"),
		new CityListClass_E("RYK", "Reykjavik", "레이캬비크", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass_E("RHDS", "Rhodes", "로도스", "그리스", "Europe/Athens"),
		new CityListClass_E("RHYL", "Rhyl", "릴", "영국", "Europe/London"),
		new CityListClass_E("RIANO", "Riano", "리아노", "스페인", "Europe/Madrid"),
		new CityListClass_E("RBD", "Ribadeo", "리바데오", "스페인", "Europe/Madrid"),
		new CityListClass_E("RBDSL", "Ribadesella", "리바데세야", "스페인", "Europe/Madrid"),
		new CityListClass_E("RIBE", "Ribe", "리베", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("RBRB", "Ribeira Brava", "리베이라 브라바", "포르투칼", "Atlantic/Madeira"),
		new CityListClass_E("RBRG", "Ribeira Grande", "리베이라그란데", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("RBR", "Ribeirao Preto", "히베이라웅 쁘레또", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("RBRLT", "Riberalta", "리베랄타", "볼리비아", "America/La_Paz"),
		new CityListClass_E("RCHLN", "Richland", "리칠랜드", "미국", "America/Los_Angeles"),
		new CityListClass_E("RCM", "Richmond", "리치먼드-버지니아", "미국", "America/New_York"),
		new CityListClass_E("RIC", "Richmond", "리치먼드-캘리포니아", "미국", "America/Los_Angeles"),
		new CityListClass_E("RCMND", "Richmond", "리치먼드-켄터키", "미국", "America/New_York"),
		new CityListClass_E("RCHMN", "Richmond", "리치몬드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("RDGWD", "Ridgewood", "리지우드", "미국", "America/New_York"),
		new CityListClass_E("INNKR", "Ried im Innkreis", "리트 임 잉크라이스", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("RJK", "Rijeka", "리예카", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("RNGKB", "Ringkobing", "링쾨빙", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("BRNC1", "Rio Branco", "리오 브랑코", "브라질", "America/Rio_Branco"),
		new CityListClass_E("RDJ", "Rio de Janeiro", "리오 데 자네이로", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("RGL", "Rio Gallegos", "리오 갈레 고스", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("RBMB", "Riobamba", "리오밤바", "에콰도르", "America/Guayaquil"),
		new CityListClass_E("RIVAS", "Rivas", "리바스", "니카라과", "America/Managua"),
		new CityListClass_E("RVR", "Rivera", "리베라", "우루과이", "America/Montevideo"),
		new CityListClass_E("RVRSD", "Riversdale", "리버스데일", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("RVRD", "Riverside", "리버사이드", "미국", "America/Los_Angeles"),
		new CityListClass_E("RVRP", "Riviere-Pilote", "리비 에르", "마르티니크", "America/Martinique"),
		new CityListClass_E("RYDH", "Riyadh", "리야드", "사우디아라비아", "Asia/Riyadh"),
		new CityListClass_E("RJSN", "Rjasan", "르하잔", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("RDT", "Road Town", "로드 타운", "세인트 키츠 네비스", "America/Tortola"),
		new CityListClass_E("RNN", "Roanne", "로안", "프랑스", "Europe/Paris"),
		new CityListClass_E("RNK", "Roanoke", "로어노크", "미국", "America/New_York"),
		new CityListClass_E("ROH", "Rocha", "로샤", "우루과이", "America/Montevideo"),
		new CityListClass_E("RNY", "Rochester", "로체스터-뉴욕", "미국", "America/New_York"),
		new CityListClass_E("RCHST", "Rochester", "로체스터-뉴햄프셔", "미국", "America/New_York"),
		new CityListClass_E("RNYMN", "Rochester", "로체스터-미네소타", "미국", "America/Chicago"),
		new CityListClass_E("HILL", "Rock Hill", "락 힐", "미국", "America/New_York"),
		new CityListClass_E("RCKFR", "Rockford", "록퍼드", "미국", "America/Chicago"),
		new CityListClass_E("RCKHM", "Rockhampton", "록햄프턴", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("MOUNT", "Rocky Mount", "로키마운트", "미국", "America/New_York"),
		new CityListClass_E("RODZ", "rOdz", "롯쯔", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("RGRS", "Rogers", "로저스", "미국", "America/Chicago"),
		new CityListClass_E("RKSKS", "Rokiskis", "로키스키스", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("RKYCN", "Rokycany", "로키차니", "체코", "Europe/Prague"),
		new CityListClass_E("ROM", "Roma", "로마", "이탈리아", "Europe/Rome"),
		new CityListClass_E("ROMGA", "Rome", "롬", "미국", "America/New_York"),
		new CityListClass_E("ROMZA", "romza", "로마자", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("RQTS", "Roquetas de Mar", "로퀘타스 데 마르", "스페인", "Europe/Madrid"),
		new CityListClass_E("ROROS", "Roros", "로로스", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("RSA", "Rosario", "로사리오", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("RTO", "Rosarito", "로사리토", "멕시코", "America/Mazatlan"),
		new CityListClass_E("RSCMM", "Roscommon", "로스코먼", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("RSU", "Roseau", "로조", "도미니카", "America/Dominica"),
		new CityListClass_E("RSKLD", "Roskilde", "로스킬레", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("ROS", "Rostock", "로스토크", "독일", "Europe/Berlin"),
		new CityListClass_E("RSTOV", "Rostov-on-Don", "로스토프온돈", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("RSWLL", "Roswell", "로즈웰-뉴멕시코", "미국", "America/Denver"),
		new CityListClass_E("RSWEL", "Roswell", "로즈웰-조지아", "미국", "America/New_York"),
		new CityListClass_E("RTR", "Rotorua", "로터루아", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass_E("ROT", "Rotterdam", "로테르담", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("ROU", "Rouen", "루앙", "프랑스", "Europe/Paris"),
//		new CityListClass_E("SLSKA", "Ruda Slaska", "루다실롱스카", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("RUKOW", "rukOw", "루크오우", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("RMI", "Rumoi", "루모이", "일본", "Asia/Tokyo"),
		new CityListClass_E("RUNDU", "Rundu", "룬두", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("RUSE", "Ruse", "루세", "불가리아", "Europe/Sofia"),
		new CityListClass_E("RUSNE", "Rusne", "루스네", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("RTLND", "Rutland", "러틀랜드", "미국", "America/New_York"),
//		new CityListClass_E("RYBNK", "Rybnik", "리브니크", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("RZSZW", "RzeszOw", "제슈프", "폴란드", "Europe/Warsaw"),

	};
}
