package com.weathernews.Weather;

public class S {
	public final static CityListClass_E[] s = new CityListClass_E[] {
		new CityListClass_E("SRBRC", "Saarbrucken", "자르브뤼켄", "독일", "Europe/Berlin"),
		new CityListClass_E("SRLS", "Saarlouis", "자얼루이", "독일", "Europe/Berlin"),
		new CityListClass_E("SBDLL", "Sabadell", "사바델", "스페인", "Europe/Madrid"),
		new CityListClass_E("SBNT", "Sabaneta", "사바네타", "아루바", "America/Aruba"),
		new CityListClass_E("11H20402", "Sacheon", "사천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("HRBRS", "Sachs Harbour", "삭스 하버", "캐나다", "America/Yellowknife"),
		new CityListClass_E("SAC", "Sacramento", "새크라멘토", "미국", "America/Los_Angeles"),
		new CityListClass_E("SAG", "Saga", "사가", "일본", "Asia/Tokyo"),
		new CityListClass_E("SGNW", "Saginaw", "새기노", "미국", "America/Detroit"),
		new CityListClass_E("SGNY", "Saguenay", "사그네이", "캐나다", "America/Montreal"),
		new CityListClass_E("SHGN", "SahagUn", "사하군", "스페인", "Europe/Madrid"),
		new CityListClass_E("SAIGOU", "Saigou", "사이고우", "일본", "Asia/Tokyo"),
		new CityListClass_E("SAE", "Saiki", "사이키", "일본", "Asia/Tokyo"),
		new CityListClass_E("ALBNS", "Saint Albans", "세인트올번스", "영국", "Europe/London"),
		new CityListClass_E("SANAB", "Saint Ann's Bay", "세이트 앤 베이", "자메이카", "America/Jamaica"),
		new CityListClass_E("CLOMN", "Saint Cloud", "세인트 클라우드", "미국", "America/Chicago"),
		new CityListClass_E("GRG3", "Saint George", "세인트 조지", "미국", "America/Denver"),
		new CityListClass_E("GRGS", "Saint George's", "세인트 조지스", "그레나다", "America/Grenada"),
		new CityListClass_E("SAINT", "Saint Ives", "세인트이브스", "영국", "Europe/London"),
		new CityListClass_E("SNV", "Saint John", "세인트 존", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("SAINTJ", "Saint John's", "세인트 존스", "앤티가바부다", "America/Antigua"),
		new CityListClass_E("VLLGS", "Saint John's Village", "세인트 존스 빌리지", "몬세라트산", "America/Montserrat"),
		new CityListClass_E("JSPH", "Saint Joseph", "세인트 조셉", "미국", "America/Chicago"),
		new CityListClass_E("SANTJS", "Saint Joseph", "세인트 조셉", "도미니카", "America/Dominica"),
		new CityListClass_E("SLSMO", "Saint Louis", "세인트 루이스", "미국", "America/Chicago"),
		new CityListClass_E("SAINTP", "Saint Paul", "세인트 폴", "미국", "America/Chicago"),
		new CityListClass_E("STPGU", "Saint Petersburg", "세인트 피터즈버그", "미국", "America/New_York"),
		new CityListClass_E("LEN", "Saint Petersburg", "세인트피터즈버그", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("QNTN", "Saint Quentin", "생캉탱", "프랑스", "Europe/Paris"),
		new CityListClass_E("BRUC", "Saint-Brieuc", "생브리외", "프랑스", "Europe/Paris"),
		new CityListClass_E("SNTDN", "Saint-Denis", "생드니", "프랑스", "Indian/Reunion"),
		new CityListClass_E("DZR", "Saint-Dizier", "생대지에", "프랑스", "Europe/Paris"),
		new CityListClass_E("ETNN", "Saint-Etienne", "생테티엔", "프랑스", "Europe/Paris"),
		new CityListClass_E("GRGSS", "Saint-Georges", "세인트 조지스", "기아나", "America/Cayenne"),
		new CityListClass_E("LRNT", "Saint-Laurent du Maroni", "세인트 로랑 다다오", "기아나", "America/Cayenne"),
		new CityListClass_E("SAINTM", "Saint-Malo", "생말로", "프랑스", "Europe/Paris"),
		new CityListClass_E("SANTMR", "Saint-Marc", "세인트 마크", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("NZR", "Saint-Nazaire", "생나제르", "프랑스", "Europe/Paris"),
		new CityListClass_E("SNTA", "Sainte-Anne", "샹테안느", "과들루프섬", "America/Guadeloupe"),
		new CityListClass_E("SNTM", "Sainte-Marie", "샹테마리", "마르티니크", "America/Martinique"),
		new CityListClass_E("SPN", "Saipan", "사이판", "북마리아나 제도", "Pacific/Saipan"),
		new CityListClass_E("SAI", "Saitama", "사이타마", "일본", "Asia/Tokyo"),
		new CityListClass_E("SKN", "Sakaiminato", "사카이미나토", "일본", "Asia/Tokyo"),
		new CityListClass_E("SKRY1", "Sakarya", "사카리아", "터키", "Europe/Istanbul"),
		new CityListClass_E("SKT", "Sakata", "사카타", "일본", "Asia/Tokyo"),
		new CityListClass_E("SAKIA", "Sakiai", "사키아이", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("SLL", "Salalah", "살랄라", "오만", "Asia/Muscat"),
		new CityListClass_E("SLMNCA", "Salamanca", "살라망카", "스페인", "Europe/Madrid"),
		new CityListClass_E("INFNT", "Salas de los Infantes", "살라스 드로스 인판테스", "스페인", "Europe/Madrid"),
		new CityListClass_E("SBY", "Saldanha", "살다나", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("SALE", "Sale", "세일", "오스트레일리아", "Australia/Melbourne"),
		new CityListClass_E("SLM", "Salem", "살렘", "몬세라트산", "America/Montserrat"),
		new CityListClass_E("SALEM", "Salem", "세일럼", "미국", "America/New_York"),
		new CityListClass_E("SLMOR", "Salem", "세일럼", "미국", "America/Boise"),
		new CityListClass_E("SLGTR", "SalgOtarjan", "셔로터랸", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SLN1", "Salina", "살리나", "미국", "America/Chicago"),
		new CityListClass_E("SCZ", "Salina Cruz", "살리나 크루즈", "멕시코", "America/Mexico_City"),
		new CityListClass_E("SLNU", "Salinas", "샐리나스", "미국", "America/Los_Angeles"),
		new CityListClass_E("SLSBR", "Salisbury", "솔즈베리", "미국", "America/New_York"),
		new CityListClass_E("SLLT", "Salluit", "살루트", "캐나다", "America/Montreal"),
		new CityListClass_E("SLTLK", "Salt Lake City", "솔트 레이크 시티", "미국", "America/Denver"),
		new CityListClass_E("SALTA", "Salta", "살타", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("SLTLL", "Saltillo", "살티요", "멕시코", "America/Monterrey"),
		new CityListClass_E("SALTO", "Salto", "살토", "우루과이", "America/Montevideo"),
		new CityListClass_E("GUAIR", "Salto del Guaira", "살토 델 과이라", "파라과이", "America/Asuncion"),
		new CityListClass_E("SAL", "Salvador", "살바도르", "브라질", "America/Bahia"),
		new CityListClass_E("SLZBR", "Salzburg", "잘츠부르크", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("SMAR", "Samara", "사마라", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("11D20602", "Samcheok", "삼척", "대한민국", "Asia/Seoul"),
		new CityListClass_E("SMFY", "Samfya", "삼피아", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("SAMOS", "Samos", "사모스", "그리스", "Europe/Athens"),
		new CityListClass_E("SMN", "Samsun", "삼순", "터키", "Europe/Istanbul"),
		new CityListClass_E("SAGTX1", "San Angelo", "샌앤젤로", "미국", "America/Chicago"),
		new CityListClass_E("SNT", "San Antonio", "산 안토니오", "칠레", "America/Santiago"),
		new CityListClass_E("SATO", "San Antonio", "샌안토니오", "미국", "America/Chicago"),
		new CityListClass_E("SBRNRD", "San Bernardino", "샌버너디노", "미국", "America/Los_Angeles"),
		new CityListClass_E("CRLS1", "San Carlos", "산 카를로스", "니카라과", "America/Managua"),
		new CityListClass_E("CRLSS", "San Carlos", "산 카를로스", "베네수엘라", "America/Caracas"),
		new CityListClass_E("BRLCH", "San Carlos de Bariloche", "산 카를로스 데 바리로체", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("CLMNTS", "San Clemente", "산클레멘테", "스페인", "Europe/Madrid"),
		new CityListClass_E("CRSTB", "San Cristobal", "산 크리스토발", "베네수엘라", "America/Caracas"),
		new CityListClass_E("LAGUN", "San CristObal de La Laguna", "산크리스토발 데 라 라구나", "스페인", "Atlantic/Canary"),
		new CityListClass_E("SDI", "San Diego", "샌디에이고", "미국", "America/Los_Angeles"),
		new CityListClass_E("FLP", "San Felipe", "산 펠리페", "베네수엘라", "America/Caracas"),
		new CityListClass_E("PPL", "San Felipe de Puerto Plata", "산 펠리페 데 푸에르토 플라타", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("SANFR", "San Fernando", "산페르난도", "필리핀", "Asia/Manila"),
		new CityListClass_E("SFL", "San Fernando", "산페르난도", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass_E("FRNNDA", "San Fernando Apure", "산페르난도데아푸레", "베네수엘라", "America/Caracas"),
		new CityListClass_E("SFO", "San Francisco", "샌프란시스코", "미국", "America/Los_Angeles"),
		new CityListClass_E("FRNCSM", "San Francisco de Macoris", "산프란시스코 데 마코리스", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("ISDR", "San Isidro", "산이시드로", "코스타리카", "America/Costa_Rica"),
		new CityListClass_E("JOSE", "San Jose", "산호세", "코스타리카", "America/Costa_Rica"),
		new CityListClass_E("SJOS", "San Jose", "새너제이", "미국", "America/Los_Angeles"),
		new CityListClass_E("MAYOJ", "San Jose de Mayo", "산호세데마요", "우루과이", "America/Montevideo"),
		new CityListClass_E("SJUAN", "San Juan", "산후안", "미국", "America/Puerto_Rico"),
		new CityListClass_E("JUAN", "San Juan", "산후안", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("MRRS", "San Juan de los Morros", "산후안데로스모로스", "베네수엘라", "America/Caracas"),
		new CityListClass_E("SLRH", "San Lorenzo", "산로렌소", "온두라스", "America/Tegucigalpa"),
		new CityListClass_E("SANL", "San Luis Obispo", "샌루이스오비스포", "미국", "America/Los_Angeles"),
		new CityListClass_E("PTSL", "San Luis Potosi", "산루이스포토시", "멕시코", "America/Mexico_City"),
		new CityListClass_E("MRN", "San Marino", "산마리노", "San Marino", "Europe/San_Marino"),
		new CityListClass_E("VLDGL", "San Martin de Valdeiglesias", "산마르틴", "스페인", "Europe/Madrid"),
		new CityListClass_E("TCMN", "San Miguel de Tucuman", "산미겔데투쿠만", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("MGLT", "San Miguelito", "산미구엘리또", "파나마", "America/Panama"),
		new CityListClass_E("MQL", "San Miquel", "산미겔", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("PEDRO", "San Pedro", "산페드로", "파라과이", "America/Asuncion"),
		new CityListClass_E("SAQ", "San Pedro de Macoris", "산페드로데마코리스", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("PEDROS", "San Pedro Sula", "산페드로술라", "온두라스", "America/Tegucigalpa"),
		new CityListClass_E("QNTNS", "San Quintin", "산낀띤", "멕시코", "America/Mazatlan"),
		new CityListClass_E("RFLS", "San Rafael", "산 라파엘", "미국", "America/Los_Angeles"),
		new CityListClass_E("SLVDRS", "San Salvador", "산살바도르", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("SBSTNG", "San Sebastian de la Gomera", "산세바스찬 데라고메라", "스페인", "Atlantic/Canary"),
		new CityListClass_E("VCNT", "San Vicente", "산비센테", "칠레", "America/Santiago"),
		new CityListClass_E("SANVIC", "San Vicente", "산비센테", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("ALCNTV", "San Vicente de Alcantara", "산비센테 데 알칸타라", "스페인", "Europe/Madrid"),
		new CityListClass_E("SANAA", "Sanaa", "사나", "예멘", "Asia/Aden"),
		new CityListClass_E("11H20703", "Sancheong", "산청", "대한민국", "Asia/Seoul"),
		new CityListClass_E("SNN", "Sandakan", "산다칸", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("SANDE", "Sande", "산데", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("SNDMR", "Sandomierz", "산도미에슈", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("PDJ", "Sandy Point Town", "샌디포인트타운", "세인트 키츠 네비스", "America/St_Kitts"),
		new CityListClass_E("SPRNGS", "Sandy Springs", "샌디 스프링스", "미국", "America/New_York"),
		new CityListClass_E("11H10302", "Sangju", "상주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("GRNDS", "Sangre Grande", "상그레그란데", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass_E("SNKLQ", "Sanikiluaq", "사니킬루아크", "캐나다", "America/Pangnirtung"),
		new CityListClass_E("GLLN", "Sankt Gallen", "장크트갈렌", "스위스", "Europe/Zurich"),
		new CityListClass_E("PNGJ", "Sankt Johann im Pongau", "장크트 요한 임 퐁가우", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("MRTZS", "Sankt-Moritz", "장크트모리츠", "스위스", "Europe/Zurich"),
		new CityListClass_E("SNLRF", "Sanliurfa", "우르파", "터키", "Europe/Istanbul"),
		new CityListClass_E("BRRMD", "Sanlucar de Barrameda", "산루가르데바라메다", "스페인", "Europe/Madrid"),
//		new CityListClass_E("SANOK", "Sanok", "사노크", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SNSK", "Sanski Most", "산스키모스트", "보스니아-헤르체고비나", "Europe/Sarajevo"),
		new CityListClass_E("SANCA", "Santa Ana", "산타 아나", "미국", "America/Los_Angeles"),
		new CityListClass_E("SANTA", "Santa Ana", "산타아나", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("SBB", "Santa Barbara", "산타 바바라", "미국", "America/Los_Angeles"),
		new CityListClass_E("CLRT", "Santa Clarita", "산타 클라리타", "미국", "America/Los_Angeles"),
		new CityListClass_E("SANTO", "Santa Cruz", "산타쿠루즈", "포르투칼", "Atlantic/Madeira"),
		new CityListClass_E("SNZ", "Santa Cruz", "산타크루스", "미국", "America/Los_Angeles"),
		new CityListClass_E("SANTAC", "Santa Cruz", "산타크루스", "아루바", "America/Aruba"),
		new CityListClass_E("GAI", "Santa Cruz da Graciosa", "산타구루즈 다 그라시오사", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("SCLP", "Santa Cruz de la Palma", "산타구루즈데라팔마", "스페인", "Atlantic/Canary"),
		new CityListClass_E("SCDLS", "Santa Cruz de la Sierra", "산타크루스데라시에라", "볼리비아", "America/La_Paz"),
		new CityListClass_E("SCR", "Santa Cruz de Tenerife", "산타쿠루즈데테네리페", "스페인", "Atlantic/Canary"),
		new CityListClass_E("SNF", "Santa Fe", "산타페", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("SANTAF", "Santa Fe", "샌타페이", "미국", "America/Denver"),
		new CityListClass_E("SMR", "Santa Marta", "산타 마르타", "콜롬비아", "America/Bogota"),
		new CityListClass_E("SAMO", "Santa Monica", "산타 모니카", "미국", "America/Los_Angeles"),
		new CityListClass_E("OLLL", "Santa Olalla del Cala", "산타오랄라델칼라", "스페인", "Europe/Madrid"),
		new CityListClass_E("SROU", "Santa Rosa", "산타 로사", "미국", "America/Los_Angeles"),
		new CityListClass_E("COPAN", "Santa Rosa de Copan", "산타 로사 데 코판", "온두라스", "America/Tegucigalpa"),
		new CityListClass_E("SNR", "Santa Rosalia", "산타 로살리아", "멕시코", "America/Mazatlan"),
		new CityListClass_E("STR", "Santander", "산탄데르", "스페인", "Europe/Madrid"),
		new CityListClass_E("SNTAR", "Santarem", "산타렘", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("STGC", "Santiago", "산티아고", "칠레", "America/Santiago"),
		new CityListClass_E("SNTG", "Santiago", "산티아고", "파나마", "America/Panama"),
		new CityListClass_E("SNTGC", "Santiago de Cacem", "산티아고데카셈", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("CMPST", "Santiago de Compostela", "산티아고데콤포스텔라", "스페인", "Europe/Madrid"),
		new CityListClass_E("CBLLR", "Santiago de los Caballeros", "산티아고 데 로스 카바예로스", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("ANDRES", "Santo Andre", "산투 안드레", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("SAF", "Santo Domingo", "산토 도 밍고", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass_E("CLRDS", "Santo Domingo de los Colorados", "산토 도밍고 드 로스 콜로라도", "에콰도르", "America/Guayaquil"),
//		new CityListClass_E("STS", "Santos", "산투스", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("CMPS", "Sao Jose dos Campos", "상 조세 도스 캄포스", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("SLB", "Sao Luis", "상루이스", "브라질", "America/Bahia"),
		new CityListClass_E("PAULO", "Sao Paulo", "상파울루", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("SOT", "Sao Tome", "사오톰", "상투메프린시페", "Africa/Sao_Tome"),
		new CityListClass_E("VCNTS", "Sao Vicente", "상베센테", "포르투칼", "Atlantic/Madeira"),
		new CityListClass_E("SAPP", "Sapporo", "삿포로", "일본", "Asia/Tokyo"),
		new CityListClass_E("SRJV", "Sarajevo", "사라예보", "보스니아-헤르체고비나", "Europe/Sarajevo"),
		new CityListClass_E("SRNSK", "Saransk", "사란스크", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("SRST", "Sarasota", "새러소타", "미국", "America/New_York"),
		new CityListClass_E("SRTG", "Saratoga Springs", "새러토가 스프링스", "미국", "America/New_York"),
		new CityListClass_E("SRTV", "Saratov", "사라토브", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("SRNN", "Sarnen", "자르넨", "스위스", "Europe/Zurich"),
		new CityListClass_E("SASE", "Sasebo", "사세보", "일본", "Asia/Tokyo"),
		new CityListClass_E("SSKTN", "Saskatoon", "새스커툰", "캐나다", "America/Regina"),
		new CityListClass_E("SSSR", "Sassari", "사사리", "이탈리아", "Europe/Rome"),
		new CityListClass_E("STRLJ", "Satoraljaujhely", "샤토럴려우이헤이", "헝가리", "Europe/Budapest"),
		new CityListClass_E("MARES", "Satu Mare", "사투마레", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("SAUE", "Saue", "사우에", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("SAUL", "Saul", "사울", "기아나", "America/Cayenne"),
		new CityListClass_E("SSM", "Sault Ste. Marie", "수세인트마리", "캐나다", "America/Toronto"),
		new CityListClass_E("STRS", "Sauteurs", "소퇴르", "그레나다", "America/Grenada"),
		new CityListClass_E("SVA", "Savannah", "서배너", "미국", "America/New_York"),
		new CityListClass_E("SVNK", "savnik", "사브니크", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("SCAR", "Scarborough", "스카버러", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass_E("SCHN1", "Schaan", "샨", "리히텐슈타인", "Europe/Vaduz"),
		new CityListClass_E("SCHFF", "Schaffhausen", "샤프하우젠", "스위스", "Europe/Zurich"),
		new CityListClass_E("SCHMB", "Schaumburg", "샤움버그", "미국", "America/Chicago"),
		new CityListClass_E("SCHBB", "Scheibbs", "슈아이브스", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("SCHNC", "Schenectady", "스케넥터디", "미국", "America/New_York"),
		new CityListClass_E("SCHWR", "Schwerin", "슈베린", "독일", "Europe/Berlin"),
		new CityListClass_E("SCHWY", "Schwyz", "슈비츠", "스위스", "Europe/Zurich"),
		new CityListClass_E("SCTTSD", "Scottsdale", "스코츠데일", "미국", "America/Denver"),
		new CityListClass_E("SCRNT", "Scranton", "스크랜턴", "미국", "America/New_York"),
		new CityListClass_E("SEA", "Seattle", "시애틀", "미국", "America/Los_Angeles"),
		new CityListClass_E("SGV", "Segovia", "세고비아", "스페인", "Europe/Madrid"),
		new CityListClass_E("SLFSS", "Selfoss", "셀포스", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass_E("PHKW", "Selibe-Phikwe", "세리베 피크베", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("SEM", "Semarang", "세마랑", "인도네시아", "Asia/Jakarta"),
		new CityListClass_E("SNNG", "Senanga", "세난가", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("SEN", "Sendai", "센다이", "일본", "Asia/Tokyo"),
		new CityListClass_E("SNKL", "Senekal", "세네칼", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("SENJ", "Senj", "센", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("SNSNT", "Sensuntepeque", "센순테페케", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("11C20202", "Seocheon", "서천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11G00401", "Seogwipo", "서귀포", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11H10605", "Seongju", "성주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11B20605", "Seongnam", "성남", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11G00302", "Seongpanak", "성판악", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11G00101", "Seongsan", "성산", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11C20101", "Seosan", "서산", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11B10101", "Seoul", "서울", "대한민국", "Asia/Seoul"),
		new CityListClass_E("KRJNS", "SepOlno Krajenskie", "세프올노 크라젠스키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SIL", "Sept-Iles", "세틸", "캐나다", "America/Montreal"),
		new CityListClass_E("SRMBN", "Seremban", "세렘반", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("SRNG", "Seronga", "세롱가", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("SRW", "Serowe", "세로베", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("SERPA", "Serpa", "세르파", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("SRRS", "Serres", "세라이", "그리스", "Europe/Athens"),
		new CityListClass_E("SERTA", "Serta", "세르타", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("SSFNT", "Sesfontein", "세스폰테인", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("SSHK", "Sesheke", "세쉐케", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("SSVT", "Sesvete", "자그레브-외곽", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("STCSS", "Setcases", "셋케이시스", "스페인", "Europe/Madrid"),
		new CityListClass_E("SEV", "Sevilla", "세비야", "스페인", "Europe/Madrid"),
		new CityListClass_E("SZN", "SeZana", "세자나", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("GHRGH", "Sfantu Gheorghe", "스핀두게오르게", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("SHKW", "Shakawe", "샤카베", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("SHA", "Shanghai", "상하이", "중국", "Asia/Shanghai"),
		new CityListClass_E("SHJ", "Sharjah", "샤르자", "아랍에미리트", "Asia/Dubai"),
		new CityListClass_E("SHYKH", "Sharm ash Shaykh", "샴 엘 쉐이크", "이집트", "Africa/Cairo"),
		new CityListClass_E("SHWN", "Shawnee", "쇼니", "미국", "America/Chicago"),
		new CityListClass_E("SHBYG", "Sheboygan", "셰보이건", "미국", "America/Chicago"),
//		new CityListClass_E("SHFFL", "Sheffield", "쉐필드", "영국", "Europe/London"),
		new CityListClass_E("SHRBR", "Sherbrooke", "셔브룩", "캐나다", "America/Montreal"),
		new CityListClass_E("SHS", "Shimonoseki", "시모노세키", "일본", "Asia/Tokyo"),
		new CityListClass_E("SHNJ", "Shinjou", "신조우", "일본", "Asia/Tokyo"),
		new CityListClass_E("SHNKB", "Shinkiba", "신키바", "일본", "Asia/Tokyo"),
		new CityListClass_E("SHIMK", "Shionomisaki", "시오노미사키", "일본", "Asia/Tokyo"),
		new CityListClass_E("SROISH", "Shiroishi", "시로이시", "일본", "Asia/Tokyo"),
		new CityListClass_E("SHI", "Shizuoka", "시즈오카", "일본", "Asia/Tokyo"),
//		new CityListClass_E("SHKDR", "Shkoder", "슈코더르", "알바니아", "Europe/Tirane"),
		new CityListClass_E("SHOBR", "Shoubara", "쇼우바라", "일본", "Asia/Tokyo"),
		new CityListClass_E("SHVLA", "Shreveport", "슈리브포트", "미국", "America/Chicago"),
		new CityListClass_E("SHRWS", "Shrewsbury", "슈루즈버리", "영국", "Europe/London"),
		new CityListClass_E("SHMN", "Shumen", "슈멘", "불가리아", "Europe/Sofia"),
		new CityListClass_E("RACHA", "Si Racha", "시라차", "태국", "Asia/Bangkok"),
		new CityListClass_E("SIAUL", "Siauliai", "시아울리아이", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("SBN", "sibenik", "시베니크", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("SIBIU", "Sibiu", "시비우", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("SIBU", "Sibu", "시부", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass_E("SIGN", "Siegen", "지겐", "독일", "Europe/Berlin"),
		new CityListClass_E("SIENA", "Siena", "시에나", "이탈리아", "Europe/Rome"),
		new CityListClass_E("SGNZ", "Siguenza", "시구엔자", "스페인", "Europe/Madrid"),
		new CityListClass_E("11B20202", "Siheung", "시흥", "대한민국", "Asia/Seoul"),
		new CityListClass_E("SIIRT", "Siirt", "시이르트", "터키", "Europe/Istanbul"),
		new CityListClass_E("SIKEA", "Sikea", "시키아", "그리스", "Europe/Athens"),
		new CityListClass_E("SLSTR", "Silistra", "실리스트라", "불가리아", "Europe/Sofia"),
		new CityListClass_E("SLKBR", "Silkeborg", "실게보르", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("SLLM", "Sillamae", "실라마에", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("SLT1", "Silute", "실루트", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("SPRNG1", "Silver Spring", "실버 스프링", "미국", "America/New_York"),
		new CityListClass_E("SIMI", "Simi", "시미", "그리스", "Europe/Athens"),
		new CityListClass_E("SIVLLY", "Simi Valley", "시미 밸리", "미국", "America/Los_Angeles"),
		new CityListClass_E("21F20803", "Sinan", "신안", "대한민국", "Asia/Seoul"),
		new CityListClass_E("SINDI", "Sindi", "신디", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("CDS", "Sines", "시네스", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("DANJ", "Singapore", "싱가폴", "싱가폴", "Asia/Singapore"),
		new CityListClass_E("NCL", "Sint Nicolaas", "신트 니콜라스", "아루바", "America/Aruba"),
		new CityListClass_E("NKLS", "Sint-Niklaas", "신트니클라스", "벨기에", "Europe/Brussels"),
		new CityListClass_E("SFK", "SiOfok", "시오포크", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SION1", "Sion", "시옹", "스위스", "Europe/Zurich"),
		new CityListClass_E("SIOUX", "Sioux City", "수 시티", "미국", "America/Chicago"),
		new CityListClass_E("SIOUXF", "Sioux Falls", "수 폴스", "미국", "America/Chicago"),
		new CityListClass_E("SPR1", "Siparia", "시파리아", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass_E("SRCS", "Siracusa", "시라쿠사", "이탈리아", "Europe/Rome"),
		new CityListClass_E("SRKW", "Sirakawa", "시라카와", "일본", "Asia/Tokyo"),
		new CityListClass_E("SISAK", "Sisak", "시사크", "크로아티아", "Europe/Zagreb"),
//		new CityListClass_E("STK1", "Siteki", "시테키", "스와질란드", "Africa/Mbabane"),
		new CityListClass_E("SITT", "Sitrah", "시트라", "바레인", "Asia/Bahrain"),
		new CityListClass_E("SIVAS", "Sivas", "시바스", "터키", "Europe/Istanbul"),
		new CityListClass_E("SIWAH", "Siwah", "시와", "이집트", "Africa/Cairo"),
		new CityListClass_E("SKG", "Skagen", "스카겐", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("SKRZY", "Skarzysko-Kamienna", "카미엔나", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SKIEN", "Skien", "시엔", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("SKPJ", "Skopje", "스코페", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("SLTNA", "Slatina", "슬라티나", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("SLTN", "Slatina", "슬라티나", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("SLVNS", "Slavonski Brod", "슬라폰스키브로트", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("SLIGO", "Sligo", "슬라이고", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("SLVN", "Sliven", "슬리벤", "불가리아", "Europe/Sofia"),
		new CityListClass_E("SLBZ", "Slobozia", "슬로보지아", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("SLGH", "Slough", "슬로", "영국", "Europe/London"),
		new CityListClass_E("SLVNJ", "Slovenj Gradec", "글로베니그라데츠", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass_E("SMDRV", "Smederevo", "스메데레보", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("SMTHR", "Smithers", "스미더스", "캐나다", "America/Vancouver"),
		new CityListClass_E("SMTHT", "Smithtown", "스미스타운", "미국", "America/New_York"),
		new CityListClass_E("SMLNS", "Smolensk", "스몰렌스크", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("SMLYN", "Smolyan", "스몰랸", "불가리아", "Europe/Sofia"),
		new CityListClass_E("SOFIA", "Sofia", "소피아", "불가리아", "Europe/Sofia"),
		new CityListClass_E("11D20401", "Sokcho", "속초", "대한민국", "Asia/Seoul"),
		new CityListClass_E("SKLV", "Sokolov", "스콜로프", "체코", "Europe/Prague"),
		new CityListClass_E("SKRK", "SokOrka", "소카", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SLTHR", "Solothurn", "졸로투른", "스위스", "Europe/Zurich"),
		new CityListClass_E("SLSN", "Solsona", "솔소나", "스페인", "Europe/Madrid"),
		new CityListClass_E("SLWZ", "Solwezi", "솔베지", "잠비아", "Africa/Lusaka"),
		new CityListClass_E("SMMRD", "Sommerda", "솜머다", "독일", "Europe/Berlin"),
		new CityListClass_E("SDB", "Sonderborg", "쇠네르보르", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("SNDR", "Sondrio", "소드리오", "이탈리아", "Europe/Rome"),
		new CityListClass_E("SNSNT1", "Sonsonate", "손소나테", "엘살바도르", "America/El_Salvador"),
		new CityListClass_E("SPRN1", "Sopron", "쇼프론", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SORIA", "Soria", "소리아", "스페인", "Europe/Madrid"),
		new CityListClass_E("SORO1", "Soro", "로뢰", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("SRCB", "Sorocaba", "소루카바", "브라질", "America/Sao_Paulo"),
		new CityListClass_E("SFLN", "Souflion", "소프리온", "그리스", "Europe/Athens"),
		new CityListClass_E("SFRR", "Soufriere", "수프리에르", "세인트루시아", "America/St_Lucia"),
		new CityListClass_E("SBEND", "South Bend", "사우스 벤드", "미국", "America/Indianapolis"),
		new CityListClass_E("TAHOE", "South Lake Tahoe", "사우스 레이크 타호", "미국", "America/Los_Angeles"),
		new CityListClass_E("STHMP", "Southampton", "사우샘프턴", "미국", "America/New_York"),
		new CityListClass_E("SOU", "Southampton", "사우스햄턴", "영국", "Europe/London"),
//		new CityListClass_E("STHND", "Southend-on-Sea", "사우스엔드온시", "영국", "Europe/London"),
		new CityListClass_E("SOWE", "Soweto", "소웨토", "남아프리카공화국", "Africa/Johannesburg"),
//		new CityListClass_E("SPA1", "Spa", "스파", "벨기에", "Europe/Brussels"),
		new CityListClass_E("SPRTN", "Spartanburg", "스파턴버그", "미국", "America/New_York"),
		new CityListClass_E("SPGHT", "Speightstown", "스페이츠 타운", "바베이도스", "America/Barbados"),
		new CityListClass_E("SPTTL", "Spittal an der Drau", "슈피탈드라우", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("SPL", "Split", "스플리트", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("SPKN", "Spokane", "스포캔", "미국", "America/Los_Angeles"),
		new CityListClass_E("SPRNG2", "Springdale", "스프링데일", "미국", "America/Chicago"),
		new CityListClass_E("SPGMA", "Springfield", "스프링필드-매사추세츠", "미국", "America/New_York"),
		new CityListClass_E("SPGMO", "Springfield", "스프링필드-미주리", "미국", "America/Chicago"),
		new CityListClass_E("SPNGF", "Springfield", "스프링필드-오하이오", "미국", "America/New_York"),
		new CityListClass_E("SPNGA", "Springfield", "스프링필드-일리노이", "미국", "America/Chicago"),
		new CityListClass_E("SRWN1", "Srawno", "스라우노", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("JYWRD", "Sri Jayawardanapura Kotte", "스리자야와르데네푸라코테", "스리랑카", "Asia/Colombo"),
		new CityListClass_E("SRNGR", "Srinagar", "스리나가르", "인도", "Asia/Calcutta"),
		new CityListClass_E("SRPSK", "Srupsk", "슬럽스크", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("CTHRNS", "St. Catharines", "세인트 캐서린스", "캐나다", "America/Toronto"),
		new CityListClass_E("SJF", "St. John's", "세인트 존스", "캐나다", "America/St_Johns"),
		new CityListClass_E("PLTNS", "St. Polten", "장크트푈텐", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("STLW", "Stalowa Wola", "스탈로아볼라", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("STMFR", "Stamford", "스탬퍼드", "미국", "America/New_York"),
//		new CityListClass_E("ZGR", "Stara Zagora", "스타라자고라", "불가리아", "Europe/Sofia"),
		new CityListClass_E("SZCZC", "Stargard Szczecinski", "스타르가르트슈체친스키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("STRGR", "Starogard Gdanski", "스나로가드구덴스키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("CLLG", "State College", "스테이트칼리지", "미국", "America/New_York"),
		new CityListClass_E("STTSB", "Statesboro", "스테이츠버러", "미국", "America/New_York"),
		new CityListClass_E("STNTN", "Staunton", "스톤턴", "미국", "America/New_York"),
		new CityListClass_E("SVR", "Stavanger", "스타방게르", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("STWRP", "Stawropol", "스타브로폴", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("STEGE", "Stege", "스티지", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("STNKJ", "Steinkjer", "스테인헤르", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("STNKP", "Steinkopf", "슈타인코프", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("STRHT", "Sterling Heights", "스털링 하이츠", "미국", "America/Detroit"),
		new CityListClass_E("STYNB", "Steynburg", "스텐버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("STIP", "stip", "스팁", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("STRLN", "Stirling", "스털링", "영국", "Europe/London"),
		new CityListClass_E("SDN", "Stockholm", "스톡홀름", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("STO", "Stockton", "스톡턴", "미국", "America/Los_Angeles"),
		new CityListClass_E("TRENT", "Stoke-on-Trent", "스노크온트렌트", "영국", "Europe/London"),
		new CityListClass_E("SRY", "Stornoway", "스토너웨이", "영국", "Europe/London"),
//		new CityListClass_E("STRMN", "Storuman", "흐토루만", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("STRHN", "Strahan", "스트라한", "오스트레일리아", "Australia/Hobart"),
		new CityListClass_E("STRKN", "Strakonice", "스트라코니스", "체코", "Europe/Prague"),
		new CityListClass_E("STRLS", "Stralsund", "슈트랄준트", "독일", "Europe/Berlin"),
		new CityListClass_E("STRBG", "Strasbourg", "스트라스부르", "프랑스", "Europe/Paris"),
		new CityListClass_E("STRMS", "Stromsund", "스트롬순드", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("STRG", "Struga", "스투르가", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("STRMC", "Strumica", "스투루미차", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("STRYD", "Strydenburg", "스트리덴버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("STRZG", "Strzegom", "스트셰곰", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("OPLSK", "Strzelce Opolskie", "스트셸체오폴스키에", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("STRZL", "Strzelin", "스트셸린", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("STTGT", "Stuttgart", "슈트트가르트", "독일", "Europe/Berlin"),
		new CityListClass_E("SBTC", "Subotica", "수보티차", "세르비아", "Europe/Belgrade"),
		new CityListClass_E("SCVA", "Suceava", "수체아바", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("SCHDN", "SuchedniOw", "수체드니오", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SUCRE", "Sucre", "수크레", "볼리비아", "America/La_Paz"),
		new CityListClass_E("SUE", "Suez", "수에즈", "이집트", "Africa/Cairo"),
		new CityListClass_E("SUH", "Suhar", "수하르", "오만", "Asia/Muscat"),
		new CityListClass_E("SUHL", "Suhl", "줄", "독일", "Europe/Berlin"),
		new CityListClass_E("SKM", "Sukumo", "스쿠모", "일본", "Asia/Tokyo"),
		new CityListClass_E("SLCN", "Sulecin", "줄레친", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SLTNB", "Sultanbeyli", "슐탄베일리", "터키", "Europe/Istanbul"),
		new CityListClass_E("SMS", "Summerside", "섬머사이드", "캐나다", "America/Goose_Bay"),
		new CityListClass_E("SUMOT", "Sumoto", "스모토", "일본", "Asia/Tokyo"),
		new CityListClass_E("11F10403", "Sunchang", "순창", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11F20405", "Suncheon", "순천", "대한민국", "Asia/Seoul"),
		new CityListClass_E("11F20603", "Suncheon", "순천(주암)", "대한민국", "Asia/Seoul"),
		new CityListClass_E("SDV", "Sundsvall", "순스발", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("SNGPK", "Sungaipakning", "선가이파크닝", "인도네시아", "Asia/Jakarta"),
		new CityListClass_E("SNNDL", "Sunndalsora", "순달소라", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("SVL", "Sunnyvale", "서니베일", "미국", "America/Los_Angeles"),
		new CityListClass_E("SNSHN", "Sunshine Coast", "선샤인 코스트", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass_E("SUR1", "Sur", "수르", "오만", "Asia/Muscat"),
		new CityListClass_E("SRB", "Surabaya", "수라바야", "인도네시아", "Asia/Jakarta"),
		new CityListClass_E("SUT", "Surat Thani", "수라트타니", "태국", "Asia/Bangkok"),
		new CityListClass_E("SRGT", "Surgut", "수르구트", "러시아 연방 국가", "Asia/Yekaterinburg"),
		new CityListClass_E("SSC", "Susice", "수지스", "체코", "Europe/Prague"),
		new CityListClass_E("STHRL", "Sutherland", "서덜랜드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("STTS", "Suttsu", "슷츠", "일본", "Asia/Tokyo"),
		new CityListClass_E("SUV", "Suva", "수바", "피지", "Pacific/Fiji"),
		new CityListClass_E("SUWA", "Suwa", "스와", "일본", "Asia/Tokyo"),
		new CityListClass_E("SWRK", "Suwarki", "스왈키", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("11B20601", "Suwon", "수원", "대한민국", "Asia/Seoul"),
		new CityListClass_E("NKL1", "Sveti Nikole", "스베티니콜", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("SVLVR", "Svolvar", "스볼베르", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("SWKPM", "Swakopmund", "스와콥문드", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("SWDNC", "Swidnica", "시비드니차", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SWDNK", "Swidnik", "핀드닉", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("SWDWN", "Swidwin", "스위드윈", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SWBDZ", "Swiebodzin", "스위보진", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SWC", "Swiecie", "스위치", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("CRRNTS", "Swift Current", "스위프트 커런트", "캐나다", "America/Regina"),
		new CityListClass_E("SWNDN", "Swindon", "스윈던", "영국", "Europe/London"),
		new CityListClass_E("SDY", "Sydney", "시드니", "오스트레일리아", "Australia/Sydney"),
		new CityListClass_E("SYD", "Sydney", "시드니", "캐나다", "America/Halifax"),
		new CityListClass_E("SYKTY", "Syktyvkar", "식티프카르", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("SYRCS", "Syracuse", "시러큐스", "미국", "America/New_York"),
		new CityListClass_E("SZCZC1", "Szczecin", "슈체친", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SZCZY", "Szczytno", "스키노", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("SZGD", "Szeged", "슈제츠트", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SZKSF", "Szekesfehervar", "세케슈페헤르바르", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SZKSZ", "Szekszard", "체크자드", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SZNTS", "Szentes", "센테시", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SZLNK", "Szolnok", "솔노크", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SZMBT", "Szombathely", "솜보텔리", "헝가리", "Europe/Budapest"),
		new CityListClass_E("SZPRT", "Szprotawa", "슈프로타바", "폴란드", "Europe/Warsaw"),

	};
}
