package com.weathernews.Weather;

class SA {
	public final static CityListClass[] sa = new CityListClass[] {
		new CityListClass("SAG", "사가", "일본", "Asia/Tokyo"),
		new CityListClass("SGNY", "사그네이", "캐나다", "America/Montreal"),
		new CityListClass("SANAA", "사나", "예멘", "Asia/Aden"),
//		new CityListClass("SANOK", "사노크", "폴란드", "Europe/Warsaw"),
		new CityListClass("SNKLQ", "사니킬루아크", "캐나다", "America/Pangnirtung"),
		new CityListClass("ZRGZ", "사라고사", "스페인", "Europe/Madrid"),
		new CityListClass("SRJV", "사라예보", "보스니아-헤르체고비나", "Europe/Sarajevo"),
		new CityListClass("SRTV", "사라토브", "러시아", "Europe/Moscow"),
		new CityListClass("SRNSK", "사란스크", "러시아", "Asia/Yekaterinburg"),
		new CityListClass("SMAR", "사마라", "러시아", "Asia/Yekaterinburg"),
		new CityListClass("ZMR1", "사모라", "스페인", "Europe/Madrid"),
		new CityListClass("SAMOS", "사모스", "그리스", "Europe/Athens"),
		new CityListClass("SBNT", "사바네타", "아루바", "America/Aruba"),
		new CityListClass("SBDLL", "사바델", "스페인", "Europe/Madrid"),
		new CityListClass("SVNK", "사브니크", "세르비아", "Europe/Belgrade"),
		new CityListClass("SSSR", "사사리", "이탈리아", "Europe/Rome"),
		new CityListClass("SASE", "사세보", "일본", "Asia/Tokyo"),
		new CityListClass("SOT", "사오톰", "상투메프린시페", "Africa/Sao_Tome"),
		new CityListClass("STHMP", "사우샘프턴", "미국", "America/New_York"),
		new CityListClass("TAHOE", "사우스 레이크 타호", "미국", "America/Los_Angeles"),
		new CityListClass("SBEND", "사우스 벤드", "미국", "America/Indianapolis"),
//		new CityListClass("STHND", "사우스엔드온시", "영국", "Europe/London"),
		new CityListClass("SOU", "사우스햄턴", "영국", "Europe/London"),
		new CityListClass("SAUE", "사우에", "에스토니아", "Europe/Tallinn"),
		new CityListClass("THSND", "사우전드 오크스", "미국", "America/Los_Angeles"),
		new CityListClass("SAUL", "사울", "기아나", "America/Cayenne"),
		new CityListClass("SAIGOU", "사이고우", "일본", "Asia/Tokyo"),
		new CityListClass("SAE", "사이키", "일본", "Asia/Tokyo"),
		new CityListClass("SAI", "사이타마", "일본", "Asia/Tokyo"),
		new CityListClass("SPN", "사이판", "북마리아나 제도", "Pacific/Saipan"),
		new CityListClass("11H20402", "사천", "대한민국", "Asia/Seoul"),
		new CityListClass("SKRY1", "사카리아", "터키", "Europe/Istanbul"),
		new CityListClass("SKN", "사카이미나토", "일본", "Asia/Tokyo"),
		new CityListClass("SKT", "사카타", "일본", "Asia/Tokyo"),
		new CityListClass("ZCTCS", "사카테카스", "멕시코", "America/Merida"),
		new CityListClass("SAKIA", "사키아이", "리투아니아", "Europe/Vilnius"),
		new CityListClass("MARES", "사투마레", "루마니아", "Europe/Bucharest"),
		new CityListClass("ZAFRA", "사프라", "스페인", "Europe/Madrid"),
		new CityListClass("SHGN", "사하군", "스페인", "Europe/Madrid"),
		new CityListClass("HRBRS", "삭스 하버", "캐나다", "America/Yellowknife"),
		new CityListClass("RFLS", "산 라파엘", "미국", "America/Los_Angeles"),
		new CityListClass("SNT", "산 안토니오", "칠레", "America/Santiago"),
		new CityListClass("CRLS1", "산 카를로스", "니카라과", "America/Managua"),
		new CityListClass("CRLSS", "산 카를로스", "베네수엘라", "America/Caracas"),
		new CityListClass("BRLCH", "산 카를로스 데 바리로체", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("CRSTB", "산 크리스토발", "베네수엘라", "America/Caracas"),
		new CityListClass("FLP", "산 펠리페", "베네수엘라", "America/Caracas"),
		new CityListClass("PPL", "산 펠리페 데 푸에르토 플라타", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass("QNTNS", "산낀띤", "멕시코", "America/Mazatlan"),
		new CityListClass("SNN", "산다칸", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("SANDE", "산데", "노르웨이", "Europe/Oslo"),
		new CityListClass("SNDMR", "산도미에슈", "폴란드", "Europe/Warsaw"),
		new CityListClass("SLRH", "산로렌소", "온두라스", "America/Tegucigalpa"),
		new CityListClass("BRRMD", "산루가르데바라메다", "스페인", "Europe/Madrid"),
		new CityListClass("PTSL", "산루이스포토시", "멕시코", "America/Mexico_City"),
		new CityListClass("VLDGL", "산마르틴", "스페인", "Europe/Madrid"),
		new CityListClass("MRN", "산마리노", "San Marino", "Europe/San_Marino"),
		new CityListClass("MQL", "산미겔", "엘살바도르", "America/El_Salvador"),
		new CityListClass("TCMN", "산미겔데투쿠만", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("MGLT", "산미구엘리또", "파나마", "America/Panama"),
		new CityListClass("VCNT", "산비센테", "칠레", "America/Santiago"),
		new CityListClass("SANVIC", "산비센테", "엘살바도르", "America/El_Salvador"),
		new CityListClass("ALCNTV", "산비센테 데 알칸타라", "스페인", "Europe/Madrid"),
		new CityListClass("SLVDRS", "산살바도르", "엘살바도르", "America/El_Salvador"),
		new CityListClass("SBSTNG", "산세바스찬 데라고메라", "스페인", "Atlantic/Canary"),
		new CityListClass("SNSK", "산스키모스트", "보스니아-헤르체고비나", "Europe/Sarajevo"),
		new CityListClass("ISDR", "산이시드로", "코스타리카", "America/Costa_Rica"),
		new CityListClass("11H20703", "산청", "대한민국", "Asia/Seoul"),
		new CityListClass("LAGUN", "산크리스토발 데 라 라구나", "스페인", "Atlantic/Canary"),
		new CityListClass("CLMNTS", "산클레멘테", "스페인", "Europe/Madrid"),
		new CityListClass("SROU", "산타 로사", "미국", "America/Los_Angeles"),
		new CityListClass("COPAN", "산타 로사 데 코판", "온두라스", "America/Tegucigalpa"),
		new CityListClass("SNR", "산타 로살리아", "멕시코", "America/Mazatlan"),
		new CityListClass("SMR", "산타 마르타", "콜롬비아", "America/Bogota"),
		new CityListClass("SAMO", "산타 모니카", "미국", "America/Los_Angeles"),
		new CityListClass("SBB", "산타 바바라", "미국", "America/Los_Angeles"),
		new CityListClass("SANCA", "산타 아나", "미국", "America/Los_Angeles"),
		new CityListClass("CLRT", "산타 클라리타", "미국", "America/Los_Angeles"),
		new CityListClass("GAI", "산타구루즈 다 그라시오사", "포르투칼", "Atlantic/Azores"),
		new CityListClass("SCLP", "산타구루즈데라팔마", "스페인", "Atlantic/Canary"),
		new CityListClass("SNTAR", "산타렘", "포르투칼", "Europe/Lisbon"),
		new CityListClass("SANTA", "산타아나", "엘살바도르", "America/El_Salvador"),
		new CityListClass("OLLL", "산타오랄라델칼라", "스페인", "Europe/Madrid"),
		new CityListClass("SANTO", "산타쿠루즈", "포르투칼", "Atlantic/Madeira"),
		new CityListClass("SCR", "산타쿠루즈데테네리페", "스페인", "Atlantic/Canary"),
		new CityListClass("SNZ", "산타크루스", "미국", "America/Los_Angeles"),
		new CityListClass("SANTAC", "산타크루스", "아루바", "America/Aruba"),
		new CityListClass("SCDLS", "산타크루스데라시에라", "볼리비아", "America/La_Paz"),
		new CityListClass("SNF", "산타페", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("STR", "산탄데르", "스페인", "Europe/Madrid"),
		new CityListClass("SAF", "산토 도 밍고", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass("CLRDS", "산토 도밍고 드 로스 콜로라도", "에콰도르", "America/Guayaquil"),
		new CityListClass("ANDRES", "산투 안드레", "브라질", "America/Sao_Paulo"),
//		new CityListClass("STS", "산투스", "브라질", "America/Sao_Paulo"),
		new CityListClass("STGC", "산티아고", "칠레", "America/Santiago"),
		new CityListClass("SNTG", "산티아고", "파나마", "America/Panama"),
		new CityListClass("CBLLR", "산티아고 데 로스 카바예로스", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass("SNTGC", "산티아고데카셈", "포르투칼", "Europe/Lisbon"),
		new CityListClass("CMPST", "산티아고데콤포스텔라", "스페인", "Europe/Madrid"),
		new CityListClass("PEDRO", "산페드로", "파라과이", "America/Asuncion"),
		new CityListClass("SAQ", "산페드로데마코리스", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass("PEDROS", "산페드로술라", "온두라스", "America/Tegucigalpa"),
		new CityListClass("SANFR", "산페르난도", "필리핀", "Asia/Manila"),
		new CityListClass("SFL", "산페르난도", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass("FRNNDA", "산페르난도데아푸레", "베네수엘라", "America/Caracas"),
		new CityListClass("FRNCSM", "산프란시스코 데 마코리스", "도미나카공화국", "America/Santo_Domingo"),
		new CityListClass("JOSE", "산호세", "코스타리카", "America/Costa_Rica"),
		new CityListClass("MAYOJ", "산호세데마요", "우루과이", "America/Montevideo"),
		new CityListClass("SJUAN", "산후안", "미국", "America/Puerto_Rico"),
		new CityListClass("JUAN", "산후안", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("MRRS", "산후안데로스모로스", "베네수엘라", "America/Caracas"),
		new CityListClass("SBY", "살다나", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SLMNCA", "살라망카", "스페인", "Europe/Madrid"),
		new CityListClass("INFNT", "살라스 드로스 인판테스", "스페인", "Europe/Madrid"),
		new CityListClass("SLL", "살랄라", "오만", "Asia/Muscat"),
		new CityListClass("SLM", "살렘", "몬세라트산", "America/Montserrat"),
		new CityListClass("SLLT", "살루트", "캐나다", "America/Montreal"),
		new CityListClass("SLN1", "살리나", "미국", "America/Chicago"),
		new CityListClass("SCZ", "살리나 크루즈", "멕시코", "America/Mexico_City"),
		new CityListClass("SAL", "살바도르", "브라질", "America/Bahia"),
		new CityListClass("SALTA", "살타", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass("SALTO", "살토", "우루과이", "America/Montevideo"),
		new CityListClass("GUAIR", "살토 델 과이라", "파라과이", "America/Asuncion"),
		new CityListClass("SLTLL", "살티요", "멕시코", "America/Monterrey"),
		new CityListClass("ZAM", "삼보앙가", "필리핀", "Asia/Manila"),
		new CityListClass("ZAMC", "삼보앙가시티", "필리핀", "Asia/Manila"),
		new CityListClass("SMN", "삼순", "터키", "Europe/Istanbul"),
		new CityListClass("11D20602", "삼척", "대한민국", "Asia/Seoul"),
		new CityListClass("SMFY", "삼피아", "잠비아", "Africa/Lusaka"),
		new CityListClass("SAPP", "삿포로", "일본", "Asia/Tokyo"),
		new CityListClass("CMPS", "상 조세 도스 캄포스", "브라질", "America/Sao_Paulo"),
		new CityListClass("GRNDS", "상그레그란데", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass("SLB", "상루이스", "브라질", "America/Bahia"),
		new CityListClass("VCNTS", "상베센테", "포르투칼", "Atlantic/Madeira"),
		new CityListClass("11H10302", "상주", "대한민국", "Asia/Seoul"),
		new CityListClass("PAULO", "상파울루", "브라질", "America/Sao_Paulo"),
		new CityListClass("SHA", "상하이", "중국", "Asia/Shanghai"),
		new CityListClass("SGNW", "새기노", "미국", "America/Detroit"),
		new CityListClass("SJOS", "새너제이", "미국", "America/Los_Angeles"),
		new CityListClass("SRST", "새러소타", "미국", "America/New_York"),
		new CityListClass("SRTG", "새러토가 스프링스", "미국", "America/New_York"),
		new CityListClass("SSKTN", "새스커툰", "캐나다", "America/Regina"),
		new CityListClass("SAC", "새크라멘토", "미국", "America/Los_Angeles"),
		new CityListClass("SPRNGS", "샌디 스프링스", "미국", "America/New_York"),
		new CityListClass("SDI", "샌디에이고", "미국", "America/Los_Angeles"),
		new CityListClass("PDJ", "샌디포인트타운", "세인트 키츠 네비스", "America/St_Kitts"),
		new CityListClass("SANL", "샌루이스오비스포", "미국", "America/Los_Angeles"),
		new CityListClass("SBRNRD", "샌버너디노", "미국", "America/Los_Angeles"),
		new CityListClass("SATO", "샌안토니오", "미국", "America/Chicago"),
		new CityListClass("SAGTX1", "샌앤젤로", "미국", "America/Chicago"),
		new CityListClass("SANTAF", "샌타페이", "미국", "America/Denver"),
		new CityListClass("SFO", "샌프란시스코", "미국", "America/Los_Angeles"),
		new CityListClass("SLNU", "샐리나스", "미국", "America/Los_Angeles"),
		new CityListClass("NZR", "생나제르", "프랑스", "Europe/Paris"),
		new CityListClass("DZR", "생대지에", "프랑스", "Europe/Paris"),
		new CityListClass("SNTDN", "생드니", "프랑스", "Indian/Reunion"),
		new CityListClass("SAINTM", "생말로", "프랑스", "Europe/Paris"),
		new CityListClass("BRUC", "생브리외", "프랑스", "Europe/Paris"),
		new CityListClass("QNTN", "생캉탱", "프랑스", "Europe/Paris"),
		new CityListClass("ETNN", "생테티엔", "프랑스", "Europe/Paris"),
		new CityListClass("CHMPG", "샤롱장샹파뉴", "프랑스", "Europe/Paris"),
		new CityListClass("SHJ", "샤르자", "아랍에미리트", "Asia/Dubai"),
		new CityListClass("SHRQH", "샤르자토후국", "아랍에미리트", "Asia/Dubai"),
		new CityListClass("CHRTR", "샤르트르", "프랑스", "Europe/Paris"),
		new CityListClass("CHRLR", "샤를루아", "벨기에", "Europe/Brussels"),
		new CityListClass("CHRLVM", "샤를르 빌 메지에르", "프랑스", "Europe/Paris"),
		new CityListClass("CHRLVL", "샤를르빌", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass("SCHMB", "샤움버그", "미국", "America/Chicago"),
		new CityListClass("CHYNN", "샤이엔", "미국", "America/Denver"),
		new CityListClass("SHKW", "샤카베", "보츠와나", "Africa/Gaborone"),
		new CityListClass("CHTBL", "샤토 벨레르", "세인트 빈센트 그레나딘", "America/St_Vincent"),
		new CityListClass("STRLJ", "샤토럴려우이헤이", "헝가리", "Europe/Budapest"),
		new CityListClass("CHTRX", "샤토르", "프랑스", "Europe/Paris"),
		new CityListClass("SCHFF", "샤프하우젠", "스위스", "Europe/Zurich"),
		new CityListClass("SCHN1", "샨", "리히텐슈타인", "Europe/Vaduz"),
		new CityListClass("CHRNC", "샬럿", "미국", "America/New_York"),
		new CityListClass("CHRAM", "샬럿 아말리에", "버진 아일랜드", "America/St_Thomas"),
		new CityListClass("CTT", "샬럿 타운", "캐나다", "America/Goose_Bay"),
		new CityListClass("CHRLT", "샬로츠빌", "미국", "America/New_York"),
		new CityListClass("CHLN", "샬롱쉬르손", "프랑스", "Europe/Paris"),
		new CityListClass("SHYKH", "샴 엘 쉐이크", "이집트", "Africa/Cairo"),
		new CityListClass("CHMPG1", "샴페인", "미국", "America/Chicago"),
		new CityListClass("SNTM", "샹테마리", "마르티니크", "America/Martinique"),
		new CityListClass("SNTA", "샹테안느", "과들루프섬", "America/Guadeloupe"),
		new CityListClass("11G00401", "서귀포", "대한민국", "Asia/Seoul"),
		new CityListClass("SVL", "서니베일", "미국", "America/Los_Angeles"),
		new CityListClass("STHRL", "서덜랜드", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SVA", "서배너", "미국", "America/New_York"),
		new CityListClass("11C20101", "서산", "대한민국", "Asia/Seoul"),
		new CityListClass("11B10101", "서울", "대한민국", "Asia/Seoul"),
		new CityListClass("11C20202", "서천", "대한민국", "Asia/Seoul"),
		new CityListClass("SNGPK", "선가이파크닝", "인도네시아", "Asia/Jakarta"),
		new CityListClass("THB", "선더 베이", "캐나다", "America/Toronto"),
		new CityListClass("SNSHN", "선샤인 코스트", "오스트레일리아", "Australia/Brisbane"),
		new CityListClass("SMS", "섬머사이드", "캐나다", "America/Goose_Bay"),
		new CityListClass("11B20605", "성남", "대한민국", "Asia/Seoul"),
		new CityListClass("11G00101", "성산", "대한민국", "Asia/Seoul"),
		new CityListClass("11H10605", "성주", "대한민국", "Asia/Seoul"),
		new CityListClass("11G00302", "성판악", "대한민국", "Asia/Seoul"),
		new CityListClass("SGV", "세고비아", "스페인", "Europe/Madrid"),
		new CityListClass("SNNG", "세난가", "잠비아", "Africa/Lusaka"),
		new CityListClass("SNKL", "세네칼", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("CDNA", "세두나", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass("SRRS", "세라이", "그리스", "Europe/Athens"),
		new CityListClass("SRMBN", "세렘반", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("SRW", "세로베", "보츠와나", "Africa/Gaborone"),
		new CityListClass("SRNG", "세롱가", "보츠와나", "Africa/Gaborone"),
		new CityListClass("CLRD", "세루 콜로라도", "아루바", "America/Aruba"),
		new CityListClass("PSRG", "세르베라 드 피수에르가", "스페인", "Europe/Madrid"),
		new CityListClass("SERTA", "세르타", "포르투칼", "Europe/Lisbon"),
		new CityListClass("SERPA", "세르파", "포르투칼", "Europe/Lisbon"),
		new CityListClass("PHKW", "세리베 피크베", "보츠와나", "Africa/Gaborone"),
		new CityListClass("CRRK", "세리크", "알바니아", "Europe/Tirane"),
		new CityListClass("SEM", "세마랑", "인도네시아", "Asia/Jakarta"),
		new CityListClass("CEBC", "세부시티", "필리핀", "Asia/Manila"),
		new CityListClass("SEV", "세비야", "스페인", "Europe/Madrid"),
		new CityListClass("SSHK", "세쉐케", "잠비아", "Africa/Lusaka"),
		new CityListClass("SSFNT", "세스폰테인", "나미비아", "Africa/Windhoek"),
		new CityListClass("SANAB", "세이트 앤 베이", "자메이카", "America/Jamaica"),
		new CityListClass("LRNT", "세인트 로랑 다다오", "기아나", "America/Cayenne"),
		new CityListClass("SLSMO", "세인트 루이스", "미국", "America/Chicago"),
		new CityListClass("SANTMR", "세인트 마크", "아이티", "America/Port-au-Prince"),
		new CityListClass("JSPH", "세인트 조셉", "미국", "America/Chicago"),
		new CityListClass("SANTJS", "세인트 조셉", "도미니카", "America/Dominica"),
		new CityListClass("GRG3", "세인트 조지", "미국", "America/Denver"),
		new CityListClass("GRGS", "세인트 조지스", "그레나다", "America/Grenada"),
		new CityListClass("GRGSS", "세인트 조지스", "기아나", "America/Cayenne"),
		new CityListClass("SNV", "세인트 존", "캐나다", "America/Goose_Bay"),
		new CityListClass("SAINTJ", "세인트 존스", "앤티가바부다", "America/Antigua"),
		new CityListClass("SJF", "세인트 존스", "캐나다", "America/St_Johns"),
		new CityListClass("VLLGS", "세인트 존스 빌리지", "몬세라트산", "America/Montserrat"),
//		new CityListClass("CTHRNS", "세인트 캐서린스", "캐나다", "America/Toronto"),
		new CityListClass("CLOMN", "세인트 클라우드", "미국", "America/Chicago"),
		new CityListClass("SAINTP", "세인트 폴", "미국", "America/Chicago"),
		new CityListClass("STPGU", "세인트 피터즈버그", "미국", "America/New_York"),
		new CityListClass("ALBNS", "세인트올번스", "영국", "Europe/London"),
		new CityListClass("SAINT", "세인트이브스", "영국", "Europe/London"),
		new CityListClass("LEN", "세인트피터즈버그", "러시아", "Europe/Moscow"),
		new CityListClass("SALE", "세일", "오스트레일리아", "Australia/Melbourne"),
		new CityListClass("SALEM", "세일럼", "미국", "America/New_York"),
		new CityListClass("SLMOR", "세일럼", "미국", "America/Boise"),
		new CityListClass("SZN", "세자나", "슬로바키아", "Europe/Ljubljana"),
		new CityListClass("SZKSF", "세케슈페헤르바르", "헝가리", "Europe/Budapest"),
		new CityListClass("SIL", "세틸", "캐나다", "America/Montreal"),
		new CityListClass("KRJNS", "세프올노 크라젠스키", "폴란드", "Europe/Warsaw"),
		new CityListClass("SENJ", "센", "크로아티아", "Europe/Zagreb"),
		new CityListClass("SEN", "센다이", "일본", "Asia/Tokyo"),
		new CityListClass("SNSNT", "센순테페케", "엘살바도르", "America/El_Salvador"),
		new CityListClass("CNTNN", "센터니얼", "미국", "America/Denver"),
		new CityListClass("SZNTS", "센테시", "헝가리", "Europe/Budapest"),
		new CityListClass("THRLS", "셀레스", "아일랜드", "Europe/Dublin"),
		new CityListClass("SLFSS", "셀포스", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass("STCSS", "셋케이시스", "스페인", "Europe/Madrid"),
		new CityListClass("SLGTR", "셔로터랸", "헝가리", "Europe/Budapest"),
		new CityListClass("SHRBR", "셔브룩", "캐나다", "America/Montreal"),
		new CityListClass("SHBYG", "셰보이건", "미국", "America/Chicago"),
		new CityListClass("SNDR", "소드리오", "이탈리아", "Europe/Rome"),
		new CityListClass("SRCB", "소루카바", "브라질", "America/Sao_Paulo"),
		new CityListClass("SORIA", "소리아", "스페인", "Europe/Madrid"),
		new CityListClass("SOWE", "소웨토", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SKRK", "소카", "폴란드", "Europe/Warsaw"),
		new CityListClass("STRS", "소퇴르", "그레나다", "America/Grenada"),
		new CityListClass("SFLN", "소프리온", "그리스", "Europe/Athens"),
		new CityListClass("SOFIA", "소피아", "불가리아", "Europe/Sofia"),
		new CityListClass("11D20401", "속초", "대한민국", "Asia/Seoul"),
		new CityListClass("SNSNT1", "손소나테", "엘살바도르", "America/El_Salvador"),
		new CityListClass("SZLNK", "솔노크", "헝가리", "Europe/Budapest"),
		new CityListClass("SLWZ", "솔베지", "잠비아", "Africa/Lusaka"),
		new CityListClass("SLSN", "솔소나", "스페인", "Europe/Madrid"),
		new CityListClass("SLSBR", "솔즈베리", "미국", "America/New_York"),
		new CityListClass("SLTLK", "솔트 레이크 시티", "미국", "America/Denver"),
		new CityListClass("SMMRD", "솜머다", "독일", "Europe/Berlin"),
		new CityListClass("SZMBT", "솜보텔리", "헝가리", "Europe/Budapest"),
		new CityListClass("SDB", "쇠네르보르", "덴마크", "Europe/Copenhagen"),
		new CityListClass("SHWN", "쇼니", "미국", "America/Chicago"),
		new CityListClass("CHMNT", "쇼몽", "프랑스", "Europe/Paris"),
		new CityListClass("SHOBR", "쇼우바라", "일본", "Asia/Tokyo"),
		new CityListClass("SPRN1", "쇼프론", "헝가리", "Europe/Budapest"),
		new CityListClass("SIOUX", "수 시티", "미국", "America/Chicago"),
		new CityListClass("SIOUXF", "수 폴스", "미국", "America/Chicago"),
		new CityListClass("SRB", "수라바야", "인도네시아", "Asia/Jakarta"),
		new CityListClass("SUT", "수라트타니", "태국", "Asia/Bangkok"),
		new CityListClass("SUR1", "수르", "오만", "Asia/Muscat"),
		new CityListClass("SRGT", "수르구트", "러시아", "Asia/Yekaterinburg"),
		new CityListClass("SUV", "수바", "피지", "Pacific/Fiji"),
		new CityListClass("SBTC", "수보티차", "세르비아", "Europe/Belgrade"),
		new CityListClass("SSM", "수세인트마리", "캐나다", "America/Toronto"),
		new CityListClass("SUE", "수에즈", "이집트", "Africa/Cairo"),
		new CityListClass("SWYD", "수와이다", "시리아", "Asia/Damascus"),
		new CityListClass("11B20601", "수원", "대한민국", "Asia/Seoul"),
		new CityListClass("SSC", "수지스", "체코", "Europe/Prague"),
		new CityListClass("SCHDN", "수체드니오", "폴란드", "Europe/Warsaw"),
		new CityListClass("SCVA", "수체아바", "루마니아", "Europe/Bucharest"),
		new CityListClass("SUCRE", "수크레", "볼리비아", "America/La_Paz"),
		new CityListClass("SFRR", "수프리에르", "세인트루시아", "America/St_Lucia"),
		new CityListClass("SUH", "수하르", "오만", "Asia/Muscat"),
		new CityListClass("SNNDL", "순달소라", "노르웨이", "Europe/Oslo"),
		new CityListClass("SDV", "순스발", "스웨덴", "Europe/Stockholm"),
		new CityListClass("11F10403", "순창", "대한민국", "Asia/Seoul"),
		new CityListClass("11F20405", "순천", "대한민국", "Asia/Seoul"),
		new CityListClass("11F20603", "순천(주암)", "대한민국", "Asia/Seoul"),
//		new CityListClass("SHFFL", "쉐필드", "영국", "Europe/London"),
		new CityListClass("OCTVL", "쉘부르", "프랑스", "Europe/Paris"),
		new CityListClass("SHRWS", "슈루즈버리", "영국", "Europe/London"),
		new CityListClass("SHVLA", "슈리브포트", "미국", "America/Chicago"),
		new CityListClass("SHMN", "슈멘", "불가리아", "Europe/Sofia"),
		new CityListClass("SCHWR", "슈베린", "독일", "Europe/Berlin"),
		new CityListClass("SCHWY", "슈비츠", "스위스", "Europe/Zurich"),
		new CityListClass("SCHBB", "슈아이브스", "오스트리아", "Europe/Vienna"),
		new CityListClass("SZGD", "슈제츠트", "헝가리", "Europe/Budapest"),
		new CityListClass("SZCZC1", "슈체친", "폴란드", "Europe/Warsaw"),
//		new CityListClass("SHKDR", "슈코더르", "알바니아", "Europe/Tirane"),
		new CityListClass("STNKP", "슈타인코프", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("STRLS", "슈트랄준트", "독일", "Europe/Berlin"),
		new CityListClass("STTGT", "슈트트가르트", "독일", "Europe/Berlin"),
		new CityListClass("SZPRT", "슈프로타바", "폴란드", "Europe/Warsaw"),
		new CityListClass("SPTTL", "슈피탈드라우", "오스트리아", "Europe/Vienna"),
		new CityListClass("SLTNB", "슐탄베일리", "터키", "Europe/Istanbul"),
		new CityListClass("STRGR", "스나로가드구덴스키", "폴란드", "Europe/Warsaw"),
		new CityListClass("TRENT", "스노크온트렌트", "영국", "Europe/London"),
		new CityListClass("SRWN1", "스라우노", "폴란드", "Europe/Warsaw"),
		new CityListClass("SRNGR", "스리나가르", "인도", "Asia/Calcutta"),
		new CityListClass("JYWRD", "스리자야와르데네푸라코테", "스리랑카", "Asia/Colombo"),
		new CityListClass("SMDRV", "스메데레보", "세르비아", "Europe/Belgrade"),
		new CityListClass("SUMOT", "스모토", "일본", "Asia/Tokyo"),
		new CityListClass("SMLYN", "스몰랸", "불가리아", "Europe/Sofia"),
		new CityListClass("SMLNS", "스몰렌스크", "러시아", "Europe/Moscow"),
		new CityListClass("SMTHR", "스미더스", "캐나다", "America/Vancouver"),
		new CityListClass("SMTHT", "스미스타운", "미국", "America/New_York"),
		new CityListClass("NKL1", "스베티니콜", "마케도니아", "Europe/Skopje"),
		new CityListClass("SVLVR", "스볼베르", "노르웨이", "Europe/Oslo"),
		new CityListClass("SUWA", "스와", "일본", "Asia/Tokyo"),
		new CityListClass("SWKPM", "스와콥문드", "나미비아", "Africa/Windhoek"),
		new CityListClass("ABRTW", "스완지", "영국", "Europe/London"),
		new CityListClass("SWRK", "스왈키", "폴란드", "Europe/Warsaw"),
//		new CityListClass("SWDWN", "스위드윈", "폴란드", "Europe/Warsaw"),
		new CityListClass("SWBDZ", "스위보진", "폴란드", "Europe/Warsaw"),
		new CityListClass("SWC", "스위치", "폴란드", "Europe/Warsaw"),
		new CityListClass("CRRNTS", "스위프트 커런트", "캐나다", "America/Regina"),
		new CityListClass("SWNDN", "스윈던", "영국", "Europe/London"),
		new CityListClass("SKG", "스카겐", "덴마크", "Europe/Copenhagen"),
		new CityListClass("SCAR", "스카버러", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass("SCHNC", "스케넥터디", "미국", "America/New_York"),
		new CityListClass("SCTTSD", "스코츠데일", "미국", "America/Denver"),
		new CityListClass("SKPJ", "스코페", "마케도니아", "Europe/Skopje"),
		new CityListClass("SKLV", "스콜로프", "체코", "Europe/Prague"),
		new CityListClass("SKM", "스쿠모", "일본", "Asia/Tokyo"),
		new CityListClass("SCRNT", "스크랜턴", "미국", "America/New_York"),
		new CityListClass("SZCZY", "스키노", "폴란드", "Europe/Warsaw"),
//		new CityListClass("ZGR", "스타라자고라", "불가리아", "Europe/Sofia"),
		new CityListClass("SZCZC", "스타르가르트슈체친스키", "폴란드", "Europe/Warsaw"),
		new CityListClass("SVR", "스타방게르", "노르웨이", "Europe/Oslo"),
		new CityListClass("STWRP", "스타브로폴", "러시아", "Europe/Moscow"),
		new CityListClass("STLW", "스탈로아볼라", "폴란드", "Europe/Warsaw"),
		new CityListClass("STMFR", "스탬퍼드", "미국", "America/New_York"),
		new CityListClass("STRLN", "스털링", "영국", "Europe/London"),
		new CityListClass("STRHT", "스털링 하이츠", "미국", "America/Detroit"),
		new CityListClass("STTSB", "스테이츠버러", "미국", "America/New_York"),
		new CityListClass("CLLG", "스테이트칼리지", "미국", "America/New_York"),
		new CityListClass("STNKJ", "스테인헤르", "노르웨이", "Europe/Oslo"),
		new CityListClass("STYNB", "스텐버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SRY", "스토너웨이", "영국", "Europe/London"),
		new CityListClass("STO", "스톡턴", "미국", "America/Los_Angeles"),
		new CityListClass("SDN", "스톡홀름", "스웨덴", "Europe/Stockholm"),
		new CityListClass("STNTN", "스톤턴", "미국", "America/New_York"),
		new CityListClass("STRMC", "스투루미차", "마케도니아", "Europe/Skopje"),
		new CityListClass("STRG", "스투르가", "마케도니아", "Europe/Skopje"),
		new CityListClass("STRBG", "스트라스부르", "프랑스", "Europe/Paris"),
		new CityListClass("STRKN", "스트라코니스", "체코", "Europe/Prague"),
		new CityListClass("STRHN", "스트라한", "오스트레일리아", "Australia/Hobart"),
		new CityListClass("STRMS", "스트롬순드", "스웨덴", "Europe/Stockholm"),
		new CityListClass("STRYD", "스트리덴버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("STRZG", "스트셰곰", "폴란드", "Europe/Warsaw"),
		new CityListClass("STRZL", "스트셸린", "폴란드", "Europe/Warsaw"),
		new CityListClass("OPLSK", "스트셸체오폴스키에", "폴란드", "Europe/Warsaw"),
		new CityListClass("STEGE", "스티지", "덴마크", "Europe/Copenhagen"),
		new CityListClass("STIP", "스팁", "마케도니아", "Europe/Skopje"),
//		new CityListClass("SPA1", "스파", "벨기에", "Europe/Brussels"),
		new CityListClass("SPRTN", "스파턴버그", "미국", "America/New_York"),
		new CityListClass("SPGHT", "스페이츠 타운", "바베이도스", "America/Barbados"),
		new CityListClass("SPKN", "스포캔", "미국", "America/Los_Angeles"),
		new CityListClass("SPRNG2", "스프링데일", "미국", "America/Chicago"),
		new CityListClass("SPGMA", "스프링필드-매사추세츠", "미국", "America/New_York"),
		new CityListClass("SPGMO", "스프링필드-미주리", "미국", "America/Chicago"),
		new CityListClass("SPNGF", "스프링필드-오하이오", "미국", "America/New_York"),
		new CityListClass("SPNGA", "스프링필드-일리노이", "미국", "America/Chicago"),
		new CityListClass("SPL", "스플리트", "크로아티아", "Europe/Zagreb"),
		new CityListClass("GHRGH", "스핀두게오르게", "루마니아", "Europe/Bucharest"),
		new CityListClass("WSCHW", "스호바", "폴란드", "Europe/Warsaw"),
//		new CityListClass("SLASK", "슬라스키에", "폴란드", "Europe/Warsaw"),
		new CityListClass("SLIGO", "슬라이고", "아일랜드", "Europe/Dublin"),
		new CityListClass("SLTNA", "슬라티나", "크로아티아", "Europe/Zagreb"),
		new CityListClass("SLTN", "슬라티나", "루마니아", "Europe/Bucharest"),
		new CityListClass("SLVNS", "슬라폰스키브로트", "크로아티아", "Europe/Zagreb"),
		new CityListClass("SRPSK", "슬럽스크", "폴란드", "Europe/Warsaw"),
		new CityListClass("SLGH", "슬로", "영국", "Europe/London"),
		new CityListClass("SLBZ", "슬로보지아", "루마니아", "Europe/Bucharest"),
		new CityListClass("SLVN", "슬리벤", "불가리아", "Europe/Sofia"),
		new CityListClass("STTS", "슷츠", "일본", "Asia/Tokyo"),
		new CityListClass("SGNZ", "시구엔자", "스페인", "Europe/Madrid"),
		new CityListClass("CDS", "시네스", "포르투칼", "Europe/Lisbon"),
		new CityListClass("CEDARD", "시더 래피즈", "미국", "America/Chicago"),
		new CityListClass("CEDAR", "시더 시티", "미국", "America/Denver"),
		new CityListClass("SDY", "시드니", "오스트레일리아", "Australia/Sydney"),
		new CityListClass("SYD", "시드니", "캐나다", "America/Halifax"),
		new CityListClass("RACHA", "시라차", "태국", "Asia/Bangkok"),
		new CityListClass("SRKW", "시라카와", "일본", "Asia/Tokyo"),
		new CityListClass("SRCS", "시라쿠사", "이탈리아", "Europe/Rome"),
		new CityListClass("SYRCS", "시러큐스", "미국", "America/New_York"),
		new CityListClass("SROISH", "시로이시", "일본", "Asia/Tokyo"),
		new CityListClass("SHS", "시모노세키", "일본", "Asia/Tokyo"),
		new CityListClass("CHMO", "시모이우", "모잠비크", "Africa/Maputo"),
		new CityListClass("SIMI", "시미", "그리스", "Europe/Athens"),
		new CityListClass("SIVLLY", "시미 밸리", "미국", "America/Los_Angeles"),
		new CityListClass("SIVAS", "시바스", "터키", "Europe/Istanbul"),
		new CityListClass("SBN", "시베니크", "크로아티아", "Europe/Zagreb"),
		new CityListClass("SIBU", "시부", "말레이시아", "Asia/Kuala_Lumpur"),
		new CityListClass("SWDNC", "시비드니차", "폴란드", "Europe/Warsaw"),
		new CityListClass("SIBIU", "시비우", "루마니아", "Europe/Bucharest"),
		new CityListClass("SISAK", "시사크", "크로아티아", "Europe/Zagreb"),
		new CityListClass("SIAUL", "시아울리아이", "리투아니아", "Europe/Vilnius"),
		new CityListClass("SEA", "시애틀", "미국", "America/Los_Angeles"),
		new CityListClass("SIENA", "시에나", "이탈리아", "Europe/Rome"),
		new CityListClass("SKIEN", "시엔", "노르웨이", "Europe/Oslo"),
		new CityListClass("SHIMK", "시오노미사키", "일본", "Asia/Tokyo"),
		new CityListClass("SFK", "시오포크", "헝가리", "Europe/Budapest"),
		new CityListClass("SION1", "시옹", "스위스", "Europe/Zurich"),
		new CityListClass("SIWAH", "시와", "이집트", "Africa/Cairo"),
		new CityListClass("CIW", "시완단", "인도네시아", "Asia/Jakarta"),
		new CityListClass("GYN", "시우다드 가이아나", "베네수엘라", "America/Caracas"),
		new CityListClass("DLCS", "시우다드 델리시아스", "멕시코", "America/Chihuahua"),
		new CityListClass("RDRG", "시우다드 로드리고", "스페인", "Europe/Madrid"),
		new CityListClass("BLVR", "시우다드 볼리바르", "베네수엘라", "America/Caracas"),
		new CityListClass("VCTM", "시우다드 빅토리아", "멕시코", "America/Monterrey"),
		new CityListClass("OBRGN", "시우다드 오브레곤", "멕시코", "America/Hermosillo"),
		new CityListClass("CDD", "시우다드레알", "스페인", "Europe/Madrid"),
		new CityListClass("CTDLL", "시우타델라", "스페인", "Europe/Madrid"),
		new CityListClass("SIIRT", "시이르트", "터키", "Europe/Istanbul"),
		new CityListClass("SHI", "시즈오카", "일본", "Asia/Tokyo"),
		new CityListClass("CGO", "시카고", "미국", "America/Chicago"),
		new CityListClass("SIKEA", "시키아", "그리스", "Europe/Athens"),
//		new CityListClass("STK1", "시테키", "스와질란드", "Africa/Mbabane"),
		new CityListClass("SITT", "시트라", "바레인", "Asia/Bahrain"),
		new CityListClass("CTRSD", "시트러스달", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass("SPR1", "시파리아", "트리니다드토바고", "America/Port_of_Spain"),
		new CityListClass("11B20202", "시흥", "대한민국", "Asia/Seoul"),
		new CityListClass("SYKTY", "식티프카르", "러시아", "Europe/Moscow"),
		new CityListClass("SINDI", "신디", "에스토니아", "Europe/Tallinn"),
		new CityListClass("CICNT", "신시내티", "미국", "America/New_York"),
		new CityListClass("21F20803", "신안", "대한민국", "Asia/Seoul"),
		new CityListClass("SHNJ", "신조우", "일본", "Asia/Tokyo"),
		new CityListClass("SHNKB", "신키바", "일본", "Asia/Tokyo"),
		new CityListClass("NCL", "신트 니콜라스", "아루바", "America/Aruba"),
		new CityListClass("NKLS", "신트니클라스", "벨기에", "Europe/Brussels"),
		new CityListClass("SLKBR", "실게보르", "덴마크", "Europe/Copenhagen"),
		new CityListClass("SLLM", "실라마에", "에스토니아", "Europe/Tallinn"),
		new CityListClass("SLT1", "실루트", "리투아니아", "Europe/Vilnius"),
		new CityListClass("SLSTR", "실리스트라", "불가리아", "Europe/Sofia"),
		new CityListClass("SPRNG1", "실버 스프링", "미국", "America/New_York"),
		new CityListClass("DANJ", "싱가폴", "싱가폴", "Asia/Singapore"),

//		new CityListClass("SAG","사가","일본","Asia/Tokyo"),
//		new CityListClass("SGNY","사그네이","캐나다","America/Montreal"),
//		new CityListClass("SANAA","사나","예멘","Asia/Aden"),
//		new CityListClass("SANOK","사노크","폴란드","Europe/Warsaw"),
//		new CityListClass("SNKLQ","사니킬루아크","캐나다","America/Pangnirtung"),
//		new CityListClass("ZRGZ","사라고사","스페인","Europe/Madrid"),
//		new CityListClass("SRJV","사라예보","보스니아-헤르체고비나","Europe/Sarajevo"),
//		new CityListClass("SRTV","사라토브","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("SRNSK","사란스크","러시아 연방 국가","Asia/Yekaterinburg"),
//		new CityListClass("SMAR","사마라","러시아 연방 국가","Asia/Yekaterinburg"),
//		new CityListClass("ZMR1","사모라","스페인","Europe/Madrid"),
//		new CityListClass("SAMOS","사모스","그리스","Europe/Athens"),
//		new CityListClass("SBNT","사바네타","아루바","America/Aruba"),
//		new CityListClass("SBDLL","사바델","스페인","Europe/Madrid"),
//		new CityListClass("SVNK","사브니크","세르비아","Europe/Belgrade"),
//		new CityListClass("SSSR","사사리","이탈리아","Europe/Rome"),
//		new CityListClass("SASE","사에보","일본","Asia/Tokyo"),
//		new CityListClass("SOT","사오톰","상투메프린시페","Africa/Sao_Tome"),
//		new CityListClass("STHMP","사우샘프턴","미국","America/New_York"),
//		new CityListClass("TAHOE","사우스 레이크 타호","미국","America/Los_Angeles"),
//		new CityListClass("SBEND","사우스 벤드","미국","America/Indianapolis"),
//		new CityListClass("STHND","사우스엔드온시","영국","Europe/London"),
//		new CityListClass("SOU","사우스햄턴","영국","Europe/London"),
//		new CityListClass("SAUE","사우에","에스토니아","Europe/Tallinn"),
//		new CityListClass("THSND","사우전드 오크스","미국","America/Los_Angeles"),
//		new CityListClass("SAUL","사울","기아나","America/Cayenne"),
//		new CityListClass("SAIGOU","사이고우","일본","Asia/Tokyo"),
//		new CityListClass("SAE","사이키","일본","Asia/Tokyo"),
//		new CityListClass("SAI","사이타마","일본","Asia/Tokyo"),
//		new CityListClass("SPN","사이판","북마리아나 제도","Pacific/Saipan"),
//			new CityListClass("11H20402","사천","대한민국","Asia/Seoul"),
//		new CityListClass("SKRY1","사카리아","터키","Europe/Istanbul"),
//		new CityListClass("SKN","사카이미나토","일본","Asia/Tokyo"),
//		new CityListClass("SKT","사카타","일본","Asia/Tokyo"),
//		new CityListClass("ZCTCS","사카테카스","멕시코","America/Merida"),
//	    	new CityListClass("SAKIA","사키아이","리투아니아","Europe/Vilnius"),
//		new CityListClass("MARES","사투마레","루마니아","Europe/Bucharest"),
//		new CityListClass("ZAFRA","사프라","스페인","Europe/Madrid"),
//		new CityListClass("SHGN","사하군","스페인","Europe/Madrid"),
//		new CityListClass("HRBRS","삭스 하버","캐나다","America/Yellowknife"),
//		new CityListClass("RFLS","산 라파엘","미국","America/Los_Angeles"),
//		new CityListClass("SNT","산 안토니오","칠레","America/Santiago"),
//		new CityListClass("CRLS1","산 카를로스","니카라과","America/Managua"),
//	    	new CityListClass("CRLSS","산 카를로스","베네수엘라","America/Caracas"),
//		new CityListClass("BRLCH","산 카를로스 데 바리로체","아르헨티나","America/Argentina/Buenos_Aires"),
//	    	new CityListClass("CRSTB","산 크리스토발","베네수엘라","America/Caracas"),
//	    	new CityListClass("FLP","산 펠리페","베네수엘라","America/Caracas"),
//		new CityListClass("PPL","산 펠리페 데 푸에르토 플라타","도미나카공화국","America/Santo_Domingo"),
//		new CityListClass("QNTNS","산낀띤","멕시코","America/Mazatlan"),
//		new CityListClass("SNN","산다칸","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("SANDE","산데","노르웨이","Europe/Oslo"),
//		new CityListClass("SNDMR","산도미에슈","폴란드","Europe/Warsaw"),
//	    	new CityListClass("SLRH","산로렌소","온두라스","America/Tegucigalpa"),
//		new CityListClass("BRRMD","산루가르데바라메다","스페인","Europe/Madrid"),
//		new CityListClass("PTSL","산루이스포토시","멕시코","America/Mexico_City"),
//		new CityListClass("VLDGL","산마르틴","스페인","Europe/Madrid"),
//		new CityListClass("MRN","산마리노","San Marino","Europe/San_Marino"),
//		new CityListClass("MQL","산미겔","엘살바도르","America/El_Salvador"),
//		new CityListClass("TCMN","산미겔데투쿠만","아르헨티나","America/Argentina/Buenos_Aires"),
//		new CityListClass("MGLT","산미구엘리또","파나마","America/Panama"),
//		new CityListClass("VCNT","산비센테","칠레","America/Santiago"),
//		new CityListClass("SANVIC","산비센테","엘살바도르","America/El_Salvador"),
//		new CityListClass("ALCNTV","산비센테 데 알칸타라","스페인","Europe/Madrid"),
//		new CityListClass("SLVDRS","산살바도르","엘살바도르","America/El_Salvador"),
//		new CityListClass("SBSTNG","산세바스찬 데라고메라","스페인","Atlantic/Canary"),
//		new CityListClass("SNSK","산스키모스트","보스니아-헤르체고비나","Europe/Sarajevo"),
//		new CityListClass("ISDR","산이시드로","코스타리카","America/Costa_Rica"),
//			new CityListClass("11H20703","산청","대한민국","Asia/Seoul"),
//		new CityListClass("LAGUN","산크리스토발 데 라 라구나","스페인","Atlantic/Canary"),
//		new CityListClass("CLMNTS","산클레멘테","스페인","Europe/Madrid"),
//		new CityListClass("SROU","산타 로사","미국","America/Los_Angeles"),
//	    	new CityListClass("COPAN","산타 로사 데 코판","온두라스","America/Tegucigalpa"),
//		new CityListClass("SNR","산타 로살리아","멕시코","America/Mazatlan"),
//		new CityListClass("SMR","산타 마르타","콜롬비아","America/Bogota"),
//		new CityListClass("SAMO","산타 모니카","미국","America/Los_Angeles"),
//		new CityListClass("SBB","산타 바바라","미국","America/Los_Angeles"),
//		new CityListClass("SANCA","산타 아나","미국","America/Los_Angeles"),
//		new CityListClass("CLRT","산타 클라리타","미국","America/Los_Angeles"),
//		new CityListClass("GAI","산타구루즈 다 그라시오사","포르투칼","Atlantic/Azores"),
//		new CityListClass("SCLP","산타구루즈데라팔마","스페인","Atlantic/Canary"),
//		new CityListClass("SNTAR","산타렘","포르투칼","Europe/Lisbon"),
//		new CityListClass("SANTA","산타아나","엘살바도르","America/El_Salvador"),
//		new CityListClass("OLLL","산타오랄라델칼라","스페인","Europe/Madrid"),
//		new CityListClass("SANTO","산타쿠루즈","포르투칼","Atlantic/Madeira"),
//		new CityListClass("SCR","산타쿠루즈데테네리페","스페인","Atlantic/Canary"),
//		new CityListClass("SNZ","산타크루스","미국","America/Los_Angeles"),
//		new CityListClass("SANTAC","산타크루스","아루바","America/Aruba"),
//		new CityListClass("SCDLS","산타크루스데라시에라","볼리비아","America/La_Paz"),
//		new CityListClass("SNF","산타페","아르헨티나","America/Argentina/Buenos_Aires"),
//		new CityListClass("STR","산탄데르","스페인","Europe/Madrid"),
//		new CityListClass("SAF","산토 도 밍고","도미나카공화국","America/Santo_Domingo"),
//		new CityListClass("CLRDS","산토 도밍고 드 로스 콜로라도","에콰도르","America/Guayaquil"),
//		new CityListClass("ANDRES","산투 안드레","브라질","America/Sao_Paulo"),
//		new CityListClass("STS","산투스","브라질","America/Sao_Paulo"),
//		new CityListClass("STGC","산티아고","칠레","America/Santiago"),
//		new CityListClass("SNTG","산티아고","파나마","America/Panama"),
//		new CityListClass("CBLLR","산티아고 데 로스 카바예로스","도미나카공화국","America/Santo_Domingo"),
//		new CityListClass("SNTGC","산티아고데카셈","포르투칼","Europe/Lisbon"),
//		new CityListClass("CMPST","산티아고데콤포스텔라","스페인","Europe/Madrid"),
//		new CityListClass("PEDRO","산페드로","파라과이","America/Asuncion"),
//		new CityListClass("SAQ","산페드로데마코리스","도미나카공화국","America/Santo_Domingo"),
//	    	new CityListClass("PEDROS","산페드로술라","온두라스","America/Tegucigalpa"),
//		new CityListClass("SANFR","산페르난도","필리핀","Asia/Manila"),
//		new CityListClass("SFL","산페르난도","트리니다드토바고","America/Port_of_Spain"),
//	    	new CityListClass("FRNNDA","산페르난도데아푸레","베네수엘라","America/Caracas"),
//		new CityListClass("FRNCSM","산프란시스코 데 마코리스","도미나카공화국","America/Santo_Domingo"),
//		new CityListClass("JOSE","산호세","코스타리카","America/Costa_Rica"),
//		new CityListClass("MAYOJ","산호세데마요","우루과이","America/Montevideo"),
//		new CityListClass("SJUAN","산후안","미국","America/Puerto_Rico"),
//		new CityListClass("JUAN","산후안","아르헨티나","America/Argentina/Buenos_Aires"),
//	    	new CityListClass("MRRS","산후안데로스모로스","베네수엘라","America/Caracas"),
//		new CityListClass("SBY","살다나","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SLMNCA","살라망카","스페인","Europe/Madrid"),
//		new CityListClass("INFNT","살라스 드로스 인판테스","스페인","Europe/Madrid"),
//		new CityListClass("SLL","살랄라","오만","Asia/Muscat"),
//		new CityListClass("SLM","살렘","몬세라트산","America/Montserrat"),
//		new CityListClass("SLLT","살루트","캐나다","America/Montreal"),
//		new CityListClass("SLN1","살리나","미국","America/Chicago"),
//		new CityListClass("SCZ","살리나 크루즈","멕시코","America/Mexico_City"),
//		new CityListClass("SAL","살바도르","브라질","America/Bahia"),
//		new CityListClass("SALTA","살타","아르헨티나","America/Argentina/Buenos_Aires"),
//		new CityListClass("SALTO","살토","우루과이","America/Montevideo"),
//		new CityListClass("GUAIR","살토 델 과이라","파라과이","America/Asuncion"),
//		new CityListClass("SLTLL","살티요","멕시코","America/Monterrey"),
//		new CityListClass("ZAM","삼보앙가","필리핀","Asia/Manila"),
//		new CityListClass("ZAMC","삼보앙가시티","필리핀","Asia/Manila"),
//		new CityListClass("SMN","삼순","터키","Europe/Istanbul"),
//			new CityListClass("11D20602","삼척","대한민국","Asia/Seoul"),
//		new CityListClass("SMFY","삼피아","잠비아","Africa/Lusaka"),
//		new CityListClass("SAPP","삿포로","일본","Asia/Tokyo"),
//		new CityListClass("CMPS","상 조세 도스 캄포스","브라질","America/Sao_Paulo"),
//		new CityListClass("GRNDS","상그레그란데","트리니다드토바고","America/Port_of_Spain"),
//		new CityListClass("SLB","상루이스","브라질","America/Bahia"),
//		new CityListClass("VCNTS","상베센테","포르투칼","Atlantic/Madeira"),
//			new CityListClass("11H10302","상주","대한민국","Asia/Seoul"),
//		new CityListClass("PAULO","상파울루","브라질","America/Sao_Paulo"),
//		new CityListClass("SHA","상하이","중국","Asia/Shanghai"),
//		new CityListClass("SGNW","새기노","미국","America/Detroit"),
//		new CityListClass("SJOS","새너제이","미국","America/Los_Angeles"),
//		new CityListClass("SRST","새러소타","미국","America/New_York"),
//		new CityListClass("SRTG","새러토가 스프링스","미국","America/New_York"),
//		new CityListClass("SSKTN","새스커툰","캐나다","America/Regina"),
//		new CityListClass("SAC","새크라멘토","미국","America/Los_Angeles"),
//		new CityListClass("SPRNGS","샌디 스프링스","미국","America/New_York"),
//		new CityListClass("SDI","샌디에이고","미국","America/Los_Angeles"),
//		new CityListClass("PDJ","샌디포인트타운","세인트 키츠 네비스","America/St_Kitts"),
//		new CityListClass("SANL","샌루이스오비스포","미국","America/Los_Angeles"),
//		new CityListClass("SBRNRD","샌버너디노","미국","America/Los_Angeles"),
//		new CityListClass("SATO","샌안토니오","미국","America/Chicago"),
//		new CityListClass("SAGTX1","샌앤젤로","미국","America/Chicago"),
//		new CityListClass("SANTAF","샌타페이","미국","America/Denver"),
//		new CityListClass("SFO","샌프란시스코","미국","America/Los_Angeles"),
//		new CityListClass("SLNU","샐리나스","미국","America/Los_Angeles"),
//		new CityListClass("NZR","생나제르","프랑스","Europe/Paris"),
//		new CityListClass("DZR","생대지에","프랑스","Europe/Paris"),
//		new CityListClass("SNTDN","생드니","프랑스","Indian/Reunion"),
//		new CityListClass("SAINTM","생말로","프랑스","Europe/Paris"),
//		new CityListClass("BRUC","생브리외","프랑스","Europe/Paris"),
//		new CityListClass("QNTN","생캉탱","프랑스","Europe/Paris"),
//		new CityListClass("ETNN","생테티엔","프랑스","Europe/Paris"),
//		new CityListClass("CHMPG","샤롱장샹파뉴","프랑스","Europe/Paris"),
//		new CityListClass("SHJ","샤르자","아랍에미리트","Asia/Dubai"),
//		new CityListClass("SHRQH","샤르자토후국","아랍에미리트","Asia/Dubai"),
//		new CityListClass("CHRTR","샤르트르","프랑스","Europe/Paris"),
//		new CityListClass("CHRLR","샤를루아","벨기에","Europe/Brussels"),
//		new CityListClass("CHRLVM","샤를르 빌 메지에르","프랑스","Europe/Paris"),
//		new CityListClass("CHRLVL","샤를르빌","오스트레일리아","Australia/Brisbane"),
//		new CityListClass("SCHMB","샤움버그","미국","America/Chicago"),
//		new CityListClass("CHYNN","샤이엔","미국","America/Denver"),
//		new CityListClass("SHKW","샤카베","보츠와나","Africa/Gaborone"),
//		new CityListClass("CHTBL","샤토 벨레르","세인트 빈센트 그레나딘","America/St_Vincent"),
//		new CityListClass("CHTRX","샤토르","프랑스","Europe/Paris"),
//		new CityListClass("SCHFF","샤프하우젠","스위스","Europe/Zurich"),
//		new CityListClass("SCHN1","샨","리히텐슈타인","Europe/Vaduz"),
//		new CityListClass("CHRNC","샬럿","미국","America/New_York"),
//		new CityListClass("CHRAM","샬럿 아말리에","버진 아일랜드","America/St_Thomas"),
//		new CityListClass("CTT","샬럿 타운","캐나다","America/Goose_Bay"),
//		new CityListClass("CHRLT","샬로츠빌","미국","America/New_York"),
//		new CityListClass("CHLN","샬롱쉬르손","프랑스","Europe/Paris"),
//			new CityListClass("SHYKH","샴 엘 쉐이크","이집트","Africa/Cairo"),
//		new CityListClass("CHMPG1","샴페인","미국","America/Chicago"),
//		new CityListClass("SNTM","샹테마리","마르티니크","America/Martinique"),
//		new CityListClass("SNTA","샹테안느","과들루프섬","America/Guadeloupe"),
//			
//			new CityListClass("11G00401","서귀포","대한민국","Asia/Seoul"),
//		new CityListClass("SVL","서니베일","미국","America/Los_Angeles"),
//		new CityListClass("STHRL","서덜랜드","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SVA","서배너","미국","America/New_York"),
//			new CityListClass("11C20101","서산","대한민국","Asia/Seoul"),
//			new CityListClass("11B10101","서울","대한민국","Asia/Seoul"),
//			new CityListClass("11C20202","서천","대한민국","Asia/Seoul"),
//		new CityListClass("SNGPK","선가이파크닝","인도네시아","Asia/Jakarta"),
//		new CityListClass("THB","선더 베이","캐나다","America/Toronto"),
//		new CityListClass("SNSHN","선샤인 코스트","오스트레일리아","Australia/Brisbane"),
//		new CityListClass("SMS","섬머사이드","캐나다","America/Goose_Bay"),
//			new CityListClass("11B20605","성남","대한민국","Asia/Seoul"),
//			new CityListClass("11G00101","성산","대한민국","Asia/Seoul"),
//			new CityListClass("11H10605","성주","대한민국","Asia/Seoul"),
//			new CityListClass("11G00302","성판악","대한민국","Asia/Seoul"),
//		new CityListClass("SGV","세고비아","스페인","Europe/Madrid"),
//		new CityListClass("SNNG","세난가","잠비아","Africa/Lusaka"),
//		new CityListClass("SNKL","세네칼","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("CDNA","세두나","오스트레일리아","Australia/Adelaide"),
//		new CityListClass("SRRS","세라이","그리스","Europe/Athens"),
//		new CityListClass("SRMBN","세렘반","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("SRW","세로베","보츠와나","Africa/Gaborone"),
//		new CityListClass("SRNG","세롱가","보츠와나","Africa/Gaborone"),
//		new CityListClass("CLRD","세루 콜로라도","아루바","America/Aruba"),
//		new CityListClass("PSRG","세르베라 드 피수에르가","스페인","Europe/Madrid"),
//		new CityListClass("SERTA","세르타","포르투칼","Europe/Lisbon"),
//		new CityListClass("SERPA","세르파","포르투칼","Europe/Lisbon"),
//		new CityListClass("PHKW","세리베 피크베","보츠와나","Africa/Gaborone"),
//		new CityListClass("CRRK","세리크","알바니아","Europe/Tirane"),
//		new CityListClass("SEM","세마랑","인도네시아","Asia/Jakarta"),
//		new CityListClass("CEBC","세부시티","필리핀","Asia/Manila"),
//		new CityListClass("SEV","세비야","스페인","Europe/Madrid"),
//		new CityListClass("SSHK","세쉐케","잠비아","Africa/Lusaka"),
//		new CityListClass("SSFNT","세스폰테인","나미비아","Africa/Windhoek"),
//		new CityListClass("SANAB","세이트 앤 베이","자메이카","America/Jamaica"),
//		new CityListClass("LRNT","세인트 로랑 다다오","기아나","America/Cayenne"),
//		new CityListClass("SLSMO","세인트 루이스","미국","America/Chicago"),
//		new CityListClass("SANTMR","세인트 마크","아이티","America/Port-au-Prince"),
//		new CityListClass("JSPH","세인트 조셉","미국","America/Chicago"),
//		new CityListClass("SANTJS","세인트 조셉","도미니카","America/Dominica"),
//		new CityListClass("GRG3","세인트 조지","미국","America/Denver"),
//		new CityListClass("GRGS","세인트 조지스","그레나다","America/Grenada"),
//		new CityListClass("GRGSS","세인트 조지스","기아나","America/Cayenne"),
//		new CityListClass("SNV","세인트 존","캐나다","America/Goose_Bay"),
//		new CityListClass("SJF","세인트 존스","캐나다","America/St_Johns"),
//		new CityListClass("SAINTJ","세인트 존스","앤티가바부다","America/Antigua"),
//		new CityListClass("VLLGS","세인트 존스 빌리지","몬세라트산","America/Montserrat"),
//		new CityListClass("CTHRNS","세인트 캐서린스","캐나다","America/Toronto"),
//		new CityListClass("CLOMN","세인트 클라우드","미국","America/Chicago"),
//		new CityListClass("SAINTP","세인트 폴","미국","America/Chicago"),
//		new CityListClass("STPGU","세인트 피터즈버그","미국","America/New_York"),
//		new CityListClass("ALBNS","세인트올번스","영국","Europe/London"),
//		new CityListClass("SAINT","세인트이브스","영국","Europe/London"),
//		new CityListClass("LEN","세인트피터즈버그","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("SALE","세일","오스트레일리아","Australia/Melbourne"),
//		new CityListClass("SALEM","세일럼","미국","America/New_York"),
//		new CityListClass("SLMOR","세일럼","미국","America/Boise"),
//		new CityListClass("SZN","세자나","슬로바키아","Europe/Ljubljana"),
//		new CityListClass("SIL","세틸","캐나다","America/Montreal"),
//		new CityListClass("KRJNS","세프올노 크라젠스키","폴란드","Europe/Warsaw"),
//		new CityListClass("SENJ","센","크로아티아","Europe/Zagreb"),
//		new CityListClass("SEN","센다이","일본","Asia/Tokyo"),
//		new CityListClass("SNSNT","센순테페케","엘살바도르","America/El_Salvador"),
//		new CityListClass("CNTNN","센터니얼","미국","America/Denver"),
//		new CityListClass("THRLS","셀레스","아일랜드","Europe/Dublin"),
//		new CityListClass("SLFSS","셀포스","아이스랜드","Atlantic/Reykjavik"),
//		new CityListClass("STCSS","셋케이시스","스페인","Europe/Madrid"),
//		new CityListClass("SHRBR","셔브룩","캐나다","America/Montreal"),
//		new CityListClass("SHBYG","셰보이건","미국","America/Chicago"),
//		new CityListClass("SNDR","소드리오","이탈리아","Europe/Rome"),
//		new CityListClass("SRCB","소루카바","브라질","America/Sao_Paulo"),
//		new CityListClass("SORIA","소리아","스페인","Europe/Madrid"),
//		new CityListClass("SOWE","소웨토","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SKRK","소카","폴란드","Europe/Warsaw"),
//		new CityListClass("STRS","소퇴르","그레나다","America/Grenada"),
//		new CityListClass("SFLN","소프리온","그리스","Europe/Athens"),
//		new CityListClass("SOFIA","소피아","불가리아","Europe/Sofia"),
//			new CityListClass("11D20401","속초","대한민국","Asia/Seoul"),
//		new CityListClass("SNSNT1","손소나테","엘살바도르","America/El_Salvador"),
//		new CityListClass("SLWZ","솔베지","잠비아","Africa/Lusaka"),
//		new CityListClass("SLSN","솔소나","스페인","Europe/Madrid"),
//		new CityListClass("SLSBR","솔즈베리","미국","America/New_York"),
//		new CityListClass("SLTLK","솔트 레이크 시티","미국","America/Denver"),
//		new CityListClass("SMMRD","솜머다","독일","Europe/Berlin"),
//		new CityListClass("SDB","쇠네르보르","덴마크","Europe/Copenhagen"),
//		new CityListClass("SHWN","쇼니","미국","America/Chicago"),
//		new CityListClass("CHMNT","쇼몽","프랑스","Europe/Paris"),
//		new CityListClass("SHOBR","쇼우바라","일본","Asia/Tokyo"),
//		new CityListClass("SIOUX","수 시티","미국","America/Chicago"),
//		new CityListClass("SIOUXF","수 폴스","미국","America/Chicago"),
//		new CityListClass("SRB","수라바야","인도네시아","Asia/Jakarta"),
//		new CityListClass("SUT","수라트타니","태국","Asia/Bangkok"),
//		new CityListClass("SUR1","수르","오만","Asia/Muscat"),
//		new CityListClass("SRGT","수르구트","러시아 연방 국가","Asia/Yekaterinburg"),
//		new CityListClass("SUMOT","수모토","일본","Asia/Tokyo"),
//		new CityListClass("SUV","수바","피지","Pacific/Fiji"),
//		new CityListClass("SBTC","수보티차","세르비아","Europe/Belgrade"),
//		new CityListClass("SSM","수세인트마리","캐나다","America/Toronto"),
//			new CityListClass("SUE","수에즈","이집트","Africa/Cairo"),
//		new CityListClass("SUWA","수와","일본","Asia/Tokyo"),
//		new CityListClass("SWYD","수와이다","시리아","Asia/Damascus"),
//			new CityListClass("11B20601","수원","대한민국","Asia/Seoul"),
//		new CityListClass("SSC","수지스","체코","Europe/Prague"),
//		new CityListClass("SCHDN","수체드니오","폴란드","Europe/Warsaw"),
//		new CityListClass("SCVA","수체아바","루마니아","Europe/Bucharest"),
//		new CityListClass("STTS","수츠","일본","Asia/Tokyo"),
//		new CityListClass("SKM","수쿠모","일본","Asia/Tokyo"),
//		new CityListClass("SUCRE","수크레","볼리비아","America/La_Paz"),
//		new CityListClass("SFRR","수프리에르","세인트루시아","America/St_Lucia"),
//		new CityListClass("SUH","수하르","오만","Asia/Muscat"),
//		new CityListClass("SNNDL","순달소라","노르웨이","Europe/Oslo"),
//		new CityListClass("SDV","순스발","스웨덴","Europe/Stockholm"),
//			new CityListClass("11F10403","순창","대한민국","Asia/Seoul"),
//			new CityListClass("11F20405","순천","대한민국","Asia/Seoul"),
//			new CityListClass("11F20603","순천(주암)","대한민국","Asia/Seoul"),
//		new CityListClass("SHFFL","쉐필드","영국","Europe/London"),
//		new CityListClass("OCTVL","쉘부르","프랑스","Europe/Paris"),
//		new CityListClass("SHRWS","슈루즈버리","영국","Europe/London"),
//		new CityListClass("SHVLA","슈리브포트","미국","America/Chicago"),
//		new CityListClass("SHMN","슈멘","불가리아","Europe/Sofia"),
//		new CityListClass("SCHWR","슈베린","독일","Europe/Berlin"),
//		new CityListClass("SCHWY","슈비츠","스위스","Europe/Zurich"),
//		new CityListClass("SCHBB","슈아이브스","오스트리아","Europe/Vienna"),
//		new CityListClass("SZCZC1","슈체친","폴란드","Europe/Warsaw"),
//		new CityListClass("SHKDR","슈코더르","알바니아","Europe/Tirane"),
//		new CityListClass("STNKP","슈타인코프","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("STRLS","슈트랄준트","독일","Europe/Berlin"),
//		new CityListClass("STTGT","슈트트가르트","독일","Europe/Berlin"),
//		new CityListClass("SZPRT","슈프로타바","폴란드","Europe/Warsaw"),
//		new CityListClass("SPTTL","슈피탈드라우","오스트리아","Europe/Vienna"),
//		new CityListClass("SLTNB","슐탄베일리","터키","Europe/Istanbul"),
//		new CityListClass("STRGR","스나로가드구덴스키","폴란드","Europe/Warsaw"),
//		new CityListClass("TRENT","스노크온트렌트","영국","Europe/London"),
//		new CityListClass("SRWN1","스라우노","폴란드","Europe/Warsaw"),
//		new CityListClass("SRNGR","스리나가르","인도","Asia/Calcutta"),
//		new CityListClass("JYWRD","스리자야와르데네푸라코테","스리랑카","Asia/Colombo"),
//		new CityListClass("SMDRV","스메데레보","세르비아","Europe/Belgrade"),
//		new CityListClass("SMLYN","스몰랸","불가리아","Europe/Sofia"),
//		new CityListClass("SMLNS","스몰렌스크","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("SMTHR","스미더스","캐나다","America/Vancouver"),
//		new CityListClass("SMTHT","스미스타운","미국","America/New_York"),
//		new CityListClass("NKL1","스베티니콜","마케도니아","Europe/Skopje"),
//		new CityListClass("SVLVR","스볼베르","노르웨이","Europe/Oslo"),
//		new CityListClass("SWKPM","스와콥문드","나미비아","Africa/Windhoek"),
//		new CityListClass("ABRTW","스완지","영국","Europe/London"),
//		new CityListClass("SWRK","스왈키","폴란드","Europe/Warsaw"),
//		new CityListClass("SWDWN","스위드윈","폴란드","Europe/Warsaw"),
//		new CityListClass("SWBDZ","스위보진","폴란드","Europe/Warsaw"),
//		new CityListClass("SWC","스위치","폴란드","Europe/Warsaw"),
//		new CityListClass("CRRNTS","스위프트 커런트","캐나다","America/Regina"),
//		new CityListClass("SWNDN","스윈던","영국","Europe/London"),
//		new CityListClass("SKG","스카겐","덴마크","Europe/Copenhagen"),
//		new CityListClass("SCAR","스카버러","트리니다드토바고","America/Port_of_Spain"),
//		new CityListClass("SCHNC","스케넥터디","미국","America/New_York"),
//		new CityListClass("SCTTSD","스코츠데일","미국","America/Denver"),
//		new CityListClass("SKPJ","스코페","마케도니아","Europe/Skopje"),
//		new CityListClass("SKLV","스콜로프","체코","Europe/Prague"),
//		new CityListClass("SCRNT","스크랜턴","미국","America/New_York"),
//		new CityListClass("SZCZY","스키노","폴란드","Europe/Warsaw"),
//		new CityListClass("ZGR","스타라자고라","불가리아","Europe/Sofia"),
//		new CityListClass("SZCZC","스타르가르트슈체친스키","폴란드","Europe/Warsaw"),
//		new CityListClass("SVR","스타방게르","노르웨이","Europe/Oslo"),
//		new CityListClass("STWRP","스타브로폴","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("STLW","스탈로아볼라","폴란드","Europe/Warsaw"),
//		new CityListClass("STMFR","스탬퍼드","미국","America/New_York"),
//		new CityListClass("STRLN","스털링","영국","Europe/London"),
//		new CityListClass("STRHT","스털링 하이츠","미국","America/Detroit"),
//		new CityListClass("STTSB","스테이츠버러","미국","America/New_York"),
//		new CityListClass("CLLG","스테이트칼리지","미국","America/New_York"),
//		new CityListClass("STNKJ","스테인헤르","노르웨이","Europe/Oslo"),
//		new CityListClass("STYNB","스텐버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SRY","스토너웨이","영국","Europe/London"),
//		new CityListClass("STO","스톡턴","미국","America/Los_Angeles"),
//		new CityListClass("SDN","스톡홀름","스웨덴","Europe/Stockholm"),
//		new CityListClass("STNTN","스톤턴","미국","America/New_York"),
//		new CityListClass("STRMC","스투루미차","마케도니아","Europe/Skopje"),
//		new CityListClass("STRG","스투르가","마케도니아","Europe/Skopje"),
//		new CityListClass("STRBG","스트라스부르","프랑스","Europe/Paris"),
//		new CityListClass("STRKN","스트라코니스","체코","Europe/Prague"),
//		new CityListClass("STRHN","스트라한","오스트레일리아","Australia/Hobart"),
//		new CityListClass("STRMS","스트롬순드","스웨덴","Europe/Stockholm"),
//		new CityListClass("STRYD","스트리덴버그","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("STRZG","스트셰곰","폴란드","Europe/Warsaw"),
//		new CityListClass("STRZL","스트셸린","폴란드","Europe/Warsaw"),
//		new CityListClass("OPLSK","스트셸체오폴스키에","폴란드","Europe/Warsaw"),
//		new CityListClass("STEGE","스티지","덴마크","Europe/Copenhagen"),
//		new CityListClass("STIP","스팁","마케도니아","Europe/Skopje"),
//		new CityListClass("SPA1","스파","벨기에","Europe/Brussels"),
//		new CityListClass("SPRTN","스파턴버그","미국","America/New_York"),
//		new CityListClass("SPGHT","스페이츠 타운","바베이도스","America/Barbados"),
//		new CityListClass("SPKN","스포캔","미국","America/Los_Angeles"),
//		new CityListClass("SPRNG2","스프링데일","미국","America/Chicago"),
//		new CityListClass("SPGMA","스프링필드-매사추세츠","미국","America/New_York"),
//		new CityListClass("SPGMO","스프링필드-미주리","미국","America/Chicago"),
//		new CityListClass("SPNGF","스프링필드-오하이오","미국","America/New_York"),
//		new CityListClass("SPNGA","스프링필드-일리노이","미국","America/Chicago"),
//		new CityListClass("SPL","스플리트","크로아티아","Europe/Zagreb"),
//		new CityListClass("GHRGH","스핀두게오르게","루마니아","Europe/Bucharest"),
//		new CityListClass("WSCHW","스호바","폴란드","Europe/Warsaw"),
//		new CityListClass("SLASK","슬라스키에","폴란드","Europe/Warsaw"),
//		new CityListClass("SLIGO","슬라이고","아일랜드","Europe/Dublin"),
//		new CityListClass("SLTNA","슬라티나","크로아티아","Europe/Zagreb"),
//		new CityListClass("SLTN","슬라티나","루마니아","Europe/Bucharest"),
//		new CityListClass("SLVNS","슬라폰스키브로트","크로아티아","Europe/Zagreb"),
//		new CityListClass("SRPSK","슬럽스크","폴란드","Europe/Warsaw"),
//		new CityListClass("SLGH","슬로","영국","Europe/London"),
//		new CityListClass("SLBZ","슬로보지아","루마니아","Europe/Bucharest"),
//		new CityListClass("SLVN","슬리벤","불가리아","Europe/Sofia"),
//		new CityListClass("SGNZ","시구엔자","스페인","Europe/Madrid"),
//		new CityListClass("CDS","시네스","포르투칼","Europe/Lisbon"),
//		new CityListClass("CEDARD","시더 래피즈","미국","America/Chicago"),
//		new CityListClass("CEDAR","시더 시티","미국","America/Denver"),
//		new CityListClass("SDY","시드니","오스트레일리아","Australia/Sydney"),
//		new CityListClass("SYD","시드니","캐나다","America/Halifax"),
//		new CityListClass("RACHA","시라차","태국","Asia/Bangkok"),
//		new CityListClass("SRKW","시라카와","일본","Asia/Tokyo"),
//		new CityListClass("SRCS","시라쿠사","이탈리아","Europe/Rome"),
//		new CityListClass("SYRCS","시러큐스","미국","America/New_York"),
//		new CityListClass("SROISH","시로이시","일본","Asia/Tokyo"),
//		new CityListClass("SHS","시모노세키","일본","Asia/Tokyo"),
//		new CityListClass("CHMO","시모이우","모잠비크","Africa/Maputo"),
//		new CityListClass("SIMI","시미","그리스","Europe/Athens"),
//		new CityListClass("SIVLLY","시미 밸리","미국","America/Los_Angeles"),
//		new CityListClass("SIVAS","시바스","터키","Europe/Istanbul"),
//		new CityListClass("SBN","시베니크","크로아티아","Europe/Zagreb"),
//		new CityListClass("SIBU","시부","말레이시아","Asia/Kuala_Lumpur"),
//		new CityListClass("SWDNC","시비드니차","폴란드","Europe/Warsaw"),
//		new CityListClass("SIBIU","시비우","루마니아","Europe/Bucharest"),
//		new CityListClass("SISAK","시사크","크로아티아","Europe/Zagreb"),
//	    	new CityListClass("SIAUL","시아울리아이","리투아니아","Europe/Vilnius"),
//		new CityListClass("SEA","시애틀","미국","America/Los_Angeles"),
//		new CityListClass("SIENA","시에나","이탈리아","Europe/Rome"),
//		new CityListClass("SKIEN","시엔","노르웨이","Europe/Oslo"),
//		new CityListClass("SHIMK","시오노미사키","일본","Asia/Tokyo"),
//		new CityListClass("SION1","시옹","스위스","Europe/Zurich"),
//			new CityListClass("SIWAH","시와","이집트","Africa/Cairo"),
//		new CityListClass("CIW","시완단","인도네시아","Asia/Jakarta"),
//	    	new CityListClass("GYN","시우다드 가이아나","베네수엘라","America/Caracas"),
//		new CityListClass("DLCS","시우다드 델리시아스","멕시코","America/Chihuahua"),
//		new CityListClass("RDRG","시우다드 로드리고","스페인","Europe/Madrid"),
//	    	new CityListClass("BLVR","시우다드 볼리바르","베네수엘라","America/Caracas"),
//		new CityListClass("VCTM","시우다드 빅토리아","멕시코","America/Monterrey"),
//		new CityListClass("OBRGN","시우다드 오브레곤","멕시코","America/Hermosillo"),
//		new CityListClass("CDD","시우다드레알","스페인","Europe/Madrid"),
//		new CityListClass("CTDLL","시우타델라","스페인","Europe/Madrid"),
//		new CityListClass("SIIRT","시이르트","터키","Europe/Istanbul"),
//		new CityListClass("SHI","시즈오카","일본","Asia/Tokyo"),
//		new CityListClass("CGO","시카고","미국","America/Chicago"),
//		new CityListClass("SIKEA","시키아","그리스","Europe/Athens"),
//		new CityListClass("STK1","시테키","스와질란드","Africa/Mbabane"),
//		new CityListClass("SITT","시트라","바레인","Asia/Bahrain"),
//		new CityListClass("CTRSD","시트러스달","남아프리카공화국","Africa/Johannesburg"),
//		new CityListClass("SPR1","시파리아","트리니다드토바고","America/Port_of_Spain"),
//			new CityListClass("11B20202","시흥","대한민국","Asia/Seoul"),
//		new CityListClass("SYKTY","식티프카르","러시아 연방 국가","Europe/Moscow"),
//		new CityListClass("SINDI","신디","에스토니아","Europe/Tallinn"),
//		new CityListClass("CICNT","신시내티","미국","America/New_York"),
//			new CityListClass("21F20803","신안","대한민국","Asia/Seoul"),
//		new CityListClass("SHNJ","신조우","일본","Asia/Tokyo"),
//		new CityListClass("SHNKB","신키바","일본","Asia/Tokyo"),
//		new CityListClass("NCL","신트 니콜라스","아루바","America/Aruba"),
//		new CityListClass("NKLS","신트니클라스","벨기에","Europe/Brussels"),
//		new CityListClass("SLKBR","실게보르","덴마크","Europe/Copenhagen"),
//		new CityListClass("SLLM","실라마에","에스토니아","Europe/Tallinn"),
//	    	new CityListClass("SLT1","실루트","리투아니아","Europe/Vilnius"),
//		new CityListClass("SLSTR","실리스트라","불가리아","Europe/Sofia"),
//		new CityListClass("SPRNG1","실버 스프링","미국","America/New_York"),
//		new CityListClass("DANJ","싱가폴","싱가폴","Asia/Singapore"),
//		new CityListClass("TSU","쓰","일본","Asia/Tokyo"),
	};
}
