package com.weathernews.Weather;
public class Spain_europe {
    public final static CityListClass[] Spain_europe = new CityListClass[] {
	new CityListClass("GAN",	"간디아",	"스페인",	"Europe/Madrid"),
	new CityListClass("GUESA",	"게스",	"스페인",	"Europe/Madrid"),
	new CityListClass("GUADA",	"과달라하라",	"스페인",	"Europe/Madrid"),
	new CityListClass("GDLP",	"과달루페",	"스페인",	"Europe/Madrid"),
	new CityListClass("GDX",	"과딕스",	"스페인",	"Europe/Madrid"),
	new CityListClass("GND",	"그라나다",	"스페인",	"Europe/Madrid"),
	new CityListClass("GRNDSS",	"그란다스 데 살리메",	"스페인",	"Europe/Madrid"),
	new CityListClass("NVLMR",	"나발모랄데라모타",	"스페인",	"Europe/Madrid"),
	new CityListClass("NERVA",	"네르바",	"스페인",	"Europe/Madrid"),
	new CityListClass("SBSTN",	"도노스티아/산 세바스챤",	"스페인",	"Europe/Madrid"),
	new CityListClass("HRMNS",	"도스 에르마나스",	"스페인",	"Europe/Madrid"),
	new CityListClass("CNCPC",	"라 리네아 데 콘셉시온",	"스페인",	"Europe/Madrid"),
	new CityListClass("WGC",	"라스팔마스 데 그란 카나리아",	"스페인",	"Atlantic/Canary"),
	new CityListClass("LALIN",	"란",	"스페인",	"Europe/Madrid"),
	new CityListClass("LMBRR",	"럼브게라스",	"스페인",	"Europe/Madrid"),
	new CityListClass("LBRJ",	"레브리하",	"스페인",	"Europe/Madrid"),
	new CityListClass("LEPE",	"레뻬",	"스페인",	"Europe/Madrid"),
	new CityListClass("LES",	"레스",	"스페인",	"Europe/Madrid"),
	new CityListClass("LEOES",	"레온",	"스페인",	"Europe/Madrid"),
	new CityListClass("REUS",	"레우스",	"스페인",	"Europe/Madrid"),
	new CityListClass("RNS",	"레이노사",	"스페인",	"Europe/Madrid"),
	new CityListClass("RQN",	"레퀘나",	"스페인",	"Europe/Madrid"),
	new CityListClass("BLLQ",	"레투에르타 델 블라크",	"스페인",	"Europe/Madrid"),
	new CityListClass("LGRN",	"로그로뇨",	"스페인",	"Europe/Madrid"),
	new CityListClass("LORA",	"로라델리오",	"스페인",	"Europe/Madrid"),
	new CityListClass("LRCA",	"로르카",	"스페인",	"Europe/Madrid"),
	new CityListClass("RQTS",	"로퀘타스 데 마르",	"스페인",	"Europe/Madrid"),
	new CityListClass("LUGOE",	"루고",	"스페인",	"Europe/Madrid"),
	new CityListClass("RUA",	"루아",	"스페인",	"Europe/Madrid"),
	new CityListClass("LRC",	"루아르카",	"스페인",	"Europe/Madrid"),
	new CityListClass("LNRS",	"리나레스",	"스페인",	"Europe/Madrid"),
	new CityListClass("RBDSL",	"리바데세야",	"스페인",	"Europe/Madrid"),
	new CityListClass("RBD",	"리바데오",	"스페인",	"Europe/Madrid"),
	new CityListClass("RIANO",	"리아노",	"스페인",	"Europe/Madrid"),
	new CityListClass("MBL",	"마 르벨라",	"스페인",	"Europe/Madrid"),
	new CityListClass("MNCR",	"마나코르",	"스페인",	"Europe/Madrid"),
	new CityListClass("MDRE",	"마드리드",	"스페인",	"Europe/Madrid"),
	new CityListClass("MTR1",	"마타로",	"스페인",	"Europe/Madrid"),
	new CityListClass("MJDHN",	"마하다혼다",	"스페인",	"Europe/Madrid"),
	new CityListClass("MAHON",	"마혼",	"스페인",	"Europe/Madrid"),
	new CityListClass("MNRS",	"만레사",	"스페인",	"Europe/Madrid"),
	new CityListClass("MLG",	"말라가",	"스페인",	"Europe/Madrid"),
	new CityListClass("MDNP",	"메디나 데 포마르",	"스페인",	"Europe/Madrid"),
	new CityListClass("RSC",	"메디나데리오세코",	"스페인",	"Europe/Madrid"),
	new CityListClass("MRD1",	"메리다",	"스페인",	"Europe/Madrid"),
	new CityListClass("MRTLL",	"모라탈라",	"스페인",	"Europe/Madrid"),
	new CityListClass("MRLL",	"모렐라",	"스페인",	"Europe/Madrid"),
	new CityListClass("MFRNTR",	"모론데라프론테라",	"스페인",	"Europe/Madrid"),
	new CityListClass("MTR",	"모트릴",	"스페인",	"Europe/Madrid"),
	new CityListClass("MNTR",	"몬토루",	"스페인",	"Europe/Madrid"),
	new CityListClass("MNFRT",	"몬포테 데 레모스",	"스페인",	"Europe/Madrid"),
	new CityListClass("MRCA",	"무르시아",	"스페인",	"Europe/Madrid"),
	new CityListClass("MRNDE",	"미란다데에브로",	"스페인",	"Europe/Madrid"),
	new CityListClass("BDJZ",	"바다호스",	"스페인",	"Europe/Madrid"),
	new CityListClass("BDLN",	"바달로나",	"스페인",	"Europe/Madrid"),
	new CityListClass("BRBT",	"바르바테",	"스페인",	"Europe/Madrid"),
	new CityListClass("BAE",	"바르셀로나",	"스페인",	"Europe/Madrid"),
	new CityListClass("BAZA",	"바사",	"스페인",	"Europe/Madrid"),
	new CityListClass("SGRA",	"바사 드 세그라",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLLDD",	"바야돌리드",	"스페인",	"Europe/Madrid"),
	new CityListClass("VAL",	"발렌시아",	"스페인",	"Europe/Madrid"),
	new CityListClass("VALTR",	"발렌시아 드 라스 토레스",	"스페인",	"Europe/Madrid"),
	new CityListClass("BNVNT",	"베나벤테",	"스페인",	"Europe/Madrid"),
	new CityListClass("BNDRM",	"베니도름",	"스페인",	"Europe/Madrid"),
	new CityListClass("VERIN",	"베린",	"스페인",	"Europe/Madrid"),
	new CityListClass("BEJAR",	"베자르",	"스페인",	"Europe/Madrid"),
	new CityListClass("BURGO",	"부그고 데 오스마",	"스페인",	"Europe/Madrid"),
	new CityListClass("BURGS",	"부르고스",	"스페인",	"Europe/Madrid"),
	new CityListClass("BTRG",	"부이뜨라고 데 로소야",	"스페인",	"Europe/Madrid"),
	new CityListClass("VIG",	"비고",	"스페인",	"Europe/Madrid"),
	new CityListClass("VNRS",	"비나로스",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLLN",	"비예나",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLLBL",	"비차블리누",	"스페인",	"Europe/Madrid"),
	new CityListClass("BCRP",	"비코프",	"스페인",	"Europe/Madrid"),
	new CityListClass("GSTZV",	"비토리아 가스테이스",	"스페인",	"Europe/Madrid"),
	new CityListClass("VTGDN",	"비티구디노",	"스페인",	"Europe/Madrid"),
	new CityListClass("VIC",	"빅",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLLNVF",	"빌라 델 프레즈노",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLLRL",	"빌라레알",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLLBA",	"빌라바",	"스페인",	"Europe/Madrid"),
	new CityListClass("BIB",	"빌바오",	"스페인",	"Europe/Madrid"),
	new CityListClass("PZBLN",	"뽀소블란꼬",	"스페인",	"Europe/Madrid"),
	new CityListClass("ZRGZ",	"사라고사",	"스페인",	"Europe/Madrid"),
	new CityListClass("ZMR1",	"사모라",	"스페인",	"Europe/Madrid"),
	new CityListClass("SBDLL",	"사바델",	"스페인",	"Europe/Madrid"),
	new CityListClass("ZAFRA",	"사프라",	"스페인",	"Europe/Madrid"),
	new CityListClass("SHGN",	"사하군",	"스페인",	"Europe/Madrid"),
	new CityListClass("BRRMD",	"산루가르데바라메다",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLDGL",	"산마르틴",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALCNTV",	"산비센테 데 알칸타라",	"스페인",	"Europe/Madrid"),
	new CityListClass("SBSTNG",	"산세바스찬 데라고메라",	"스페인",	"Atlantic/Canary"),
	new CityListClass("LAGUN",	"산크리스토발 데 라 라구나",	"스페인",	"Atlantic/Canary"),
	new CityListClass("CLMNTS",	"산클레멘테",	"스페인",	"Europe/Madrid"),
	new CityListClass("SCLP",	"산타구루즈데라팔마",	"스페인",	"Atlantic/Canary"),
	new CityListClass("OLLL",	"산타오랄라델칼라",	"스페인",	"Europe/Madrid"),
	new CityListClass("SCR",	"산타쿠루즈데테네리페",	"스페인",	"Atlantic/Canary"),
	new CityListClass("STR",	"산탄데르",	"스페인",	"Europe/Madrid"),
	new CityListClass("CMPST",	"산티아고데콤포스텔라",	"스페인",	"Europe/Madrid"),
	new CityListClass("SLMNCA",	"살라망카",	"스페인",	"Europe/Madrid"),
	new CityListClass("INFNT",	"살라스 드로스 인판테스",	"스페인",	"Europe/Madrid"),
	new CityListClass("SGV",	"세고비아",	"스페인",	"Europe/Madrid"),
	new CityListClass("PSRG",	"세르베라 드 피수에르가",	"스페인",	"Europe/Madrid"),
	new CityListClass("SEV",	"세비야",	"스페인",	"Europe/Madrid"),
	new CityListClass("STCSS",	"셋케이시스",	"스페인",	"Europe/Madrid"),
	new CityListClass("SORIA",	"소리아",	"스페인",	"Europe/Madrid"),
	new CityListClass("SLSN",	"솔소나",	"스페인",	"Europe/Madrid"),
	new CityListClass("SGNZ",	"시구엔자",	"스페인",	"Europe/Madrid"),
	new CityListClass("RDRG",	"시우다드 로드리고",	"스페인",	"Europe/Madrid"),
	new CityListClass("CDD",	"시우다드레알",	"스페인",	"Europe/Madrid"),
	new CityListClass("CTDLL",	"시우타델라",	"스페인",	"Europe/Madrid"),
	new CityListClass("AGLS",	"아길라스",	"스페인",	"Europe/Madrid"),
	new CityListClass("ADRA",	"아드라",	"스페인",	"Europe/Madrid"),
//	new CityListClass("OLMOS",	"아라스 데 로스 오르모스",	"스페인",	"Europe/Madrid"),
	new CityListClass("ARND",	"아란다 데 두에로",	"스페인",	"Europe/Madrid"),
	new CityListClass("ARNJZ",	"아랑후에스",	"스페인",	"Europe/Madrid"),
	new CityListClass("ARNS",	"아레나스 드 산 페드로",	"스페인",	"Europe/Madrid"),
	new CityListClass("ARVL",	"아레발로",	"스페인",	"Europe/Madrid"),
	new CityListClass("ARR",	"아레시페",	"스페인",	"Atlantic/Canary"),
	new CityListClass("ARONA",	"아로나",	"스페인",	"Atlantic/Canary"),
	new CityListClass("ARTSS",	"아르테사데세그레",	"스페인",	"Europe/Madrid"),
	new CityListClass("AVLA",	"아빌라",	"스페인",	"Europe/Madrid"),
	new CityListClass("AVL",	"아빌레스",	"스페인",	"Europe/Madrid"),
	new CityListClass("ASCO",	"아스코",	"스페인",	"Europe/Madrid"),
	new CityListClass("ASTRG",	"아스토르가",	"스페인",	"Europe/Madrid"),
	new CityListClass("HNRSA",	"알깔라 데 에나레스",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALCL",	"알깔라 라 레알",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALCRC",	"알꼬르꽁",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALI",	"알리칸테",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALMNS",	"알만사",	"스페인",	"Europe/Madrid"),
	new CityListClass("AMR",	"알메리아",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALBCT",	"알바세테",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALBNC",	"알반체즈",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALCRZ",	"알카라즈",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALCZR",	"알카사르데산후안",	"스페인",	"Europe/Madrid"),
	new CityListClass("AGEE",	"알헤시라스",	"스페인",	"Europe/Madrid"),
	new CityListClass("ALNS",	"앨라니스",	"스페인",	"Europe/Madrid"),
	new CityListClass("EZCRY",	"에즈까레이",	"스페인",	"Europe/Madrid"),
	new CityListClass("ECIJA",	"에키자",	"스페인",	"Europe/Madrid"),
	new CityListClass("ENCNS",	"엔시나소라",	"스페인",	"Europe/Madrid"),
	new CityListClass("EJIDO",	"엘 에히도",	"스페인",	"Europe/Madrid"),
	new CityListClass("ELZND",	"엘리존도",	"스페인",	"Europe/Madrid"),
	new CityListClass("ELX",	"엘체",	"스페인",	"Europe/Madrid"),
	new CityListClass("SUERT",	"엘폰데 수에르",	"스페인",	"Europe/Madrid"),
	new CityListClass("LLD",	"예이다",	"스페인",	"Europe/Madrid"),
	new CityListClass("ORTGR",	"오르티구웨이라",	"스페인",	"Europe/Madrid"),
	new CityListClass("OVD",	"오비에도",	"스페인",	"Europe/Madrid"),
	new CityListClass("ORNS",	"오우렌세",	"스페인",	"Europe/Madrid"),
	new CityListClass("UBEDA",	"우베다",	"스페인",	"Europe/Madrid"),
	new CityListClass("UBRQ",	"우브리께",	"스페인",	"Europe/Madrid"),
	new CityListClass("HSCR",	"우아스카르",	"스페인",	"Europe/Madrid"),
	new CityListClass("HSC1",	"우에스카",	"스페인",	"Europe/Madrid"),
	new CityListClass("HVA",	"우엘바",	"스페인",	"Europe/Madrid"),
	new CityListClass("UTRR",	"우트레라",	"스페인",	"Europe/Madrid"),
	new CityListClass("INST",	"이니에스타",	"스페인",	"Europe/Madrid"),
	new CityListClass("IBZ",	"이비자 타운",	"스페인",	"Europe/Madrid"),
	new CityListClass("JRC",	"제리카",	"스페인",	"Europe/Madrid"),
	new CityListClass("GRNA",	"지로나",	"스페인",	"Europe/Madrid"),
	new CityListClass("CDZ",	"카디스",	"스페인",	"Europe/Madrid"),
	new CityListClass("CTS",	"카르타헤나",	"스페인",	"Europe/Madrid"),
	new CityListClass("CBZS",	"카베자스 루비아스",	"스페인",	"Europe/Madrid"),
	new CityListClass("CRBNR",	"카보네라",	"스페인",	"Europe/Madrid"),
	new CityListClass("CCRS",	"카세레스",	"스페인",	"Europe/Madrid"),
	new CityListClass("CTL",	"카스테욘데라플라나",	"스페인",	"Europe/Madrid"),
	new CityListClass("CNVRS",	"칼라버라스",	"스페인",	"Europe/Madrid"),
	new CityListClass("CLHRR",	"칼라오라",	"스페인",	"Europe/Madrid"),
	new CityListClass("CLTYD",	"칼라타유드",	"스페인",	"Europe/Madrid"),
	new CityListClass("CLLL",	"칼레라",	"스페인",	"Europe/Madrid"),
	new CityListClass("CLV1",	"칼비아",	"스페인",	"Europe/Madrid"),
	new CityListClass("CMPLL",	"캄필로스",	"스페인",	"Europe/Madrid"),
	new CityListClass("CSTR",	"캐스투에라",	"스페인",	"Europe/Madrid"),
	new CityListClass("CSTRN",	"캐스트로누노",	"스페인",	"Europe/Madrid"),
	new CityListClass("LCO",	"코루나",	"스페인",	"Europe/Madrid"),
	new CityListClass("CRDE",	"코르도바",	"스페인",	"Europe/Madrid"),
	new CityListClass("CORIA",	"코리아",	"스페인",	"Europe/Madrid"),
	new CityListClass("CMLLS",	"코미야스",	"스페인",	"Europe/Madrid"),
	new CityListClass("VLLLB",	"콜라도 빌라바",	"스페인",	"Europe/Madrid"),
	new CityListClass("CLLR",	"쿠에야르",	"스페인",	"Europe/Madrid"),
	new CityListClass("CNC1",	"쿠엔카",	"스페인",	"Europe/Madrid"),
	new CityListClass("TRA",	"타라고나",	"스페인",	"Europe/Madrid"),
	new CityListClass("TRNCON",	"타란콘",	"스페인",	"Europe/Madrid"),
	new CityListClass("TRRG",	"타레가",	"스페인",	"Europe/Madrid"),
	new CityListClass("TLVR",	"탈라베라데라레이나",	"스페인",	"Europe/Madrid"),
	new CityListClass("TRRSS1",	"테라사",	"스페인",	"Europe/Madrid"),
//	new CityListClass("TERUL",	"테루엘",	"스페인",	"Europe/Madrid"),
	new CityListClass("TELDE",	"텔데",	"스페인",	"Atlantic/Canary"),
	new CityListClass("TRR",	"토레비자",	"스페인",	"Europe/Madrid"),
	new CityListClass("TRRLV",	"토렐라베가",	"스페인",	"Europe/Madrid"),
	new CityListClass("TRTS",	"토르토사",	"스페인",	"Europe/Madrid"),
	new CityListClass("TMLLS",	"토멜로소",	"스페인",	"Europe/Madrid"),
	new CityListClass("TLD",	"톨레도",	"스페인",	"Europe/Madrid"),
	new CityListClass("TDL",	"투델라",	"스페인",	"Europe/Madrid"),
	new CityListClass("TRJLLO",	"트루히요",	"스페인",	"Europe/Madrid"),
	new CityListClass("PARLA",	"팔라",	"스페인",	"Europe/Madrid"),
	new CityListClass("PLNC",	"팔렌시아",	"스페인",	"Europe/Madrid"),
	new CityListClass("PMM",	"팔마",	"스페인",	"Europe/Madrid"),
	new CityListClass("PMPLN",	"팜플로나",	"스페인",	"Europe/Madrid"),
	new CityListClass("PNTVD",	"폰테베드라",	"스페인",	"Europe/Madrid"),
	new CityListClass("PNFRR",	"폰페라다",	"스페인",	"Europe/Madrid"),
	new CityListClass("RSR",	"푸에르토 델 로사리오",	"스페인",	"Atlantic/Canary"),
	new CityListClass("RDRGP",	"푸에블라 데 돈 로드리고",	"스페인",	"Europe/Madrid"),
	new CityListClass("SNBR",	"푸에블라 데 사나브리아",	"스페인",	"Europe/Madrid"),
	new CityListClass("PNT1",	"푸엔테헤닐",	"스페인",	"Europe/Madrid"),
	new CityListClass("FNGRL",	"푸엔히롤라",	"스페인",	"Europe/Madrid"),
	new CityListClass("PLLNO",	"푸엘톨라노",	"스페인",	"Europe/Madrid"),
	new CityListClass("FRNTR",	"프론테라",	"스페인",	"Atlantic/Canary"),
	new CityListClass("PLSNC",	"플라센시아",	"스페인",	"Europe/Madrid"),
	new CityListClass("FGRES",	"피게레스",	"스페인",	"Europe/Madrid"),
	new CityListClass("FSTRR",	"피스테라",	"스페인",	"Europe/Madrid"),
	new CityListClass("JAEN",	"하엔",	"스페인",	"Europe/Madrid"),
	new CityListClass("JFRNTR",	"헤레스데라프론테라",	"스페인",	"Europe/Madrid"),
	new CityListClass("GTF",	"헤타페",	"스페인",	"Europe/Madrid"),
	new CityListClass("HLLN",	"헬린",	"스페인",	"Europe/Madrid"),
	new CityListClass("JMLL",	"후미야",	"스페인",	"Europe/Madrid"),
	new CityListClass("GIJ",	"히혼",	"스페인",	"Europe/Madrid"),
    };
}
