package com.weathernews.Weather;
public class Sweden_europe {
    public final static CityListClass[] Sweden_europe = new CityListClass[] {
	new CityListClass("GLLVR",	"갈리바르",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("NOKN",	"노르최핑",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("NYKPN",	"니쇼핑",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("LDVK",	"루드비카",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("LUL",	"룰레오",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("LDKPN",	"리드셰핑",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("MLO",	"말뫼",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("MORA",	"모라",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("MTL4",	"모탈라",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("VRBRG",	"바르베르크",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("VSTRS",	"바스테라스",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("VAXJO",	"벡시외",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("BORLNG",	"보르랭애",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("BRGHL",	"보리홀름",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("VISBY",	"비스뷔",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("VLHLM",	"빌헬미나",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("SDV",	"순스발",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("SDN",	"스톡홀름",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("STRMS",	"스트롬순드",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("ARVK",	"아르비카",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("LJSDL",	"엘쥬스달",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("GAVLE",	"예블레",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("GTB",	"예테보리",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("ORBR",	"오레브로",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("OSTRS",	"오스터순드",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("ORS",	"외른스홀드스비크",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("OVRTR",	"외베르토르네오",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("JKKMK",	"요크모크",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("JNKPN",	"욘코핑",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("UDDVL",	"우데발라",	"스웨덴",	"Europe/Stockholm"),
//	new CityListClass("UMEA",	"우메아",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("UPPSL",	"웁살라",	"스웨덴",	"Europe/Stockholm"),
//	new CityListClass("VTLND",	"웨트란다",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("YSTAD",	"이스타드",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("KTRNH",	"카트리네홀름",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("KLMR",	"칼마르",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("KARL",	"칼스크로나",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("KRLST",	"칼스타드",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("KNGSB",	"쿵스바카",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("KRTD",	"크리스티안스타드",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("KRNA",	"키루나",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("VSTRV",	"페스테어빅",	"스웨덴",	"Europe/Stockholm"),
//	new CityListClass("HLM",	"할름스타드",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("HDKSV",	"허딕스볼",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("HSSLH",	"헤슬레홀름",	"스웨덴",	"Europe/Stockholm"),
	new CityListClass("HEL",	"헬싱보리",	"스웨덴",	"Europe/Stockholm"),
//	new CityListClass("STRMN",	"흐토루만",	"스웨덴",	"Europe/Stockholm"),
    };
}
