package com.weathernews.Weather;

public class V {
	public final static CityListClass_E[] v = new CityListClass_E[] {
		new CityListClass_E("VAC1", "Vac", "바크", "헝가리", "Europe/Budapest"),
		new CityListClass_E("VADSO", "Vadso", "바드쇠", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("VADUZ", "Vaduz", "파두츠", "리히텐슈타인", "Europe/Vaduz"),
		new CityListClass_E("VLNCE", "Valence", "발랑스", "프랑스", "Europe/Paris"),
		new CityListClass_E("VAL", "Valencia", "발렌시아", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLNC", "Valencia", "발렌시아", "베네수엘라", "America/Caracas"),
		new CityListClass_E("VALTR", "Valencia de las Torres", "발렌시아 드 라스 토레스", "스페인", "Europe/Madrid"),
		new CityListClass_E("VALGA", "Valga", "발가", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("VLLDD", "Valladolid", "바야돌리드", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLJ", "Vallejo", "발레이오", "미국", "America/Los_Angeles"),
		new CityListClass_E("VLT", "Valletta", "발레타", "몰타", "Europe/Malta"),
		new CityListClass_E("VLP", "Valparaiso", "발파라조", "칠레", "America/Santiago"),
		new CityListClass_E("VANN", "Van", "반", "터키", "Europe/Istanbul"),
		new CityListClass_E("VBCWA", "Vancouver", "밴쿠버", "미국", "America/Los_Angeles"),
		new CityListClass_E("VBC", "Vancouver", "밴쿠버", "캐나다", "America/Vancouver"),
		new CityListClass_E("VNNS", "Vannes", "반느", "프랑스", "Europe/Paris"),
		new CityListClass_E("VRZDN", "VaraZdin", "바라즈딘", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("VRBRG", "Varberg", "바르베르크", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("VRN1", "Varena", "바례나", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("VAR", "Varna", "바르나", "불가리아", "Europe/Sofia"),
		new CityListClass_E("VSL", "Vaslui", "바슬루이", "루마니아", "Europe/Bucharest"),
		new CityListClass_E("VSTRS", "Vasteras", "바스테라스", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("VSTRV", "Vastervik", "페스테어빅", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("VTCN", "Vatican", "바티칸", "Vatican City", "Europe/Vatican"),
		new CityListClass_E("VAXJO", "Vaxjo", "벡시외", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("VEJLE", "Vejle", "바일레", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("VELES", "Veles", "벨레스", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("GRCV", "Velika Gorica", "벨리카 고리차", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("NOVGD", "Velikiy Novgorod", "벨리키 노브고로트", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("TRNVV", "Veliko Tarnovo", "벨리코 트르노보", "불가리아", "Europe/Sofia"),
		new CityListClass_E("VLNGR", "Velingrad", "벨린그래드", "불가리아", "Europe/Sofia"),
		new CityListClass_E("VNZ", "Venezia", "베네치아", "이탈리아", "Europe/Rome"),
		new CityListClass_E("VENLO", "Venlo", "벤로", "네덜란드", "Europe/Amsterdam"),
		new CityListClass_E("VER", "Veracruz", "베라크루스", "멕시코", "America/Mexico_City"),
		new CityListClass_E("VRBN", "Verbania", "베르바니아", "이탈리아", "Europe/Rome"),
		new CityListClass_E("VEROI", "Veria", "베리아", "그리스", "Europe/Athens"),
		new CityListClass_E("VERIN", "Verin", "베린", "스페인", "Europe/Madrid"),
		new CityListClass_E("VRNL", "Vernal", "버널", "미국", "America/Denver"),
		new CityListClass_E("VRNNH", "Vernon Hills", "버논 힐즈", "미국", "America/Chicago"),
		new CityListClass_E("VBCH", "Vero Beach", "베로 비치", "미국", "America/New_York"),
		new CityListClass_E("VRON", "Verona", "베로나", "이탈리아", "Europe/Rome"),
		new CityListClass_E("VRRTT", "Verrettes", "베레테스", "아이티", "America/Port-au-Prince"),
		new CityListClass_E("VRSLL", "Versailles", "베르사이유", "프랑스", "Europe/Paris"),
		new CityListClass_E("VESUL", "Vesoul", "베쑬", "프랑스", "Europe/Paris"),
		new CityListClass_E("VSTMN", "Vestmannaeyjar", "베스트만나이야르", "아이스랜드", "Atlantic/Reykjavik"),
		new CityListClass_E("VSZPR", "Veszprem", "베스프렘", "헝가리", "Europe/Budapest"),
//		new CityListClass_E("VTLND", "Vetlanda", "웨트란다", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("ALNTJ", "Viana do Alentejo", "비아나 도 카스텔 로", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("VNC", "Viana do Castelo", "비아나두카스텔루", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("VBRG", "Viborg", "비보르", "덴마크", "Europe/Copenhagen"),
		new CityListClass_E("VIC", "Vic", "빅", "스페인", "Europe/Madrid"),
		new CityListClass_E("VCTR", "Victoria", "빅토리아", "세이셸", "Indian/Mahe"),
		new CityListClass_E("VICTR", "Victoria", "빅토리아", "미국", "America/Chicago"),
//		new CityListClass_E("VCTRA", "Victoria", "빅토리아", "캐나다", "America/Vancouver"),
		new CityListClass_E("VTTR", "Victoria", "빅토리아", "몰타", "Europe/Malta"),
		new CityListClass_E("VCTRV", "Victorville", "빅토빌", "미국", "America/Los_Angeles"),
		new CityListClass_E("VIDIN", "Vidin", "비딘", "불가리아", "Europe/Sofia"),
		new CityListClass_E("VDM", "Viedma", "비에드마", "아르헨티나", "America/Argentina/Buenos_Aires"),
		new CityListClass_E("VIENN", "Vienna", "비엔나", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("VNTN", "Vientiane", "비엔티안", "라오스", "Asia/Vientiane"),
		new CityListClass_E("VIEUX", "Vieux Fort", "뷰포트", "세인트루시아", "America/St_Lucia"),
		new CityListClass_E("VIG", "Vigo", "비고", "스페인", "Europe/Madrid"),
		new CityListClass_E("VOPO", "Vila do Porto", "빌라 포르투", "포르투칼", "Atlantic/Azores"),
		new CityListClass_E("FRNCC", "Vila Franca do Campo", "빌라 프란카 캄포 할", "포르투칼", "Atlantic/Azores"),
//		new CityListClass_E("GAIA", "Vila Nova de Gaia", "빌라 노바 드 가이아", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("VLHLM", "Vilhelmina", "빌헬미나", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("VLJND", "Viljandi", "빌 랸디", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("FMLC", "Villa nova de Famalicao", "빌라노바 드 파마리카오", "포르투칼", "Europe/Lisbon"),
//		new CityListClass_E("NUEVAV", "Villa Nueva", "비야누에바", "과테말라", "America/Guatemala"),
		new CityListClass_E("VLLBL", "Villablino", "비차블리누", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLLCH", "Villach", "빌라흐", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("VLLHR", "Villahermosa", "비야에르모사", "멕시코", "America/Mexico_City"),
		new CityListClass_E("VLLBA", "Villalba", "빌라바", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLLNVF", "Villanueva del Fresno", "빌라 델 프레즈노", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLLRL", "Villareal", "빌라레알", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLLRR", "Villarrica", "비야리카", "파라과이", "America/Asuncion"),
		new CityListClass_E("VLLN", "Villena", "비예나", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLNS", "Vilnius", "빌뉴스", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("VLVRD", "Vilvoorde", "빌보르드", "벨기에", "Europe/Brussels"),
		new CityListClass_E("VNRS", "Vinaros", "비나로스", "스페인", "Europe/Madrid"),
		new CityListClass_E("VNLND", "Vineland", "바인랜드", "미국", "America/New_York"),
		new CityListClass_E("VNC1", "Vinica", "비니카", "마케도니아", "Europe/Skopje"),
		new CityListClass_E("VNKVC", "Vinkovci", "빈코비치", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("VRGN", "Virginia", "버지니아", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("VRGNA", "Virginia Beach", "버지니아 비치", "미국", "America/New_York"),
		new CityListClass_E("VRVTC", "Virovitica", "비로비티차", "크로아티아", "Europe/Zagreb"),
		new CityListClass_E("VSGNS", "Visaginas", "비사기나스", "리투아니아", "Europe/Vilnius"),
		new CityListClass_E("VSL1", "Visalia", "비살리아", "미국", "America/Los_Angeles"),
		new CityListClass_E("VISBY", "Visby", "비스뷔", "스웨덴", "Europe/Stockholm"),
		new CityListClass_E("VISEU", "Viseu", "비제우", "포르투칼", "Europe/Lisbon"),
		new CityListClass_E("VIS", "Vishakhapatnam", "비샤카파트남", "인도", "Asia/Calcutta"),
		new CityListClass_E("VTRB", "Viterbo", "비테르보", "이탈리아", "Europe/Rome"),
		new CityListClass_E("VTGDN", "Vitigudino", "비티구디노", "스페인", "Europe/Madrid"),
		new CityListClass_E("VIB", "VitOria", "비토리아", "브라질", "America/Bahia"),
		new CityListClass_E("GSTZV", "Vitoria-Gasteiz", "비토리아 가스테이스", "스페인", "Europe/Madrid"),
		new CityListClass_E("VLDKV", "Vladikavkaz", "블라디캅카스", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("VLDMR", "Vladimir", "블라디미르", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("VLA", "Vladivostok", "블라디보스토크", "러시아 연방 국가", "Asia/Vladivostok"),
		new CityListClass_E("VLORE", "Vlore", "블로레", "알바니아", "Europe/Tirane"),
		new CityListClass_E("VLGGR", "Volgograd", "볼고그라드", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("VLGD", "Vologda", "볼로그다", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("VOL", "Volos", "볼로스", "그리스", "Europe/Athens"),
		new CityListClass_E("VRNSH", "Voronezh", "보로네츠", "러시아 연방 국가", "Europe/Moscow"),
		new CityListClass_E("VORU", "Voru", "보루", "에스토니아", "Europe/Tallinn"),
		new CityListClass_E("VOSS", "Voss", "보스", "노르웨이", "Europe/Oslo"),
		new CityListClass_E("VRTS1", "Vratsa", "브라차", "불가리아", "Europe/Sofia"),
		new CityListClass_E("VREDE", "Vrede", "브레데", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("VRYBR", "Vryburg", "프라이벅", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("VSTN", "Vsetin", "브세틴", "체코", "Europe/Prague"),
		new CityListClass_E("VKVR", "Vukovar", "부코바르", "크로아티아", "Europe/Zagreb"),

	};
}
