package com.weathernews.Weather;

public class W {
	public final static CityListClass_E[] w = new CityListClass_E[] {
		new CityListClass_E("WACO", "Waco", "웨이코", "미국", "America/Chicago"),
		new CityListClass_E("WDWC", "Wadowice", "바도비체", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WGG", "Wageningen", "와게닝엔", "수리남", "America/Paramaribo"),
		new CityListClass_E("WAGGA", "Wagga Wagga", "와가와가", "오스트레일리아", "Australia/Sydney"),
		new CityListClass_E("WGRW", "Wagrowiec", "봉그로비에츠", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WJM", "Wajima", "와지마", "일본", "Asia/Tokyo"),
		new CityListClass_E("WAK", "Wakayama", "와카야마", "일본", "Asia/Tokyo"),
		new CityListClass_E("WKK", "Wakkanai", "왁카나이", "일본", "Asia/Tokyo"),
		new CityListClass_E("WALLA", "Walla Walla", "왈라왈라", "미국", "America/Los_Angeles"),
		new CityListClass_E("11F20301", "Wando", "완도", "대한민국", "Asia/Seoul"),
		new CityListClass_E("WNGRT", "Wangaratta", "왕가라타", "오스트레일리아", "Australia/Melbourne"),
//		new CityListClass_E("WLBRZ", "Warbrzych", "바우브지흐", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WARCZ", "Warcz", "바르츠", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WRMBT", "Warmbaths", "웜배스", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("RBNS", "Warner Robins", "워너 로빈스", "미국", "America/New_York"),
		new CityListClass_E("WRRN1", "Warren", "워런", "미국", "America/New_York"),
		new CityListClass_E("WRRNT", "Warrenton", "워렌톤", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("WRRNM", "Warrnambool", "워넘불", "오스트레일리아", "Australia/Melbourne"),
		new CityListClass_E("WRSWO", "Warsaw", "바르샤바", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WRWCK", "Warwick", "워릭", "미국", "America/New_York"),
		new CityListClass_E("WSNGT", "Washington", "워싱턴-펜실베이니아", "미국", "America/New_York"),
		new CityListClass_E("WSGDC", "Washington", "워싱턴DC", "미국", "America/New_York"),
		new CityListClass_E("WTRBR", "Waterbury", "워터베리", "미국", "America/New_York"),
		new CityListClass_E("WTF", "Waterford", "워터포드", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("WTRIA", "Waterloo", "워털루", "미국", "America/Chicago"),
		new CityListClass_E("WTRTW", "Watertown", "워터타운-뉴욕", "미국", "America/New_York"),
		new CityListClass_E("WTRTW1", "Watertown", "워터타운-위스콘신", "미국", "America/Chicago"),
		new CityListClass_E("WTSN", "Watson Lake", "왓슨 레이크", "캐나다", "America/Dawson"),
		new CityListClass_E("WKGN", "Waukegan", "워키건", "미국", "America/Chicago"),
		new CityListClass_E("WAVRE", "Wavre", "와브르", "벨기에", "Europe/Brussels"),
		new CityListClass_E("WYCRS", "Waycross", "웨이크로스", "미국", "America/New_York"),
		new CityListClass_E("WRTN", "Weirton", "위어턴", "미국", "America/New_York"),
//		new CityListClass_E("WJHRW", "Wejherowo", "베이헤로보", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WLKM", "Welkom", "벨콤", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("WEL", "Wellington", "웰링턴", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass_E("WERDA", "Werda", "웨다", "보츠와나", "Africa/Gaborone"),
		new CityListClass_E("WRTCT", "West Hartford", "웨스트 하트퍼드", "미국", "America/New_York"),
		new CityListClass_E("WEST", "West Palm Beach", "웨스트 팜 비치", "미국", "America/New_York"),
		new CityListClass_E("WSTCO", "Westminster", "웨스트 민스터", "미국", "America/Denver"),
//		new CityListClass_E("WXFRD", "Wexford", "웩스퍼드", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("WHA", "Whangarei", "황거레이", "뉴질랜드", "Pacific/Auckland"),
		new CityListClass_E("WHY", "Whyalla", "화이앨라", "오스트레일리아", "Australia/Adelaide"),
		new CityListClass_E("WCHT", "Wichita", "위치토", "미국", "America/Chicago"),
		new CityListClass_E("WCHF", "Wichita Falls", "위치토 폴스", "미국", "America/Chicago"),
		new CityListClass_E("WCKLW", "Wicklow", "위클로", "아일랜드", "Europe/Dublin"),
		new CityListClass_E("WLN1", "Wielun", "비엘룬", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("NSTDT", "Wiener Neustadt", "비너 노이슈트", "오스트리아", "Europe/Vienna"),
		new CityListClass_E("WSBDN", "Wiesbaden", "비스바덴", "독일", "Europe/Berlin"),
		new CityListClass_E("WHH", "Wilhelmshaven", "빌헬름스하펜", "독일", "Europe/Berlin"),
		new CityListClass_E("WLKS", "Wilkes-Barre", "윌크스배러", "미국", "America/New_York"),
		new CityListClass_E("WLS", "Willemstad", "빌렘스타트", "앤틸리스제도", "America/Curacao"),
		new CityListClass_E("WLLMSP", "Williamsport", "윌리엄즈포트", "미국", "America/New_York"),
		new CityListClass_E("WLLWM", "Willowmore", "윌로우모어", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("WLN", "Wilmington", "윌밍턴-노스캘롤라이나", "미국", "America/New_York"),
		new CityListClass_E("WLG", "Wilmington", "윌밍턴-델라웨어", "미국", "America/New_York"),
		new CityListClass_E("WILTZ", "Wiltz", "빌츠", "룩셈부르크", "Europe/Luxembourg"),
		new CityListClass_E("WNBRG", "Winburg", "윈버그", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("WNCHS1", "Winchester", "윈체스터", "미국", "America/New_York"),
		new CityListClass_E("WNDK", "Windhoek", "빈트후크", "나미비아", "Africa/Windhoek"),
		new CityListClass_E("WNDSR", "Windsor", "윈저", "캐나다", "America/Toronto"),
		new CityListClass_E("WNPG", "Winnipeg", "위니펙", "캐나다", "America/Regina"),
		new CityListClass_E("WNSTN", "Winston-Salem", "윈스턴 세일럼", "미국", "America/New_York"),
		new CityListClass_E("WNTR", "Winter Haven", "윈터헤이븐", "미국", "America/New_York"),
		new CityListClass_E("WNTRP", "Winter Park", "윈터파크", "미국", "America/New_York"),
		new CityListClass_E("WNTRT", "Winterthur", "빈터투어", "스위스", "Europe/Zurich"),
		new CityListClass_E("WLFSB", "Wolfsburg", "볼프스부르크", "독일", "Europe/Berlin"),
		new CityListClass_E("WLLNG", "Wollongong", "울런공", "오스트레일리아", "Australia/Sydney"),
		new CityListClass_E("WLMRN", "Wolmaransstad", "워메이런즈 스타트", "남아프리카공화국", "Africa/Johannesburg"),
		new CityListClass_E("11D10401", "Wonju", "원주", "대한민국", "Asia/Seoul"),
		new CityListClass_E("WSTR", "Wooster", "우스터-오하이오", "미국", "America/New_York"),
		new CityListClass_E("WRCSR", "Worcester", "우스터", "남아프리카공화국", "Africa/Johannesburg"),
//		new CityListClass_E("WORCE", "Worcester", "우스터", "영국", "Europe/London"),
		new CityListClass_E("WRCST", "Worcester", "우스터-매사추세츠", "미국", "America/New_York"),
		new CityListClass_E("WRXH", "Wrexham", "렉섬", "영국", "Europe/London"),
		new CityListClass_E("WRCLW", "Wrocraw", "브로츠와프", "폴란드", "Europe/Warsaw"),
//		new CityListClass_E("WRCRW", "Wrocrawek", "브워츠와베크", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WRDW", "Wrodawa", "브워다바", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WRSZC", "Wroszczowa", "브워슈초바", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WSCHW", "Wschowa", "스호바", "폴란드", "Europe/Warsaw"),
		new CityListClass_E("WRZBR", "Wurzburg", "뷔르츠부르크", "독일", "Europe/Berlin"),
		new CityListClass_E("WYSZK", "WyszkOw", "위즈코프", "폴란드", "Europe/Warsaw"),

	};
}
